export const acneVisualTypes=["diagnosis-severity","pathogenesis-lesions","topical-retinoids","topical-combination","clascoterone","oral-antibiotics","hormonal-therapy","isotretinoin","follow-up-special-populations"];
const diagrams={
"diagnosis-severity":["Clinical pattern","Read morphology, distribution, burden, and danger together",["Identify","Comedones","Separate acne from monomorphic or noncomedonal mimics"],["Grade","Inflammation and depth","Papules, pustules, nodules, scars, and trunk disease matter"],["Measure","Life impact","Include pain, pigment, distress, and social function"],["Escalate","Atypical or scarring","Protect diagnosis and prevent permanent injury"]],
"pathogenesis-lesions":["Follicular circuit","Interrupt plugging, sebum, microbes, inflammation, and androgen signals",["Plug","Microcomedone","Abnormal keratinization begins before a visible lesion"],["Fuel","Sebum","Androgen signaling and lipid environment shape the follicle"],["Signal","C. acnes and immunity","Microbial and host responses amplify inflammation"],["Injure","Deep inflammation","Nodules increase scar and pigment risk"]],
"topical-retinoids":["Retinoid foundation","Normalize the follicle while engineering tolerability",["Target","Microcomedone","Treat the full acne-prone field, not one spot"],["Select","Molecule and vehicle","Stability, receptor profile, age, site, and access differ"],["Start","Pea-sized exposure","Use moisturizer and a tolerable frequency"],["Maintain","Prevent relapse","Continue a nonantibiotic foundation after control"]],
"topical-combination":["Complementary topical care","Give every active ingredient a defined job",["Oxidize","Benzoyl peroxide","Reduce bacterial burden and support stewardship"],["Pair","Topical antibiotic","Never leave antibiotic therapy unprotected and open ended"],["Refine","Azelaic acid","Address acne and postinflammatory pigment with tolerability"],["Simplify","One schedule","Avoid stacked irritants and product duplication"]],
clascoterone:["Local androgen pathway","Use a product-specific topical antiandrogen plan",["Block","Androgen receptor","Target a local signaling pathway"],["Label","Age 12 and older","Respect indication, amount, frequency, and site"],["Watch","Local irritation","Reduce or stop when the barrier is injured"],["Audit","Systemic signals","Exposure area, age, skin integrity, and symptoms matter"]],
"oral-antibiotics":["Antibiotic bridge","Control inflammation while planning the exit",["Select","Defined indication","Use systemic therapy for meaningful inflammatory disease"],["Combine","Benzoyl peroxide","Pair with topical nonantibiotic mechanisms"],["Administer","Product-specific rules","Manage cations, posture, food, light, and swallowing"],["Exit","Reassessment date","Stop, change mechanism, or escalate rather than drift"]],
"hormonal-therapy":["Hormonal selection","Match androgen-responsive acne to the whole patient",["Pattern","Persistent or cyclical disease","Use phenotype as one clue, not the only criterion"],["Screen","Contraceptive safety","Apply full eligibility and thrombosis reasoning"],["Monitor","Spironolactone risk","Individualize kidney, potassium, pressure, and interaction review"],["Align","Reproductive goals","Acne benefit must fit pregnancy plans and preferences"]],
isotretinoin:["High-impact therapy","Balance scar prevention with controlled systemic risk",["Qualify","Severe or refractory burden","Include scarring and psychosocial harm"],["Prevent","Embryo-fetal exposure","Use the current iPLEDGE REMS workflow exactly"],["Monitor","Targeted toxicity","Follow pregnancy, liver, lipid, symptom, and interaction risk"],["Counsel","Expected versus urgent","Separate dryness from serious headache, vision, mood, or abdominal signals"]],
"follow-up-special-populations":["Closed-loop acne care","Make the regimen usable, measurable, and stage appropriate",["Design","Morning and evening","Assign one purpose to every product"],["Protect","Barrier and sun","Use gentle care, moisturizer, and sunscreen"],["Adapt","Pregnancy and age","Reconcile every active and exact label"],["Recheck","Response and harm","Track lesions, scars, pigment, distress, adherence, and duration"]],
};
export default function AcneVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual acne-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],i)=><div key={focus}><span>{String(i+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
