const diagrams={
"adhf-assessment":{eyebrow:"Acute heart failure assessment",title:"Stabilize first, then classify congestion and perfusion, confirm the syndrome, identify the trigger, and exclude time-sensitive mimics.",accent:"#bd7769",columns:[["Stabilize","Airway, oxygenation, circulation","Treat immediate threats"],["Classify","Wet or dry, warm or cold","Guide the first pathway"],["Confirm","Clinical plus objective evidence","Challenge mimics"],["Trigger","Ischemia, rhythm, infection, access","Prevent recurrence"]]},
"adhf-decongestion":{eyebrow:"Decongestion operating loop",title:"Adequate early loop delivery, response measurement, timely escalation, composite congestion assessment, and an executable oral plan convert diuresis into durable care.",accent:"#839db4",columns:[["Dose","Account for prior exposure","Cross the effective threshold"],["Measure","Urine, sodium, symptoms, pressure","Reassess within hours"],["Escalate","Loop or second nephron site","Monitor chemistry"],["Complete","Composite euvolemia","Test the oral plan"]]},
"adhf-cardiorenal":{eyebrow:"Kidney and electrolyte trajectory",title:"Creatinine, sodium, potassium, magnesium, urine response, venous pressure, and perfusion must be interpreted together during decongestion.",accent:"#8ca47d",columns:[["Perfusion","Arterial delivery","Pressure is not flow"],["Congestion","Renal venous pressure","Back pressure matters"],["Chemistry","Sodium, potassium, magnesium","Prevent neurologic and rhythm harm"],["Trajectory","Response versus injury","Do not react to one value"]]},
"adhf-vasoactive":{eyebrow:"Vasodilator and inotrope selection",title:"Vasodilators treat pressure and afterload in selected perfused patients, while inotropes serve selected low-output states and always require an endpoint and exit strategy.",accent:"#aa8bb7",columns:[["Nitrate","Venous and ischemic relief","Check pressure and PDE5 exposure"],["Nitroprusside","Balanced rapid dilation","Monitor pressure and toxicity"],["Dobutamine","Beta-mediated inotropy","Watch rate and ischemia"],["Milrinone","PDE3 inodilator","Adjust for kidney function"]]},
"adhf-shock":{eyebrow:"Cardiogenic shock",title:"Pressure support, flow support, cause treatment, right-versus-left ventricular phenotype, organ trajectory, and a defined bridge must move together.",accent:"#c0965c",columns:[["Recognize","Hypoperfusion and trajectory","Do not wait for profound hypotension"],["Pressure","Norepinephrine when indicated","Protect organ perfusion"],["Flow","Inotrope or device","Match the failing chamber"],["Bridge","Recovery, decision, durable support","Define the exit"]]},
"adhf-transition":{eyebrow:"Hospital-to-home transition",title:"A successful discharge transfers a tested oral congestion plan, established disease therapy, laboratory ownership, early follow-up, access, education, and escalation thresholds.",accent:"#b8746c",columns:[["Reconcile","Diagnosis, trigger, medicines","Explain every change"],["Test","Oral response and stability","Avoid an untested plan"],["Schedule","Labs and early follow-up","Name the owner"],["Support","Access, literacy, caregiver, goals","Make the plan executable"]]},
};
export default function AcuteDecompensatedHeartFailureVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
