const diagrams = {
  "acs-anticoagulant-handoff": {"eyebrow": "Dosing and handoff", "title": "Match the next anticoagulant order to the treatment already given.", "accent": "#b88c62", "columns": [["Identify", "Agent, route and time", "Reconstruct prior exposure"], ["Calculate", "Weight, age and renal function", "Apply the correct regimen and limits"], ["Monitor", "Bleeding and relevant laboratory results", "Use agent-appropriate monitoring"], ["Transfer", "Procedural anticoagulation plan", "Confirm the next dose with the receiving team"]]},
  "acs-rupture-thrombosis": { eyebrow: "Acute coronary biology", title: "Plaque disruption exposes thrombogenic material, activates platelets and coagulation, and can abruptly reduce myocardial blood flow.", accent: "#c36f64", columns: [["Disrupt", "Rupture or erosion", "Expose collagen and tissue factor"], ["Activate", "Platelets", "Adhesion, signaling, and aggregation"], ["Generate", "Thrombin and fibrin", "Stabilize the growing clot"], ["Injure", "Ischemia to necrosis", "Time and collateral flow shape damage"]] },
  "acs-diagnostic-path": { eyebrow: "Rapid diagnosis", title: "Symptoms, serial ECGs, high-sensitivity troponin, hemodynamics, and competing diagnoses define the acute pathway.", accent: "#7f9eb4", columns: [["Recognize", "Symptoms and instability", "Activate emergency care"], ["Record", "ECG within 10 minutes of first contact", "Repeat for persistent suspicion or changing symptoms"], ["Measure", "Serial high-sensitivity troponin", "Identify acute myocardial injury"], ["Classify", "STEMI, NSTE-ACS, or alternative", "Choose reperfusion and antithrombotic strategy"]] },
  "acs-antithrombotic": { eyebrow: "Thrombus control", title: "Aspirin, a P2Y12 inhibitor, and parenteral anticoagulation target distinct parts of the evolving coronary thrombus.", accent: "#b88c62", columns: [["COX-1", "Aspirin", "Suppress thromboxane signaling"], ["P2Y12", "Ticagrelor, prasugrel, or clopidogrel", "Limit ADP-mediated platelet activation"], ["Coagulation", "Parenteral anticoagulant", "Reduce thrombin generation or activity"], ["Balance", "Ischemia versus bleeding", "Select agent, timing, and duration"]] },
  "acs-reperfusion": { eyebrow: "Reperfusion", title: "STEMI requires immediate artery-opening strategy, while NSTE-ACS timing follows instability and ischemic risk.", accent: "#a78ab4", columns: [["STEMI", "Primary PCI system", "Contact-to-device goal: 90 min; transfer: 120 min"], ["No timely PCI", "Selected fibrinolysis pathway", "Screen exclusions; transfer immediately after lysis"], ["Unstable NSTE", "Immediate invasive strategy", "Recurrent ischemia, shock, HF, or electrical instability"], ["Stable NSTE", "Risk-guided angiography", "Match timing to ischemic and procedural risk"]] },
  "acs-pci-shock": { eyebrow: "Procedure and shock", title: "Radial access, intravascular imaging, complete revascularization, and shock-specific culprit strategy improve procedural decision quality.", accent: "#8ca17a", columns: [["Access", "Radial preferred", "Reduce bleeding and vascular complications"], ["Optimize", "Intravascular imaging", "Guide complex lesion PCI"], ["Complete", "Treat significant nonculprit disease", "Stage or complete according to stability and anatomy"], ["Shock", "Culprit vessel first", "Avoid routine immediate nonculprit PCI"]] },
  "acs-discharge": { eyebrow: "Recovery and recurrence prevention", title: "Discharge begins a high-risk transition involving DAPT, lipid intensification, ventricular care, rehabilitation, and early follow-up.", accent: "#c29c62", columns: [["Protect", "Antithrombotic and bleeding plan", "Document each drug and planned stop date"], ["Modify", "Lipids and risk factors", "Start intensive prevention in hospital"], ["Recover", "Function and rehabilitation", "Restore confidence and capacity"], ["Reassess", "4 to 8 week lipid panel", "Close gaps in exposure and goals"]] },
};

export default function AcuteCoronarySyndromesVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
