const diagrams={
"ais-system":{eyebrow:"Stroke system",title:"Recognition, destination, imaging, reperfusion, and monitoring run in parallel because every avoidable delay converts salvageable brain into infarct.",accent:"#b87969",columns:[["Recognize","Sudden focal deficit","Record last known well"],["Route","Match destination to local network","Preserve rapid transfer"],["Image","Exclude hemorrhage and find occlusion","Do not delay eligible IV therapy"],["Treat","IV thrombolysis and thrombectomy","Use independent eligibility pathways"]]},
"ais-diagnosis":{eyebrow:"Core and penumbra",title:"Clinical severity and rapid brain and vessel imaging distinguish hemorrhage, established injury, threatened tissue, and a treatable occlusion.",accent:"#829db4",columns:[["Exam","NIHSS plus disabling function","A low score can still disable"],["CT","Exclude intracranial hemorrhage","Do not wait for every test"],["Vessel","Identify large-vessel occlusion","Activate EVT pathway"],["Advanced","Estimate mismatch when required","Select extended windows"]]},
"ais-thrombolysis":{eyebrow:"Intravenous reperfusion",title:"Thrombolysis decisions integrate time, disability, imaging, blood pressure, bleeding biology, drug exposure, and the exact alteplase or tenecteplase product pathway.",accent:"#a58bb7",columns:[["Window","Treat eligible disabling deficit rapidly","Do not wait for improvement"],["Agent","Alteplase or tenecteplase","Use exact dose and preparation"],["Safety","Control pressure and screen bleeding","Avoid adjuvant antithrombotics"],["Observe","Neurologic and pressure surveillance","Image before antithrombotics"]]},
"ais-thrombectomy":{eyebrow:"Endovascular reperfusion",title:"Occlusion site, time, imaging, deficit, core size, baseline function, and patient goals define thrombectomy eligibility without making IV thrombolysis wait.",accent:"#8da47c",columns:[["Anterior","Treat eligible proximal LVO","Early and selected late windows"],["Large core","Selected patients still benefit","Core size is not an automatic exclusion"],["Basilar","Strong benefit with NIHSS at least 10","Treat within 24 hours when eligible"],["Bridge","IVT and EVT are parallel","Do not withhold one while arranging the other"]]},
"ais-support":{eyebrow:"Protect the reperfused brain",title:"Pressure, oxygen, glucose, temperature, swallowing, mobility, thrombosis prevention, edema, and hemorrhage surveillance shape outcome after the artery opens.",accent:"#c09a60",columns:[["Pressure","Avoid hypotension and overcorrection","No routine target below 140 after EVT"],["Metabolic","Treat hypoxia, fever, and harmful glucose extremes","Avoid intensive 80 to 130 control"],["Airway","Screen swallowing before oral intake","Prevent aspiration"],["Complication","Watch edema and hemorrhage","Escalate early"]]},
"ais-transition":{eyebrow:"Cause to prevention",title:"The acute episode closes only when mechanism, antithrombotic timing, risk-factor therapy, rehabilitation, education, and follow-up ownership are explicit.",accent:"#bb7369",columns:[["Cause","Cardioembolic, large artery, small vessel, other","Do not label cryptogenic too early"],["Prevent","Match antithrombotic to mechanism","Avoid unnecessary combination"],["Recover","Begin rehabilitation and communication support","Measure function beyond NIHSS"],["Handoff","Teach warning signs and ownership","Close access gaps"]]},
};
export default function AcuteIschemicStrokeVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
