const diagrams={
"aki-detect":{eyebrow:"Detect a moving baseline",title:"AKI is a trajectory of creatinine and urine output, not a single abnormal laboratory value, and neither marker directly measures structural injury.",accent:"#b87969",columns:[["Baseline","Reconstruct prior kidney function","Do not accept the admission value blindly"],["Creatinine","Lagging functional marker","Dilution and production matter"],["Urine","Timed output per kilogram","Obstruction and diuretics change meaning"],["Stage","Use the worse criterion","Trend severity and duration"]]},
"aki-cause":{eyebrow:"Cause by physiology",title:"Perfusion, parenchymal injury, and obstruction are starting categories that must be refined through hemodynamics, exposure, sediment, imaging, and response.",accent:"#839eb5",columns:[["Perfusion","Effective arterial volume and pressure","Test fluid responsiveness, not edema alone"],["Intrinsic","Tubule, interstitium, glomerulus, vessel","Use urine and systemic clues"],["Obstruction","Bladder to collecting system","Relieve early"],["Mixed","Several insults often coexist","Update the model daily"]]},
"aki-hemodynamic":{eyebrow:"Perfusion without flooding",title:"Resuscitation replaces a reversible deficit, vasopressors restore pressure when needed, and repeated response testing prevents both underperfusion and fluid overload.",accent:"#a58bb7",columns:[["Assess","History, exam, dynamic response","Static edema is not intravascular volume"],["Fluid","Balanced crystalloid when appropriate","Give a goal and stop rule"],["Pressure","Norepinephrine for vasodilatory shock","Treat the circulation, not creatinine alone"],["Recheck","Urine, perfusion, oxygen, congestion","De-resuscitate when excess harms"]]},
"aki-drugs":{eyebrow:"Medication and exposure stewardship",title:"Drugs can alter perfusion, injure kidney structures, obstruct tubules, raise creatinine without lowering GFR, or accumulate when clearance falls.",accent:"#8da47d",columns:[["Identify","Timeline every prescription and exposure","Include OTC and contrast"],["Classify","Hemodynamic, toxic, immune, crystal, pseudoAKI","Mechanism changes action"],["Dose","Use current function and drug properties","eGFR is unstable in AKI"],["Restart","Reassess indication after recovery","Avoid permanent therapeutic omission"]]},
"aki-complications":{eyebrow:"Treat consequences while fixing cause",title:"Potassium, acid-base status, volume, uremia, nutrition, infection therapy, and drug exposure determine urgency more reliably than creatinine alone.",accent:"#c09a61",columns:[["Potassium","Stabilize, shift, remove","ECG and kinetics matter"],["Acid","Treat cause and ventilation","Bicarbonate is context specific"],["Volume","Oxygenation and perfusion","Diuretics treat overload, not injury"],["Uremia","Neurologic, pericardial, bleeding effects","Escalate for complications"]]},
"aki-recovery":{eyebrow:"AKI to AKD to recovery",title:"Kidney replacement therapy follows refractory clinical indications, while recovery requires dose transition, catheter removal, recurrence prevention, and kidney follow-up.",accent:"#ba7469",columns:[["Start KRT","Refractory electrolyte, acid, volume, toxin, uremia","No creatinine threshold alone"],["Choose","Intermittent, continuous, prolonged","Match hemodynamics and goals"],["Stop","Native clearance and output recover","Recalculate every drug"],["Follow","AKD and CKD risk persist","Assign laboratory and clinical ownership"]]},
};
export default function AcuteKidneyInjuryVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
