export const acuteOtitisMediaVisualTypes = ["anatomy-pathogenesis", "diagnostic-criteria", "differential-triage", "pain-support", "observation-decision", "amoxicillin-selection", "clavulanate-allergy", "calculations-administration", "failure-complications", "recurrence-hearing-prevention"].map((type) => `aom-${type}`);

const diagrams = {
  "anatomy-pathogenesis": ["Middle-ear pathway", "Follow pressure, fluid, and organisms from the nasopharynx", ["Inflame", "Viral mucosa", "Upper respiratory inflammation narrows the eustachian tube."], ["Obstruct", "Ventilation", "Negative pressure and impaired clearance retain middle-ear fluid."], ["Ascend", "Bacteria", "Nasopharyngeal organisms enter the fluid-filled space."], ["Resolve", "Clearance", "Inflammation improves before every trace of fluid disappears."]],
  "diagnostic-criteria": ["Diagnostic lens", "Require acute inflammation and middle-ear effusion", ["See", "Bulging", "Moderate or severe bulging is highly specific."], ["Trace", "Otorrhea", "Exclude external-canal disease before calling perforation."], ["Pair", "Mild findings", "Add recent otalgia or intense erythema."], ["Prove", "Effusion", "Use mobility or tympanometry to confirm fluid."]],
  "differential-triage": ["Ear localization", "Move from symptom to the responsible structure", ["Canal", "External", "Tragal pain and edema support otitis externa."], ["Middle", "AOM or OME", "Bulging defines infection while isolated fluid defines effusion."], ["Mastoid", "Urgent", "Swelling or auricular displacement can signal extension."], ["Neural", "Protect", "Sudden hearing or neurologic change needs another pathway."]],
  "pain-support": ["Comfort plan", "Treat pain while the disease strategy takes effect", ["Measure", "Severity", "Use sleep, feeding, play, and function."], ["Dose", "By weight", "Calculate acetaminophen or ibuprofen safely."], ["Deliver", "Precisely", "Match concentration, volume, interval, and device."], ["Recheck", "Trajectory", "Define worsening and the expected response window."]],
  "observation-decision": ["Treatment matrix", "Combine age, ears, otorrhea, severity, and access", ["Treat", "Severe or draining", "Immediate antibiotics fit severe disease or otorrhea."], ["Observe", "Selected", "Nonsevere disease can use 48 to 72 hours."], ["Support", "Analgesia", "Observation never means withholding pain care."], ["Rescue", "Reliable", "Create a prescription or reassessment mechanism."]],
  "amoxicillin-selection": ["Focused first line", "Use enough amoxicillin without unnecessary breadth", ["Confirm", "AOM", "Apply strict diagnostic criteria before prescribing."], ["Screen", "Exceptions", "Review recent exposure, conjunctivitis, failure, and allergy."], ["Calculate", "High dose", "Use 80 to 90 mg per kg per day under protocol."], ["Limit", "Duration", "Match the course to age and severity."]],
  "clavulanate-allergy": ["Selection fork", "Add spectrum or change class only for a defined reason", ["Detect", "Beta-lactamase risk", "Recent amoxicillin and conjunctivitis change the likely organism."], ["Protect", "Amoxicillin", "Clavulanate blocks selected beta-lactamases."], ["Choose", "Ratio", "ES-600 supports high amoxicillin with lower clavulanate burden."], ["Phenotype", "Allergy", "Separate intolerance, immediate allergy, and severe delayed disease."]],
  "calculations-administration": ["Dose translation", "Carry units from the scale to the oral syringe", ["Convert", "kg", "Verify weight and convert units safely."], ["Multiply", "mg per day", "Apply the indication-specific weight-based regimen."], ["Divide", "mg per dose", "Use the prescribed frequency."], ["Deliver", "mL", "Use concentration, measurable volume, quantity, and device."]],
  "failure-complications": ["Nonresponse audit", "Re-examine before escalating", ["Confirm", "Diagnosis", "Repeat otoscopy and localize the source."], ["Verify", "Delivery", "Check concentration, mL, shaking, vomiting, and missed doses."], ["Escalate", "Coverage", "Change therapy only after a defined failure."], ["Protect", "Complications", "Mastoid or neurologic signs require urgent care."]],
  "recurrence-hearing-prevention": ["Longitudinal loop", "Count episodes while protecting hearing and development", ["Count", "Distinct episodes", "Use three in 6 months or four in 12 months."], ["Examine", "Effusion", "Tube candidacy depends on current middle-ear fluid."], ["Hear", "Development", "Persistent fluid requires hearing and learning surveillance."], ["Prevent", "Durably", "Use vaccines, smoke avoidance, and family support."]],
};

export default function AcuteOtitisMediaVisual({ type }) {
  const diagram = diagrams[type.replace("aom-", "")];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual acute-otitis-media-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
