export const acuteBacterialRhinosinusitisVisualTypes = ["anatomy-pathogenesis", "diagnostic-patterns", "differential-red-flags", "testing-imaging", "watchful-waiting", "supportive-care", "first-line-antibiotics", "alternatives-safety", "dosing-administration", "failure-follow-up"].map((type) => `sinus-${type}`);

const diagrams = {
  "anatomy-pathogenesis": ["Clearance system", "Follow flow from open ostium to bacterial risk", ["Ventilate", "Open ostium", "Pressure and air exchange remain connected to the nasal cavity."], ["Move", "Ciliary transport", "Mucus and trapped particles move toward drainage."], ["Obstruct", "Viral edema", "Swelling narrows the pathway and retains secretions."], ["Reassess", "Bacterial shift", "Only a minority develop a qualifying bacterial trajectory."]],
  "diagnostic-patterns": ["Trajectory map", "Use time and change rather than mucus color", ["Follow", "Improving course", "Steady improvement remains compatible with viral disease."], ["Mark", "Ten days", "Persistent symptoms must remain without improvement."], ["Detect", "Double worsening", "New deterioration follows an initial recovery."], ["Reconcile", "Severe onset", "CDC and pediatric pathways retain a severe-onset criterion."]],
  "differential-red-flags": ["Danger compass", "Move from routine symptoms to urgent anatomy", ["Protect", "Orbit", "Vision change, proptosis, diplopia, or painful eye movement is urgent."], ["Protect", "Brain", "Neurologic change, meningismus, or seizure requires emergency evaluation."], ["Trace", "Dental source", "Unilateral foul drainage and dental findings need source control."], ["Reopen", "Alternative", "Migraine, allergy, tumor, and structural disease can mimic infection."]],
  "testing-imaging": ["Question first", "Make every test answer a defined clinical need", ["Avoid", "Routine scan", "Uncomplicated acute disease does not need imaging."], ["Select", "Complication CT", "Contrast can map orbital or intracranial spread."], ["Improve", "Culture source", "Guided sinus sampling is more relevant than a nasal swab."], ["Classify", "Time course", "Chronic and recurrent disease use separate frameworks."]],
  "watchful-waiting": ["Active observation", "Build the safety system before deferring antibiotics", ["Confirm", "Eligibility", "Disease is uncomplicated and the patient is clinically stable."], ["Treat", "Symptoms", "Observation still includes meaningful symptom care."], ["Schedule", "Reassessment", "A defined time and access route close the loop."], ["Rescue", "Start or escalate", "Worsening, nonresponse, or red flags trigger action."]],
  "supportive-care": ["Symptom toolkit", "Assign one purpose and one limit to each intervention", ["Relieve", "Pain", "Use a safe systemic analgesic when appropriate."], ["Rinse", "Saline", "Use safe water and a clean device."], ["Reduce", "Inflammation", "Intranasal steroid technique controls delivery."], ["Limit", "Adjunct risk", "Antihistamines and decongestants need a defined indication."]],
  "first-line-antibiotics": ["Focused selection", "Connect source date, pathogen, and patient", ["Choose", "Amoxicillin", "Focused exposure fits many uncomplicated patients."], ["Add", "Clavulanate", "Beta-lactamase risk supports the combination."], ["Limit", "Adult duration", "Most treated adults receive 5 to 7 days."], ["Individualize", "Child regimen", "Weight, ratio, age, and protocol define delivery."]],
  "alternatives-safety": ["Alternative gate", "Do not trade an allergy label for greater harm", ["Clarify", "Reaction", "Separate intolerance, immediate, and severe delayed injury."], ["Consider", "Doxycycline", "Selected adults require technique and interaction review."], ["Reserve", "Fluoroquinolone", "Serious disabling risks outweigh convenience."], ["Verify", "Resistance", "Macrolides are unreliable for routine adult ABRS."]],
  "dosing-administration": ["Dose translation", "Carry units through the exact formulation", ["Measure", "Kilograms", "Use a current plausible weight."], ["Calculate", "Amoxicillin", "Apply mg per kg per day and divide correctly."], ["Convert", "Exact product", "Ratio and concentration determine dose volume."], ["Deliver", "Course", "Meal timing, quantity, device, and organ function matter."]],
  "failure-follow-up": ["Closed-loop review", "Rebuild the case before broadening therapy", ["Time", "Response window", "Adults use 3 to 5 days and children about 72 hours."], ["Audit", "Delivery", "Verify product, dose, volume, schedule, and adherence."], ["Screen", "Complication", "Recheck teeth, eyes, neurologic status, and host risk."], ["Reclassify", "Disease", "Chronic or recurrent patterns leave the acute pathway."]],
};

export default function AcuteBacterialRhinosinusitisVisual({ type }) {
  const diagram = diagrams[type.replace("sinus-", "")];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual acute-bacterial-rhinosinusitis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
