export const acuteBacterialMeningitisVisualTypes = ["emergency-syndrome", "diagnostic-sequence", "csf-reasoning", "host-pathogens", "empiric-therapy", "dexamethasone", "definitive-therapy", "dosing-safety", "support-complications", "public-health-followup"].map((type) => `meningitis-${type}`);

const diagrams = {
  "emergency-syndrome": ["Emergency architecture", "Protect brain and circulation in parallel", ["Recognize", "Syndrome", "Use tempo, host, neurologic findings, rash, and systemic severity."], ["Stabilize", "Physiology", "Secure airway, stop seizure, and restore perfusion."], ["Culture", "If feasible", "Preserve organism evidence without creating delay."], ["Treat", "Immediately", "Start an effective central nervous system regimen."]],
  "diagnostic-sequence": ["Diagnostic sequence", "Collect what matters without creating an antibiotic gate", ["Blood", "Culture first", "Obtain cultures promptly when access is available."], ["Screen", "LP safety", "Identify instability, bleeding, or mass-effect concern."], ["Sample", "CSF", "Perform lumbar puncture promptly when safe."], ["Proceed", "No delay", "Treat while imaging or procedures remain pending."]],
  "csf-reasoning": ["CSF pattern", "Interpret relationships rather than isolated numbers", ["Pressure", "Opening", "Record the value and technical context."], ["Cells", "Differential", "Neutrophils support but do not define the diagnosis."], ["Chemistry", "Glucose and protein", "Pair cerebrospinal fluid glucose with blood glucose."], ["Organism", "Direct tests", "Combine stain, culture, molecular testing, and susceptibility."]],
  "host-pathogens": ["Host map", "Predict the organisms the patient can plausibly carry", ["Community", "Core", "Pneumococcus, meningococcus, and Haemophilus remain central."], ["Listeria", "Add coverage", "Age over 60, pregnancy, or immunocompromise changes therapy."], ["Neonate", "Separate", "Use a neonatal pathogen and safety pathway."], ["Hardware", "Redirect", "Neurosurgery and devices require healthcare-associated coverage."]],
  "empiric-therapy": ["Coverage design", "Give every empiric drug a defined organism role", ["Anchor", "Ceftriaxone", "Use ceftriaxone or cefotaxime at a meningitis regimen."], ["Extend", "Ampicillin", "Add for current Listeria risk."], ["Protect", "Vancomycin", "Consider when resistant pneumococcus threatens the anchor."], ["Reassess", "Narrow", "Remove unnecessary coverage when evidence arrives."]],
  "dexamethasone": ["Adjunct timing", "Place the anti-inflammatory decision beside the first antibiotic", ["Prepare", "Before", "Give dexamethasone before or with antibiotics when possible."], ["Protect", "No delay", "Never postpone the antimicrobial dose."], ["Identify", "Organism", "Continue for pneumococcus or Haemophilus type b."], ["Monitor", "Safety", "Follow glucose, gastrointestinal risk, and clinical course."]],
  "definitive-therapy": ["Definitive pathway", "Convert organism evidence into a complete treatment plan", ["Name", "Organism", "Use culture or validated molecular identification."], ["Prove", "Susceptibility", "Confirm that the narrowed agent is active."], ["Define", "Duration", "Match course to organism, source, and response."], ["Close", "Carriage", "Address meningococcal eradication before discharge."]],
  "dosing-safety": ["Exposure controls", "Central nervous system therapy is a dynamic dose problem", ["Select", "Meningitis regimen", "Do not reuse a routine infection dose."], ["Adjust", "Physiology", "Recalculate through renal and volume changes."], ["Measure", "Vancomycin", "Use the institution's serum exposure method."], ["Protect", "Neonates", "Honor ceftriaxone bilirubin and calcium contraindications."]],
  "support-complications": ["Parallel care", "Prevent secondary injury while the antimicrobial works", ["Perfuse", "Brain and body", "Avoid shock, hypotension, and hypoxemia."], ["Observe", "Neurology", "Escalate pupil, consciousness, focal, or seizure change."], ["Diagnose", "Fluid and sodium", "Treat the actual volume and electrolyte disorder."], ["Recover", "Function", "Plan hearing, cognition, mobility, and rehabilitation."]],
  "public-health-followup": ["Transmission loop", "Protect contacts and reduce recurrence", ["Isolate", "Droplet", "Continue until 24 hours of effective therapy."], ["Notify", "Public health", "Build the close-contact list immediately."], ["Prevent", "Chemoprophylaxis", "Choose quickly by exposure, life stage, and resistance."], ["Investigate", "Recurrence", "Review complement, spleen, HIV, leak, and vaccines."]],
};

export default function AcuteBacterialMeningitisVisual({ type }) {
  const diagram = diagrams[type.replace("meningitis-", "")];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual acute-bacterial-meningitis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
