const diagrams = {
  "ai-levels": ["Failure map", "Locate the missing signal before replacing it", ["Primary", "Adrenal cortex", "Low cortisol, high ACTH, and possible aldosterone loss"], ["Secondary", "Pituitary ACTH", "Low cortisol and low or inappropriately normal ACTH"], ["Tertiary", "Hypothalamus or exogenous feedback", "Reduced CRH and ACTH with preserved RAAS"]],
  "ai-primary": ["Primary disease", "Connect cortical injury to the phenotype", ["Destroy", "Autoimmune or acquired injury", "Reduce glucocorticoid and mineralocorticoid reserve"], ["Signal", "ACTH rises", "Feedback loss can produce hyperpigmentation"], ["Deplete", "Salt and volume", "High renin, low aldosterone, and hyperkalemia can emerge"]],
  "ai-central": ["Exposure audit", "Reconstruct every glucocorticoid route", ["Add", "Dose and duration", "Risk generally rises beyond physiologic exposure for three to four weeks"], ["Combine", "Local and injected routes", "Multiple formulations can produce systemic suppression"], ["Amplify", "CYP3A4 inhibition", "Reduced metabolism can reveal Cushing features and HPA suppression"]],
  "ai-patterns": ["Pattern recognition", "Use physiology to classify the deficit", ["Cortisol", "Low stress reserve", "Weakness, nausea, hypotension, and hypoglycemia can appear"], ["ACTH", "High or low", "The direction locates confirmed cortisol deficiency"], ["RAAS", "Renin and aldosterone", "Mineralocorticoid loss separates primary from most central disease"]],
  "ai-testing": ["Diagnostic sequence", "Ask what the test must establish", ["Screen", "Morning cortisol", "Interpret through timing, binding, assay, and recent exposure"], ["Confirm", "Corticotropin test", "Measure adrenal response when the patient is stable"], ["Recover", "Morning continuum", "Above 10 supports recovery, 5 to 10 is indeterminate, below 5 remains low"]],
  "ai-glucocorticoid": ["Replacement rhythm", "Provide enough cortisol action without chronic excess", ["Wake", "Largest hydrocortisone dose", "Approximate the normal morning peak"], ["Day", "Smaller later doses", "Support function while limiting evening exposure"], ["Review", "Clinical response", "Separate under-replacement from over-replacement and timing problems"]],
  "ai-mineralocorticoid": ["Volume control", "Replace aldosterone action only when it is missing", ["Start", "Fludrocortisone", "Primary disease may need 50 to 100 micrograms daily initially"], ["Measure", "Pressure, potassium, and renin", "Use the whole volume and electrolyte pattern"], ["Adjust", "Salt loss or excess", "Balance craving and postural symptoms against edema and hypertension"]],
  "ai-preparedness": ["Crisis prevention", "Match stress coverage to severity and absorption", ["Oral", "Minor illness", "Use the personalized higher dose when stable and absorbing"], ["Inject", "Vomiting or major stress", "Parenteral hydrocortisone replaces failed oral coverage"], ["Prepare", "Card, kit, and trained people", "A rehearsed response shortens time to treatment"]],
  "ai-crisis": ["Emergency sequence", "Treat adrenal crisis before certainty", ["Replace", "Hydrocortisone 100 mg", "Give IV or IM immediately"], ["Resuscitate", "Isotonic saline", "Restore intravascular volume and correct hypoglycemia"], ["Continue", "200 mg over 24 hours", "Use infusion or 50 mg every six hours while treating the trigger"]],
  "ai-follow-up": ["Durable care", "Adapt replacement across changing physiology", ["Anticipate", "Pregnancy, labor, and procedures", "Plan stress coverage before demand rises"], ["Monitor", "Dose and mineralocorticoid effect", "Look for both deficiency and chronic excess"], ["Repair", "Post-crisis system review", "Correct the failed instruction, supply, recognition, or communication step"]],
};

export default function AdrenalInsufficiencyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
