const diagrams = {
  "adrenal-hpa": ["Feedback system", "Read the HPA axis as a timed control loop", ["Signal", "CRH and ACTH", "Hypothalamus drives pituitary ACTH and adrenal cortisol synthesis"], ["Respond", "Circadian and stress input", "Cortisol output rises near waking and during physiologic stress"], ["Restrain", "Negative feedback", "Endogenous and exogenous glucocorticoids reduce CRH and ACTH"]],
  "adrenal-zones": ["Cortical map", "Match each adrenal zone to its product", ["Outer", "Zona glomerulosa", "Angiotensin II and potassium regulate aldosterone"], ["Middle", "Zona fasciculata", "ACTH supports cortisol synthesis"], ["Inner", "Zona reticularis", "ACTH contributes to adrenal androgen production"]],
  "adrenal-steroidogenesis": ["Carbon flow", "Direct cholesterol through zone-specific enzymes", ["Enter", "StAR and CYP11A1", "Mitochondrial cholesterol becomes pregnenolone"], ["Branch", "CYP17A1 and CYP21A2", "Hydroxylation directs cortisol, mineralocorticoid, or androgen flow"], ["Finish", "CYP11B1 or CYP11B2", "Distinct mitochondrial enzymes complete cortisol or aldosterone"]],
  "adrenal-gr": ["Intracellular signaling", "Convert steroid exposure into gene regulation", ["Bind", "Cytosolic GR complex", "Ligand changes a chaperone-associated receptor conformation"], ["Move", "Nuclear translocation", "Activated receptor reaches chromatin and transcriptional machinery"], ["Regulate", "GRE and network effects", "Direct and indirect signaling changes inflammation and metabolism"]],
  "adrenal-mr": ["Prereceptor selectivity", "Protect mineralocorticoid signaling from cortisol", ["Compete", "Aldosterone and cortisol", "Both can bind the mineralocorticoid receptor with high affinity"], ["Protect", "11-beta-HSD2", "Local cortisol inactivation preserves aldosterone selectivity"], ["Transport", "Sodium and potassium", "MR signaling promotes sodium retention and potassium secretion"]],
  "adrenal-sar": ["Steroid design", "Use substitutions to tune potency and salt retention", ["Activate", "11-beta-hydroxyl", "The active alcohol supports glucocorticoid receptor recognition"], ["Select", "1,2 double bond and 6-methyl", "These changes raise glucocorticoid selectivity and reduce salt retention"], ["Extend", "9-fluoro and C16 groups", "Potency rises while C16 substitution can suppress mineralocorticoid activity"]],
  "adrenal-family": ["Drug spectrum", "Choose potency and duration for the task", ["Short", "Hydrocortisone", "Endogenous-like exposure with meaningful mineralocorticoid activity"], ["Intermediate", "Prednisone family", "Flexible systemic anti-inflammatory exposure with varied activation"], ["Long", "Dexamethasone family", "High potency and long action with little mineralocorticoid effect"]],
  "adrenal-disposition": ["Exposure pathway", "Follow the drug from formulation to receptor", ["Activate", "11-keto prodrugs", "Prednisone and cortisone require conversion to active alcohols"], ["Metabolize", "Protein binding and CYP3A4", "Disposition and interacting drugs alter free and total exposure"], ["Localize", "Targeted delivery", "Route and first-pass extraction can reduce but not erase systemic effects"]],
  "adrenal-equivalence": ["Conversion logic", "Translate total daily anti-inflammatory exposure", ["Reference", "Hydrocortisone 20 mg", "Use a common approximate potency anchor"], ["Convert", "Prednisone 5 or methylprednisolone 4", "Scale the complete daily dose through equivalent units"], ["Rebuild", "Schedule and clinical context", "Duration, route, mineralocorticoid action, and indication still differ"]],
  "adrenal-safety": ["Cumulative risk", "Treat every route as part of one exposure", ["Count", "Dose, potency, time, and route", "Multiple products and metabolic inhibitors can accumulate"], ["Detect", "Systemic toxicity and suppression", "Monitor metabolic, infectious, skeletal, ocular, and endocrine effects"], ["Withdraw", "Disease control before taper", "Reduce faster above physiologic exposure and more slowly near recovery"]],
};

export default function AdrenalPharmacologyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
