const views={
  "spectrum-mechanism":["Exposure","Acetaldehyde","Steatosis","Fibrosis"],"screening-staging":["AUDIT-C","Biomarker","FIB-4","Elastography"],"recovery-system":["Motivation","Medication","Behavioral care","Follow-up"],"withdrawal":["Risk","Benzodiazepine","Monitor","Escalate"],"thiamine-nutrition":["Thiamine","Magnesium","Protein","Refeeding"],"aud-medications":["Acamprosate","Naltrexone","Baclofen","Avoid disulfiram"],"hepatitis-diagnosis":["Jaundice","AST and ALT","Infection screen","MELD"],"steroid-lille":["Eligibility","Prednisolone","Day 4 or 7","Stop if no response"],"nac-support":["NAC","Nutrition","Organ support","AUD care"],"cirrhosis-complications":["Ascites","Bleeding","HE","HCC"],"transplant-ethics":["Medical urgency","Relapse risk","Support","Center pathway"],"integrated-case":["Stabilize","Treat AUD","Protect liver","Sustain recovery"]};
export const alcoholAssociatedLiverDiseaseVisualTypes=Object.keys(views).map(key=>`alcohol-associated-liver-disease-${key}`);
export default function AlcoholAssociatedLiverDiseaseVisual({type}){const key=type.replace("alcohol-associated-liver-disease-","");const labels=views[key]||views["integrated-case"];
if(key === "transplant-ethics") {
  const nodes = [["Refer", "Medical indication", "Begin evaluation early."], ["Assess", "Benefit and risk", "Use multidisciplinary review."], ["Support", "Practical care needs", "Address access barriers."], ["Continue", "AUD and graft care", "Plan ongoing treatment."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Individualized liver-transplant evaluation and ongoing alcohol-use-disorder care"><figcaption><span>Transplant evaluation and recovery</span><strong>Refer, assess, support and continue care</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "recovery-system") {
  const nodes = [["Discuss", "Goals and readiness", "Keep the patient involved."], ["Treat", "AUD and liver disease", "Tailor professional care."], ["Connect", "Follow-up and access", "Confirm a reachable next step."], ["Reassess", "Return to drinking", "Revise care and support."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Ongoing alcohol-use-disorder recovery care alongside liver treatment"><figcaption><span>Ongoing recovery care</span><strong>Discuss, treat, connect and reassess</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "screening-staging") {
  const nodes = [["Screen", "Validated adult tool", "A positive screen prompts assessment."], ["Quantify", "Volume and strength", "Count U.S. drink equivalents."], ["Interpret", "Biomarker window", "Use exposure tests in context."], ["Stage", "Noninvasive assessment", "Review confounders and uncertainty."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Adult alcohol screening, exposure assessment and contextual fibrosis staging"><figcaption><span>Screening and liver assessment</span><strong>Ask, assess and connect care</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "spectrum-mechanism") {
  const nodes = [["Ethanol", "ADH reaction", "Forms acetaldehyde and NADH."], ["Acetaldehyde", "ALDH reaction", "Forms acetate and NADH."], ["Injury", "Redox and inflammation", "Fat and cell injury can coexist."], ["Stage", "Fibrosis and complications", "Assess the current liver phenotype."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Ethanol metabolism and assessment of alcohol-associated liver injury"><figcaption><span>Metabolism and disease</span><strong>Separate metabolism, injury and stage</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "withdrawal") {
  const nodes = [["Assess", "Risk and care setting", "Use history, current illness and available monitoring."], ["Treat", "Liver-sensitive regimen", "Titrate treatment and check response."], ["Monitor", "Symptoms and breathing", "Use valid assessment; review sedation and cognition."], ["Escalate", "Complications and recovery", "Act on seizures or delirium and connect ongoing care."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Alcohol withdrawal assessment and treatment"><figcaption><span>Withdrawal care</span><strong>Assess, treat and reassess withdrawal</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "aud-medications") {
  const nodes = [["Assess", "Recovery and liver status", "Distinguish withdrawal and verify compensation."], ["Verify", "Kidney function and opioids", "Match the exact product and regimen to the patient."], ["Monitor", "Cognition, breathing and mood", "Review adverse effects and changing organ function."], ["Continue", "Integrated recovery care", "Avoid disulfiram in ALD and coordinate follow-up."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="AUD medication selection and continuing care"><figcaption><span>Medication selection</span><strong>AUD medication selection and continuing care</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "steroid-lille") {
  const nodes = [["Select", "Severity and eligibility", "Confirm the syndrome and control treatment hazards."], ["Verify", "Drug, dose and route", "Use the prescribed regimen and assign safety reviews."], ["Assess", "Lille on day 4 or 7", "Check timed data, units and the unrounded score."], ["Act", "Response and continuing care", "Stop nonresponse and reassess new hazards promptly."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Corticosteroid selection and timed AH response review"><figcaption><span>Treatment assessment</span><strong>Corticosteroid selection and timed AH response review</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "hepatitis-diagnosis") {
  const nodes = [["Recognize", "Timeline and jaundice", "Establish exposure, recent jaundice and the clinical pattern."], ["Evaluate", "Pattern and other causes", "Assess competing causes, infection and urgent organ problems."], ["Classify", "Confidence and severity", "Use selective confirmation and assess severity separately."], ["Coordinate", "Acute care and recovery", "Continue nutrition, complication care and AUD follow-up."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="AH diagnosis and coordinated initial care"><figcaption><span>Clinical assessment</span><strong>AH diagnosis and coordinated initial care</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "nac-support") {
  const nodes = [["Select", "Eligible disease therapy", "Confirm severe AH and check steroid eligibility."], ["Verify", "Indication, dose and fluid", "Reconcile the NAC protocol, dilution, rate and reaction history."], ["Support", "Nutrition, infection and organs", "Measure intake and evaluate new deterioration promptly."], ["Reassess", "Response and recovery", "Review Lille response, organ function and continuing AUD care."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="NAC and coordinated severe hepatitis support"><figcaption><span>Coordinated care</span><strong>NAC and coordinated severe hepatitis support</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "thiamine-nutrition") {
  const nodes = [["Recognize", "Brain and glucose emergencies", "Assess new confusion or ataxia. Treat urgent hypoglycemia promptly."], ["Treat", "Thiamine and magnesium", "Match thiamine to purpose. Check and correct low magnesium."], ["Calculate", "Individual nutrition goals", "Choose the weight basis and preserve adequate energy and protein."], ["Advance", "Monitored feeding", "Assess refeeding risk, electrolytes and actual intake before escalation."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Protect cognition and rebuild nutrition with monitored feeding"><figcaption><span>Clinical priorities</span><strong>Protect cognition and rebuild nutrition</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}

if(key === "cirrhosis-complications") {
  const nodes = [["Continue", "Alcohol recovery", "Coordinate AUD treatment and liver follow-up."], ["Assess", "Ascites and infection", "Evaluate new deterioration, even without fever."], ["Protect", "Bleeding, cognition and kidneys", "Match treatment to the complication and current organ function."], ["Follow", "HCC and advanced care", "Maintain eligible surveillance, nutrition and timely referral."]];
  return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label="Alcohol recovery and cirrhosis care proceed together"><figcaption><span>Parallel care</span><strong>Alcohol recovery and cirrhosis care proceed together</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={verb}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em style={{fontSize:"0.875rem"}}>{focus}</em><p style={{fontSize:"0.875rem"}}>{detail}</p></div>)}</div></figure>;
}
return <figure className="chol-visual alcohol-associated-liver-disease-visual" aria-label={`Alcohol-associated liver disease visual: ${key.replaceAll("-"," ")}`}><div className="chol-visual__copy"><span>Liver and recovery</span><h3>{key.replaceAll("-"," ")}</h3><p>Connect hepatic injury, withdrawal safety, addiction treatment, nutrition, and long-term recovery without stigma.</p></div><div className="chol-visual__stage" aria-hidden="true"><svg viewBox="0 0 620 300"><defs><linearGradient id={`ald-${key}`} x1="0" x2="1"><stop stopColor="#e8c181" stopOpacity=".55"/><stop offset="1" stopColor="#793732" stopOpacity=".12"/></linearGradient></defs><path d="M179 183 C166 129 203 77 274 67 C351 56 434 83 451 137 C469 194 407 236 334 241 C258 247 193 225 179 183Z" fill={`url(#ald-${key})`} stroke="#d2a261" strokeOpacity=".42"/><path d="M305 70 C285 113 287 186 319 238" fill="none" stroke="#f0ce94" strokeOpacity=".25"/>{labels.map((label,index)=>{const p=[[89,58],[531,58],[89,245],[531,245]][index];return <g key={label}><path d={`M${p[0]} ${p[1]} Q310 150 310 150`} fill="none" stroke="#c99a62" strokeOpacity=".3"/><circle cx={p[0]} cy={p[1]} r="5" fill={index===0?"#efd19a":"#9f4a43"}/><text x={p[0]} y={p[1]-15} textAnchor="middle" fill="#f3eee6" fontSize="14">{label}</text></g>})}</svg></div></figure>}
