const diagrams={
"ar-pediatric-formulations":{"accent": "#c5a36c", "eyebrow": "Pediatric formulation check", "title": "Age, concentration, and daily total", "columns": [["Identify", "Product and indication", "A liquid and a dissolving tablet can have different minimum ages."], ["Measure", "mL × mg/mL = mg", "Cetirizine 1 mg/mL: 2.5 mL supplies 2.5 mg."], ["Reconcile", "Count every dose", "At ages 2–5, the reviewed cetirizine liquid permits at most 5 mg/day; alternative schedules are not additive."]]},
"ar-first-generation-formulations":{"accent": "#b99375", "eyebrow": "Release formulation matters", "title": "One ingredient, different intervals", "columns": [["Immediate release", "Chlorpheniramine 4 mg", "Reviewed adult tablet: one every 4–6 hours, at most six in 24 hours."], ["Extended release", "Chlorpheniramine 12 mg", "Reviewed adult tablet: one every 12 hours, at most two in 24 hours."], ["Shared risk", "24 mg/day is a ceiling", "Both schedules can cause sedation and anticholinergic harm. Never combine them to extend the maximum."]]},

"ar-otc-steroids":{"accent": "#c5a36c", "eyebrow": "OTC steroid selection", "title": "Product, age, dose and follow-up", "columns": [["Identify", "Exact formulation", "Fluticasone propionate and furoate have different strengths and pediatric ages."], ["Calculate", "Both nostrils", "Sprays per nostril × two nostrils × strength × daily frequency."], ["Reassess", "Label-specific timing", "Rhinocort: two weeks without improvement; reviewed Flonase, Nasacort and Nasonex: one week."]]},
"ar-prescription-steroids":{"accent": "#c5a36c", "eyebrow": "Prescription delivery", "title": "One class, different devices", "columns": [["Omnaris", "Seasonal ≥6; perennial ≥12", "50 mcg spray; two per nostril once daily."], ["Zetonna", "Seasonal or perennial ≥12", "37 mcg aerosol; one per nostril once daily."], ["Qnasl", "Strength depends on age", "40 mcg for ages 4–11; 80 mcg from age 12. No priming."]]},
"ar-nasal-antihistamines":{"accent": "#c5a36c", "eyebrow": "Nasal antihistamine products", "title": "Single agents and combinations", "columns": [["Single agent", "Astepro or olopatadine", "Check age-specific dosing; nasal antihistamines can cause sedation."], ["Combination", "Dymista or Ryaltris", "Each contains an antihistamine and a corticosteroid; doses differ."], ["Safety", "Review before use", "Consider sedation, interactions, nasal injury and product-specific warnings."]]},
"ar-oral-antihistamines":{"accent": "#c5a36c", "eyebrow": "Oral antihistamine selection", "title": "Match the product to the patient", "columns": [["Formulation", "Check label and indication", "Tablet, liquid and combination directions cannot be freely exchanged."], ["Function", "Kidney and liver review", "OTC advice and prescription dose adjustments may differ."], ["Follow-up", "Recognize adverse effects", "Review sedation, urinary symptoms and severe itching after stopping chronic cetirizine or levocetirizine."]]},
"ar-phenotype":{accent:"#b99375",eyebrow:"Rhinitis differential",title:"Pattern, trigger, anatomy, and red flags",columns:[["Allergic","Itch, sneeze, eye","Relevant allergen exposure and IgE"],["Nonallergic","Irritant or neural","Weather, odor, food, hormones, medicine"],["Other","Infection or structure","Sinus, septum, polyp, leak, foreign body, mass"]]},
"ar-immunology":{accent:"#c88372",eyebrow:"Allergic cascade",title:"From sensitization to an allergic response",columns:[["Prime","Allergen-specific IgE","B-cell class switching and mast-cell loading"],["Trigger","Mediator release","Histamine drives rapid itch, sneeze, and rhinorrhea"],["Persist","Late inflammation","Cell recruitment sustains congestion and hyperreactivity"]]},
"ar-technique":{accent:"#7da39b",eyebrow:"Delivery system",title:"Prepare, follow product directions, reassess",columns:[["Prepare","Prime and clear","Correct product setup and a gently cleared nose"],["Place","Away from septum","Lateral aim; head and breathing per product"],["Prove","Return technique","Observe use, adherence, tolerability, and response"]]},
"ar-therapy":{accent:"#8a9db4",eyebrow:"Treatment ladder",title:"Local control first, combination when needed",columns:[["Control","Intranasal steroid","Broad anti-inflammatory symptom control"],["Accelerate","Intranasal antihistamine","Rapid local H1 blockade across phenotypes"],["Combine","Fixed nasal product","Conditional choice: onset, response, cost and preference"]]},
"ar-adjuncts":{accent:"#9e9273",eyebrow:"Residual symptom map",title:"Name the unresolved problem before adding therapy",columns:[["Secretion","Ipratropium","Target profuse watery rhinorrhea"],["Eye","Topical antihistamine","Treat uncomplicated allergic itching and tearing"],["Boundary","Decongestant or montelukast","Define duration, eligibility, and serious risk"]]},
"ar-safety":{accent:"#a48ba2",eyebrow:"Benefit and burden",title:"Age, pregnancy, cognition, airway, and anatomy",columns:[["Patient","Development and life","Growth, school, work, pregnancy, falls"],["Product","Local and systemic harm","Bleeding, sedation, pressure, retention, interactions"],["Pathway","Refer when needed","Asthma, polyps, structure, unilateral signs, occupational disease"]]},
"ar-followup":{accent:"#739ca0",eyebrow:"Control loop",title:"Measure, audit, adapt, and simplify",columns:[["Measure","Symptoms and function","Sleep, work, eye, nose, rescue use, and adverse effects"],["Audit","Exposure and delivery","Access, technique, persistence, and treatment duration"],["Adapt","Continue or redirect","Step down, escalate, refer, or revise the diagnosis"]]},
"ar-immunotherapy":{accent:"#c5a36c",eyebrow:"Disease modification",title:"Relevant allergen, controlled exposure, sustained course",columns:[["Confirm","Clinical relevance","Test, exposure, and symptom pattern agree"],["Choose","SCIT or approved SLIT","Setting, protocol, adherence, and patient goals"],["Protect","Anaphylaxis readiness","Asthma control, epinephrine, observation, education"]]}
};
export default function AllergicRhinitisVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
