const diagrams={
"ar-phenotype":{accent:"#b99375",eyebrow:"Rhinitis differential",title:"Pattern, trigger, anatomy, and red flags",columns:[["Allergic","Itch, sneeze, eye","Relevant allergen exposure and IgE"],["Nonallergic","Irritant or neural","Weather, odor, food, hormones, medicine"],["Other","Infection or structure","Sinus, septum, polyp, leak, foreign body, mass"]]},
"ar-immunology":{accent:"#c88372",eyebrow:"Allergic cascade",title:"Sensitization becomes symptoms through exposure",columns:[["Prime","Allergen-specific IgE","B-cell class switching and mast-cell loading"],["Trigger","Mediator release","Histamine drives rapid itch, sneeze, and rhinorrhea"],["Persist","Late inflammation","Cell recruitment sustains congestion and hyperreactivity"]]},
"ar-technique":{accent:"#7da39b",eyebrow:"Delivery system",title:"Prepare, aim laterally, inhale gently, reassess",columns:[["Prepare","Prime and clear","Correct product setup and a gently cleared nose"],["Place","Away from septum","Neutral head and lateral nozzle direction"],["Prove","Return technique","Observe use, adherence, tolerability, and response"]]},
"ar-therapy":{accent:"#8a9db4",eyebrow:"Treatment ladder",title:"Local control first, combination when needed",columns:[["Control","Intranasal steroid","Broad anti-inflammatory symptom control"],["Accelerate","Intranasal antihistamine","Rapid local H1 blockade across phenotypes"],["Combine","Fixed nasal product","Greater and faster control when monotherapy is insufficient"]]},
"ar-adjuncts":{accent:"#9e9273",eyebrow:"Residual symptom map",title:"Name the unresolved problem before adding therapy",columns:[["Secretion","Ipratropium","Target profuse watery rhinorrhea"],["Eye","Topical antihistamine","Treat uncomplicated allergic itching and tearing"],["Boundary","Decongestant or montelukast","Define duration, eligibility, and serious risk"]]},
"ar-safety":{accent:"#a48ba2",eyebrow:"Benefit and burden",title:"Age, pregnancy, cognition, airway, and anatomy",columns:[["Patient","Development and life","Growth, school, work, pregnancy, falls"],["Product","Local and systemic harm","Bleeding, sedation, pressure, retention, interactions"],["Pathway","Refer when needed","Asthma, polyps, structure, unilateral signs, occupational disease"]]},
"ar-followup":{accent:"#739ca0",eyebrow:"Control loop",title:"Measure, audit, adapt, and simplify",columns:[["Measure","Symptoms and function","Sleep, work, eye, nose, rescue use, and adverse effects"],["Audit","Exposure and delivery","Access, technique, persistence, and treatment duration"],["Adapt","Continue or redirect","Step down, escalate, refer, or revise the diagnosis"]]},
"ar-immunotherapy":{accent:"#c5a36c",eyebrow:"Disease modification",title:"Relevant allergen, controlled exposure, sustained course",columns:[["Confirm","Clinical relevance","Test, exposure, and symptom pattern agree"],["Choose","SCIT or approved SLIT","Setting, protocol, adherence, and patient goals"],["Protect","Anaphylaxis readiness","Asthma control, epinephrine, observation, education"]]}
};
export default function AllergicRhinitisVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
