export const animalHumanBitesVisualTypes=["bite-triage","dog-cat-mechanics","human-bites","bite-wound-care","bite-microbiology","antibiotic-prophylaxis","infected-bites","rabies-risk","rabies-pep","prevention-follow-up"];
const diagrams={
"bite-triage":["Exposure triage","Identify life threats, anatomy, exposure biology, and time-sensitive prevention",["Stabilize","Bleeding and major trauma","Life threats come first"],["Map","Species, mechanism, site","Surface size can mislead"],["Test","Motion, sensation, perfusion","Protect deep structures"],["Prevent","Tetanus, rabies, blood exposure","Start clocks early"]],
"dog-cat-mechanics":["Mechanism map","Crush, tear, puncture, inoculation, and host risk create different wounds",["Dog","Crush and laceration","Inspect devitalized tissue"],["Cat","Deep narrow puncture","Assume hidden inoculation"],["Hand","Tendon and joint proximity","Test function carefully"],["Host","Immune and vascular reserve","Lower the referral threshold"]],
"human-bites":["Human bite pathway","Direct bites and closed-fist injuries threaten tissue, joint, and blood exposure",["Expose","Open the clenched hand","Inspect the true tract"],["Explore","Joint, tendon, tooth fragment","Small wounds can be deep"],["Screen","Blood in either direction","Assess both people"],["Escalate","Hand surgery and infection care","Delay threatens function"]],
"bite-wound-care":["Wound-care sequence","Control bleeding, irrigate, explore, debride selectively, and plan closure",["Clean","Soap and copious water","Reduce inoculum early"],["Inspect","Depth and foreign material","Do not probe blindly"],["Preserve","Viable tissue and function","Debride by indication"],["Close","Site and contamination decide","Follow-up remains essential"]],
"bite-microbiology":["Polymicrobial ecology","Mouth flora, skin flora, wound conditions, and host reserve shape infection",["Animal","Pasteurella and mixed flora","Rapid local infection can occur"],["Human","Eikenella and anaerobes","Common narrow drugs can fail"],["Host","Capnocytophaga risk","Asplenia raises urgency"],["Depth","Abscess, joint, bone","Source control matters"]],
"antibiotic-prophylaxis":["Preemptive decision","Use wound, anatomy, delay, closure, and host risk instead of treating every bite alike",["High risk","Hand, face, foot, deep puncture","Benefit is more plausible"],["Host risk","Immune, spleen, liver, vascular","Complications can accelerate"],["Coverage","Aerobes plus anaerobes","Match oral flora"],["Recheck","Twenty-four to forty-eight hours","Prophylaxis is not closure"]],
"infected-bites":["Infection pathway","Classify severity, obtain useful cultures, cover mixed flora, and secure source control",["Recognize","Pain, swelling, pus, spread","Trajectory defines concern"],["Culture","Drainage or severe disease","Use results to narrow"],["Treat","Aerobic and anaerobic cover","Account for allergy and organs"],["Escalate","Abscess, joint, bone, sepsis","Procedure can be decisive"]],
"rabies-risk":["Rabies assessment","Species, geography, behavior, exposure route, and animal availability determine the public-health pathway",["Exposure","Bite, scratch, saliva to tissue","Objects do not transmit rabies"],["Animal","Bat and reservoir species","Risk varies by place"],["Observe","Healthy dog, cat, ferret","Coordinate ten-day observation"],["Decide","Public-health consultation","Do not guess alone"]],
"rabies-pep":["Postexposure protection","Wound cleansing, immune globulin, and vaccine create immediate and active protection",["Clean","Soap, water, virucidal agent","Begin immediately"],["HRIG","Infiltrate around wounds","One dose for unvaccinated people"],["Vaccine","Days zero, three, seven, fourteen","Use the deltoid or thigh"],["Adapt","Prior vaccine or immune compromise","Regimen changes"]],
"prevention-follow-up":["Closed-loop prevention","Tetanus, bloodborne assessment, safeguarding, infection review, and function complete care",["Tetanus","Dirty or major wound rules","Document the series"],["Blood","Visible blood changes risk","Human bites expose both people"],["Protect","Safeguarding and reporting","Context matters"],["Return","Function, infection, systemic signs","Set a dated checkpoint"]],
};
export default function AnimalHumanBitesVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual animal-human-bites-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
