const diagrams = {
  "antiplatelet-platelet-cycle": { eyebrow: "Platelet biology", title: "Vessel injury recruits platelets through adhesion, activation, secretion, and aggregation.", accent: "#c36f64", columns: [["Adhere", "vWF and GPIb", "Anchor platelets at injured endothelium"], ["Activate", "ADP, thromboxane, and thrombin", "Amplify shape change and secretion"], ["Recruit", "P2Y12 signaling", "Sustain activation and lower cyclic AMP"], ["Aggregate", "GPIIb/IIIa and fibrinogen", "Bridge activated platelets"]] },
  "antiplatelet-aspirin": { eyebrow: "Thromboxane control", title: "Aspirin acetylates platelet COX-1 irreversibly, so recovery depends on production of new platelets.", accent: "#c69a62", columns: [["Enter", "Rapidly absorbed loading dose", "Match formulation to urgency"], ["Acetylate", "Platelet COX-1", "Block arachidonic acid conversion"], ["Suppress", "Thromboxane A2", "Reduce activation and vasoconstriction"], ["Recover", "New platelet production", "Effect persists beyond plasma exposure"]] },
  "antiplatelet-p2y12": { eyebrow: "Oral P2Y12 strategy", title: "Clopidogrel, prasugrel, and ticagrelor share a target but differ in activation, reversibility, dosing, interactions, and recovery.", accent: "#7f9eb4", columns: [["Clopidogrel", "Two-step prodrug", "CYP2C19 variability matters"], ["Prasugrel", "Efficient prodrug activation", "Avoid after stroke or TIA"], ["Ticagrelor", "Direct reversible inhibitor", "Twice daily with dyspnea risk"], ["Select", "Patient and procedure", "Balance ischemia, bleeding, access, and adherence"]] },
  "antiplatelet-iv-agents": { eyebrow: "Intravenous platelet control", title: "Cangrelor provides rapid reversible P2Y12 inhibition, while GPIIb/IIIa inhibitors block the final aggregation pathway.", accent: "#a78ab4", columns: [["Cangrelor", "Seconds to effect", "Useful when oral therapy is not established"], ["Transition", "Time oral loading correctly", "Prevent a gap or receptor competition"], ["Eptifibatide", "GPIIb/IIIa blockade", "Renal dose and platelet surveillance"], ["Tirofiban", "GPIIb/IIIa blockade", "Renal adjustment and bleeding control"]] },
  "antiplatelet-variability": { eyebrow: "Response variability", title: "An apparent treatment failure can reflect biology, activation, absorption, interaction, adherence, or the wrong diagnosis.", accent: "#8ca17a", columns: [["Verify", "Administration and adherence", "Confirm load, maintenance, and access"], ["Review", "Genes and interactions", "CYP2C19 and CYP3A can matter"], ["Measure", "Selected testing", "Use only when a result can change care"], ["Act", "Switch or correct the cause", "Avoid blind dose escalation"]] },
  "antiplatelet-bleeding": { eyebrow: "Safety and procedures", title: "Safe platelet inhibition requires a written plan for bleeding, procedures, interruption, resumption, and counseling.", accent: "#b88c62", columns: [["Assess", "Site and severity", "Check hemodynamics, hemoglobin, and platelets"], ["Control", "Source and supportive care", "Stop active bleeding and restore perfusion"], ["Coordinate", "Procedure timing", "Account for agent-specific offset"], ["Restart", "Ischemic indication", "Resume when hemostasis permits"]] },
};

export default function AntiplateletPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
