export const antimicrobialFoundationsStewardshipVisualTypes = [
  "infection-hypothesis", "specimen-diagnostics", "empiric-therapy", "susceptibility-interpretation", "pk-pd-optimization",
  "resistance-mechanisms", "definitive-therapy", "source-control-response", "stewardship-interventions", "measurement-handoff",
];

const diagrams = {
  "infection-hypothesis": ["Clinical frame", "Build an infection hypothesis before naming an antimicrobial", ["Syndrome", "Localize the process", "Anatomic site predicts pathogens, penetration, and source control"], ["Host", "Define the clinical margin", "Immune status, organ function, devices, and prior exposure reshape risk"], ["Severity", "Set the speed and breadth", "Instability can justify immediate broad empiric therapy"], ["Alternatives", "Keep noninfection visible", "Inflammation, ischemia, toxin, and medication effects can mimic infection"]],
  "specimen-diagnostics": ["Diagnostic chain", "Make every specimen capable of changing treatment", ["Indicate", "Ask a clinical question", "Do not culture colonized sites without a syndrome"], ["Collect", "Right site, time, and volume", "Obtain high-value samples before therapy when safe"], ["Protect", "Prevent contamination", "Technique preserves the meaning of a positive result"], ["Interpret", "Integrate the result", "Organism, burden, site, host, and prior therapy determine significance"]],
  "empiric-therapy": ["Empiric design", "Cover what is dangerous and plausible without treating every organism", ["Site", "Likely pathogen ecology", "Community, hospital, device, and anatomic source matter"], ["History", "Resistance probability", "Prior cultures and recent antimicrobials are patient-specific data"], ["Drug", "Exposure at the target", "Spectrum, penetration, allergy, organ function, and interactions constrain choice"], ["Clock", "Reassessment plan", "Every empiric regimen needs a stop, narrow, or confirm checkpoint"]],
  "susceptibility-interpretation": ["AST reasoning", "Translate an in vitro category into a patient-specific regimen", ["Identity", "Confirm organism relevance", "A laboratory result does not prove infection"], ["MIC", "Read against a breakpoint", "The number has meaning only for the organism, drug, method, and dosing context"], ["Category", "S, SDD, I, or R", "SDD requires the specified higher or prolonged exposure"], ["Clinical fit", "Site and patient", "Penetration, source control, safety, and evidence remain necessary"]],
  "pk-pd-optimization": ["Exposure target", "Match dose design to the pharmacodynamic driver", ["Time", "Time above MIC", "Beta-lactam exposure can improve through shorter intervals or prolonged infusion"], ["Peak", "Peak relative to MIC", "Aminoglycoside activity favors an adequate peak with toxicity-aware spacing"], ["Area", "AUC relative to MIC", "Total exposure matters for agents such as vancomycin"], ["Patient", "Dynamic pharmacokinetics", "Kidney function, weight, fluids, critical illness, and support therapies change exposure"]],
  "resistance-mechanisms": ["Resistance map", "Connect the mechanism to the phenotype and the next diagnostic question", ["Destroy", "Enzymatic inactivation", "Beta-lactamases and modifying enzymes neutralize drug"], ["Change", "Target modification", "Altered binding reduces antimicrobial effect"], ["Exclude", "Permeability and efflux", "Less drug reaches the intracellular target"], ["Persist", "Biofilm and selected populations", "Devices and exposure can protect difficult-to-eradicate communities"]],
  "definitive-therapy": ["Therapy convergence", "Turn early uncertainty into the narrowest effective complete plan", ["Confirm", "Diagnosis and organism", "Reconcile microbiology with syndrome and response"], ["Narrow", "Spectrum and number of agents", "Remove redundant or unsupported coverage"], ["Optimize", "Dose, route, interval, duration", "Use site, MIC, PK/PD, organ function, and evidence"], ["Document", "Endpoint and contingency", "State indication, planned stop date, monitoring, and failure response"]],
  "source-control-response": ["Response audit", "When treatment fails, recheck the whole system rather than only changing drugs", ["Patient", "Trajectory and severity", "Vital signs, organ function, symptoms, and biomarkers provide trends"], ["Drug", "Exposure and toxicity", "Dose, delivery, absorption, interactions, and adherence can fail"], ["Microbe", "Identity and resistance", "The pathogen, phenotype, or diagnosis can be wrong"], ["Source", "Drain, remove, repair", "Abscess, obstruction, necrosis, and infected hardware can defeat adequate therapy"]],
  "stewardship-interventions": ["Stewardship system", "Coordinate people and interventions around safer antimicrobial decisions", ["Lead", "Accountability and expertise", "Leadership, physician, pharmacist, laboratory, nursing, and infection prevention align"], ["Guide", "Local evidence", "Guidelines and antibiograms shape but do not replace patient assessment"], ["Intervene", "Preauthorization and feedback", "High-impact review changes drug, dose, route, and duration"], ["Teach", "Transparent reasoning", "Education works best when paired with actionable systems"]],
  "measurement-handoff": ["Closed loop", "Measure use, communicate the plan, and learn from outcomes", ["Count", "Days of therapy", "Any amount of one agent on one patient-day counts as one antimicrobial day"], ["Balance", "Use and harm", "Track appropriateness, resistance, C difficile, toxicity, and clinical outcomes"], ["Handoff", "Indication and stop plan", "Transitions preserve cultures, pending tests, duration, and monitoring"], ["Improve", "Feedback cycle", "Report data to teams, test changes, and watch for unintended effects"]],
};

export default function AntimicrobialFoundationsStewardshipVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual antimicrobial-foundations-stewardship-visual" aria-label={title}>
    <figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption>
    <div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}>
      <span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p>
    </div>)}</div>
  </figure>;
}
