const diagrams = {
  "htn-medchem-ace": { eyebrow: "ACE inhibitor design", title: "A zinc-binding motif, peptide-mimetic geometry, and exposure strategy define each ACE inhibitor.", accent: "#7ca7bc", columns: [["Anchor", "Thiol, carboxylate, or phosphinate", "Coordinate catalytic zinc differently"], ["Recognition", "Proline-like terminus", "Fit the peptidase substrate pocket"], ["Exposure", "Active drug or ester prodrug", "Balance polarity with oral absorption"], ["Behavior", "Renal clearance + duration", "Structure predicts monitoring, not indication alone"]] },
  "htn-medchem-arb": { eyebrow: "RAAS ligand design", title: "ARB and renin-inhibitor scaffolds solve different recognition problems in the same pathway.", accent: "#c28770", columns: [["ARB acid", "Tetrazole or carboxylate", "Create a persistent anionic recognition group"], ["Hydrophobe", "Biphenyl and related domains", "Occupy AT1 lipophilic regions"], ["Prodrug", "Medoxomil or cilexetil ester", "Mask polarity before hydrolysis"], ["Renin", "Large peptidomimetic", "High affinity creates a permeability tradeoff"]] },
  "htn-medchem-ccb": { eyebrow: "Calcium-channel scaffolds", title: "Dihydropyridine oxidation, ionization, and ring substitution shape vascular exposure and duration.", accent: "#c2a061", columns: [["Core", "1,4-dihydropyridine", "Redox-sensitive ring supports L-type binding"], ["Esters", "3,5-dicarboxylates", "Tune shape, lipophilicity, and metabolism"], ["Aryl", "C4 substituted phenyl", "Orientation and electronics influence binding"], ["Access", "Amlodipine basic side chain", "Long residence differs from faster lipophilic agents"]] },
  "htn-medchem-central": { eyebrow: "Central and adrenergic agents", title: "Charge, lipophilicity, and metabolic activation determine access to central pressure circuits.", accent: "#9b8dbb", columns: [["Clonidine", "Imidazoline-like basic scaffold", "Central access and receptor engagement"], ["Methyldopa", "Amino-acid prodrug", "Transport and enzymatic conversion create active transmitter"], ["Beta block", "Aryloxypropanolamine", "Substitution tunes receptor and tissue exposure"], ["Alpha block", "Quinazoline or sulfonamide designs", "Urovascular preference is whole-molecule behavior"]] },
  "htn-medchem-vasodilator": { eyebrow: "Direct vasodilators", title: "Reactive, donor, channel-opening, and endothelin scaffolds demand different safety reasoning.", accent: "#c77c6e", columns: [["Hydralazine", "Hydrazinophthalazine", "Acetylation and reactive chemistry affect exposure"], ["Minoxidil", "Sulfate-active metabolite", "Bioactivation opens potassium channels"], ["Nitro agents", "NO or nitrosyl delivery", "Release kinetics and toxic metabolites matter"], ["Endothelin", "Dual receptor antagonist", "Potent oral scaffold carries fluid and fetal risk"]] },
  "htn-medchem-integration": { eyebrow: "Structure to product", title: "The clinically relevant molecule includes stereochemistry, salt, formulation, metabolism, and patient physiology.", accent: "#8fa57c", columns: [["Identity", "Active moiety + stereochemistry", "Do not confuse salt mass with active structure"], ["Delivery", "Immediate, extended, or infusion", "Formulation changes the concentration curve"], ["Metabolism", "Active drug, prodrug, active metabolite", "Genotype and interactions may alter exposure"], ["Decision", "Structure plus patient context", "Chemistry predicts questions, not outcomes by itself"]] },
};

export default function AntihypertensiveMedicinalChemistryVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
