const diagrams = {
  "arrhythmia-cell-electrophysiology": { eyebrow: "Cellular electrophysiology", title: "Fast-response and slow-response tissues use different currents, conduction velocities, refractory behavior, and drug-sensitive phases.", accent: "#b57a67", columns: [["Fast tissue", "Sodium-driven phase 0", "Atria, ventricles, His-Purkinje"], ["Slow tissue", "Calcium-driven phase 0", "SA and AV nodes"], ["Repolarize", "Potassium currents", "Restore excitability"], ["Refractory", "Channel recovery", "Limits premature propagation"]] },
  "arrhythmia-automaticity": { eyebrow: "Impulse generation", title: "Enhanced normal automaticity and abnormal automaticity create focal rhythms when phase 4 slope, threshold, or maximum diastolic potential changes.", accent: "#87a68a", columns: [["Slope", "Faster phase 4 rise", "Reach threshold sooner"], ["Threshold", "Easier activation", "Increase firing probability"], ["Potential", "Less negative baseline", "Alter channel availability"], ["Drivers", "Catecholamines, ischemia, electrolytes", "Correct the substrate"]] },
  "arrhythmia-triggered-activity": { eyebrow: "Triggered activity", title: "Afterdepolarizations depend on a preceding action potential and emerge from repolarization delay or intracellular calcium overload.", accent: "#9d8db8", columns: [["EAD", "During phases 2 or 3", "Long QT and pause dependence"], ["DAD", "After repolarization", "Calcium overload and fast rates"], ["Trigger", "Cross threshold", "Create ectopy or tachycardia"], ["Control", "Remove cause and stabilize", "Match therapy to mechanism"]] },
  "arrhythmia-reentry": { eyebrow: "Reentry", title: "Reentry requires a circuit, unidirectional block, and conduction slow enough for previously refractory tissue to recover before the impulse returns.", accent: "#c39861", columns: [["Circuit", "Anatomic or functional path", "Provide a route"], ["Block", "One direction fails", "Force alternate travel"], ["Delay", "Slow conduction", "Allow recovery ahead"], ["Interrupt", "Block pathway or prolong refractoriness", "Terminate the loop"]] },
  "arrhythmia-substrate-triggers": { eyebrow: "Substrate and triggers", title: "Fibrosis, scar, chamber stretch, ischemia, genetics, autonomic tone, drugs, and metabolic stress combine to initiate and sustain arrhythmia.", accent: "#ba6f6f", columns: [["Substrate", "Scar, fibrosis, dilation", "Create heterogeneity"], ["Trigger", "Premature beat or burst", "Enter the vulnerable circuit"], ["Modulator", "Autonomic and metabolic state", "Change threshold and conduction"], ["Outcome", "Burden and hemodynamics", "Determine clinical consequence"]] },
  "arrhythmia-mechanism-treatment": { eyebrow: "Mechanism to treatment", title: "Rate, rhythm, electrical therapy, ablation, devices, and risk-factor control work at different levels of the arrhythmia system.", accent: "#819db2", columns: [["Stabilize", "Restore perfusion", "Electric therapy when unstable"], ["Suppress", "Alter channels or autonomic tone", "Reduce initiation or maintenance"], ["Eliminate", "Ablate circuit or focus", "Modify the substrate"], ["Prevent harm", "Anticoagulation and devices", "Address downstream risk"]] },
};
export default function ArrhythmiaPathophysiologyVisual({ type }) { const d = diagrams[type]; if (!d) return null; return <figure className="chol-visual" style={{ "--chol-accent": d.accent }} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([name, action, detail], i) => <div key={name}><span>{String(i + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div></figure>; }
