const diagrams = {
  "asthma-biologics": {"accent": "#b99754", "eyebrow": "Product-specific decisions", "title": "Target, regimen and delivery must agree", "columns": [["Target", "Identify the pathway", "A cytokine and its receptor are different binding targets"], ["Regimen", "Check age and interval", "Related mechanisms do not make doses interchangeable"], ["Delivery", "Confirm who administers", "Home use depends on the exact device and patient selection"]]},
  "asthma-omalizumab": {"accent": "#b99754", "eyebrow": "Dose verification", "title": "A complete dose includes its interval and presentation", "columns": [["Select", "Use the asthma table", "Match age, weight and pretreatment IgE"], ["Schedule", "Read the interval", "The same milligram dose may have a different interval"], ["Administer", "Identify the presentation", "Vial and prefilled volumes and site instructions differ"]]},

  "asthma-aerosol-devices": {"accent": "#b99754", "eyebrow": "Device identification", "title": "Identify the inhaler before preparing a dose", "columns": [["Identify", "Exact product and device", "An ingredient name does not determine priming or cleaning"], ["Prepare", "Use its own instructions", "Separate test sprays from prescribed treatment puffs"], ["Observe", "Patient demonstration", "Check loading, actuation and inhalation together"]]},
  "asthma-powder-devices": {"accent": "#b99754", "eyebrow": "Dry-powder delivery", "title": "Loading a dose is not proof of inhaling it", "columns": [["Load", "Follow the device sequence", "A lever, twist or cap prepares the dose"], ["Inhale", "Keep exhaled moisture out", "Exhale away, then use the instructed inspiratory technique"], ["Verify", "Watch the demonstration", "Counter movement and taste alone do not prove delivery"]]},
  "asthma-nebulized-preparation": {"accent": "#b99754", "eyebrow": "Prescribed dilution example", "title": "Drug amount and final volume are separate quantities", "columns": [["Prescribed", "2.5 mg albuterol", "The drug amount remains 2.5 mg after dilution"], ["Measure", "0.5 mL of 5 mg/mL", "2.5 mg divided by 5 mg/mL gives 0.5 mL"], ["Dilute", "Add 2.5 mL saline", "0.5 mL drug plus 2.5 mL saline gives 3 mL"]]},
  "asthma-biology": { accent: "#b77968", eyebrow: "Airway biology", title: "Inflammation changes flow, sensitivity, and structure", columns: [["Signal", "Inflammatory network", "Epithelium, immune cells, cytokines, edema, and mucus"], ["Narrow", "Variable obstruction", "Smooth muscle contraction changes expiratory flow"], ["Persist", "Remodeling risk", "Repeated injury can make limitation less reversible"]] },
  "asthma-diagnosis": { accent: "#8aa5b7", eyebrow: "Diagnostic logic from age 6", title: "Pattern, variability, confirmation, and phenotype", columns: [["Pattern", "Variable symptoms", "Wheeze, dyspnea, tightness, or cough change over time"], ["Prove", "Variable airflow", "Spirometry, peak flow, treatment response, or challenge"], ["Describe", "Traits and mimics", "Type 2 signals, exposure, occupation, and competing disease"]] },
  "asthma-risk": { accent: "#c79a77", eyebrow: "Longitudinal control", title: "Measure impairment and future danger separately", columns: [["Now", "Symptom control", "Four weeks: day, night, activity and symptom-driven SABA; exclude pre-exercise use"], ["Next", "Future risk", "Prior attacks, low airflow, SABA exposure, and inadequate ICS"], ["Verify", "Implementation", "Access, adherence, technique, exposure, and comorbidity"]] },
  "asthma-pharmacology": { accent: "#8da68a", eyebrow: "Airway pharmacology", title: "Relieve smooth muscle and control inflammation", columns: [["Relax", "Beta2 agonism", "Beta2 signaling raises cyclic AMP to relax airway muscle"], ["Control", "Inhaled steroid", "Repeated airway exposure suppresses inflammatory signaling"], ["Deliver", "Device and technique", "Flow, coordination, spacer, access, and preference shape dose"]] },
  "asthma-adjuncts": { accent: "#9e8b6d", eyebrow: "Add-on pharmacology", title: "Add a pathway only when benefit exceeds burden", columns: [["Open", "Muscarinic blockade", "Reduce vagal bronchoconstriction with a selected short or long role"], ["Modify", "Leukotriene signaling", "Check agent-specific mood, liver and interaction precautions"], ["Monitor", "Systemic exposure", "Theophylline and corticosteroids demand toxicity surveillance"]] },
  "asthma-strategy": { accent: "#c9a45f", eyebrow: "Adult and adolescent controller and reliever", title: "Both tracks preserve inhaled corticosteroid exposure", columns: [["Track 1", "ICS-formoterol", "AIR-only for Steps 1 and 2, MART for Steps 3 through 5"], ["Track 2", "ICS-containing alternative", "ICS-SABA or daily ICS-containing control plus reliever"], ["Context", "Guideline and label", "Match evidence to product, age, device, jurisdiction, and limit"]] },
  "asthma-severe": { accent: "#a78da8", eyebrow: "Advanced disease", title: "Confirm severe asthma before selecting a biologic", columns: [["Confirm", "Optimized treatment", "Verify diagnosis, adherence and technique; address contributing factors"], ["Profile", "Treatable traits", "Allergy, eosinophils, FeNO, polyps, dermatitis, and steroid burden"], ["Target", "Biologic pathway", "IgE, IL-5 or its receptor, IL-4R alpha, or TSLP; reassess response"]] },
  "asthma-acute": { accent: "#c56f62", eyebrow: "Acute pathway", title: "Assess, reverse, suppress, reassess, and prevent", columns: [["Triage", "Severity and failure", "Speech, effort, oxygen, airflow, mental status, and quiet chest"], ["Treat", "Airflow and inflammation", "Rapid bronchodilator; oxygen for hypoxemia; adjuncts by severity"], ["Close", "Prevention loop", "ICS-containing regimen, technique, action plan, and early follow-up"]] },
};

export default function AsthmaVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, mechanism, explanation], index) => <div key={name}>
      <span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{mechanism}</em><p>{explanation}</p>
    </div>)}</div>
  </figure>;
}
