export const atopicDermatitisVisualTypes=["diagnosis-assessment","barrier-immunology","foundational-skin-care","topical-corticosteroids","steroid-sparing-topicals","newer-topicals","infection-flare-rescue","biologics-phototherapy","systemic-safety","special-populations-follow-up"];
const diagrams={
"diagnosis-assessment":["Clinical pattern","Confirm disease, quantify burden, and protect dangerous mimics",["Pattern","Relapsing pruritic eczema","Use age, site, morphology, xerosis, and history"],["Burden","Skin plus life","Measure itch, sleep, pain, infection, function, and mood"],["Mimic","Conflicting clues","Consider contact disease, scabies, psoriasis, infection, and drug eruption"],["Urgency","Vesicle, eye, fever, pain","Escalate infection and systemic threat"]],
"barrier-immunology":["Self-reinforcing circuit","Barrier failure, immune signaling, microbes, and scratching amplify disease",["Leak","Water and lipid loss","Dryness and fissures increase irritant entry"],["Signal","IL-4, IL-13, IL-31, JAK","Inflammation and itch weaken the barrier"],["Scratch","Mechanical injury","Excoriation deepens inflammation and infection risk"],["Repair","Barrier plus inflammation","Treat both sides of the circuit"]],
"foundational-skin-care":["Daily system","Add water, retain it, reduce irritation, and test real triggers",["Bathe","Brief and comfortable","Avoid prolonged hot exposure"],["Seal","Prompt moisturizer","Choose a tolerated ointment, cream, or lotion"],["Simplify","Fragrance-free routine","Reduce cleanser and product burden"],["Investigate","Reproducible exposure","Use patch testing when contact allergy is plausible"]],
"topical-corticosteroids":["Potency with purpose","Match drug, site, amount, time, and maintenance",["Map","Face, folds, trunk, hands","Skin vulnerability and thickness differ"],["Dose","Fingertip units","Write grams, frequency, duration, and stop rules"],["Control","Adequate flare treatment","Avoid undertreatment driven by vague fear"],["Protect","Cumulative exposure","Watch atrophy, striae, eye, infection, growth, and HPA risk"]],
"steroid-sparing-topicals":["Nonsteroidal control","Choose calcineurin or PDE4 therapy for a defined role",["Preserve","Sensitive sites","Calcineurin inhibitors avoid steroid atrophy"],["Prepare","Transient burning","Set expectations and protect adherence"],["Use","Crisaborole age 3 months","Follow exact twice-daily labeling"],["Maintain","Intermittent proactive care","Treat recurrent sites between flares"]],
"newer-topicals":["Current topical landscape","Match pathway, age, strength, body area, and label limits",["AhR","Tapinarof 1 percent","Once daily from age 2"],["PDE4","Roflumilast cream","Age-specific 0.05 and 0.15 percent strengths"],["JAK","Ruxolitinib 1.5 percent","Short-term, noncontinuous, up to 20 percent body area"],["Audit","Tube and combination limits","Topical route still requires exposure controls"]],
"infection-flare-rescue":["Acute decision","Separate inflamed disease from infected or dangerous disease",["Recognize","Crust, pus, vesicle, fever","Identify bacterial, viral, fungal, or systemic threat"],["Target","Evidence of infection","Avoid routine antimicrobials for every flare"],["Wrap","Hydration and delivery","Occlusion changes absorption and infection risk"],["Dilute","Selected bleach bath","Exact volume, concentration, frequency, and supervision"]],
"biologics-phototherapy":["Escalation by pathway","Choose light or biologic therapy through phenotype and label",["IL-4R alpha","Dupilumab","Broad type 2 pathway with product-specific age and weight dosing"],["IL-13","Tralokinumab or lebrikizumab","Distinct labels, schedules, and eye monitoring"],["IL-31R alpha","Nemolizumab","Itch pathway with concomitant topical therapy"],["Light","Narrowband UVB","Dosed medical exposure, not tanning"]],
"systemic-safety":["Systemic choice","Balance speed, durability, organ risk, infection, and reproduction",["JAK","Abrocitinib or upadacitinib","Screen infection, thrombosis, cardiovascular, cancer, and laboratory risk"],["Conventional","Drug-specific monitoring","Cyclosporine, methotrexate, azathioprine, or mycophenolate"],["Avoid","Routine systemic steroids","Rebound and cumulative harm undermine durable care"],["Transition","Exit and maintenance","Every rescue needs a long-term plan"]],
"special-populations-follow-up":["Whole-patient follow-up","Measure disease across age, skin, life, comorbidity, and access",["Child","Growth and caregiver technique","Use age-specific labels and quantities"],["Pregnancy","Narrative benefit and risk","Reconcile every topical and systemic exposure"],["Skin color","Texture and pigment","Do not rely on redness alone"],["Close loop","Skin, itch, sleep, infection","Set targets, timing, and escalation"]],
};
export default function AtopicDermatitisVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual atopic-dermatitis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
