const diagrams = {
  "atrial-arrhythmia-map": { eyebrow: "Atrial rhythm map", title: "Atrial arrhythmias differ by organization, circuit, AV nodal dependence, regularity, stroke risk, and response to therapy.", accent: "#ba7d68", columns: [["AF", "Disorganized atrial activation", "Irregular ventricular response"], ["Flutter", "Macroreentry", "Organized atrial activity"], ["AT", "Focal or microreentrant", "Atrial morphology localizes origin"], ["AV reentry", "AVNRT or AVRT", "Abrupt regular tachycardia"]] },
  "atrial-af-framework": { eyebrow: "Atrial fibrillation framework", title: "AF care combines burden and symptoms, substrate modification, stroke prevention, rate or rhythm strategy, and longitudinal reassessment.", accent: "#889fb5", columns: [["Stage", "Risk through permanent AF", "Describe current disease"], ["Modify", "Weight, pressure, sleep, alcohol", "Reduce progression drivers"], ["Prevent", "Estimate thromboembolic risk", "Select anticoagulation"], ["Control", "Rate, rhythm, ablation", "Use shared goals"]] },
  "atrial-rate-rhythm": { eyebrow: "Rate and rhythm control", title: "Stability, ventricular function, preexcitation, symptoms, duration, substrate, and drug risk determine whether to slow, convert, or ablate.", accent: "#8fa681", columns: [["Stability", "Cardioversion when unstable", "Do not delay for taxonomy"], ["Rate", "AV nodal slowing", "Match to ventricular function"], ["Rhythm", "Drug or electrical conversion", "Protect against embolism"], ["Durability", "Maintenance or ablation", "Reassess burden and goals"]] },
  "atrial-stroke-prevention": { eyebrow: "Stroke prevention", title: "Thromboembolic prevention follows annual risk, valve context, kidney and liver function, bleeding modifiers, adherence, and patient preference.", accent: "#c19a62", columns: [["Estimate", "Validated risk score", "Use modifiers when intermediate"], ["Select", "DOAC or warfarin", "Respect valve exclusions"], ["Implement", "Dose, adherence, interactions", "Avoid aspirin substitution"], ["Reassess", "Risk changes over time", "Update at transitions"]] },
  "atrial-svt-circuits": { eyebrow: "Regular supraventricular tachycardias", title: "Vagal maneuvers and adenosine can interrupt AV-node-dependent circuits, while flutter and focal atrial tachycardia may only reveal atrial activity.", accent: "#a98bb8", columns: [["AVNRT", "Dual AV nodal pathways", "AV node is in circuit"], ["AVRT", "Accessory pathway circuit", "Check for preexcitation"], ["Flutter", "Atrial macroreentry", "AV block can unmask waves"], ["Focal AT", "Automatic or triggered focus", "Treat source and substrate"]] },
  "atrial-special-safety": { eyebrow: "High-risk atrial rhythm states", title: "Preexcitation, heart failure, acute coronary syndrome, pregnancy, postoperative stress, and toxicity change otherwise familiar atrial-rhythm choices.", accent: "#bd7070", columns: [["Preexcitation", "Avoid AV nodal blockade in AF", "Protect against VF"], ["Heart failure", "Respect ventricular function", "Avoid harmful negative inotropy"], ["Acute illness", "Treat the driver", "Separate cause from response"], ["Transition", "Cardioversion and anticoagulation", "Plan before and after"]] },
};
export default function AtrialArrhythmiasVisual({ type }) { const d = diagrams[type]; if (!d) return null; return <figure className="chol-visual" style={{ "--chol-accent": d.accent }} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,a,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{a}</em><p>{x}</p></div>)}</div></figure>; }
