const diagrams = {
  "bph-framework": ["Clinical layers", "Do not collapse symptoms, anatomy, and function", ["Symptoms", "LUTS", "Storage, voiding, and post-micturition experiences"], ["Anatomy", "Enlargement", "Transition-zone growth can add fixed resistance"], ["Function", "Obstruction", "Pressure and flow reveal the outlet-bladder relationship"]],
  "bph-evaluation": ["Diagnostic pathway", "Start broad, then test with purpose", ["Listen", "Pattern and bother", "History, medicines, IPSS, goals, and red flags"], ["Examine", "Core baseline", "Physical examination and urinalysis frame the first decision"], ["Resolve", "Targeted evidence", "PSA context, residual, flow, imaging, or referral when useful"]],
  "bph-goals": ["Treatment frame", "Bother, risk, and preference set the direction", ["Bother", "What must improve", "Name the symptom and quality-of-life target"], ["Risk", "What must be prevented", "Enlargement, retention, renal injury, infection, stones, and bleeding"], ["Preference", "What the patient values", "Speed, sexual function, burden, durability, and procedures"]],
  "bph-alpha": ["Dynamic resistance", "Relax the outlet without changing gland volume", ["Block", "Alpha-1 signaling", "Reduce smooth muscle contraction in prostate and bladder neck"], ["Flow", "Rapid symptom benefit", "Improvement begins sooner than with gland modification"], ["Select", "Safety profile", "Balance orthostasis, ejaculation, interactions, and cataract plans"]],
  "bph-fiveari": ["Androgen pathway", "Reduce the growth signal over time", ["Substrate", "Testosterone", "5-alpha-reductase converts testosterone within prostate tissue"], ["Signal", "Dihydrotestosterone", "DHT supports androgen-driven gland growth"], ["Modify", "Finasteride or dutasteride", "Lower DHT, reduce volume, and reduce progression risk in enlargement"]],
  "bph-tadalafil": ["Smooth muscle signal", "Preserve cyclic GMP for daily symptom therapy", ["Initiate", "Nitric oxide", "Guanylate cyclase produces cyclic GMP"], ["Preserve", "PDE5 inhibition", "Tadalafil slows cyclic GMP breakdown"], ["Relax", "Lower urinary tract", "Daily therapy can improve LUTS and erectile function"]],
  "bph-storage": ["Residual symptom", "Treat the bladder only after checking emptying", ["Describe", "Urgency and frequency", "Separate storage symptoms from polyuria and nocturnal production"], ["Measure", "Residual and flow", "Estimate retention risk and detrusor performance"], ["Target", "Muscarinic or beta-3", "Choose bladder therapy using cognition, pressure, interactions, and organ function"]],
  "bph-retention": ["Acute pathway", "Stabilize first, then plan durable care", ["Decompress", "Drain the bladder", "Protect comfort, bladder function, and kidney function"], ["Explain", "Find the trigger", "Review obstruction, infection, constipation, anesthesia, and medicines"], ["Test", "Voiding trial", "Use alpha blockade, adequate time, and recurrence counseling"]],
  "bph-procedures": ["Procedure decision", "Anatomy and priorities determine fit", ["Indication", "Complication or burden", "Retention, renal injury, infection, stones, bleeding, or refractory symptoms"], ["Architecture", "Size and shape", "Median lobe, gland volume, and outlet anatomy constrain options"], ["Tradeoff", "Durability and function", "Compare anesthesia, bleeding, catheter time, ejaculation, and retreatment"]],
  "bph-followup": ["Care loop", "Every prescription needs a decision endpoint", ["Measure", "Benefit", "Repeat symptoms and the patient-prioritized goal"], ["Protect", "Safety", "Track hemodynamics, sexual effects, retention, interactions, and PSA context"], ["Change", "Strategy", "Reconsider diagnosis, adherence, mechanism, and procedural care"]],
};

export default function BenignProstaticHyperplasiaVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
