export const betaLactamPharmacologyVisualTypes = [
  "core-chemistry-pbps", "penicillin-families", "cephalosporin-reasoning", "carbapenems", "aztreonam-monobactam",
  "inhibitor-combinations", "exposure-dose-design", "allergy-side-chains", "safety-monitoring", "clinical-integration",
];

const diagrams = {
  "core-chemistry-pbps": ["Molecular sequence", "Follow the reactive ring from target binding to wall failure", ["Enter", "Reach the periplasm", "Porins, charge, and side chains influence gram-negative access"], ["Acylate", "Bind the PBP", "The strained carbonyl reacts with the active-site serine"], ["Interrupt", "Stop cross-linking", "Transpeptidation can no longer stabilize peptidoglycan"], ["Fail", "Lose wall integrity", "Growth and autolysis expose the weakened bacterial cell"]],
  "penicillin-families": ["Penicillin map", "Separate four families by the problem each structure solves", ["Natural", "Focused susceptible activity", "Penicillin G and V remain enzyme vulnerable"], ["Stable", "Resist staphylococcal penicillinase", "Oxacillin-class agents do not overcome PBP2a"], ["Enter", "Expand selected gram-negative access", "Aminopenicillins still need enzyme and site review"], ["Extend", "Reach susceptible Pseudomonas", "Piperacillin-tazobactam requires AST and reassessment"]],
  "cephalosporin-reasoning": ["Agent lens", "Use generation as orientation, then reason at the drug level", ["Target", "PBP affinity", "Ceftaroline and ceftobiprole reach altered PBP targets"], ["Resist", "Enzyme stability", "AmpC, ESBL, carbapenemase, and MBL profiles differ"], ["Enter", "Permeability and uptake", "Cefiderocol uses iron transport to reach gram-negative targets"], ["Protect", "Agent-specific safety", "Cefepime and ceftriaxone demand different surveillance"]],
  "carbapenems": ["Carbapenem decision", "Use broad stability without erasing clinically important differences", ["Justify", "Name the resistance problem", "ESBL or another mechanism must fit the syndrome and AST"], ["Differentiate", "Check missing organisms", "Ertapenem does not reliably cover Pseudomonas or Acinetobacter"], ["Adapt", "Follow renal clearance", "Dynamic function changes both efficacy and neurotoxicity"], ["Protect", "Review valproate", "The interaction can lower concentrations and trigger seizures"]],
  "aztreonam-monobactam": ["Focused niche", "Keep allergy opportunity and microbiologic limits in the same view", ["Target", "Aerobic gram-negative", "PBP3 inhibition does not cover gram-positive or anaerobic organisms"], ["Verify", "Demand susceptibility", "Allergy convenience cannot substitute for AST"], ["Compare", "Review ceftazidime", "A shared side chain creates a specific cross-reactivity concern"], ["Protect", "Address co-produced enzymes", "MBL stability can be lost to an accompanying serine beta-lactamase"]],
  "inhibitor-combinations": ["Enzyme matching", "An inhibitor works only when its biochemical profile fits", ["Identify", "Define the enzyme", "ESBL, AmpC, KPC, OXA, and MBL are not interchangeable"], ["Pair", "Inspect the partner", "The protected beta-lactam must still enter and bind its PBP"], ["Test", "Confirm in vitro activity", "Co-produced enzymes and permeability can change the phenotype"], ["Reserve", "Use current guidance", "Novel combinations protect future treatment options"]],
  "exposure-dose-design": ["PK and PD loop", "Translate a susceptible result into an achievable regimen", ["Target", "Free time above MIC", "Set the exposure needed for organism, site, and severity"], ["Deliver", "Dose, interval, infusion", "Validate stability, access, compatibility, and workflow"], ["Adapt", "Dynamic clearance", "Renal function, dialysis, body size, and critical illness change exposure"], ["Close", "Response and toxicity", "Reassess the infected compartment and the patient trajectory"]],
  "allergy-side-chains": ["Allergy pathway", "Replace one vague label with a structured, molecular decision", ["Describe", "Culprit and phenotype", "Timing, manifestations, treatment, and later tolerance define risk"], ["Classify", "Immediate, benign delayed, or severe delayed", "Different immune patterns require different pathways"], ["Compare", "R-group side chains", "Cross-reactivity is pair specific rather than uniformly class wide"], ["Choose", "Challenge, testing, desensitization, or avoidance", "Match the tool to risk, urgency, and clinical need"]],
  "safety-monitoring": ["Safety surveillance", "Connect each signal to the selected agent and exposure", ["Brain", "Neurotoxicity", "Cefepime accumulation can cause encephalopathy, myoclonus, or seizure"], ["Kidney", "Clearance and injury", "Dose review follows the renal trajectory, not one old value"], ["Newborn", "Calcium and bilirubin", "Ceftriaxone restrictions protect vulnerable neonates"], ["System", "Blood, liver, gut, and formulation", "Duration and patient factors determine the monitoring plan"]],
  "clinical-integration": ["Definitive plan", "Converge from uncertainty to the narrowest reliable complete regimen", ["Confirm", "Diagnosis and source", "Do not optimize therapy for colonization or contamination"], ["Resolve", "Organism, AST, and mechanism", "Interpret current breakpoints with their dosing assumptions"], ["Fit", "Site, exposure, allergy, and safety", "The regimen must be achievable in the actual patient"], ["Document", "Duration and reassessment", "State the endpoint, monitoring, pending evidence, and owner"]],
};

export default function BetaLactamPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual beta-lactam-pharmacology-visual" aria-label={title}>
    <figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption>
    <div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}>
      <span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p>
    </div>)}</div>
  </figure>;
}
