export const burnAssessmentInitialCareVisualTypes=["burn-emergency","burn-depth","burn-extent","thermal-first-aid","chemical-electrical","burn-referral","minor-burn-care","burn-topicals","burn-resuscitation","burn-recovery"];
const diagrams={
"burn-emergency":["Emergency sequence","Stop exposure, protect the rescuer, secure airway and circulation, and prevent hypothermia",["Scene","Heat, smoke, current, chemical","Do not create a second patient"],["Airway","Voice, soot, stridor, enclosure","Deterioration can be delayed"],["Circulation","Trauma, shock, circumferential injury","Burns can hide other injury"],["Warmth","Cool the burn, warm the person","Avoid systemic hypothermia"]],
"burn-depth":["Depth spectrum","Appearance, moisture, blanching, sensation, pain, and evolution describe tissue injury",["Superficial","Dry, red, blanching","Not counted in TBSA"],["Superficial partial","Moist, blistered, very painful","Dermis remains viable"],["Deep partial","Pale, drier, less blanching","Healing risk rises"],["Full thickness","Leathery, variable color, numb","Specialized care is required"]],
"burn-extent":["Extent map","Depth plus total body surface area plus location defines severity",["Count","Partial and full thickness","Exclude superficial erythema"],["Small","Patient palmar surface","About one percent"],["Adult","Rule of nines","Rapid initial estimate"],["Child","Lund and Browder","Adjust for body proportions"]],
"thermal-first-aid":["Thermal first aid","End the heat exposure, cool locally, remove constriction, cover, and reassess",["Stop","Remove the heat source","Protect the rescuer"],["Cool","Cool running water","Never ice"],["Remove","Jewelry and loose clothing","Leave adherent material"],["Cover","Clean nonadherent protection","Keep the patient warm"]],
"chemical-electrical":["Special mechanism pathway","Decontamination and electrical safety precede ordinary skin care",["Chemical","Remove clothing and irrigate","Call poison or emergency support"],["Powder","Brush dry material first","Avoid activating the agent"],["Electrical","Disconnect the source","Hidden internal injury matters"],["Lightning","Trauma and cardiac risk","Emergency evaluation"]],
"burn-referral":["Referral framework","Depth, extent, location, mechanism, comorbidity, pain, trauma, age, and resources determine consultation",["Depth","Full or potentially deep","Any size can matter"],["Extent","Partial thickness at least ten percent","Count correctly"],["Location","Face, hands, feet, genitals, joints","Function changes urgency"],["Mechanism","Inhalation, chemical, electrical","Special expertise is needed"]],
"minor-burn-care":["Healing environment","Clean, moist, protected, comfortable, and inspectable",["Clean","Gentle soap and water","Avoid repeated tissue injury"],["Moisturize","Plain petroleum jelly","No routine topical antibiotic"],["Protect","Nonstick dressing","Do not pop blisters casually"],["Recheck","Pain, drainage, healing","Escalate an abnormal course"]],
"burn-topicals":["Topical decision","Match the wound, depth, organism risk, product, and dressing rather than treating every burn alike",["Default","Petroleum and nonstick cover","Minor superficial care"],["Avoid","Butter, toothpaste, ice","Home remedies can harm"],["SSD","Specialist-directed adjunct","Second and third degree label"],["Monitor","Blood, kidney, liver, skin","Exposure can become systemic"]],
"burn-resuscitation":["Resuscitation loop","Estimate, start, titrate, reassess, and prevent fluid creep",["Estimate","Two mL per kg per percent","Adults at least twenty percent TBSA"],["Time","From the moment of burn","Delay changes delivery"],["Titrate","Urine output and physiology","Formula is only a start"],["Audit","Edema and compartment pressure","More fluid is not always better"]],
"burn-recovery":["Recovery continuum","Prevent infection, preserve motion, support metabolism, protect scars, and address trauma",["Observe","Pain, odor, drainage, fever","Trajectory matters"],["Move","Positioning and range of motion","Prevent contracture"],["Support","Protein, energy, sleep, mood","Large burns are systemic"],["Protect","Sun and scar plan after closure","Recovery continues for months"]],
};
export default function BurnAssessmentInitialCareVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual burn-assessment-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
