const diagrams = {
  "celiac-mechanism": { eyebrow: "Immune enteropathy", title: "Exposure, susceptibility, and mucosal injury form one disease pathway", accent: "#d7a16f", columns: [["Expose", "Gluten peptides", "Wheat, barley, and rye supply the trigger while the patient is consuming gluten."], ["Present", "Compatible HLA context", "Tissue transglutaminase modification and antigen presentation support an adaptive immune response."], ["Injure", "Villous surface is lost", "Inflammation, crypt hyperplasia, and villous atrophy reduce absorption and create systemic consequences."]] },
  "celiac-spectrum": { eyebrow: "Clinical recognition", title: "The intestine may be quiet while another organ reveals the disease", accent: "#b9957d", columns: [["Gut", "Variable digestive phenotype", "Diarrhea, pain, bloating, weight loss, nausea, or constipation can appear across ages."], ["System", "Nutrient and organ clues", "Iron deficiency, low bone density, elevated liver tests, neuropathic symptoms, and fatigue can dominate."], ["Context", "Risk changes probability", "Family history, type 1 diabetes, thyroid disease, IgA deficiency, and growth concerns support case finding."]] },
  "celiac-serology": { eyebrow: "Diagnostic serology", title: "The test is only as interpretable as the diet and immune context", accent: "#83a9b0", columns: [["Expose", "Keep gluten in the diet", "Testing after gluten withdrawal can reduce antibody concentrations and diagnostic sensitivity."], ["Pair", "tTG-IgA plus total IgA", "The total IgA result determines whether an IgA-based negative screen can be trusted."], ["Escalate", "Follow clinical probability", "High-probability disease can require biopsy even when screening serology is negative."]] },
  "celiac-biopsy": { eyebrow: "Diagnostic confirmation", title: "Patchy disease requires the right tissue from the right locations", accent: "#a88eb8", columns: [["Sample", "Bulb and distal duodenum", "Multiple specimens reduce the chance that patchy injury is missed."], ["Integrate", "Histology plus context", "Villous injury is interpreted with serology, gluten exposure, medicines, and competing enteropathies."], ["Exclude", "Use HLA selectively", "Absence of compatible HLA can rule out disease; presence does not prove it."]] },
  "celiac-diet": { eyebrow: "Disease-modifying treatment", title: "A safe diet is strict, nutritionally complete, and workable in real life", accent: "#c8aa68", columns: [["Remove", "Wheat, barley, and rye", "FDA-regulated gluten-free claims use a less-than-20-ppm threshold and ingredient rules."], ["Protect", "Control cross-contact", "Shared fryers, toasters, surfaces, flour dust, and preparation systems can transfer gluten."], ["Sustain", "Use expert dietitian care", "Nutrition, culture, cost, food access, oats, and unnecessary restriction require individual planning."]] },
  "celiac-nutrition": { eyebrow: "Recovery and prevention", title: "Stopping the trigger does not automatically repair every consequence", accent: "#89a681", columns: [["Measure", "Find actual deficits", "Blood counts, iron, folate, B12, vitamin D, calcium, and other tests follow the phenotype."], ["Repair", "Restore bone and growth", "Replace documented deficits and track skeletal risk, weight, growth, and pubertal development."], ["Prevent", "Review vaccination", "Pneumococcal prevention follows current age, risk, prior-dose, and asplenia guidance."]] },
  "celiac-dh": { eyebrow: "Dermatitis herpetiformis", title: "Skin control and disease control are related but not interchangeable", accent: "#c87772", columns: [["Treat", "Keep the diet foundational", "A strict gluten-free diet addresses both intestinal and skin disease over time."], ["Control", "Use dapsone deliberately", "Dapsone can rapidly reduce pruritus and lesions but does not heal intestinal disease."], ["Monitor", "Protect blood and liver", "CBC, hemoglobin, liver tests, G6PD context, cyanosis, rash, fever, and weakness belong in the safety plan."]] },
  "celiac-medicines": { eyebrow: "Medication excipients", title: "The exact product resolves the question, not the generic name", accent: "#8298b1", columns: [["Match", "Identify the dispensed product", "Manufacturer, strength, dosage form, imprint, and NDC distinguish products with different excipients."], ["Verify", "Use current information", "Review DailyMed, OTC inactive ingredients, and manufacturer information when needed."], ["Calibrate", "Avoid unnecessary interruption", "Most US oral medicines contain no or virtually no gluten, so unverified fear should not stop needed care."]] },
  "celiac-followup": { eyebrow: "Longitudinal response", title: "Recovery is measured across symptoms, nutrition, serology, and tissue", accent: "#8da49e", columns: [["Review", "Assess the diet expertly", "Dietitian interview remains the standard adherence assessment and can find both exposure and overrestriction."], ["Trend", "Use serology with limits", "Falling tTG supports response but does not independently prove mucosal healing."], ["Reassess", "Biopsy when it answers a question", "Persistent disease and selected adult follow-up can justify repeat duodenal assessment."]] },
  "celiac-nonresponsive": { eyebrow: "Persistent disease", title: "Refractory disease is the end of the workup, not the beginning", accent: "#af847c", columns: [["Confirm", "Revisit the diagnosis", "Review original gluten exposure, serology, biopsy quality, HLA context, and alternative enteropathies."], ["Investigate", "Find exposure and alternatives", "Dietary review and phenotype-directed testing address contamination, intolerance, IBS, SIBO, pancreatic disease, and colitis."], ["Refer", "Escalate persistent enteropathy", "Villous atrophy despite verified long-term treatment requires specialist classification and complication assessment."]] },
};

export default function CeliacDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual celiac-disease-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
