const diagrams={
"hf-treatment-pillars":{eyebrow:"HFrEF treatment architecture",title:"Four complementary disease-modifying pillars should be established early, then titrated around physiology, tolerance, access, and patient goals.",accent:"#b97b69",columns:[["ARNI or RAS","Neurohormonal and peptide balance","Pressure, kidney, potassium"],["Beta blocker","Adrenergic protection","Start when compensated"],["MRA","Aldosterone blockade","Potassium surveillance"],["SGLT2","Cardiorenal protection","Diabetes not required"]]},
"hf-ras-mra":{eyebrow:"RAAS, neprilysin, and mineralocorticoids",title:"ARNI, ACE inhibitors, ARBs, and MRAs modify related pathways but are not interchangeable or safely stackable without drug-specific rules.",accent:"#859eb5",columns:[["ARNI","ARB plus neprilysin inhibition","Respect ACE washout"],["ACE or ARB","Alternative RAS strategy","Choose one pathway"],["MRA","Block aldosterone signaling","Kidney and potassium"],["Monitor","Pressure, chemistry, exposure","Preserve benefit safely"]]},
"hf-beta-rate":{eyebrow:"Rate and adrenergic strategy",title:"Evidence-based beta blockers improve outcomes after compensation, while ivabradine and digoxin occupy narrower rhythm, heart-rate, and symptom roles.",accent:"#a68bb7",columns:[["Stabilize","Confirm perfusion and congestion","Do not titrate in shock"],["Block","Use an evidence-based beta blocker","Agent and formulation matter"],["Refine","Sinus rate or AF context","Match mechanism"],["Follow","Pulse, conduction, symptoms","Avoid additive block"]]},
"hf-sglt2-diuresis":{eyebrow:"Cardiorenal benefit and decongestion",title:"SGLT2 inhibitors modify outcomes, while loop and sequential diuretics control volume. Their goals overlap clinically but are not equivalent.",accent:"#89a37e",columns:[["Protect","SGLT2 across diabetes status","Screen fasting and illness"],["Decongest","Loop diuretic to euvolemia","Measure response"],["Escalate","Confirm resistance mechanism","Monitor sequential block"],["Maintain","Lowest effective volume regimen","Keep the pillars"]]},
"hf-additional-therapy":{eyebrow:"Therapy for residual risk",title:"Hydralazine plus isosorbide dinitrate, ivabradine, digoxin, vericiguat, intravenous iron, devices, and advanced care follow a defined phenotype and goal.",accent:"#c0995d",columns:[["Identify","Residual mechanism or risk","Do not skip the foundation"],["Select","Match evidence population","Use exact regimen"],["Measure","Symptoms, admissions, rhythm","Know the intended benefit"],["Escalate","Device, ablation, specialty care","Refer before decline"]]},
"hf-phenotype-implementation":{eyebrow:"Across the ejection-fraction spectrum",title:"HFmrEF, HFpEF, and HFimpEF require trajectory, comorbidity, congestion, kidney, metabolic, and access reasoning rather than a single-number algorithm.",accent:"#b7736c",columns:[["HFmrEF","Use phenotype continuum","SGLT2 has central evidence"],["HFpEF","Multisystem care","Treat obesity and comorbidity"],["HFimpEF","Remission, not cure","Continue disease therapy"],["Implement","Labs, access, adherence","Reassess rapidly"]]},
};
export default function ChronicHeartFailureVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
