const diagrams = {
  "ccd-nitrate-schedules": { eyebrow: "Daily schedules", title: "Each formulation needs its own schedule; preventive doses never replace the emergency rescue plan.", accent: "#b38a62", columns: [["Patch", "8 AM on, 10 PM off", "14 hours on; 10 hours off before the next morning"], ["Mononitrate IR", "8 AM and 3 PM", "7 hours between daytime doses; 17 hours overnight"], ["Mononitrate ER", "On waking", "Once daily; do not copy the IR schedule"], ["Dinitrate IR", "8 AM, 2 PM and 6 PM", "Example angina schedule with a 14-hour overnight gap"]] },
  "ccd-disease-spectrum": { eyebrow: "Chronic coronary disease", title: "Coronary disease includes obstructive, nonobstructive, previously revascularized, and ischemic syndromes with different mechanisms.", accent: "#c88771", columns: [["Plaque", "Atherosclerotic burden", "Can remain silent or produce fixed obstruction"], ["Flow", "Demand and supply mismatch", "Symptoms emerge when reserve is insufficient"], ["Function", "Microvascular or vasomotor disease", "Angina can occur without major obstruction"], ["History", "MI or revascularization", "Observed disease determines prevention intensity"]] },
  "ccd-prevention": { eyebrow: "Event prevention", title: "Durable risk reduction combines lifestyle, rehabilitation, lipids, blood pressure, tobacco treatment, metabolism, and antithrombotic care.", accent: "#8aa27a", columns: [["Behavior", "Movement, nutrition, tobacco", "Build repeatable rather than idealized plans"], ["Biology", "Lipids, pressure, glucose", "Use current risk-based goals"], ["Thrombosis", "Antiplatelet strategy", "Balance ischemia and bleeding"], ["System", "Rehabilitation and access", "Make the plan deliverable"]] },
  "ccd-antithrombotic": { eyebrow: "Antithrombotic strategy", title: "The correct regimen depends on coronary history, time from PCI or ACS, oral-anticoagulant indication, ischemic risk, and bleeding risk.", accent: "#b38a62", columns: [["Baseline", "Single antiplatelet", "Common long-term CCD foundation"], ["After PCI", "Time-limited DAPT", "Duration follows presentation and risk"], ["With OAC", "Minimize overlapping therapy", "Avoid indefinite bleeding burden without benefit"], ["Review", "Procedures and adherence", "Never interrupt a recent stent regimen casually"]] },
  "ccd-angina": { eyebrow: "Angina control", title: "Antianginal drugs either reduce myocardial oxygen demand, improve supply, or alter ischemic cellular stress.", accent: "#7f9fb5", columns: [["Demand", "Beta blocker or non-DHP CCB", "Reduce rate, contractility, or both"], ["Vasodilation", "DHP CCB or nitrate", "DHPs reduce afterload; nitrates reduce preload and can relieve coronary spasm"], ["Cell", "Ranolazine", "Inhibits late sodium current; exact antianginal mechanism remains uncertain"], ["Escalate", "Combine or revascularize", "Treat persistent symptoms by mechanism"]] },
  "ccd-testing-revascularization": { eyebrow: "Testing and intervention", title: "Testing should answer a changed clinical question, and revascularization should match symptoms, anatomy, function, and prognosis.", accent: "#a38db5", columns: [["Change", "New symptoms or function", "Reassess when the clinical state changes"], ["Test", "Anatomy or ischemia", "Choose the modality for the question"], ["Decide", "GDMT versus revascularization", "Use anatomy, physiology, symptoms, and preference"], ["Avoid", "Routine surveillance", "Do not image stable patients without a reason"]] },
  "ccd-follow-up": { eyebrow: "Longitudinal care", title: "Every follow-up visit distinguishes unstable symptoms, preventable events, treatment burden, and barriers to sustained care.", accent: "#c19b62", columns: [["Symptoms", "Pattern, threshold, nitroglycerin", "Detect change and acute danger"], ["Prevention", "Goals and medication exposure", "Confirm the regimen actually occurred"], ["Function", "Activity and quality of life", "Measure what matters to the patient"], ["Access", "Cost, transport, rehabilitation", "Treat system barriers as clinical data"]] },
};

export default function ChronicCoronaryDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
