const diagrams = {
  "cic-phenotype": { eyebrow: "Phenotype map", title: "Constipation is more than a count of bowel movements", accent: "#c99a68", columns: [["Stool", "Hard or lumpy", "Use Bristol form and effort, not frequency alone."], ["Evacuation", "Straining or incomplete", "Outlet symptoms can persist even when stool is soft."], ["Outcome", "Complete and spontaneous", "Track the result that reflects the patient's actual burden."]] },
  "cic-triage": { eyebrow: "Diagnostic triage", title: "The timeline separates primary constipation from a reversible cause", accent: "#c67061", columns: [["Urgency", "Bleeding, obstruction, systemic change", "Alarm features move evaluation ahead of routine self-treatment."], ["Exposure", "Medicines and supplements", "Link symptom onset to opioids, anticholinergics, minerals, and other causes."], ["Probability", "Targeted testing", "Order studies from history and examination rather than a universal panel."]] },
  "cic-evacuation": { eyebrow: "Outlet physiology", title: "Propulsion and relaxation must occur in the same moment", accent: "#8aa6b0", columns: [["Examine", "Simulated evacuation", "Assess push, descent, and anal relaxation during a purposeful rectal examination."], ["Measure", "Manometry plus balloon", "Combine pressure physiology with practical evacuation performance."], ["Retrain", "Pelvic floor biofeedback", "Correct coordination instead of adding secretion to an unresolved outlet disorder."]] },
  "cic-foundation": { eyebrow: "Foundation", title: "A useful first step is specific enough to evaluate", accent: "#9cad7a", columns: [["Form", "Soluble fiber", "Psyllium creates a hydrated gel when titrated with safe fluid intake."], ["Timing", "Gastrocolic window", "Create an unhurried post-meal opportunity with supportive posture."], ["Measure", "Comfort and completeness", "A daily bowel movement is not the only definition of success."]] },
  "cic-osmotic": { eyebrow: "Luminal water", title: "Osmotic therapies share a direction, not an identical safety profile", accent: "#6d9fb3", columns: [["PEG", "Strong chronic evidence", "Retains water with limited fermentation and a measurable stool response."], ["Magnesium", "Renal constraint", "Accumulation risk changes selection when kidney function is reduced."], ["Lactulose", "Fermentation tradeoff", "Gas and bloating can limit a therapy that increases luminal osmoles."]] },
  "cic-stimulant": { eyebrow: "Propulsive rescue", title: "Stimulate with a purpose, a dose, and a stop rule", accent: "#d08b61", columns: [["Strong", "Bisacodyl or picosulfate", "Use short term or as rescue with coating-aware administration."], ["Conditional", "Senna", "Titrate against cramping, urgency, and diarrhea."], ["Uncertain", "Docusate", "Familiarity does not replace evidence of meaningful benefit."]] },
  "cic-secretagogues": { eyebrow: "Epithelial secretion", title: "Three prescription pathways move chloride and water into the lumen", accent: "#a685b4", columns: [["ClC-2", "Lubiprostone", "Use 24 mcg twice daily with food and water for adult CIC."], ["GC-C", "Linaclotide", "Use the CIC dose before a meal and stop for severe diarrhea."], ["GC-C", "Plecanatide", "Use 3 mg daily with flexible meal timing in adults."]] },
  "cic-prucalopride": { eyebrow: "Motility signaling", title: "5-HT4 activation recruits the enteric propulsive circuit", accent: "#ca7f92", columns: [["Signal", "Enteric acetylcholine", "Selective 5-HT4 agonism strengthens the peristaltic reflex."], ["Dose", "Renal function", "Use 2 mg daily, reduced to 1 mg in severe renal impairment."], ["Monitor", "Mood and tolerance", "Act on new depression, suicidal thinking, severe diarrhea, or persistent pain."]] },
  "cic-refractory": { eyebrow: "Refractory pathway", title: "Prove the mechanism before calling treatment exhausted", accent: "#b19365", columns: [["Outlet", "Anorectal testing", "Identify and treat a defecatory disorder before escalating the label."], ["Transit", "Off and on therapy", "Document slow transit and the persistence of disease on maximal treatment."], ["Selection", "Surgery last", "Require objective physiology and careful exclusion of poor-outcome patterns."]] },
  "cic-longitudinal": { eyebrow: "Learning loop", title: "Keep what works, remove what does not, reopen the diagnosis when needed", accent: "#7f9c91", columns: [["Target", "One measurable burden", "Choose frequency, form, straining, completeness, pain, or function."], ["Decision", "Continue, modify, or stop", "Use a planned review date instead of passive accumulation."], ["Reassess", "New story, new pathway", "Alarm features or phenotype change require diagnostic reconsideration."]] },
};

export default function ChronicIdiopathicConstipationVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
