const diagrams = {
  "ckdc-surveillance": { accent: "#b98a72", eyebrow: "Surveillance", title: "Confirm, connect, and escalate", columns: [["Confirm", "Is the signal real?", "Repeat unexpected results and verify context"], ["Connect", "What mechanism fits?", "Kidney function, illness, nutrition, volume, and medicines"], ["Escalate", "What changes care?", "Symptoms, trajectory, treatment threshold, or referral"]] },
  "ckdc-anemia": { accent: "#bd6f67", eyebrow: "Erythropoiesis", title: "Production needs signal, iron, and safety", columns: [["Cause", "More than low EPO", "Blood loss, iron restriction, inflammation, nutrition, and marrow"], ["Iron", "Stores plus availability", "Ferritin and TSAT interpreted together"], ["Stimulate", "ESA or HIF-PHI", "Individual goals, lowest effective exposure, and current label"]] },
  "ckdc-mbd": { accent: "#c7aa72", eyebrow: "CKD-MBD", title: "Kidney, parathyroid, bone, and vessel", columns: [["Retention", "Phosphate and FGF23", "A changing endocrine response to falling filtration"], ["Turnover", "PTH and bone", "Use serial calcium, phosphate, PTH, and alkaline phosphatase"], ["Calcification", "Vascular consequence", "Limit avoidable calcium and phosphate burden"]] },
  "ckdc-electrolytes": { accent: "#8da183", eyebrow: "Homeostasis", title: "Potassium and acid are linked", columns: [["Input", "Diet and medicines", "Find actual sources and salt substitutes"], ["Shift", "Insulin and acid-base", "Acute physiology changes extracellular potassium"], ["Remove", "Kidney, gut, or dialysis", "Preserve beneficial therapy when control is safe"]] },
  "ckdc-volume": { accent: "#749eaa", eyebrow: "Body composition", title: "Congestion can coexist with wasting", columns: [["Fluid", "Sodium and water", "Symptoms, JVP, weight, pressure, and response"], ["Fuel", "Energy and protein", "Intake, inflammation, restrictions, and losses"], ["Function", "Muscle and resilience", "Strength, mobility, appetite, and quality of life"]] },
  "ckdc-advanced": { accent: "#a18aaa", eyebrow: "Advanced care", title: "Symptoms, preparation, and choice", columns: [["Recognize", "Uremic syndrome", "Track symptoms and failed homeostasis"], ["Prepare", "Before crisis", "Transplant, access, home therapies, and support"], ["Align", "Goals and burden", "Dialysis or comprehensive conservative care"]] },
};
export default function CkdComplicationsVisual({ type }) { const d = diagrams[type]; if (!d) return null; return <figure className="chol-visual" style={{ "--chol-accent": d.accent }} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>; }
