export const clindamycinPharmacologyVisualTypes = ["structure-mechanism", "spectrum-boundaries", "resistance-d-test", "systemic-roles", "route-specific-use", "dosing-pk", "administration-preparation", "cdiff-safety", "monitoring-special-populations", "integration"];

const diagrams = {
  "structure-mechanism": ["Translation gate", "A chlorinated lincosamide stops peptide elongation at the 50S ribosome", ["Modify", "Lincomycin scaffold", "The 7-chloro substitution produces clindamycin."], ["Bind", "23S rRNA", "The drug occupies a site in the bacterial 50S subunit."], ["Interrupt", "Peptide elongation", "Protein synthesis slows before a complete chain forms."], ["Suppress", "Bacterial growth", "Activity is usually bacteriostatic and syndrome dependent."]],
  "spectrum-boundaries": ["Coverage map", "Useful activity becomes safe only when the missing organisms remain visible", ["Consider", "Susceptible gram-positive", "Verify local and isolate-specific resistance."], ["Consider", "Selected anaerobes", "Match activity to source, site, and current guidance."], ["Exclude", "Aerobic gram-negative", "Enterobacterales and Pseudomonas need another plan."], ["Protect", "Bite coverage", "Eikenella and Pasteurella defeat monotherapy."]],
  "resistance-d-test": ["Induction test", "Paired disks expose a resistance pathway hidden by the initial result", ["Notice", "Erythromycin resistant", "This phenotype can signal inducible erm activity."], ["Place", "Clindamycin nearby", "The microbiology laboratory creates the induction challenge."], ["Read", "D-shaped flattening", "A positive zone shows inducible clindamycin resistance."], ["Replace", "Do not escalate", "Choose an active alternative rather than increasing dose."]],
  "systemic-roles": ["Syndrome boundary", "Clindamycin works inside a complete infection and source-control plan", ["Drain", "Skin and abscess", "Antibiotics do not replace source control."], ["Pair", "Invasive streptococci", "Use toxin suppression beside active cell-wall therapy."], ["Culture", "Bone and joint", "Penetration cannot overcome resistance or hardware."], ["Correct", "Dental prophylaxis", "Current AHA guidance no longer recommends clindamycin."]],
  "route-specific-use": ["Formulation map", "One active moiety carries different instructions across three clinical spaces", ["Systemic", "Oral or IV", "Use a justified infection, dose, duration, and CDI plan."], ["Topical", "Inflammatory acne", "Pair with benzoyl peroxide and define the stop date."], ["Vaginal", "Bacterial vaginosis", "Match the exact cream, ovule, or single-dose product."], ["Counsel", "Barrier interval", "Oil-based vehicles can weaken latex or rubber products."]],
  "dosing-pk": ["Exposure map", "High oral absorption supports transition while site and metabolism preserve hard limits", ["Absorb", "About 90 percent", "Food does not appreciably change serum exposure."], ["Dose", "Every six hours", "Serious and more severe infections use different ranges."], ["Distribute", "Tissue and bone", "Broad distribution still excludes useful CSF exposure."], ["Metabolize", "Mainly CYP3A4", "Review interactions and severe hepatic disease."]],
  "administration-preparation": ["Administration clock", "Water, posture, dose, and time turn technique into safety", ["Swallow", "6 to 8 ounces", "Use enough water with every capsule."], ["Remain", "Upright 30 minutes", "Reduce esophageal irritation after the dose."], ["Infuse", "No faster than 30 mg/min", "Never use a rapid intravenous push."], ["Calculate", "900 mg in at least 30 min", "Dose and minimum infusion time move together."]],
  "cdiff-safety": ["Delayed hazard", "The boxed warning follows the patient beyond the final dose", ["Select", "Justified infection", "Avoid unnecessary microbiome disruption."], ["Recognize", "Watery diarrhea", "Symptoms can begin during therapy or more than two months later."], ["Stage", "Severity and testing", "Test only within a compatible clinical syndrome."], ["Act", "Stop and treat", "Remove unnecessary antibiotics and use current CDI care."]],
  "monitoring-special-populations": ["Safety ownership", "Every major toxicity has a trigger, measurement, and action", ["Stop", "SJS, TEN, or DRESS", "Severe hypersensitivity requires permanent discontinuation."], ["Trend", "CBC and organ tests", "Monitor prolonged therapy at defined intervals."], ["Review", "CYP3A and paralytics", "Exposure and neuromuscular interactions need separate plans."], ["Narrate", "Pregnancy and lactation", "Use timing, route, evidence, alternatives, and follow-up."]],
  "integration": ["Closed-loop regimen", "Make resistance, exposure, safety, response, and exit agree", ["Define", "Syndrome and source", "Confirm organisms, severity, cultures, and source action."], ["Verify", "Susceptibility and D-zone", "Do not hide inducible resistance."], ["Execute", "Exact route and dose", "Make administration reconstructable."], ["Exit", "Narrow, stop, or switch", "Use response, microbiology, toxicity, and duration."]],
};

export default function ClindamycinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual clindamycin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
