const diagrams = {
  "coagulation-hemostasis": { eyebrow: "Hemostasis architecture", title: "Vessel repair coordinates vasoconstriction, platelet plug formation, thrombin and fibrin generation, clot control, and fibrinolysis.", accent: "#c36f64", columns: [["Contain", "Vessel response", "Reduce immediate blood loss"], ["Plug", "Platelet hemostasis", "Adhere, activate, and aggregate"], ["Stabilize", "Thrombin and fibrin", "Reinforce the platelet plug"], ["Resolve", "Fibrinolysis and repair", "Limit and remodel the clot"]] },
  "coagulation-targets": { eyebrow: "Anticoagulant targets", title: "Anticoagulants reduce thrombin generation or activity through antithrombin, vitamin K pathways, factor Xa, or thrombin itself.", accent: "#b88c62", columns: [["Antithrombin", "UFH, LMWH, fondaparinux", "Accelerate inhibition of activated factors"], ["Vitamin K", "Warfarin", "Reduce synthesis of functional factors"], ["Factor Xa", "Apixaban, rivaroxaban, edoxaban", "Reduce prothrombinase activity"], ["Thrombin", "Dabigatran and parenteral DTIs", "Block fibrin generation and amplification"]] },
  "coagulation-laboratory": { eyebrow: "Laboratory interpretation", title: "A clotting test is useful only when its pathway, reagent, timing, drug sensitivity, and clinical question are known.", accent: "#7f9eb4", columns: [["PT and INR", "Vitamin K pathway sensitivity", "Standardize warfarin monitoring"], ["aPTT", "Intrinsic and common pathways", "Can guide UFH in validated systems"], ["Anti-Xa", "Drug-calibrated activity", "Interpret with the correct calibrator"], ["Special assays", "Thrombin time and drug levels", "Use selectively for urgent questions"]] },
  "coagulation-selection": { eyebrow: "Patient-specific selection", title: "The indication identifies eligible options, while organ function, age, weight, pregnancy, adherence, access, and procedures determine the safest fit.", accent: "#8ca17a", columns: [["Indication", "AF, VTE, valve, pregnancy, or procedure", "Do not assume one dose fits all"], ["Exposure", "Kidney, liver, weight, interactions", "Predict accumulation or underexposure"], ["Implementation", "Route, frequency, monitoring, cost", "Choose a regimen the patient can sustain"], ["Reassess", "Clinical and laboratory change", "Update the plan over time"]] },
  "coagulation-transitions": { eyebrow: "Transitions and procedures", title: "Safe interruption depends on indication, half-life, organ function, procedure bleeding risk, neuraxial exposure, and the plan for resumed protection.", accent: "#a78ab4", columns: [["Map", "Last dose and clearance", "Estimate residual anticoagulant effect"], ["Balance", "Thrombosis versus bleeding", "Avoid reflexive bridging"], ["Coordinate", "Procedure and neuraxial timing", "Use product-specific guidance"], ["Resume", "Hemostasis and indication", "Close the unprotected interval"]] },
  "coagulation-bleeding-hit": { eyebrow: "Critical anticoagulant safety", title: "Major bleeding and HIT demand rapid recognition, source control, mechanism-specific treatment, and a deliberate return to thrombosis prevention.", accent: "#c29c62", columns: [["Stabilize", "Severity and source", "Restore perfusion and control bleeding"], ["Reverse", "Match agent to strategy", "Account for last dose and organ function"], ["Recognize HIT", "Platelet fall plus thrombosis pattern", "Stop all heparin exposure"], ["Restart", "Treat the underlying risk", "Resume protection when medically appropriate"]] },
};

export default function CoagulationAnticoagulantVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
