export const commonEyeConditionsVisualTypes=["red-eye-triage","infectious-conjunctivitis","allergic-conjunctivitis","blepharitis-demodex","dry-eye-foundations","dry-eye-pharmacotherapy","inflammation-steroid-boundaries","redness-medication-injury","ophthalmic-dosage-technique","sterility-lenses-preservatives","special-populations-follow-up"];
const diagrams={
"red-eye-triage":["Vision first","A red eye becomes urgent when function or deep tissue is threatened",["See","Visual acuity","Ask what changed, how fast, and in which eye"],["Feel","Pain and photophobia","Move beyond routine conjunctivitis when either is prominent"],["Inspect","Cornea and pupil","Opacity, defect, irregular pupil, or trauma changes urgency"],["Escalate","Lens, chemical, or severe disease","Protect the cornea before cosmetic appearance"]],
"infectious-conjunctivitis":["Infection map","Separate self-limited viral disease from bacterial and invasive pathways",["Viral","Watery and contagious","Support, contain spread, and recognize severe adenoviral or herpetic disease"],["Bacterial","Purulent and overlapping","Use therapy only when the clinical pathway supports it"],["Corneal","Contact-lens risk","Remove lenses and seek prompt ophthalmic evaluation"],["Systemic","Gonococcal or chlamydial","Use urgent systemic evaluation and treatment"]],
"allergic-conjunctivitis":["Allergy circuit","Itch, exposure, and bilateral tearing point to local histamine signaling",["Trigger","Relevant allergen","Match pollen, animal, dust, mold, cosmetic, or lens exposure"],["Signal","Histamine and mast cells","Connect itch and tearing to a mechanism"],["Treat","Dual-action local therapy","Use exact-label ocular antihistamine or mast-cell treatment"],["Reject","Pain or vision loss","Send atypical features down another pathway"]],
"blepharitis-demodex":["Lid margin","The lash line and meibomian glands shape chronic ocular-surface disease",["Anterior","Crust and debris","Sustain lid hygiene rather than one-time cleaning"],["Posterior","Meibomian dysfunction","Warm, mobilize, and restore the lipid layer"],["Demodex","Collarettes","Identify a specific parasite-linked phenotype"],["Integrate","Dry eye and rosacea","Treat connected surface and skin drivers"]],
"dry-eye-foundations":["Tear film","Quality, stability, sensation, and exposure determine surface health",["Aqueous","Tear supply","Recognize lacrimal and autoimmune contributors"],["Lipid","Evaporation control","Assess lids, glands, blink, airflow, and screens"],["Mucin","Surface spread","Maintain a wettable epithelial interface"],["Neural","Symptom signaling","Do not force every symptom to match one sign"]],
"dry-eye-pharmacotherapy":["Layered care","Match persistent disease to mechanism, formulation, and follow-up",["Lubricate","Artificial tears","Choose viscosity, preservative burden, and frequency"],["Modulate","Lifitegrast or cyclosporine","Set onset and tolerability expectations"],["Stimulate","Tear pathway options","Use product-specific delivery and labeling"],["Reassess","Signs and symptoms","Confirm technique, adherence, lids, environment, and cornea"]],
"inflammation-steroid-boundaries":["Power and risk","Local anti-inflammatory therapy still requires diagnostic control",["Define","Exact indication","Do not treat an undiagnosed red eye with leftovers"],["Exclude","Infection and defect","Steroids can worsen microbial or herpetic disease"],["Monitor","Pressure and lens","Track intraocular pressure and cataract risk"],["Stop","Duration and response","Use the shortest clinician-directed course that fits"]],
"redness-medication-injury":["Cause before color","Whitening the eye cannot replace a diagnosis",["Question","Why is it red","Allergy, infection, dryness, inflammation, trauma, and pressure differ"],["Trace","Medication exposure","Connect dose, duration, route, and ocular structure"],["Protect","Retina and nerve","Use drug-specific surveillance before symptoms become permanent"],["Escalate","Sudden change","Vision loss, field change, color change, or pain demands action"]],
"ophthalmic-dosage-technique":["One-drop system","Preparation, placement, spacing, and drainage control the dose",["Prepare","Wash and verify","Check eye, product, formulation, seal, and expiration"],["Place","Conjunctival sac","Avoid the cornea and keep the tip sterile"],["Retain","Close and occlude","Reduce nasolacrimal drainage and systemic exposure"],["Sequence","Space and thicken","Separate products and put ointment last"]],
"sterility-lenses-preservatives":["Surface safety","Sterility and contact-lens behavior belong in every recommendation",["Protect","Tip clearance","Never touch the eye, skin, hands, clothing, or surfaces"],["Remove","Contact lenses","Follow exact-label wait time or infection-related no-wear plan"],["Limit","Preservative burden","Consider surface tolerance when exposure is frequent"],["Verify","Recall and source","Use sterile, approved, intact products from reliable channels"]],
"special-populations-follow-up":["Close the loop","Age, pregnancy, access, and trajectory change ocular risk",["Child","Age-specific urgency","Treat neonatal and poorly examinable disease differently"],["Pregnancy","Local is not zero systemic","Balance indication, evidence, and drainage reduction"],["Return","Expected course","Define a response window for every plan"],["Refer","Pain, light, or sight","Escalate whenever the pattern threatens vision"]],
};
export default function CommonEyeConditionsVisual({type}){const d=diagrams[type];if(!d)return null;const [eyebrow,title,...nodes]=d;return <figure className="chol-visual common-eye-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],i)=><div key={focus}><span>{String(i+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
