export const commonEarConditionsVisualTypes=["ear-triage","acute-otitis-externa","tympanum-host-risk","otic-pharmacotherapy","ear-drop-technique","cerumen-impaction","tinnitus","special-populations-follow-up"];
const diagrams={
"ear-triage":["Anatomic triage","Localize pain, sound, balance, drainage, and neurologic threat",["Canal","Pain and discharge","External inflammation, trauma, foreign body, or wax"],["Middle","Pressure and membrane","Effusion, perforation, tube, or acute infection"],["Inner","Hearing and balance","Sudden loss, vertigo, or ototoxic exposure"],["Neural","Asymmetry and deficit","Escalate focal or time-sensitive findings"]],
"acute-otitis-externa":["Canal infection","Deliver topical therapy, relieve pain, and restore access",["Confirm","Tragal tenderness","Separate canal disease from middle and referred pain"],["Open","Debris or edema","Use trained cleaning or a wick when delivery is blocked"],["Treat","Topical first","Reserve systemic antibiotics for spread or defined host risk"],["Recheck","48 to 72 hours","Question diagnosis, delivery, fungus, dermatitis, and extension"]],
"tympanum-host-risk":["Barrier and host","The membrane and the patient determine product safety",["Membrane","Intact or open","Tube, perforation, surgery, or uncertainty changes exposure"],["Host","Diabetes or immune risk","Look for severe persistent pain and invasive extension"],["Nerve","Facial or other deficit","Treat cranial findings as urgent"],["Route","Non-ototoxic choice","Protect inner-ear structures when the barrier is open"]],
"otic-pharmacotherapy":["Product selection","Match organism, inflammation, barrier, formulation, and label",["Localize","Topical concentration","Use high canal exposure for uncomplicated disease"],["Select","Fluoroquinolone option","Account for tube or perforation when present"],["Avoid","Ototoxic exposure","Do not assume an unseen membrane is intact"],["Prepare","Shake and hand-warm","Respect suspension and temperature instructions"]],
"ear-drop-technique":["Delivery sequence","Position, straighten, instill, distribute, and dwell",["Warm","Closed bottle","Reduce cold-triggered dizziness without uncontrolled heat"],["Position","Affected ear upward","Use age-appropriate pinna movement"],["Instill","No tip contact","Protect sterility and give the exact dose"],["Remain","Adequate dwell","Use gentle tragal movement when directed"]],
"cerumen-impaction":["Wax decision","Treat symptoms or blocked examination, not the sight of wax alone",["Define","Clinical impaction","Hearing, fullness, pain, tinnitus, or blocked view"],["Modify","Anatomy and host","Tube, surgery, stenosis, bleeding, diabetes, or immunity"],["Remove","Safe method","Cerumenolytic, irrigation, or manual care by risk"],["Reassess","Persistent symptoms","Find the next diagnosis after wax clears"]],
tinnitus:["Sound without source","Classify urgency, hearing, burden, and secondary clues",["Time","Sudden or persistent","Protect sudden hearing-loss pathways"],["Pattern","Pulse or asymmetry","Investigate vascular, neural, or structural sources"],["Burden","Sleep and function","Measure distress, mood, concentration, and safety"],["Support","CBT, hearing, sound","Reduce impact without promising a universal cure"]],
"special-populations-follow-up":["Closed-loop ear care","Age, devices, host risk, technique, and trajectory shape safety",["Child","Tube or foreign body","Use exact pediatric assessment and labeling"],["Older adult","Hearing and devices","Do not stop after wax if impairment remains"],["Return","Expected response","Define a 48 to 72 hour checkpoint when infection is treated"],["Escalate","Pain, swelling, hearing, balance","Act on mastoid, neurologic, invasive, or sudden findings"]],
};
export default function CommonEarConditionsVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual common-ear-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
