export const communityAcquiredPneumoniaAdultsVisualTypes=["biology-pathogenesis","diagnosis-imaging","severity-disposition","microbiology-testing","outpatient-selection","inpatient-selection","resistant-pathogens","viral-guideline-conflict","duration-follow-up","integration-prevention"].map(type=>`cap-${type}`);
const diagrams={
"biology-pathogenesis":["Alveolar sequence","Connect infection to gas exchange and systemic risk",["Enter","Distal airspace","A pathogen reaches an alveolar compartment."],["Fill","Inflammation","Cells and fluid reduce effective ventilation."],["Mismatch","Gas exchange","Perfusion continues through poorly ventilated units."],["Escalate","Systemic response","Hypoxemia, organ injury, or sepsis can follow."]],
"diagnosis-imaging":["Diagnostic frame","Require syndrome, lung evidence, and alternatives",["Hear","Compatible story","Cough, dyspnea, fever, pain, and trajectory raise suspicion."],["Measure","Physiology","Vitals, oxygen, work, perfusion, and mentation define consequence."],["Confirm","New infiltrate","Radiograph or expert ultrasound supports adult CAP."],["Reopen","Alternative","Embolism, edema, aspiration, and chronic infection can mimic it."]],
"severity-disposition":["Disposition ladder","Move from score to the real delivery environment",["Estimate","PSI","A validated rule supports mortality and site decisions."],["Detect","Major criterion","Ventilation or vasopressor shock defines severe CAP."],["Count","Minor criteria","Three or more establish severe disease."],["Verify","Home safety","Intake, support, access, oxygen, and goals still matter."]],
"microbiology-testing":["Testing loop","Order only when the result can change care",["Collect","High-value specimen","Severe or resistant-risk disease supports cultures."],["Interpret","Colonization","A detected organism is not automatically causal."],["Narrow","Negative evidence","Validated MRSA screening can support de-escalation."],["Own","Result and action","Every pending test needs a reviewer and decision."]],
"outpatient-selection":["Outpatient fork","Match comorbidity, spectrum, and patient safety",["Focus","Healthy adult","Amoxicillin or doxycycline can fit."],["Verify","Macrolide resistance","Monotherapy needs a low local rate."],["Broaden","Comorbidity","Use combination therapy or a selected respiratory quinolone."],["Audit","Patient risk","Allergy, QT, organs, interactions, and access choose the path."]],
"inpatient-selection":["Inpatient frame","Build around severity and reliable exposure",["Pair","Nonsevere CAP","Beta-lactam plus macrolide is a standard frame."],["Combine","Severe CAP","Beta-lactam plus macrolide or respiratory quinolone is required."],["Transition","IV to oral","Current stability and absorption control route."],["Limit","Anaerobic add-on","Aspiration alone does not prove abscess or empyema."]],
"resistant-pathogens":["Resistance gate","Use prior microbiology instead of a broad label",["Retrieve","Prior isolate","Respiratory MRSA or Pseudomonas history changes risk."],["Review","Recent IV therapy","A 90-day exposure strengthens concern."],["Culture","Before broadening","Microbiology makes later narrowing possible."],["De-escalate","Prompt review","A reasonable start still needs an exit."]],
"viral-guideline-conflict":["Evidence split","Show the points of agreement and disagreement",["Agree","Low-risk outpatient","Virus-positive disease can avoid antibiotics when bacterial suspicion is low."],["Agree","Severe CAP","Empiric antibacterial therapy remains appropriate."],["Dispute","Comorbid outpatient","ATS favors treatment while IDSA rejects a routine default."],["Dispute","Nonsevere inpatient","ATS favors treatment while IDSA favors dynamic individualization."]],
"duration-follow-up":["Stability clock","Let response and disease biology control duration",["Measure","Clinical stability","Vitals, oxygen, mentation, and intake must recover."],["Consider","Three-day minimum","Selected stable nonsevere adults may stop before day five."],["Extend","Severe or complicated","Necrosis, resistant pathogens, or deep infection need more."],["Recheck","Failure","Reopen diagnosis, delivery, organism, and source control."]],
"integration-prevention":["Closed-loop plan","Connect today’s regimen to the next protected state",["Write","Complete prescription","Dose, route, safety, monitoring, and exit are explicit."],["Separate","Pediatric scope","Children require age-specific evidence and protocols."],["Prevent","Vaccination","Reconcile influenza, pneumococcal, and COVID-19 protection."],["Assign","Follow-up owner","Response, recurrence, and imaging questions reach someone."]],
};
export default function CommunityAcquiredPneumoniaAdultsVisual({type}){const diagram=diagrams[type.replace("cap-","")];if(!diagram)return null;const[eyebrow,title,...nodes]=diagram;return <figure className="chol-visual community-acquired-pneumonia-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={`${verb}-${focus}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
