const diagrams = {
  "contraception-selection": ["Selection framework", "Begin with the person, then narrow by medical eligibility", ["Goals", "Pregnancy, bleeding, privacy, control", "Ask what the patient wants from the method"], ["Eligibility", "U.S. MEC and interactions", "Remove options with unacceptable risk"], ["Choice", "Shared decision", "Support the patient's preference among safe methods"]],
  "contraception-combined": ["Combined methods", "One hormone pair, several delivery systems", ["Estrogen", "Suppress follicular recruitment", "Reduce FSH-driven follicular development"], ["Progestin", "Block the LH surge and thicken mucus", "Prevent ovulation and sperm passage"], ["Format", "Pill, patch, or ring", "Match schedule and product instructions to real use"]],
  "contraception-estrogen-risk": ["Estrogen screen", "Vascular risk changes combined-method eligibility", ["Measure", "Blood pressure and smoking", "Quantify current cardiovascular risk"], ["Clarify", "Migraine aura and thrombosis", "Separate ordinary headache from focal neurologic aura"], ["Decide", "U.S. MEC category", "Avoid category 4 and carefully evaluate category 3"]],
  "contraception-progestin": ["Progestin methods", "No estrogen does not mean one uniform method", ["Daily", "Product-specific POP", "Use the correct missed-pill window"], ["Depot", "DMPA injection", "Plan reinjection, bone counseling, and return to fertility"], ["Context", "Testosterone use", "Do not assume amenorrhea prevents pregnancy"]],
  "contraception-iuds": ["Intrauterine choice", "Copper and levonorgestrel solve different problems", ["LNG", "Local progestin", "Highly effective contraception with less bleeding over time"], ["Copper", "Hormone-free sperm inhibition", "Long acting and effective for emergency use, with more bleeding possible"], ["Place", "Shared pain plan", "Use person-centered analgesia and avoid routine misoprostol"]],
  "contraception-implant": ["Implant care", "Effectiveness is simple, bleeding management is individualized", ["Prevent", "Etonogestrel exposure", "Suppress ovulation and thicken cervical mucus"], ["Assess", "Changed bleeding", "Exclude another cause when the pattern requires it"], ["Honor", "Removal request", "Remove at any time and offer another method if desired"]],
  "contraception-emergency": ["Emergency options", "Time, effectiveness, and hormonal restart define the choice", ["Copper IUD", "Most effective and ongoing", "Place within the eligible five-day window"], ["Ulipristal", "30 mg within five days", "Wait five days before hormonal contraception"], ["Levonorgestrel", "1.5 mg as soon as possible", "Restart regular hormones immediately with backup"]],
  "contraception-quick-start": ["Start pathway", "Remove delay without losing safety", ["Exclude", "Reasonably certain not pregnant", "Use the CDC checklist and testing when useful"], ["Start", "Initiate the selected method", "Do not require the next menstrual period routinely"], ["Protect", "Backup and missed-use plan", "Give a method-specific date and action sequence"]],
  "contraception-interactions": ["Interaction map", "Review both the contraceptive and the other medicine", ["Induce", "Lower hormone exposure", "Rifampin and selected inducers can reduce efficacy"], ["Shift", "Lamotrigine concentration", "Estrogen can lower exposure and hormone-free intervals can raise it"], ["Adapt", "Method or monitoring", "Choose an interaction-resistant plan and coordinate care"]],
  "contraception-care-loop": ["Care loop", "A contraceptive choice can change as the patient changes", ["Teach", "Use and expectations", "Confirm start, backup, missed use, and warning symptoms"], ["Review", "Satisfaction and health", "Assess bleeding, adherence, new conditions, and new medicines"], ["Transition", "Switch, stop, or plan pregnancy", "Preserve autonomy and continuous reproductive care"]],
};

export default function ContraceptivePharmacotherapyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
