export const coughCommonColdVisualTypes = ["triage", "product-selection", "supportive-care", "cough-therapy", "congestion", "pediatrics", "interaction-safety", "evidence-natural-products", "follow-up"];
const diagrams = {
  triage:["Clinical entry","Separate a self-limited cold from a time-sensitive alternate diagnosis",["Define","Onset and trajectory","Ask when symptoms began, changed, improved, or returned"],["Screen","Risk and severity","Check breathing, hydration, vital signs, oxygenation, and focal findings"],["Differentiate","Flu and COVID-19","Protect the early antiviral window when risk supports testing"],["Escalate","Red flags","Move beyond self-care when the pattern no longer fits"]],
  "product-selection":["Ingredient audit","Treat the symptom without buying avoidable harm",["Name","Active ingredients","Ignore the front-brand promise until the Drug Facts panel is read"],["Match","One symptom, one purpose","Each ingredient needs a current target"],["Sum","Total exposure","Find duplicate acetaminophen, antihistamine, and dextromethorphan"],["Verify","Exact product","Age, strength, formulation, and device control the dose"]],
  "supportive-care":["Low-risk relief","Start with measures that respect the natural course",["Hydrate","Fluids and rest","Support comfort without claiming viral eradication"],["Open","Saline and suction","Relieve nasal obstruction with clean mechanical care"],["Soothe","Honey after age one","Use age and swallowing safety"],["Relieve","Pain and fever","Calculate total analgesic exposure across every product"]],
  "cough-therapy":["Cough decision","Decide whether to clear mucus, suppress a reflex, or investigate",["Expectorate","Guaifenesin","Target productive secretions rather than every cough"],["Suppress","Dextromethorphan","Screen MAOIs, serotonergic burden, sedation, and misuse"],["Anesthetize","Benzonatate","Swallow whole, use from age ten, and lock it away"],["Restrict","Opioid products","Adult-only labeling does not erase respiratory and addiction risk"]],
  congestion:["Congestion pathway","Separate local relief, systemic exposure, and uncertain efficacy",["Stimulate","Pseudoephedrine","Screen pressure, heart, thyroid, diabetes, urinary, and MAOI risk"],["Question","Oral phenylephrine","FDA's proposed removal concerns lack of efficacy"],["Limit","Topical sprays","Give oxymetazoline or phenylephrine a short stop date"],["Prevent","Rebound","Do not treat rhinitis medicamentosa with more continuous spray"]],
  pediatrics:["Pediatric safety","Use age, product, dose, and caregiver technique as one system",["Avoid","Young-child products","Current CDC guidance is more conservative than older dosing tables"],["Support","Infants and toddlers","Use saline, suction, hydration, and clinical assessment"],["Measure","Milliliters","Use a product-specific syringe or cup, never a household spoon"],["Protect","Storage","Prevent benzonatate, opioid, and combination-product ingestion"]],
  "interaction-safety":["Safety screen","Read the medicine cabinet before recommending another product",["Block","MAOI conflict","Dextromethorphan and decongestants require exact-label separation"],["Recognize","Serotonin toxicity","Agitation, clonus, hyperreflexia, tremor, and fever form a syndrome"],["Reduce","CNS depression","Sedating antihistamines, opioids, alcohol, and sleep aids can compound"],["Protect","Cardiovascular reserve","Sympathomimetics can worsen pressure, rate, and ischemic risk"]],
  "evidence-natural-products":["Evidence lens","Separate modest uncertain benefit from confident marketing",["Consider","Oral zinc","Early use may shorten some colds but formulation and tolerance matter"],["Avoid","Intranasal zinc","Loss of smell makes this route unacceptable"],["Limit","Vitamin C claims","Do not promise prevention or cure from megadoses"],["Reject","Homeopathic certainty","No FDA-approved homeopathic cough and cold product exists"]],
  "follow-up":["Closed-loop care","Give every self-care plan an expected course and exit",["Expect","Improvement","Most uncomplicated colds resolve without specific treatment"],["Stop","Product date","Topical decongestants and symptom medicines need boundaries"],["Return","Worsening pattern","Breathing difficulty, dehydration, prolonged fever, or double worsening changes care"],["Steward","Antibiotics","Use them for a defined bacterial diagnosis, not mucus color"]],
};
export default function CoughCommonColdVisual({type}) { const item=diagrams[type]; if(!item)return null; const [eyebrow,title,...nodes]=item; return <figure className="chol-visual cough-cold-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],i)=><div key={focus}><span>{String(i+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>; }
