const diagrams = {
  "cushing-recognition": ["Clinical signal", "Separate cortisol excess from common look-alikes", ["Observe", "Progressive pattern", "Bruising, weakness, striae, fracture, diabetes, and hypertension cluster"], ["Reconstruct", "Every glucocorticoid route", "Oral, injected, inhaled, topical, ocular, and hidden products count"], ["Name", "Syndrome or disease", "Pituitary ACTH defines Cushing disease within the broader syndrome"]],
  "cushing-testing": ["Biochemical proof", "Test excess, rhythm, and feedback", ["Nadir", "Late-night saliva", "Repeated sampling tests loss of the nocturnal low point"], ["Integration", "Urine free cortisol", "Complete collections estimate daily unbound cortisol excretion"], ["Feedback", "Dexamethasone suppression", "Adequate drug exposure should suppress normal morning cortisol"]],
  "cushing-acth": ["Causal branch", "Classify confirmed hypercortisolism with ACTH", ["Low", "ACTH independent", "Localize autonomous adrenal cortisol production"], ["Measurable", "ACTH dependent", "Differentiate pituitary and ectopic secretion"], ["Borderline", "Repeat and contextualize", "Protect the branch point from handling and assay error"]],
  "cushing-localization": ["Source map", "Let biochemistry choose the image", ["Adrenal", "Suppressed ACTH", "Use adrenal imaging after ACTH-independent classification"], ["Pituitary", "Measurable ACTH", "MRI supports but does not prove a corticotroph source"], ["Resolve", "Petrosal sinus sampling", "Selected discordant cases require central-to-peripheral ACTH comparison"]],
  "cushing-severity": ["Urgency map", "Control multisystem cortisol toxicity", ["Threat", "Infection and thrombosis", "Search actively because ordinary warning signs may be muted"], ["Stabilize", "Potassium, glucose, and pressure", "Treat immediate injury while cortisol control develops"], ["Escalate", "Rapid cortisol control", "Severe disease may need intensive or definitive therapy"]],
  "cushing-surgery": ["Cause-directed care", "Remove the source and measure recovery", ["Resect", "Pituitary, adrenal, or ectopic tumor", "Match the operation to established localization"], ["Replace", "Postoperative hypocortisolism", "Support the suppressed normal axis during recovery"], ["Follow", "Persistent or recurrent disease", "Long-term biochemical surveillance remains necessary"]],
  "cushing-steroidogenesis": ["Enzyme control", "Lower cortisol while tracking pathway diversion", ["Block", "CYP11B1", "Osilodrostat and metyrapone reduce terminal cortisol synthesis"], ["Broaden", "Steroidogenic CYP inhibition", "Levoketoconazole adds hepatic, QT, and interaction constraints"], ["Balance", "Titrate or block and replace", "Choose control strategy from severity and variability"]],
  "cushing-directed": ["Targeted therapy", "Match the endpoint to the mechanism", ["Pituitary", "Pasireotide", "Reduce ACTH while monitoring severe hyperglycemia risk"], ["Selected use", "Cabergoline", "Off-label pituitary therapy requires response surveillance"], ["Receptor", "Mifepristone", "Judge clinical response because cortisol does not normalize reliably"]],
  "cushing-longterm": ["Durable sequence", "Plan beyond the next cortisol result", ["Bridge", "Pituitary radiation", "Medical control may be needed during delayed response"], ["Definitive", "Bilateral adrenalectomy", "Rapid control creates permanent replacement dependence"], ["Recover", "Lifelong surveillance", "Track recurrence, tumor behavior, hormones, and comorbidity repair"]],
};

export default function CushingSyndromeVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
