export const daptomycinPharmacologyVisualTypes = ["structure-mechanism", "spectrum-resistance", "site-selection", "dosing-pk", "renal-dialysis", "preparation-administration", "myopathy-statin", "eosinophilic-pneumonia", "immune-neurologic-lab", "integration"];

const diagrams = {
  "structure-mechanism": ["Membrane event", "Calcium turns a cyclic lipopeptide into a selective membrane disruptor", ["Fold", "Calcium association", "The anionic peptide adopts a more membrane-active conformation."], ["Recruit", "Phosphatidylglycerol", "Anionic gram-positive lipids attract and organize the complex."], ["Insert", "Decanoyl tail", "The lipophilic chain enters the membrane environment."], ["Collapse", "Potential and organization", "Electrical and envelope systems fail downstream."]],
  "spectrum-resistance": ["Susceptibility map", "Species, MIC, and dose assumption must agree", ["Cover", "Susceptible gram-positive organisms", "MRSA and selected enterococci can be targets."], ["Exclude", "Gram-negative organisms", "Outer-envelope biology prevents useful activity."], ["Interpret", "E. faecium SDD", "The category assumes a defined higher-dose strategy."], ["Repeat", "Persistent bacteremia", "Membrane adaptation can emerge during high-burden infection."]],
  "site-selection": ["Anatomic gate", "A susceptible isolate is not enough when the site disables the drug", ["Treat", "cSSSI", "Pair an indicated regimen with drainage and debridement."], ["Clear", "S. aureus bacteremia", "Repeat cultures, investigate source, and assess metastatic foci."], ["Support", "Right-sided endocarditis", "Keep the labeled evidence boundary visible."], ["Reject", "Primary pneumonia", "Pulmonary surfactant inhibits antibacterial activity."]],
  "dosing-pk": ["Exposure design", "Convert a weight-based target into an executable dose", ["Select", "Dosing weight", "Document the current weight and evidence-based convention."], ["Calculate", "Milligrams", "Multiply weight by the indication-specific mg/kg target."], ["Distinguish", "Labeled and off-label", "Higher specialist doses do not become new label indications."], ["Preserve", "Once-daily ceiling", "Do not divide exposure into more frequent routine doses."]],
  "renal-dialysis": ["Clearance pathway", "Renal trajectory and dialysis timing control the interval", ["Estimate", "Creatinine clearance", "Use the current adult label threshold and changing physiology."], ["Extend", "Below 30 mL/min", "The labeled adult interval becomes every 48 hours."], ["Coordinate", "Hemodialysis", "Give after the session when possible and document actual timing."], ["Escalate", "Pediatric renal uncertainty", "Do not invent a child regimen from the adult rule."]],
  "preparation-administration": ["Product workflow", "The vial label determines every operational step", ["Identify", "Exact formulation", "Vial strength and reconstitution instructions can differ."], ["Reconstitute", "50 mg/mL", "Use the permitted fluid and avoid vigorous shaking."], ["Protect", "Compatibility", "CUBICIN RF is incompatible with dextrose-containing diluents."], ["Time", "Age-specific administration", "Adults and children do not share every injection option."]],
  "myopathy-statin": ["Muscle surveillance", "Make CPK, symptoms, renal function, and statins one system", ["Baseline", "CPK and muscle context", "Exercise, disease, trauma, and medicines affect interpretation."], ["Trend", "At least weekly", "Increase frequency when risk or values rise."], ["Act", "Symptoms plus 1,000 U/L", "The labeled discontinuation threshold is lower when symptoms are present."], ["Balance", "Statin need", "Consider temporary suspension using cardiovascular and infection context."]],
  "eosinophilic-pneumonia": ["Pulmonary warning", "A drug that cannot treat pneumonia can cause an inflammatory pneumonia", ["Time", "Usually 2 to 4 weeks", "Exposure history frames the differential."], ["Recognize", "Fever, dyspnea, hypoxemia", "Diffuse infiltrates or organizing pneumonia raise urgency."], ["Stop", "Daptomycin", "Immediate discontinuation is part of the labeled response."], ["Treat", "Inflammation and original infection", "Support oxygenation, consider steroids, and replace coverage."]],
  "immune-neurologic-lab": ["Signal separation", "Phenotype determines whether the threat is immune, neurologic, renal, or analytical", ["Escalate", "DRESS or blistering disease", "Assess mucosa, eosinophils, and every organ."], ["Investigate", "TIN or neuropathy", "New renal or distal neurologic change needs a cause map."], ["Verify", "Discordant PT or INR", "Repeat near trough or with an alternative reagent."], ["Contextualize", "Pregnancy, lactation, and age", "Use narrative evidence rather than retired letters."]],
  "integration": ["Closed-loop regimen", "Make site, exposure, operations, safety, and exit agree", ["Define", "Organism and compartment", "Confirm the drug can reach and remain active at the site."], ["Execute", "Dose and exact product", "Make every calculation and preparation reconstructable."], ["Measure", "Cultures, CPK, kidney, and lungs", "Response and toxicity share one timeline."], ["Exit", "Narrow, switch, or stop", "Write source, failure, and completion thresholds early."]],
};

export default function DaptomycinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual daptomycin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
