const diagrams = {
  "diarrhea-phenotype": { eyebrow: "Phenotype map", title: "Duration and stool character define the first diagnostic branches", accent: "#77a9b5", columns: [["Time", "Acute to chronic", "Duration changes the likely causes and the need for testing."], ["Form", "Watery, fatty, inflammatory", "Stool character reveals mechanism and urgency."], ["Function", "Tolerable to incapacitating", "Burden matters alongside the number of stools."]] },
  "diarrhea-triage": { eyebrow: "Safety gate", title: "Hydration and inflammatory features come before symptom control", accent: "#c86f61", columns: [["Perfusion", "Urine, mentation, vital signs", "Volume loss can be the immediate threat."], ["Inflammation", "Blood, fever, severe pain", "Dysentery moves care away from routine antimotility use."], ["Host", "Age, immunity, comorbidity", "Vulnerability lowers the threshold for escalation."]] },
  "diarrhea-causes": { eyebrow: "Cause timeline", title: "The exposure map often finds the diagnosis before the laboratory does", accent: "#b79364", columns: [["People", "Contacts and outbreaks", "Shared illness can identify transmission and public health risk."], ["Products", "Medicines and supplements", "New starts and dose changes can create a reversible cause."], ["Places", "Food, water, travel", "Environment narrows the infectious differential."]] },
  "diarrhea-rehydration": { eyebrow: "Transport physiology", title: "Glucose carries sodium, and water follows", accent: "#6da4bf", columns: [["Cotransport", "SGLT1", "Sodium and glucose enter the epithelial cell together."], ["Balance", "Reduced osmolarity", "A measured electrolyte solution replaces water without excess solute."], ["Precision", "Exact dilution", "The correct water volume determines safety and performance."]] },
  "diarrhea-testing": { eyebrow: "Decision testing", title: "Every test should answer a question that changes care", accent: "#a786b4", columns: [["Acute", "Severity and exposure", "Test when the result changes treatment or public health action."], ["Healthcare", "C. difficile context", "Compatible symptoms and risk make the test interpretable."], ["Chronic", "Actionable causes", "Prioritize inflammation, Giardia, celiac disease, and bile acid diarrhea."]] },
  "diarrhea-supportive": { eyebrow: "Support system", title: "Recovery depends on more than a medicine", accent: "#8da77b", columns: [["Restore", "Fluid and nutrition", "Replace losses and resume tolerable nourishment."], ["Protect", "Skin and transmission", "Reduce injury and interrupt fecal-oral spread."], ["Reassess", "A defined window", "Stop self-care when the phenotype or severity changes."]] },
  "diarrhea-bismuth": { eyebrow: "Salicylate check", title: "The active ingredient matters more than the familiar bottle", accent: "#c8a46d", columns: [["Role", "Secretion and microbes", "Selected noninvasive symptoms can improve."], ["Dose", "Read the concentration", "Regular and maximum-strength liquids use different volumes."], ["Safety", "Bleeding and Reye risk", "Age, pregnancy, allergy, and interacting drugs shape selection."]] },
  "diarrhea-antimotility": { eyebrow: "Motility boundary", title: "Slow the bowel only when slowing the bowel is safe", accent: "#cb806f", columns: [["Select", "Nonbloody and afebrile", "Inflammatory features exclude routine monotherapy."], ["Limit", "Dose and duration", "Label boundaries protect against cardiac and gastrointestinal harm."], ["Escalate", "Arrhythmia or distention", "Toxicity and obstruction signals require urgent care."]] },
  "diarrhea-travel": { eyebrow: "Travel pathway", title: "Functional severity determines the intensity of treatment", accent: "#8b98ba", columns: [["Mild", "Tolerable", "Hydration and selected symptom relief are usually enough."], ["Moderate", "Disruptive", "A prescribed antibiotic plan can be considered."], ["Severe", "Incapacitating or dysentery", "Cause-directed treatment and evaluation take priority."]] },
  "diarrhea-persistent": { eyebrow: "Diagnostic reset", title: "Persistence turns a symptom episode into a cause-finding problem", accent: "#7f9f91", columns: [["Infection", "Protozoa and Giardia", "Duration after travel or water exposure changes probability."], ["Mechanism", "Bile acid and malabsorption", "Chronic watery or fatty patterns need targeted evaluation."], ["Trajectory", "New alarm evidence", "Nocturnal symptoms, weight loss, anemia, or blood reopen the case."]] },
};

export default function DiarrheaAssessmentVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
