const diagrams = {
  "supp-traditional-use": { eyebrow: "Exposure identity", title: "Translate a plant tradition into a product you can evaluate", accent: "#b6946e", columns: [["Name", "Species and plant part", "Record the scientific name and whether the exposure uses root, leaf, flower, fruit, bark, seed, or another part."], ["Prepare", "Method and formulation", "Distinguish food, tea, powder, tincture, extract, topical, capsule, and enhanced formulation."], ["Test", "Evidence and outcome", "Honor historical context while asking whether current clinical evidence matches the product and goal."]] },
  "supp-regulation": { eyebrow: "Regulatory map", title: "Category defines what the label can prove", accent: "#d5a978", columns: [["Identify", "Product category", "Supplement, drug, food, medical food, cosmetic, or homeopathic product."], ["Interrogate", "Label and intended use", "Read serving, ingredients, claims, disclaimer, and directions together."], ["Infer", "Evidence boundary", "Market access and a disclaimer do not establish FDA approval or efficacy."]] },
  "supp-evidence": { eyebrow: "Evidence architecture", title: "Mechanism, quality, and clinical benefit are separate questions", accent: "#9caf9b", columns: [["Match", "Exact intervention", "Species, extraction, dose, route, duration, and product must align."], ["Judge", "Outcome evidence", "Prioritize controlled evidence and clinically meaningful outcomes."], ["Qualify", "Identity and purity", "Use verification as a quality signal, never as proof of benefit."]] },
  "supp-reconciliation": { eyebrow: "Exposure reconstruction", title: "The interaction often hides outside the medication list", accent: "#86abb5", columns: [["Ask", "Purpose-based prompts", "Sleep, energy, mood, exercise, digestion, pain, weight, and general health."], ["Capture", "Product and daily dose", "Record label, serving, frequency, timing, source, and recent changes."], ["Map", "Mechanism and consequence", "Connect enzymes, transporters, absorption, additive effects, and organ risk."]] },
  "supp-bleeding": { eyebrow: "Procedure safety", title: "Replace the herb list with cumulative risk", accent: "#c97c84", columns: [["Product", "Evidence and exposure", "Identify the ingredient, formulation, dose, duration, and confidence."], ["Patient", "Bleeding reserve", "Add anticoagulants, antiplatelets, NSAIDs, disease, history, and labs."], ["Procedure", "Team plan", "Set individualized stop, monitoring, and restart decisions."]] },
  "supp-organ-risk": { eyebrow: "High-consequence toxicity", title: "Recognize the pattern before causality is complete", accent: "#d17d70", columns: [["Liver", "Kava and extracts", "Treat jaundice, dark urine, fatigue, and abdominal symptoms urgently."], ["Heart", "Stimulant mixtures", "Assess pressure, rate, rhythm, chest symptoms, seizure, and co-exposures."], ["Electrolytes", "True licorice", "Connect hypertension, edema, and hypokalemia to glycyrrhizin."]] },
  "supp-botanical-cases": { eyebrow: "Botanical comparison", title: "One familiar name can conceal several different exposures", accent: "#9dae82", columns: [["Plant", "Part and preparation", "Separate ripe elderberry from nonberry parts, and aloe gel from latex or whole-leaf extract."], ["Product", "Formulation and content", "Identify curcumin enhancement, EPA and DHA amounts, cannabinoids, route, and daily serving."], ["Patient", "Claim and consequence", "Match outcome evidence, interactions, toxicity, pregnancy, and organ function to the actual exposure."]] },
  "supp-neuroactive": { eyebrow: "Brain and behavior", title: "Timing and cumulative exposure define the effect", accent: "#a79bc3", columns: [["Stimulate", "Total caffeine", "Count coffee, tea, energy drinks, powders, blends, and medicines."], ["Signal", "Melatonin timing", "Match the circadian target, formulation, dose, and sleep schedule."], ["Sedate", "Combined impairment", "Add herbs, alcohol, antihistamines, opioids, cannabis, and prescriptions."]] },
  "supp-cardiometabolic": { eyebrow: "Product translation", title: "A familiar ingredient is not a standardized medicine", accent: "#c2a468", columns: [["Red yeast rice", "Variable monacolin", "Expect statin-like effects without a predictable dose or contaminant profile."], ["Omega-3", "Formulation-specific evidence", "Separate diet, prescription products, and consumer mixtures."], ["Performance blend", "Stacked stimulants", "Identify caffeine, synephrine, yohimbe, and undeclared exposure."]] },
  "supp-vitamins": { eyebrow: "Nutrient decision", title: "Supplement a measured need inside a life-stage plan", accent: "#b8a86e", columns: [["Define", "Need and cause", "Use diet, life stage, symptoms, disease, medication, and laboratory evidence."], ["Select", "Form and exposure", "Translate DFE, elemental iron, vitamin form, and duplicate products."], ["Follow", "Response and toxicity", "Measure the intended outcome and stop unnecessary accumulation."]] },
  "supp-special-categories": { eyebrow: "Category boundaries", title: "CBD, homeopathy, and medical foods answer different questions", accent: "#b2877d", columns: [["CBD", "One approved medicine", "Do not transfer prescription approval to retail oils, foods, or gummies."], ["Homeopathy", "No FDA-approved products", "Account for active ingredients, contamination, toxicity, and delayed care."], ["Medical food", "Distinctive nutritional need", "Use enterally under medical supervision for defined dietary management."]] },
  "supp-care-plan": { eyebrow: "Clinical workflow", title: "Make every decision measurable, reversible, and documented", accent: "#78a897", columns: [["Question", "Patient goal", "Name the desired outcome and the consequence of delaying proven care."], ["Plan", "Exact trial and safeguards", "Define product, dose, duration, monitoring, and stopping rule."], ["Learn", "Follow-up and reporting", "Measure benefit, act on harm, preserve product details, and report serious events."]] },
};

export default function DietarySupplementsComplementaryMedicineVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual dietary-supplements-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
