const diagrams = {
  "doac-targets": { eyebrow: "Direct anticoagulant targets", title: "Direct factor Xa inhibitors reduce thrombin generation, while dabigatran blocks thrombin activity after conversion from its prodrug.", accent: "#c36f64", columns: [["Factor Xa", "Apixaban, rivaroxaban, and edoxaban", "Reduce prothrombinase output"], ["Thrombin", "Dabigatran", "Reduce fibrin formation and amplification"], ["Exposure", "Rapid onset and shorter offset", "Adherence determines continuity"], ["Selection", "Indication and patient factors", "Do not treat products as interchangeable"]] },
  "doac-factor-xa": { eyebrow: "Oral factor Xa inhibitors", title: "Apixaban, rivaroxaban, and edoxaban share a target but use different phase, kidney, food, weight, and interaction rules.", accent: "#b88c62", columns: [["Apixaban", "Twice-daily pathways", "AF criteria differ from VTE phases"], ["Rivaroxaban", "Once or twice daily by phase", "15 and 20 mg require food"], ["Edoxaban", "Once daily after lead-in for VTE", "High CrCl restriction in NVAF"], ["Verify", "Label and indication", "Recalculate at every transition"]] },
  "doac-dabigatran": { eyebrow: "Direct thrombin inhibition", title: "Dabigatran etexilate requires conversion, kidney and P-gp review, product-aware handling, and a parenteral lead-in for adult VTE treatment.", accent: "#7f9eb4", columns: [["Absorb", "Acidified prodrug capsule", "Swallow whole and protect from moisture"], ["Convert", "Esterase activation", "Produce direct thrombin inhibitor"], ["Clear", "Kidney-dependent elimination", "Reassess during acute illness"], ["Reverse", "Idarucizumab", "Use for emergency surgery or uncontrolled major bleeding"]] },
  "doac-selection": { eyebrow: "Selection and implementation", title: "Kidney and liver function, interactions, age, weight, anatomy, pregnancy, absorption, access, and adherence determine whether a DOAC regimen is viable.", accent: "#8ca17a", columns: [["Confirm", "Indication and phase", "Apply the correct regimen"], ["Calculate", "Creatinine clearance", "Use product-specified renal criteria"], ["Screen", "P-gp, CYP3A, and hemostatic drugs", "Predict exposure and bleeding"], ["Implement", "Food, frequency, swallowing, and cost", "Prevent missed or ineffective doses"]] },
  "doac-procedures": { eyebrow: "Monitoring and procedures", title: "Routine INR monitoring is not used, but safe care still requires organ surveillance, last-dose history, product-sensitive testing, and neuraxial coordination.", accent: "#a78ab4", columns: [["Monitor", "CBC, kidney, liver, adherence", "Reassess at clinically appropriate intervals"], ["Estimate", "Last dose and clearance", "Do not rely on normal PT or aPTT alone"], ["Interrupt", "Procedure bleeding risk", "Use product and organ-specific timing"], ["Resume", "Hemostasis and indication", "Avoid an unnecessary unprotected interval"]] },
  "doac-bleeding": { eyebrow: "Bleeding and reversal", title: "Major DOAC bleeding requires resuscitation and source control plus drug-specific reversal or hemostatic support and a plan to restore anticoagulation.", accent: "#c29c62", columns: [["Identify", "Drug, dose, and last exposure", "Estimate residual effect"], ["Control", "Resuscitation and source", "Do not delay definitive hemostasis"], ["Reverse", "Idarucizumab or factor Xa strategy", "Match the confirmed agent"], ["Restart", "Underlying thrombotic risk", "Resume as soon as medically appropriate"]] },
};

export default function DirectOralAnticoagulantsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
