const diagrams={
"dipd-patterns":{accent:"#91a3af",eyebrow:"Phenotype first",title:"Localize the injury before naming the culprit",columns:[["Airway","Cough and bronchospasm","Irritation, mediator accumulation, or smooth-muscle effect"],["Parenchyma","Inflammation and fibrosis","Organizing, interstitial, eosinophilic, or alveolar injury"],["Beyond","Vascular and ventilatory","Pressure, edema, bleeding, weakness, or depressed drive"]]},
"dipd-causality":{accent:"#c2a36f",eyebrow:"Causal reasoning",title:"Exposure, latency, pattern, exclusion, and trajectory",columns:[["Expose","Build the timeline","Start, stop, dose, cycle, organ function, and procedure"],["Compare","Test alternatives","Infection, edema, embolism, tumor, radiation, and disease"],["Observe","Dechallenge","Recovery after withdrawal supports but does not prove causality"]]},
"dipd-assessment":{accent:"#7d9daf",eyebrow:"Decision-ready evidence",title:"Match every test to the question it must answer",columns:[["Image","Pattern and extent","Use radiography and CT to localize disease and alternatives"],["Measure","Physiology and gas exchange","Trend oxygen, ventilation, spirometry, volumes, and diffusion"],["Sample","Resolve uncertainty","Use lavage or biopsy only when the result can change care"]]},
"dipd-classic":{accent:"#b78373",eyebrow:"Classic toxicants",title:"Different agents, different latency and mechanism",columns:[["Retain","Amiodarone","Tissue persistence, phospholipidosis, inflammation, and fibrosis"],["React","Nitrofurantoin and MTX","Acute hypersensitivity or subacute immune pneumonitis"],["Accumulate","Bleomycin","Dose, kidney function, age, radiation, and oxygen context"]]},
"dipd-oncology":{accent:"#9a88ae",eyebrow:"Cancer therapy",title:"Grade the lung while excluding infection and tumor",columns:[["Grade 1","Observe closely","Asymptomatic and limited with repeat assessment"],["Grade 2","Hold and treat","Prednisone, prolonged taper, and 48 to 72 hour check"],["Grade 3 or 4","Hospitalize","Permanent stop, IV steroid, and rescue immunosuppression"]]},
"dipd-modern-oncology":{accent:"#b98a9f",eyebrow:"Product-specific safety",title:"The molecule, grade, and current label control the action",columns:[["Detect","New respiratory change","Investigate cough, dyspnea, fever, or new imaging promptly"],["Identify","Exact anticancer product","Separate conjugate, kinase, mTOR, cytotoxic, and radiation risk"],["Act","Follow the current label","Hold, treat, discontinue, or reconsider only by product rule"]]},
"dipd-airway-vascular":{accent:"#79a7ad",eyebrow:"Beyond pneumonitis",title:"Mechanism determines the rescue",columns:[["Airway","Cough or spasm","Remove mediator or trigger and restore airflow"],["Vessel","Pressure or bleeding","Evaluate PAH, thrombus, hemorrhage, and edema"],["Ventilation","Drive or muscle","Support airway and carbon dioxide clearance"]]},
"dipd-management":{accent:"#c77b75",eyebrow:"Close the loop",title:"Stop harm without abandoning the underlying disease",columns:[["Stabilize","Treat physiology","Oxygen, ventilation, infection, edema, or airway support"],["Recover","Measure trajectory","Symptoms, oxygen, imaging, function, and taper response"],["Prevent","Document and report","Culprit, phenotype, severity, re-exposure plan, and alternatives"]]}};
export default function DrugInducedPulmonaryDiseaseVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,e],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{e}</p></div>)}</div></figure>}
