"use client";
import {useEffect,useRef,useState} from 'react';

const chapters = {
  dicyclomine: [
    ['Meet the target','A membrane, a receptor, a signal','Muscarinic receptors receive acetylcholine signals. This scene isolates that interaction to explain one part of dicyclomine’s action.','Receptor available','Signal possible'],
    ['Follow the medicine','Approaching the receptor','Dicyclomine reaches receptor sites after oral administration. The moving cluster represents the medicine; its path and geometry are illustrative.','Drug approaching','Signal possible'],
    ['Occupy the binding site','Binding does not mean activation','Dicyclomine acts as an antagonist at muscarinic acetylcholine receptors. Occupying a receptor can prevent acetylcholine from activating it.','Antagonist bound','Activation opposed'],
    ['Interrupt the message','A signal meets a blocked receptor','The acetylcholine particle cannot activate the occupied receptor in this schematic. Blocking a signal is different from sending an opposing signal.','Activation opposed','Transmission reduced'],
    ['Change tissue behavior','Less contractile drive','Muscarinic blockade helps reduce intestinal motility and spasm. Dicyclomine also acts directly on smooth muscle; this receptor journey does not represent its entire mechanism.','Muscarinic drive reduced','Motility reduced'],
    ['Look beyond the target','Other tissues receive the same kind of signal','Muscarinic effects extend beyond the gut. Reduced salivary secretion helps explain dry mouth; the body map connects additional label-reported effects.','Multiple tissues','Secretions may decrease'],
    ['Connect the outcome','One mechanism, benefit and burden','Relief of bowel spasm is a treatment goal. Constipation and dry mouth illustrate how related effects can become unwanted consequences.','Mechanism connected','Explore the body map'],
  ],
  albuterol: [
    ['Meet the target','The airway cell membrane','A β₂-adrenergic receptor sits in the smooth-muscle cell membrane. Its activation links an extracellular drug signal to an intracellular response.','Receptor available','Baseline signaling'],
    ['Follow the medicine','Approaching the receptor','Inhaled albuterol acts at airway β₂ receptors. The moving cluster is a visual symbol for the medicine, not an atomic model or a measured trajectory.','Drug approaching','Baseline signaling'],
    ['Activate the receptor','An agonist starts a response','Albuterol is a β₂ agonist. Binding can activate the receptor, which couples to the Gs signaling pathway.','Receptor activated','Gs engaged'],
    ['Relay the message','From receptor to enzyme','Gs couples receptor activation to adenylyl cyclase. The enzyme produces the intracellular messenger cyclic AMP.','Gs signaling','Adenylyl cyclase stimulated'],
    ['Amplify the signal','A messenger inside the cell','Increased cyclic AMP mediates downstream responses that favor bronchial smooth-muscle relaxation. Particle counts here are illustrative, not measured concentrations.','cAMP signaling increased','Relaxation favored'],
    ['Change tissue behavior','More room for airflow','Relaxation of bronchial smooth muscle opens the airway. This schematic explains bronchodilation without predicting a patient’s response.','Smooth muscle relaxes','Airway opens'],
    ['Connect the outcome','Local delivery still has wider effects','The treatment target is the airway. Tremor and cardiovascular effects can still occur; explore the linked body map and label evidence to connect those observations.','Mechanism connected','Explore the body map'],
  ]
};
export default function DrugMolecularJourney({lesson,motion,onBody}) {
 const steps=chapters[lesson.id]||chapters.dicyclomine;
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false),[baseline,setBaseline]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 const frame=useRef(null); const current=steps[step];
 useEffect(()=>{setStep(0);setPlaying(false);setBaseline(false);},[lesson.id]);
 useEffect(()=>{const receive=e=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='nas-journey-ready'){setReady(true);setError('');}if(e.data?.type==='nas-journey-error')setError('The 3D scene could not load. The chapter explanations remain available.');};window.addEventListener('message',receive);const timer=setTimeout(()=>{setReady(value=>{if(!value)setError('The 3D scene is taking longer than expected. Reload the page to retry.');return value;});},30000);return()=>{window.removeEventListener('message',receive);clearTimeout(timer);};},[]);
 useEffect(()=>{if(ready)frame.current?.contentWindow?.postMessage({type:'nas-journey-state',drug:lesson.id,step,motion,baseline},location.origin);},[ready,lesson.id,step,motion,baseline]);
 useEffect(()=>{if(!playing)return;const t=setTimeout(()=>{if(step===steps.length-1)setPlaying(false);else setStep(step+1);},8500);return()=>clearTimeout(t);},[playing,step,steps.length]);
 function select(i){setPlaying(false);setStep(i);}
 return <section className="molecular-journey" aria-label={`${lesson.name} molecular journey`}>
  <aside className="journey-chapters"><span className="drug-kicker">Interactive mechanism journey</span><h4>The {lesson.name} pathway</h4><p>Move from the cell membrane to the clinical effect.</p><nav aria-label="Journey chapters">{steps.map(([name],i)=><button type="button" key={name} aria-current={step===i?'step':undefined} onClick={()=>select(i)}><span>{String(i+1).padStart(2,'0')}</span>{name}<small>{i<5?'cell':'tissue'}</small></button>)}</nav><div className="journey-transport"><button type="button" aria-label="Previous chapter" disabled={step===0} onClick={()=>select(step-1)}>←</button><button type="button" aria-pressed={playing} onClick={()=>{if(step===steps.length-1)setStep(0);setPlaying(!playing);}}>{playing?'Pause journey':'Play journey'}</button><button type="button" aria-label="Next chapter" disabled={step===steps.length-1} onClick={()=>select(step+1)}>→</button></div><div className="journey-states"><span className="drug-kicker">Qualitative pathway state</span><strong>{baseline?'Unopposed baseline':current[3]}</strong><strong>{baseline?'Drug action removed':current[4]}</strong></div><a href={lesson.source} target="_blank" rel="noreferrer">Read the source label ↗</a></aside>
  <div className="journey-main"><div className="journey-stage"><iframe ref={frame} src="/learn/body-atlas/journey.html" title="Interactive molecular mechanism scene"/><div className="journey-scene-heading"><span className="drug-kicker">{String(step+1).padStart(2,'0')} / 07 · {step<5?'Cell membrane':'Tissue response'}</span><h4>{current[1]}</h4></div>{!ready&&!error&&<p className="journey-loading" role="status">Building molecular scene…</p>}{error&&<p className="journey-loading" role="alert">{error}</p>}<div className="journey-scene-controls"><button type="button" aria-pressed={baseline} onClick={()=>setBaseline(!baseline)}>{baseline?'Show drug action':'Compare without drug'}</button><button type="button" onClick={()=>frame.current?.contentWindow?.postMessage({type:'nas-journey-reset'},location.origin)}>Reset camera</button><span>Drag to orbit · scroll to zoom</span></div></div><div className="journey-caption" aria-live="polite"><span className="drug-kicker">The connection to make</span><p>{baseline?'Without the drug overlay, inspect the baseline pathway. Return to drug action to follow this chapter’s mechanism.':current[2]}</p><div className="journey-progress" aria-label={`Chapter ${step+1} of ${steps.length}`}>{steps.map((_,i)=><button type="button" aria-label={`Go to chapter ${i+1}`} aria-pressed={step===i} key={i} onClick={()=>select(i)}/>)}</div>{step===6&&<button className="journey-body-link" type="button" onClick={onBody}>Connect this mechanism to the body map ↗</button>}<small>Conceptual 3D illustration · not a resolved molecular structure, measured simulation, or physical scale.</small></div></div>
 </section>;
}
