const diagrams = {
  "adr-taxonomy-map": { eyebrow: "Event taxonomy", title: "Name the event, the mechanism, and the system contribution separately", accent: "#c9947e", columns: [["Reaction", "Correct use", "Predictable toxicity, allergy, intolerance, or uncertainty."], ["Error", "Process failure", "Prescribing, dispensing, administration, or monitoring."], ["Decision", "Future plan", "Treat harm, improve the system, and preserve safe options."]] },
  "adr-causality-map": { eyebrow: "Causality sequence", title: "A precise timeline is stronger than a vague allergy label", accent: "#a28cab", columns: [["Expose", "Drug and dose", "Start date, formulation, route, and concurrent agents."], ["React", "Phenotype and latency", "Symptoms, organs, severity, treatment, and outcome."], ["Resolve", "Evidence and plan", "Dechallenge, later tolerance, alternatives, and uncertainty."]] },
  "adr-safety-system": { eyebrow: "Safety architecture", title: "Label, communicate, control, report, and investigate", accent: "#9d9271", columns: [["Label", "Known risk", "Boxed warning, contraindication, and monitoring."], ["Control", "Risk program", "Medication Guide and current REMS requirements."], ["Detect", "Postmarket signal", "MedWatch report, FAERS review, and further study."]] },
  "adr-immune-pathways": { eyebrow: "Mechanism map", title: "Timing and organ pattern reveal the likely immune pathway", accent: "#8e9eb0", columns: [["Immediate", "Minutes to hours", "IgE or nonimmune mediator release."], ["Cell or complex", "Blood and vessels", "Cytopenia, vasculitis, fever, and organ injury."], ["Delayed", "Days to weeks", "T-cell eruptions, SCAR, and organ hypersensitivity."]] },
  "adr-anaphylaxis": { eyebrow: "Emergency sequence", title: "Epinephrine leads because airway and circulation cannot wait", accent: "#d48272", columns: [["Recognize", "Systemic progression", "Airway, breathing, circulation, skin, or gut."], ["Treat", "IM epinephrine", "Thigh injection, safe position, help, and repeat assessment."], ["Support", "Resuscitation", "Oxygen, fluids, airway care, monitoring, and adjuncts after."]] },
  "adr-scar-triage": { eyebrow: "Cutaneous danger", title: "Pain, mucosa, fever, and organ injury move the rash into emergency care", accent: "#bd766f", columns: [["Epidermal", "SJS and TEN", "Pain, dusky lesions, mucosal injury, and detachment."], ["Systemic", "DRESS", "Facial edema, blood changes, and internal-organ injury."], ["Pustular", "AGEP", "Acute sterile pustules, fever, and neutrophilia."]] },
  "adr-beta-lactam": { eyebrow: "Penicillin pathway", title: "The history selects delabeling, challenge, skin testing, or avoidance", accent: "#82a58f", columns: [["Low risk", "Benign or inconsistent", "Document, delabel, or use supervised oral challenge."], ["Immediate risk", "IgE phenotype", "Specialist review, skin testing, then challenge when negative."], ["Severe delayed", "SCAR or organ injury", "Strict avoidance, no routine testing, and specialist plan."]] },
  "adr-cross-reactivity": { eyebrow: "Precision alternatives", title: "Structure and phenotype are more useful than a shared class name", accent: "#a493be", columns: [["Beta-lactam", "Side-chain relationship", "Compare culprit, candidate, phenotype, and severity."], ["Sulfonamide", "Structural boundary", "Antibiotic allergy does not broadly cross-react with nonantibiotics."], ["NSAID", "Reaction phenotype", "Distinguish cross-reactive COX-1 patterns from one-drug allergy."]] },
  "adr-testing-pathway": { eyebrow: "Purpose before procedure", title: "Test probability, confirm tolerance, or create temporary access", accent: "#8ba2a8", columns: [["Skin test", "Immediate immune risk", "Use a validated question and trained interpretation."], ["Challenge", "Current tolerance", "Observe selected low-risk patients with rescue capability."], ["Desensitize", "Essential therapy", "Create temporary tolerance with uninterrupted treatment."]] },
  "adr-longitudinal-record": { eyebrow: "Future safety", title: "The result must travel farther than the allergy clinic", accent: "#b3946e", columns: [["Record", "Specific phenotype", "Drug, timing, severity, treatment, test, and tolerance."], ["Teach", "Patient action", "Avoidance, emergency plan, device practice, and follow-up."], ["Synchronize", "Every care setting", "Update pharmacy, hospital, primary care, and patient records."]] },
};

export default function DrugAllergiesAdverseReactionsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual drug-allergy-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
