const diagrams = {
  "lipoprotein-transport": { eyebrow: "Lipoprotein transport", title: "ApoB particles move triglyceride and cholesterol from intestine or liver toward tissue and arterial wall.", accent: "#7ca7bc", columns: [["Intestine", "Chylomicron + apoB-48", "Deliver dietary triglyceride"], ["Liver", "VLDL + apoB-100", "Export endogenous triglyceride"], ["Remodel", "Remnant to IDL to LDL", "Lipolysis changes cargo, not particle ancestry"], ["Return", "LDL receptor clearance", "Particle residence shapes arterial exposure"]] },
  "atherogenic-burden": { eyebrow: "Atherogenic burden", title: "Cholesterol mass and particle number answer different questions about arterial exposure.", accent: "#c28770", columns: [["LDL-C", "Cholesterol within LDL", "Primary screening and treatment metric"], ["Non-HDL-C", "All cholesterol outside HDL", "Captures LDL plus remnant cholesterol"], ["ApoB", "One copy per atherogenic particle", "Clarifies discordance in selected patients"], ["Time", "Concentration multiplied by years", "Cumulative exposure drives disease"]] },
  "triglyceride-remnants": { eyebrow: "Triglyceride-rich particles", title: "Triglycerides identify remnant biology and, at severe levels, a distinct pancreatitis pathway.", accent: "#c2a061", columns: [["Production", "VLDL and chylomicrons", "Diet, liver, insulin, and genetics shape output"], ["Clearance", "LPL and remnant uptake", "ApoC-II activates while apoC-III inhibits"], ["ASCVD", "Remnant apoB particles", "Particle cholesterol can enter the arterial wall"], ["Pancreas", "Severe chylomicronemia", "Acute pancreatitis prevention becomes urgent"]] },
  "inherited-secondary": { eyebrow: "Phenotype", title: "Inherited and secondary causes are reconstructed from level, pattern, age, family, medicines, and physiology.", accent: "#9b8dbb", columns: [["Inherited", "FH, FCS, mixed phenotypes", "Age and family history raise probability"], ["Metabolic", "Diabetes, obesity, hypothyroid", "Treat the driver and the lipid risk"], ["Organ", "Kidney, liver, pregnancy", "Physiology changes both values and treatment"], ["Exposure", "Alcohol and medicines", "Timing can reveal a reversible cause"]] },
  "risk-reclassification": { eyebrow: "Risk architecture", title: "Calculate, personalize, and reclassify before choosing treatment intensity.", accent: "#8fa57c", columns: [["Calculate", "PREVENT 10 + 30 year", "Use current primary-prevention equations"], ["Personalize", "Enhancers + Lp(a) + apoB", "Add information outside the calculator"], ["Reclassify", "Coronary artery calcium", "Use when the medication decision remains uncertain"], ["Decide", "Goal + intensity + preference", "Match lifelong burden and current absolute risk"]] },
  "screening-lifecycle": { eyebrow: "Lifecourse prevention", title: "Screen early, interpret the full phenotype, and repeat when physiology or treatment changes.", accent: "#c77c6e", columns: [["Child", "Universal 9 to 11", "Earlier with FH or premature ASCVD family history"], ["Adult", "Begin at 19", "Repeat generally every five years when low risk"], ["Special", "Pregnancy, CKD, HIV, diabetes", "Risk context changes timing and decisions"], ["Follow", "Response and adherence", "Repeat after treatment or major clinical change"]] },
};

export default function DyslipidemiaRiskVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
