const diagrams = {
  "dyslipidemia-goal-map": { eyebrow: "Goal-directed care", title: "Risk determines the LDL-C and non-HDL-C goals, while percentage response tests whether therapy performed as intended.", accent: "#c99b62", columns: [["Baseline", "Untreated burden", "Define phenotype and starting exposure"], ["Risk", "Primary, secondary, or inherited", "Choose the correct pathway"], ["Goal", "Absolute value and percent response", "Use both dimensions"], ["Reassess", "Exposure, safety, and access", "Explain every unexpected result"]] },
  "dyslipidemia-primary": { eyebrow: "Primary prevention", title: "Calculate, personalize, and reclassify only when the result can change the treatment decision.", accent: "#7da6b8", columns: [["Calculate", "PREVENT 10 and 30 year", "Use verified inputs in adults without disease"], ["Personalize", "Enhancers and lifetime burden", "Add risk outside the equation"], ["Reclassify", "Coronary artery calcium", "Resolve remaining uncertainty"], ["Treat", "Lifestyle plus lipid therapy", "Match intensity and goals to risk"]] },
  "dyslipidemia-secondary": { eyebrow: "Secondary prevention", title: "Established ASCVD requires rapid goal-directed therapy, not another primary-prevention risk calculation.", accent: "#c77d6d", columns: [["Classify", "Very high risk or other ASCVD", "Set LDL-C and non-HDL-C goals"], ["Start", "Maximally tolerated statin", "Do not delay foundational therapy"], ["Combine", "Evidence-based nonstatins", "Estimate the reduction still needed"], ["Close", "Adherence, access, and response", "Escalate without therapeutic inertia"]] },
  "dyslipidemia-triglycerides": { eyebrow: "Triglyceride pathway", title: "The immediate goal changes as triglycerides move from a residual-risk marker toward chylomicronemia and pancreatitis.", accent: "#b78c5f", columns: [["Persistent", "Correct secondary drivers", "Glycemia, alcohol, diet, medicines, and disease"], ["ASCVD", "Statin remains foundation", "Treat apoB particle risk"], ["At least 500", "Pancreatitis risk rises", "Confirm fasting phenotype and consider TG therapy"], ["At least 1000", "Chylomicronemia priority", "Very-low-fat plan and specialist pathway"]] },
  "dyslipidemia-familial": { eyebrow: "Inherited disease", title: "Severe lifelong exposure requires early treatment, family detection, and therapy matched to residual receptor function.", accent: "#9e8ab6", columns: [["Detect", "LDL-C, age, family, phenotype", "Do not let a low short-term score de-risk FH"], ["Treat", "Early combination therapy", "Reduce particle-years"], ["Escalate", "Receptor-dependent or independent", "Match pathway to HeFH or HoFH"], ["Cascade", "Relatives and genetics", "Turn one diagnosis into prevention"]] },
  "dyslipidemia-implementation": { eyebrow: "Treatment reliability", title: "Before calling therapy ineffective or intolerable, verify whether the patient received the intended drug exposure.", accent: "#87a078", columns: [["Acquire", "Coverage and supply", "A prescription is not exposure"], ["Take", "Technique and schedule", "Confirm the actual regimen"], ["Measure", "Response and safety", "Use an interpretable follow-up interval"], ["Adapt", "Rechallenge, combine, or refer", "Preserve risk reduction while solving barriers"]] },
};

export default function DyslipidemiaTherapeuticsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
