const diagrams = {
  "ecg-signal-system": { eyebrow: "Signal to tracing", title: "The ECG records changing electrical vectors through calibrated leads, not mechanical contraction or a direct image of the heart.", accent: "#b98268", columns: [["Calibrate", "25 mm/s and 10 mm/mV", "Verify before measuring"], ["Vector", "Direction and magnitude", "Lead polarity shapes deflection"], ["Sequence", "P, PR, QRS, ST, T", "Map activation and recovery"], ["Correlate", "Patient and prior tracing", "Never read in isolation"]] },
  "ecg-rate-rhythm": { eyebrow: "Rate and rhythm", title: "A disciplined rhythm read links ventricular rate, regularity, atrial activity, AV relationship, and QRS width.", accent: "#84a58d", columns: [["Rate", "Count precisely", "Use regular or irregular method"], ["Regularity", "Compare R to R and P to P", "Identify patterns"], ["Atria", "Find P or flutter activity", "Track morphology and rate"], ["Relationship", "Pair P waves and QRS", "Expose block or dissociation"]] },
  "ecg-intervals-axis": { eyebrow: "Intervals and axis", title: "PR, QRS, QTc, frontal axis, and morphology localize conduction delay and frame medication risk.", accent: "#849eb4", columns: [["PR", "Atrial to ventricular conduction", "Measure onset to onset"], ["QRS", "Ventricular depolarization", "Wide means altered activation"], ["QTc", "Depolarization plus repolarization", "Correct and interpret by context"], ["Axis", "Net frontal direction", "Use limb-lead polarity"]] },
  "ecg-conduction": { eyebrow: "Conduction patterns", title: "AV block and bundle-branch block are patterns of timing and morphology whose urgency depends on symptoms, level, escape reliability, and cause.", accent: "#aa8ab6", columns: [["AV node", "PR and dropped beats", "Distinguish Wenckebach from fixed PR"], ["His-Purkinje", "Wide QRS and block", "Higher progression risk"], ["Bundle", "RBBB or LBBB pattern", "Assess concordant clinical context"], ["Stabilize", "Perfusion before taxonomy", "Treat unstable bradycardia"]] },
  "ecg-ischemia-electrolytes": { eyebrow: "ST, T, and metabolic patterns", title: "Ischemia, infarction, pericardial disease, electrolytes, and drugs can alter ST segments, T waves, QRS width, and QT.", accent: "#c16f67", columns: [["Compare", "Contiguous leads and prior ECG", "Seek a territorial pattern"], ["Integrate", "Symptoms and serial change", "One tracing is not the diagnosis"], ["Correct", "Potassium, magnesium, calcium", "Treat dangerous physiology"], ["Review", "Drugs and toxins", "Connect target to waveform"]] },
  "ecg-emergency-workflow": { eyebrow: "Instability-first workflow", title: "The ECG refines treatment only after pulse, perfusion, symptoms, and reversible threats establish urgency.", accent: "#c39a5f", columns: [["Assess", "Pulse and perfusion", "Identify instability"], ["Acquire", "12-lead plus rhythm strip", "Check quality and calibration"], ["Interpret", "Rate through ischemia", "Use a fixed sequence"], ["Act", "Treat rhythm and cause", "Repeat after intervention"]] },
};

export default function EcgInterpretationVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
