export const fidaxomicinPharmacologyVisualTypes = ["mechanism-local-pk", "diagnosis-stewardship", "selection-guidelines", "adult-dosing-response", "pediatric-dosing", "suspension-administration", "recurrence-strategy", "safety-interactions", "special-populations-monitoring", "integration"];

const diagrams = {
  "mechanism-local-pk": ["Local mechanism", "Keep transcription, exposure, and disease compartment aligned", ["Deliver", "Oral dose", "Fidaxomicin enters the gastrointestinal lumen."], ["Bind", "RNA polymerase", "The drug inhibits bacterial RNA synthesis."], ["Concentrate", "Colon", "Parent drug and OP-1118 remain largely local."], ["Limit", "Systemic use", "Minimal absorption cannot support invasive infection therapy."]],
  "diagnosis-stewardship": ["Diagnostic gate", "Symptoms and testing must agree before treatment begins", ["Count", "Unformed stools", "Three or more in 24 hours prompts evaluation."], ["Exclude", "Other causes", "Review laxatives, feeds, drugs, and competing illness."], ["Test", "Appropriate specimen", "Interpret toxin and molecular results in context."], ["Avoid", "Test of cure", "Clinical recovery can coexist with colonization."]],
  "selection-guidelines": ["Episode map", "Severity and recurrence history determine the evidence pathway", ["Initial", "Conditional preference", "Use fidaxomicin when feasible; vancomycin remains acceptable."], ["Recurrent", "Standard or extended-pulsed", "Prior episodes and prior regimens shape selection."], ["Fulminant", "Different pathway", "Shock, ileus, or megacolon needs urgent multi-route care."], ["Resolve", "Access", "Confirm coverage and dispensing before discharge."]],
  "adult-dosing-response": ["Ten-day course", "Exact dosing and clinical response move on one timeline", ["Give", "200 mg", "Administer orally twice daily."], ["Continue", "10 days", "Do not stop because symptoms improve early."], ["Flex", "With or without food", "Choose times the patient can reproduce."], ["Reassess", "Clinical trajectory", "Escalate deterioration without waiting for completion."]],
  "pediatric-dosing": ["Weight bands", "Age, kilograms, and swallowing determine product and volume", ["4 to less than 7 kg", "2 mL", "Give 80 mg twice daily."], ["7 to less than 9 kg", "3 mL", "Give 120 mg twice daily."], ["9 to less than 12.5 kg", "4 mL", "Give 160 mg twice daily."], ["12.5 kg and above", "5 mL or tablet", "Give 200 mg twice daily when age and swallowing fit."]],
  "suspension-administration": ["Dose integrity", "Preparation, mixing, measurement, and storage preserve every milliliter", ["Prepare", "130 mL water", "Follow the labeled professional mixing sequence."], ["Calculate", "40 mg per mL", "Convert the prescribed milligrams to volume."], ["Measure", "Oral syringe", "Shake vigorously before drawing each dose."], ["Store", "2 to 8 degrees Celsius", "Refrigerate and discard after 12 days."]],
  "recurrence-strategy": ["Sustained response", "Treatment success extends beyond initial symptom control", ["Resolve", "Initial episode", "Assess end-of-treatment clinical response."], ["Protect", "Sustained response", "Lower recurrence drives the comparative benefit."], ["Reassess", "New diarrhea", "Distinguish recurrent CDI from another cause."], ["Prevent", "Future exposure", "Reduce unnecessary antibiotics and communicate history."]],
  "safety-interactions": ["Low absorption, active vigilance", "Local pharmacology still requires an actionable safety screen", ["Stop", "Severe allergy", "Angioedema or dyspnea needs urgent treatment."], ["Separate", "Drug effect and disease", "Bleeding, pain, and cytopenias need context."], ["Review", "P-gp inhibitors", "Cyclosporine raises low plasma concentrations."], ["Preserve", "Clinical monitoring", "No automatic interaction dose change replaces assessment."]],
  "special-populations-monitoring": ["Evidence narratives", "State known facts, uncertainty, and the patient decision together", ["Pregnancy", "Limited human data", "Balance clinical need, alternatives, and local exposure."], ["Lactation", "No human milk data", "Include maternal and infant context."], ["Kidney", "No adjustment", "Preserve the regimen across renal impairment."], ["Liver", "Not formally studied", "Do not turn expected low impact into proven evidence."]],
  "integration": ["Closed-loop CDI plan", "Make diagnosis, episode, access, exposure, follow-up, and prevention agree", ["Confirm", "True CDI", "Symptoms and testing must support treatment."], ["Classify", "Episode and severity", "Keep fulminant disease outside fidaxomicin monotherapy."], ["Execute", "Exact product", "Align dose, formulation, duration, and technique."], ["Close", "Response and recurrence", "Own follow-up, stewardship, isolation, and cleaning."]],
};

export default function FidaxomicinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual fidaxomicin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
