export const fluoroquinolonePharmacologyVisualTypes = [
  "target-structure", "agent-spectrum", "disposition-dosing", "administration-interactions", "tendon-neurologic",
  "metabolic-cardiovascular", "resistance-stewardship", "special-populations", "monitoring-counseling", "clinical-integration",
];

const diagrams = {
  "target-structure": ["Molecular target", "Trap the cleavage complex and convert replication into lethal DNA damage", ["Enter", "Reach bacterial cytosol", "Agent structure, permeability, and efflux shape intracellular exposure"], ["Bind", "Gyrase or topoisomerase IV", "The dominant target varies with organism and agent"], ["Trap", "Prevent DNA resealing", "Cleaved DNA accumulates while replication and transcription fail"], ["Kill", "Double-strand injury", "Exposure relative to MIC drives bactericidal pharmacology"]],
  "agent-spectrum": ["Agent map", "Differentiate the class before choosing the drug", ["Ciprofloxacin", "Gram-negative emphasis", "Use for susceptible targets, including selected Pseudomonas roles"], ["Levofloxacin", "Respiratory plus urinary roles", "Dose, renal function, site, and AST remain decisive"], ["Moxifloxacin", "Respiratory and anaerobic", "No routine renal adjustment, but not a UTI agent"], ["Delafloxacin", "ABSSSI and CABP", "Labeled activity includes susceptible MRSA without universal preference"]],
  "disposition-dosing": ["Exposure system", "Make dose, clearance, site, and route agree", ["Absorb", "Oral systemic exposure", "Cations, feeds, vomiting, and formulation can lower delivery"], ["Distribute", "Match the infection site", "Serum exposure does not guarantee useful urinary or tissue exposure"], ["Adjust", "Use the exact renal table", "Ciprofloxacin, levofloxacin, moxifloxacin, and delafloxacin differ"], ["Transition", "IV to oral when ready", "Require absorption, adherence, source control, susceptibility, and stability"]],
  "administration-interactions": ["Interaction gate", "Protect oral exposure and prevent metabolic toxicity", ["Inventory", "Find every cation", "Antacids, iron, zinc, calcium, sucralfate, and binders matter"], ["Separate", "Follow the exact label", "Spacing rules depend on the agent and interacting product"], ["Review", "CYP and anticoagulation", "Ciprofloxacin plus tizanidine is contraindicated, while warfarin needs surveillance"], ["Verify", "Feeds and formulations", "Tube route, nutrition, suspension, and flushing require a written plan"]],
  "tendon-neurologic": ["Stop-signal map", "Recognize disabling class reactions before the next dose", ["Tendon", "Pain, swelling, weakness", "Stop, rest, evaluate, and replace therapy when appropriate"], ["Nerve", "Burning, tingling, numbness", "Peripheral neuropathy may persist or become irreversible"], ["Brain", "Confusion, seizure, mood change", "CNS and psychiatric effects may occur after the first dose"], ["Muscle", "Myasthenic weakness", "Bulbar or respiratory decline is an emergency"]],
  "metabolic-cardiovascular": ["Risk stack", "Combine the agent's signal with the patient's reserve", ["Glucose", "Hypoglycemia or hyperglycemia", "Older adults with diabetes and glucose-lowering therapy need active monitoring"], ["Rhythm", "QT and torsade substrate", "Review QTc, electrolytes, bradycardia, and interacting drugs"], ["Aorta", "Aneurysm and dissection", "Avoid in high-risk patients when another treatment option exists"], ["System", "Liver and C difficile", "Jaundice or significant diarrhea can require immediate reassessment"]],
  "resistance-stewardship": ["Resistance ladder", "Prevent low-level escape from becoming clinical failure", ["Target", "gyrA and parC changes", "Stepwise mutations weaken drug binding and raise MIC"], ["Access", "Porin loss and efflux", "Reduced intracellular exposure compounds target resistance"], ["Transfer", "qnr and related mechanisms", "Plasmid-mediated protection can facilitate further selection"], ["Steward", "Reserve and reassess", "Use current AST, adequate exposure, source control, and the shortest supported duration"]],
  "special-populations": ["Context first", "Replace blanket rules with product-specific evidence", ["Child", "Age, indication, and label", "Anthrax, plague, and selected infections have distinct pediatric evidence"], ["Pregnancy", "Disease risk and fetal exposure", "Use current narrative labeling and active alternatives"], ["Lactation", "Drug-specific guidance", "Route, dose, infant age, and infection context influence the plan"], ["Older adult", "Reserve and vulnerability", "Tendon, glucose, renal, CNS, QT, and aortic risks can converge"]],
  "monitoring-counseling": ["Safety contract", "Turn every warning into a recognizable action", ["Before", "Screen history and interactions", "Document prior class reaction, renal function, ECG and glucose risks, and cations"], ["During", "Track efficacy and exposure", "Review cultures, symptoms, organ function, administration, and adverse effects"], ["Stop", "Name urgent symptoms", "Tendon, neuropathy, CNS, glucose, aortic, hepatic, and severe diarrhea signals need action"], ["Close", "Confirm duration and follow-up", "State who reviews the result, when therapy ends, and what replaces it"]],
  "clinical-integration": ["Closed-loop regimen", "Make every fluoroquinolone order answer twelve questions", ["Define", "Syndrome, severity, and source", "The drug cannot repair an uncertain diagnosis or uncontrolled source"], ["Prove", "Organism, AST, and exposure", "Susceptibility requires the right dose, site, route, and adherence"], ["Protect", "Interactions and serious harms", "Screen the whole risk stack before the first dose"], ["Exit", "Narrow, switch, stop, or continue", "Reassess at culture result, clinical response, adverse signal, and planned end date"]],
};

export default function FluoroquinolonePharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual fluoroquinolone-pharmacology-visual" aria-label={title}>
    <figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption>
    <div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}>
      <span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p>
    </div>)}</div>
  </figure>;
}
