export const fosfomycinPharmacologyVisualTypes = ["structure-mechanism", "transport-resistance", "cystitis-phenotype", "organism-guidance", "dose-preparation", "pk-urine", "selection-evidence", "safety-interactions", "special-populations", "integration"];

const diagrams = {
  "structure-mechanism": ["Covalent target map", "Follow the epoxide from bacterial entry to early cell-wall arrest", ["Deliver", "Phosphonic acid", "The tromethamine salt carries a compact polar active moiety."], ["Enter", "Cytosol", "Nutrient transport systems provide target access."], ["React", "MurA cysteine", "The strained epoxide forms a covalent adduct."], ["Stop", "Peptidoglycan precursor", "An early committed cell-wall step is blocked."]],
  "transport-resistance": ["Access and escape", "Activity depends on entry, intact drug, and a reachable target", ["Import", "Transporters", "Reduced uptake lowers intracellular fosfomycin."], ["Protect", "Epoxide", "Active drug must remain chemically intact."], ["Inactivate", "FosA", "Glutathione addition can destroy target binding."], ["Interpret", "Species", "E. coli guidance does not transfer to Klebsiella."]],
  "cystitis-phenotype": ["Compartment gate", "Keep the oral sachet inside the bladder-only phenotype", ["Confirm", "Lower-tract symptoms", "Dysuria, frequency, and urgency support cystitis."], ["Exclude", "Fever or flank pain", "Upper-tract disease needs another regimen."], ["Assess", "Host complexity", "Anatomy, obstruction, pregnancy, and severity matter."], ["Recheck", "Persistence", "Culture and choose another agent after failure."]],
  "organism-guidance": ["Evidence ladder", "Move from organism identity to the supported clinical role", ["Label", "E. coli and E. faecalis", "Susceptible strains support the oral indication."], ["Guide", "ESBL E. coli", "Oral fosfomycin is an alternative for uUTI."], ["Exclude", "Klebsiella", "Frequent fosA carriage compromises transfer."], ["Verify", "Testing method", "A missing susceptibility result is missing evidence."]],
  "dose-preparation": ["One-course workflow", "Turn the exact product into one correctly prepared dose", ["Read", "5.631 grams salt", "The packet contains the tromethamine compound."], ["Convert", "3 grams active", "Counterion mass does not increase active fosfomycin."], ["Mix", "3 to 4 ounces", "Use nonhot water and the entire sachet."], ["Take", "Immediately", "Drink once after the granules dissolve."]],
  "pk-urine": ["Exposure map", "Match modest absorption and renal excretion to bladder treatment", ["Absorb", "30 to 37 percent", "Food changes rate but not the labeled administration rule."], ["Distribute", "Unbound drug", "Fosfomycin is not plasma protein bound."], ["Concentrate", "Urine", "High urinary exposure supports the cystitis role."], ["Adjust thinking", "Renal decline", "Half-life rises while urinary recovery falls."]],
  "selection-evidence": ["Decision balance", "Let comparative effectiveness temper single-dose convenience", ["Define", "uUTI", "Keep infection confined to the bladder."], ["Prefer", "Active first choices", "Use current guidance and patient context."], ["Consider", "Fosfomycin alternative", "Reserve for a supported E. coli scenario."], ["Avoid drift", "Multidose or cUTI", "Evidence remains limited outside the narrow role."]],
  "safety-interactions": ["Safety timeline", "Separate expected tolerability from urgent and delayed signals", ["Expect", "GI effects", "Diarrhea, nausea, and dyspepsia can occur."], ["Stop", "Hypersensitivity", "Anaphylaxis and angioedema need urgent care."], ["Reassess", "Delayed diarrhea", "CDAD can emerge well after the dose."], ["Reconcile", "Metoclopramide", "Faster motility can reduce urinary exposure."]],
  "special-populations": ["Evidence narrative", "Replace shortcuts with population-specific clinical reasoning", ["Describe", "Pregnancy", "Placental transfer and limited human data shape risk."], ["Discuss", "Lactation", "Milk exposure evidence is not established."], ["Verify", "Age", "The labeled regimen is for adult women."], ["Assess", "Kidney function", "Renal decline changes half-life and urinary recovery."]],
  "integration": ["Closed-loop use", "Make syndrome, organism, product, and follow-up agree", ["Confirm", "Bladder-only infection", "Exclude upper-tract and systemic disease."], ["Match", "Organism and evidence", "Use species-specific current guidance."], ["Execute", "One sachet", "Prepare the full packet correctly."], ["Close", "Two to three days", "Reassess nonresponse rather than repeating automatically."]],
};

export default function FosfomycinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual fosfomycin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
