const diagrams = {
  "gerd-barrier": { eyebrow: "Exposure system", title: "Reflux becomes disease when exposure outruns clearance and defense", accent: "#d2a46f", columns: [["Barrier", "Junction pressure", "The lower esophageal sphincter, crural diaphragm, and hiatal anatomy resist retrograde flow."], ["Exposure", "Volume and chemistry", "Transient relaxation, pressure, gastric contents, and recumbency shape the reflux event."], ["Recovery", "Clearance and defense", "Peristalsis, saliva, gravity, and epithelium limit contact and injury."]] },
  "gerd-triage": { eyebrow: "Symptom triage", title: "The symptom pattern determines whether treatment or evaluation comes first", accent: "#cf7866", columns: [["Classic", "Heartburn and regurgitation", "Troublesome typical symptoms without alarms can enter a structured empiric pathway."], ["Alarm", "Dysphagia and bleeding", "Weight loss, anemia, vomiting, odynophagia, and structural concern require prompt evaluation."], ["Mimic", "Cardiac and airway", "Chest, cough, and laryngeal symptoms require alternate causes to be considered."]] },
  "gerd-diagnosis": { eyebrow: "Question-led testing", title: "Structure, reflux exposure, and motility require different instruments", accent: "#80a9b2", columns: [["Inspect", "Endoscopy", "Find erosions, stricture, Barrett esophagus, malignancy, or another mucosal process."], ["Measure", "pH and impedance", "Quantify exposure and relate symptoms to acid and nonacid reflux."], ["Map", "Manometry", "Define motor function and junction location before probes or invasive treatment."]] },
  "gerd-lifestyle": { eyebrow: "Mechanism-based care", title: "Change the pressure, timing, or position that reproduces the symptom", accent: "#8daa7b", columns: [["Pressure", "Weight and meal size", "Reduce a relevant abdominal-pressure and gastric-reservoir contribution."], ["Timing", "Meals and sleep", "Create two to three hours between the last meal and lying down."], ["Position", "Elevate and turn", "Raise the upper body and consider left-side sleep for nocturnal exposure."]] },
  "gerd-rapid-relief": { eyebrow: "Breakthrough relief", title: "Neutralize the acid or interrupt the reflux layer", accent: "#d9b06d", columns: [["Neutralize", "Antacid", "Fast, brief relief depends on salt, bowel effect, renal function, and sodium burden."], ["Barrier", "Alginate raft", "A floating gel can reduce postprandial movement of the acid pocket."], ["Separate", "Cation interactions", "Protect absorption of vulnerable antibiotics, thyroid hormone, iron, and other medicines."]] },
  "gerd-h2ra": { eyebrow: "Histamine pathway", title: "H2 blockade fits a limited symptom window and a renal safety plan", accent: "#789fb5", columns: [["Block", "Parietal H2 receptor", "Reduce histamine-driven cyclic AMP and acid secretion, especially at night."], ["Adapt", "Tachyphylaxis", "Continuous exposure can lose effect, making intermittent use useful for selected patterns."], ["Adjust", "Kidney function", "Reduce famotidine exposure when renal clearance falls and watch CNS and QT risk."]] },
  "gerd-ppi": { eyebrow: "Acid-pump pharmacology", title: "Delivery before the meal creates inhibition after the meal", accent: "#c48dbe", columns: [["Protect", "Delayed release", "Move an acid-labile prodrug through the stomach before intestinal absorption."], ["Activate", "Acidic canaliculus", "Trap and convert the prodrug near meal-activated parietal-cell pumps."], ["Bind", "Covalent inhibition", "Suppress active hydrogen-potassium ATPase until new functional pumps appear."]] },
  "gerd-selection": { eyebrow: "Treatment design", title: "Choose intensity, correct the routine, then reassess the response", accent: "#d5a260", columns: [["Start", "Pattern and severity", "Use an eight-week premeal PPI trial for uncomplicated classic symptoms."], ["Optimize", "Timing and adherence", "Verify the actual routine before switching or increasing treatment."], ["Escalate", "Defined trial", "Use a switch, twice-daily plan, or testing question with a clear endpoint."]] },
  "gerd-persistent": { eyebrow: "Persistent symptoms", title: "Do not keep escalating acid until the mechanism is known", accent: "#a28cc3", columns: [["Verify", "Treatment exposure", "Reconstruct product, dose, timing, adherence, and the exact residual symptom."], ["Test", "Prior evidence decides", "Use off-therapy testing for unproven GERD and on-therapy impedance for established disease."], ["Redirect", "Other mechanisms", "Consider hypersensitivity, functional disease, motility, rumination, cardiac, airway, and medication causes."]] },
  "gerd-maintenance": { eyebrow: "Longitudinal control", title: "Preserve a real indication at the lowest effective intensity", accent: "#82a88e", columns: [["Maintain", "Complicated disease", "Protect severe erosions, ulcer, stricture, Barrett esophagus, or high bleeding risk."], ["Reduce", "No chronic indication", "Step down or deprescribe with rebound counseling and follow-up."], ["Monitor", "Patient-specific risk", "Use labeled risks and interactions, not unsupported fear, to guide surveillance."]] },
};

export default function GastroesophagealRefluxDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
