const diagrams = {
  "gonadal-hpg-axis": ["Signal control", "Follow the pulse from hypothalamus to gonad", ["Pulse", "Hypothalamic GnRH", "Intermittent signaling preserves pituitary response"], ["Relay", "Pituitary LH and FSH", "Gonadotropins distribute steroidogenic and gametogenic work"], ["Feedback", "Steroids and inhibin", "Downstream hormones reshape the next signal"]],
  "gonadal-testicular": ["Testicular map", "Separate androgen production from sperm support", ["LH", "Leydig cell", "Generate testosterone from cholesterol-derived precursors"], ["FSH", "Sertoli cell", "Support germ cells and produce inhibin B"], ["Local", "Intratesticular testosterone", "Maintain the concentration required for spermatogenesis"]],
  "gonadal-ovarian": ["Cycle physiology", "Build the follicle through two coordinated cells", ["Theca", "LH creates androgen substrate", "Supply precursor to the neighboring granulosa cell"], ["Granulosa", "FSH increases aromatase", "Convert androgen substrate to estradiol"], ["Luteal", "Corpus luteum produces progesterone", "Transform and stabilize the post-ovulatory endometrium"]],
  "gonadal-steroidogenesis": ["Steroid pathway", "Trace shared precursors into tissue-specific products", ["Enter", "Cholesterol through StAR", "CYP11A1 creates pregnenolone"], ["Build", "Androgen and progestogen pathways", "Tissue enzymes determine the dominant product"], ["Convert", "DHT or estradiol", "5-alpha-reductase and aromatase modify local action"]],
  "gonadal-receptors": ["Receptor context", "The ligand starts the signal, but the tissue writes the response", ["Bind", "AR, ER, or PR", "Ligand changes receptor conformation"], ["Recruit", "Co-regulators", "Cell-specific proteins amplify or restrain transcription"], ["Express", "Tissue response", "Bone, breast, endometrium, brain, and liver can diverge"]],
  "gonadal-diagnosis": ["Diagnostic logic", "Confirm the deficit, then locate the failure", ["Agree", "Symptoms plus valid laboratory evidence", "Do not diagnose from a nonspecific symptom alone"], ["Repeat", "Accurate morning testosterone", "Exclude transient illness and invalid timing"], ["Locate", "LH and FSH", "Separate primary gonadal from central signaling failure"]],
  "gonadal-formulations": ["Product selection", "Match route and kinetics to the person", ["Daily", "Topical exposure", "Flexible adjustment with transfer precautions"], ["Depot", "IM or SC ester", "Longer intervals with product-specific peaks and monitoring"], ["Oral", "Testosterone undecanoate", "Follow formulation-specific administration and blood-pressure guidance"]],
  "gonadal-safety": ["Monitoring loop", "Measure benefit and toxicity together", ["Respond", "Symptoms and testosterone", "Confirm appropriate product-specific exposure"], ["Protect", "Hematocrit and blood pressure", "Detect erythrocytosis and pressure elevation"], ["Reassess", "Prostate, fertility, edema, apnea, misuse", "Investigate new risk rather than escalating automatically"]],
  "gonadal-estrogen-progestogen": ["Hormone context", "Molecule, route, and tissue determine the clinical result", ["Estrogen", "Proliferation and systemic effects", "Support target tissues while accounting for hepatic and thrombotic context"], ["Progestogen", "Secretory transformation", "Oppose persistent endometrial estrogen exposure when needed"], ["Select", "Indication-specific regimen", "Contraception, menopause, and gynecologic care require separate risk frameworks"]],
  "gonadal-pathway-therapy": ["Intervention points", "Choose where to alter the hormone pathway", ["Signal", "GnRH agonist or antagonist", "Change pituitary gonadotropin output"], ["Synthesize", "Aromatase or 5-alpha-reductase", "Reduce formation of an active tissue hormone"], ["Respond", "Receptor modulator or antagonist", "Change tissue action after the hormone is produced"]],
};

export default function GonadalHormonePharmacologyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
