const diagrams = {
  "gyn-cycle-triage": ["Clinical triage", "Start with the threat, then define the pattern", ["First", "Stability and pregnancy", "Identify shock or pregnancy-related bleeding before routine classification"], ["Next", "Pattern and burden", "Map timing, flow, pain, anemia, and daily-life impact"], ["Then", "Cause-directed workup", "Select examination, laboratory testing, imaging, or tissue assessment"]],
  "gyn-palm-coein": ["Cause map", "Separate structure from function", ["PALM", "Structural causes", "Polyp, adenomyosis, leiomyoma, malignancy or hyperplasia"], ["COEIN", "Nonstructural causes", "Coagulopathy, ovulatory, endometrial, iatrogenic, not classified"], ["Overlap", "More than one cause", "Update the working diagnosis as evidence accumulates"]],
  "gyn-acute-aub": ["Acute response", "Control bleeding without losing diagnostic sight", ["Stabilize", "Perfusion and access", "Resuscitate and prepare blood support when indicated"], ["Control", "Patient-specific medical therapy", "Choose hormonal or antifibrinolytic treatment only when safe"], ["Escalate", "Procedural readiness", "Move quickly when instability or treatment failure persists"]],
  "gyn-hmb-selection": ["Treatment selection", "Match bleeding control to anatomy and goals", ["Nonhormonal", "Tranexamic acid or NSAID", "Preserve ovulation while targeting fibrinolysis or prostaglandins"], ["Hormonal", "LNG-IUS or systemic therapy", "Suppress endometrial growth when acceptable and safe"], ["Structural", "Procedure or surgery", "Address cavity distortion, large fibroids, or refractory symptoms"]],
  "gyn-pain-pathway": ["Pain pathway", "Separate prostaglandin pain from secondary disease", ["Primary", "Cyclic prostaglandin excess", "Start NSAID early and on schedule when safe"], ["Suppress", "Reduce menstrual activity", "Use a suitable hormonal strategy when desired"], ["Investigate", "Atypical or refractory pain", "Evaluate endometriosis, adenomyosis, fibroids, or infection"]],
  "gyn-pmdd-cycle": ["Symptom timing", "The cycle is part of the diagnosis", ["Luteal", "Symptoms emerge", "Track mood, cognition, behavior, and physical burden daily"], ["Menses", "Symptoms improve", "Look for a reproducible transition near menstrual onset"], ["Follicular", "Minimal symptoms", "Persistent symptoms suggest another disorder or comorbidity"]],
  "gyn-endometriosis-map": ["Disease map", "Symptoms can exceed what imaging reveals", ["Surface", "Superficial disease", "Normal ultrasound cannot exclude small peritoneal lesions"], ["Ovary", "Endometrioma", "Ultrasound can identify a characteristic ovarian lesion"], ["Deep", "Infiltrating disease", "Map bowel, bladder, and pelvic involvement when symptoms suggest it"]],
  "gyn-endometriosis-therapy": ["Suppression ladder", "Escalate while protecting long-term health", ["Relieve", "NSAID and supportive care", "Treat pain without claiming lesion suppression"], ["Suppress", "Combined or progestogen therapy", "Reduce cycling when pregnancy is not currently desired"], ["Intensify", "GnRH therapy with safeguards", "Apply dose, duration, add-back, bone, mood, and pregnancy precautions"]],
  "gyn-fibroid-map": ["Fibroid anatomy", "Location changes the clinical problem", ["Submucosal", "Toward the cavity", "Bleeding and fertility effects can be disproportionate"], ["Intramural", "Within the myometrium", "Bleeding, pain, and uterine bulk can coexist"], ["Subserosal", "Toward the serosa", "Pressure symptoms may dominate over bleeding"]],
  "gyn-longitudinal-care": ["Care loop", "Reassess the patient, not only the prescription", ["Measure", "Bleeding, pain, function, iron", "Define success in terms the patient can feel"], ["Protect", "Toxicity and reproductive goals", "Monitor the specific risks created by the regimen"], ["Escalate", "Failure or new red flags", "Repeat the diagnostic process when the story changes"]],
};

export default function GynecologicDisordersVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
