const diagrams={
"hf-medchem-ras":{eyebrow:"RAS medicinal chemistry",title:"ACE inhibitors and ARBs preserve target-recognition pharmacophores while prodrug masking, zinc-binding groups, acidity, lipophilicity, metabolism, and elimination distinguish each molecule.",accent:"#ba7968",columns:[["ACE","Coordinate catalytic zinc","Sulfhydryl or carboxylate"],["Prodrug","Mask polarity for absorption","Hydrolyze to active diacid"],["ARB","Anionic aromatic pharmacophore","Block AT1 recognition"],["Patient","Activation and organ clearance","Do not assume equivalence"]]},
"hf-medchem-arni":{eyebrow:"ARNI molecular system",title:"Sacubitril is activated to LBQ657, while valsartan blocks AT1 signaling that would otherwise rise within neprilysin's broad peptide network.",accent:"#849eb5",columns:[["Sacubitril","Absorbable ester prodrug","Esterase activation"],["LBQ657","Neprilysin inhibitor","Preserve vasoactive peptides"],["Valsartan","Active AT1 antagonist","Control angiotensin signaling"],["Complex","Product-specific formulation","Respect ACE separation"]]},
"hf-medchem-beta":{eyebrow:"Beta-blocker scaffold",title:"The aryloxypropanolamine motif supports adrenergic binding, while stereochemistry, aromatic substitution, alpha1 activity, CYP metabolism, and release technology shape clinical behavior.",accent:"#a68ab7",columns:[["Anchor","Aromatic ether","Hydrophobic recognition"],["Orient","Beta hydroxyl and amine","Stereochemical binding"],["Tune","Ring substitution","Selectivity and access"],["Deliver","Salt and release system","Evidence belongs to product"]]},
"hf-medchem-mra":{eyebrow:"Mineralocorticoid receptor design",title:"Steroidal and nonsteroidal antagonists share a nuclear-receptor target but differ in off-target steroid binding, metabolites, cofactor behavior, distribution, metabolism, and evidence populations.",accent:"#8da57d",columns:[["Spironolactone","Steroid plus active metabolites","Endocrine cross-reactivity"],["Eplerenone","Modified steroid","Higher receptor selectivity"],["Finerenone","Nonsteroidal scaffold","Distinct cofactor and distribution"],["Use","Potassium, kidney, interactions","Follow indication-specific evidence"]]},
"hf-medchem-renal":{eyebrow:"Renal delivery chemistry",title:"SGLT2 C-glucosides act at a luminal transporter, while highly protein-bound organic-acid loop diuretics require active tubular secretion to reach NKCC2.",accent:"#c0995e",columns:[["C-glucoside","Stable sugar carbon linkage","Oral SGLT2 inhibition"],["Aglycone","Hydrophobic selectivity region","Transporter affinity"],["Loop acid","Protein-bound organic anion","Proximal secretion"],["Lumen","Reach NKCC2","Response depends on delivery"]]},
"hf-medchem-vasodilator":{eyebrow:"Vasodilator and rate chemistry",title:"Hydralazine acetylation, nitrate bioactivation and tolerance, and ivabradine use-dependent If access connect molecular processing to pressure, heart rate, interactions, and dosing behavior.",accent:"#ba8d67",columns:[["Hydralazine","Acetylation variability","Exposure and immune risk"],["Nitrate","Bioactivate to cGMP signaling","Tolerance and PDE5 interaction"],["Ivabradine","Open-channel If access","Sinus rhythm required"],["Monitor","Pressure, pulse, exposure","Match molecule to phenotype"]]},
"hf-medchem-integrated":{eyebrow:"Structure to clinical decision",title:"Hydralazine acetylation, nitrate bioactivation, ivabradine channel access, digoxin glycoside architecture, and vericiguat sGC stimulation show why mechanism and disposition must be read together.",accent:"#b8746c",columns:[["Activate","Prodrug or bioactivation","Find the active species"],["Transport","Membrane, carrier, tissue","Locate the target"],["Clear","Enzyme, kidney, bile","Predict accumulation"],["Verify","Label, trial, guideline","Structure is not the verdict"]]},
};
export default function HeartFailureMedicinalChemistryVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
