const diagrams = {
  "hf-definition-stages": { eyebrow: "Heart failure continuum", title: "Heart failure progresses from risk to structural or biomarker evidence, symptomatic disease, and advanced refractory physiology, while ejection fraction defines a separate phenotype axis.", accent: "#bd7a6a", columns: [["Stage A", "At risk", "Prevent injury"], ["Stage B", "Pre-heart failure", "Find structure or biomarkers"], ["Stage C", "Current or prior symptoms", "Treat disease and syndrome"], ["Stage D", "Advanced refractory illness", "Refer before the window closes"]] },
  "hf-pump-mechanics": { eyebrow: "Pump mechanics", title: "Stroke volume and filling pressure emerge from preload, afterload, contractility, compliance, rhythm, valve behavior, and ventricular interaction.", accent: "#849eb5", columns: [["Fill", "Volume, time, compliance", "Pressure is not volume"], ["Contract", "Myocardial force", "Separate from load"], ["Eject", "Arterial and valve load", "Afterload is composite"], ["Recover", "Relaxation and recoil", "Prepare the next beat"]] },
  "hf-neurohormonal": { eyebrow: "Compensation becomes disease", title: "Sympathetic, RAAS, vasopressin, natriuretic, inflammatory, and remodeling signals initially protect perfusion but can later amplify congestion, arrhythmia, fibrosis, and organ injury.", accent: "#a78bb8", columns: [["Sense", "Low effective perfusion", "Baroreceptor and kidney signals"], ["Compensate", "Rate, tone, sodium, water", "Preserve pressure"], ["Pay", "Oxygen demand and congestion", "Chronic toxicity"], ["Remodel", "Myocyte and matrix change", "Progressive substrate"]] },
  "hf-congestion-cardiorenal": { eyebrow: "Congestion and cardiorenal physiology", title: "Forward flow and backward pressure interact, so kidney, liver, gut, lung, and brain dysfunction cannot be explained by arterial pressure alone.", accent: "#88a37d", columns: [["Left pressure", "Pulmonary hydrostatic load", "Interstitial and alveolar edema"], ["Right pressure", "Systemic venous hypertension", "Organ back pressure"], ["Flow", "Cardiac output", "Perfusion and oxygen delivery"], ["Kidney", "Arterial and venous forces", "Interpret the trajectory"]] },
  "hf-phenotypes": { eyebrow: "Heart failure phenotypes", title: "Reduced, mildly reduced, preserved, and improved ejection fraction describe current or historical ventricular behavior, but each requires clinical syndrome and etiologic reasoning.", accent: "#c29a5e", columns: [["HFrEF", "Ejection fraction at or below 40", "Define the cause"], ["HFmrEF", "41 to 49 percent", "Border phenotype"], ["HFpEF", "At least 50 percent", "Prove filling-pressure disease"], ["HFimpEF", "Prior low, now above 40", "Remission is not cure"]] },
  "hf-diagnostic-trajectory": { eyebrow: "Diagnostic trajectory", title: "Symptoms lead to objective confirmation, phenotype, etiology, congestion and perfusion assessment, trigger detection, and timely advanced-care referral.", accent: "#b8736b", columns: [["Confirm", "Clinical plus objective evidence", "Exclude mimics"], ["Phenotype", "Structure, function, pressures", "Use the right modality"], ["Explain", "Etiology and trigger", "Find reversible disease"], ["Project", "Trajectory and goals", "Escalate at the right time"]] },
};
export default function HeartFailurePathophysiologyVisual({ type }) { const d = diagrams[type]; if (!d) return null; return <figure className="chol-visual" style={{ "--chol-accent": d.accent }} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([name, mechanism, decision], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{mechanism}</em><p>{decision}</p></div>)}</div></figure>; }
