export const herpesLabialisVisualTypes = ["hsv-biology", "clinical-recognition", "transmission-control", "episodic-treatment", "oral-antiviral-selection", "antiviral-safety", "symptom-care", "prevention-monitoring"];
const diagrams = {
  "hsv-biology": ["Viral lifecycle", "Follow HSV from mucocutaneous entry to neuronal latency and episodic reactivation", ["Entry", "Skin or mucosa", "Local replication begins"], ["Travel", "Sensory axon", "Virus reaches the ganglion"], ["Latency", "Neuronal genome persists", "No current eradication therapy"], ["Return", "Reactivation to the lip", "Prodrome can precede vesicles"]],
  "clinical-recognition": ["Pattern recognition", "Separate recurrent labial HSV from primary disease, mimics, and urgent complications", ["Recurrent", "Familiar prodrome", "Grouped vesicles near the lip"], ["Primary", "Diffuse oral disease", "Fever and impaired intake"], ["Mimic", "Ulcer, fissure, crust", "Diagnosis changes treatment"], ["Urgent", "Eye or neurologic symptoms", "Protect sight and life"]],
  "transmission-control": ["Break the contact chain", "Visible lesions raise risk, but shedding and transfer cannot be judged perfectly by appearance", ["Contact", "Kissing and oral exposure", "Avoid during outbreaks"], ["Fomite", "Lip and personal products", "Do not share"], ["Hands", "Lesion to eye or skin", "Wash after contact"], ["Shedding", "Can occur without lesions", "Risk reduction is not zero risk"]],
  "episodic-treatment": ["Treat the replication window", "Topical benefit depends on early recognition, correct site, and sustained application", ["Prodrome", "Tingle, itch, burn", "Start immediately"], ["Docosanol", "OTC external use", "Five times daily until healed"], ["Penciclovir", "Every two waking hours", "Continue four days"], ["Acyclovir", "Cutaneous use only", "Follow exact product label"]],
  "oral-antiviral-selection": ["Match formulation to the episode", "Indication, timing, route, immune status, and renal function define the regimen", ["Valacyclovir", "Two doses in one day", "Verify renal table"], ["Acyclovir", "Activated in infected cells", "Inhibits viral DNA polymerase"], ["Buccal", "Single upper-gum dose", "Apply within one hour of prodrome"], ["Route", "Oral versus topical", "Balance benefit and burden"]],
  "antiviral-safety": ["Clear the antiviral safely", "Renal clearance connects hydration, dose, kidney injury, and neurologic toxicity", ["Kidney", "Calculate clearance", "Adjust the indication-specific dose"], ["Water", "Prevent avoidable concentration", "Respect heart and kidney limits"], ["Brain", "Confusion, tremor, seizure", "Consider accumulation"], ["Host", "Immune compromise", "Standard self-care evidence may not apply"]],
  "symptom-care": ["Protect the healing barrier", "Comfort care should reduce pain and triggers without creating new tissue injury", ["Cool", "Compress and hydration", "Support comfort"], ["Barrier", "Bland lip protection", "Avoid picking"], ["Sun", "SPF 30 plus lip balm", "Useful when sunlight is a trigger"], ["Claims", "Lysine and home remedies", "Do not replace proven care"]],
  "prevention-monitoring": ["Escalate by burden and risk", "Frequency is only one dimension of prevention and referral", ["Burden", "Episodes and function", "Consider suppressive planning"], ["Immune", "Prolonged or atypical disease", "Test and treat earlier"], ["Eczema", "Monomorphic painful spread", "Urgent systemic care"], ["Follow", "Eye, infection, duration", "Know the red flags"]],
};
export default function HerpesLabialisVisual({ type }) { const d = diagrams[type]; if (!d) return null; const [eyebrow, title, ...nodes] = d; return <figure className="chol-visual herpes-labialis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v, f, detail], i) => <div key={f}><span>{String(i + 1).padStart(2, "0")}</span><strong>{v}</strong><em>{f}</em><p>{detail}</p></div>)}</div></figure>; }
