const diagrams = {
  "emergency-triage": { eyebrow: "Triage", title: "The organ injury, not the number alone, defines a hypertensive emergency.", accent: "#c77c6e", columns: [["Verify", "Repeat correctly", "Treat the patient and a reliable signal"], ["Search", "Brain + heart + aorta + kidney + retina", "Find new or worsening injury"], ["Classify", "Severe without injury versus emergency", "The route and setting change completely"], ["Escalate", "Monitored protocol", "Match urgency to the injured organ"]] },
  "emergency-physiology": { eyebrow: "Perfusion", title: "Controlled reduction protects tissue that has adapted to high pressure.", accent: "#7ca7bc", columns: [["Autoregulation", "Chronic pressure shifts the range", "Abrupt normalization may cause ischemia"], ["Goal", "Condition-specific", "Avoid one universal target"], ["Agent", "Rapid, titratable, predictable", "Match mechanism and organ state"], ["Monitor", "Continuous pressure + organ response", "Prevent variability and overshoot"]] },
  "emergency-neurologic": { eyebrow: "Neurologic emergency", title: "Ischemia, hemorrhage, and encephalopathy require different pressure strategies.", accent: "#9b8dbb", columns: [["Image", "Exclude hemorrhage", "Do not infer stroke type from pressure"], ["Ischemia", "Reperfusion pathway", "Follow treatment-specific thresholds"], ["ICH", "Smooth sustained control", "Avoid excessive reduction"], ["Encephalopathy", "Reversible edema syndrome", "Treat while excluding mimics"]] },
  "emergency-cardiovascular": { eyebrow: "Cardiovascular emergency", title: "Aorta, coronary perfusion, and pulmonary edema demand mechanism-specific therapy.", accent: "#c28770", columns: [["Aorta", "Anti-impulse therapy first", "Reduce heart rate and wall stress"], ["Coronary", "Balance demand and perfusion", "Avoid reflex tachycardia and low diastolic pressure"], ["Edema", "Afterload + congestion", "Use vasodilation and respiratory support"], ["Drug", "Contraindications matter", "No single infusion fits every syndrome"]] },
  "emergency-special": { eyebrow: "Special populations", title: "Pregnancy, catecholamine excess, and kidney injury change the first move.", accent: "#c2a061", columns: [["Pregnancy", "Persistent 160/110 is urgent", "Use obstetric protocol and seizure prevention when indicated"], ["Catecholamine", "Alpha control before beta", "Avoid unopposed vasoconstriction"], ["Kidney", "Trend injury and volume", "Do not confuse chronic disease with acute damage"], ["Substance", "Treat physiology and exposure", "Agitation, temperature, and ischemia matter"]] },
  "emergency-transition": { eyebrow: "Transition", title: "The emergency ends only when organ injury, oral therapy, and follow-up are stable.", accent: "#8fa57c", columns: [["Reassess", "Symptoms + labs + imaging", "Confirm the organ trajectory"], ["Convert", "IV to oral deliberately", "Overlap when pharmacology requires it"], ["Reconcile", "Cause + adherence + access", "Prevent recurrence"], ["Handoff", "Targets + timing + ownership", "Make follow-up executable"]] },
};

export default function HypertensiveEmergenciesVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
