const diagrams = {
  "htn-vasodilators": {"eyebrow": "Vasodilator follow-up", "title": "Pressure reduction is only one part of the response.", "accent": "#c2a061", "columns": [["Pressure", "Measure effect and tolerance", "Avoid unmonitored escalation"], ["Compensation", "Pulse, weight and volume", "Reassess companion therapy"], ["Toxicity", "Symptoms and targeted testing", "Investigate immune or cardiac injury"]]},
  "htn-central": {"eyebrow": "Treatment transitions", "title": "Plan continued control before changing delivery.", "accent": "#c2a061", "columns": [["Identify", "Exact product and formulation", "Distinguish dose from delivery rate"], ["Transition", "Onset and prior treatment", "Plan overlap or supervised taper"], ["Reassess", "Pressure, pulse and symptoms", "Check access and delayed rebound"]]},
  "htn-beta": {"eyebrow": "Beta-blocker selection", "title": "Indication and formulation guide safe use.", "accent": "#c2a061", "columns": [["Purpose", "Confirm the clinical indication", "Assess stability and exclusions"], ["Delivery", "Check product and schedule", "Preserve the release mechanism"], ["Follow-up", "Pressure, pulse and symptoms", "Reassess after every change"]]},
  "htn-arb": {"eyebrow": "ARB follow-up", "title": "A shared receptor target does not erase product differences.", "accent": "#c2a061", "columns": [["Dose", "Identify the exact regimen", "Review volume and organ function"], ["Delivery", "Food, spacing and packaging", "Preserve product instructions"], ["Follow-up", "Symptoms, labs and interactions", "Investigate delayed adverse effects"]]},
  "htn-raas": {"eyebrow": "RAAS prescribing", "title": "Choose the product, then plan the safety checks.", "accent": "#c2a061", "columns": [["Eligibility", "Angioedema + pregnancy + regimen", "Resolve exclusions and duplicate blockade"], ["Dose", "Product + kidney function + volume", "Check concentration and administration"], ["Follow-up", "Pressure + potassium + creatinine", "Arrange testing and symptom review"]]},
  "htn-nondhp": {"eyebrow": "Non-DHP safety", "title": "Check the heart and the product before the dose.", "accent": "#c2a061", "columns": [["Eligibility", "Rhythm + ventricular function", "Check exclusions and interacting medicines"], ["Prescription", "Indication + formulation", "Use the matching dose and schedule"], ["Follow-up", "Pressure + pulse + symptoms", "Reassess benefit and cardiac tolerance"]]},
  "htn-dhp": {"eyebrow": "DHP prescribing", "title": "Identify the product before choosing the schedule.", "accent": "#c2a061", "columns": [["Formulation", "Ingredient + release system", "Verify the exact dose instructions"], ["Administration", "Food + intact dosage form", "Check the product-specific directions"], ["Titration", "Pressure + symptoms + time", "Reassess benefit and tolerability"]]},
  "htn-thiazides": {"eyebrow": "Diuretic decisions", "title": "Product, response, and safety determine the next dose.", "accent": "#c2a061", "columns": [["Product", "Verify formulation and concentration", "Do not infer equivalence from the name"], ["Response", "Pressure + volume + symptoms", "Use the lowest effective regimen"], ["Laboratory", "Sodium + potassium + magnesium", "Follow renal function and relevant metabolic risks"], ["Reassess", "Interactions and adverse effects", "Escalation is a clinical decision"]]},
  "htn-enac": {"eyebrow": "Potassium conservation", "title": "A potassium-sparing combination still needs laboratory follow-up.", "accent": "#c2a061", "columns": [["Purpose", "Correct or prevent potassium loss", "Confirm why the adjunct is needed"], ["Product", "Check the exact formulation", "Use its dose and schedule"], ["Safety", "Potassium + kidney function", "Review interacting medicines"], ["Follow-up", "Recheck after changes or illness", "Neither high nor low potassium is excluded"]]},
  "htn-mra": { eyebrow: "MRA safety", title: "Indication and product come before the dose.", accent: "#c2a061", columns: [["Indication", "Confirm the treatment role", "Assess resistance and comorbidity"], ["Eligibility", "Kidney + potassium + interactions", "Apply product-specific exclusions"], ["Formulation", "Tablet or suspension", "CaroSpir is not tablet-equivalent"], ["Follow-up", "Arrange early laboratory checks", "Review results before escalation"]] },
  "htn-measurement": { eyebrow: "Measurement", title: "Confirm the pressure, then ask whether another mechanism is driving it.", accent: "#7ca7bc", columns: [["Prepare", "Rest + posture + no talking", "Remove predictable measurement bias"], ["Fit", "Validated upper-arm cuff", "Correct bladder and arm position"], ["Confirm", "Repeated + outside-office data", "Detect white-coat and masked patterns"], ["Investigate", "Pattern + medicines + disease", "Follow secondary-cause clues"]] },
  "htn-risk-goal": { eyebrow: "Risk and goal", title: "Pressure, disease, and PREVENT risk define treatment intensity.", accent: "#c28770", columns: [["Classify", "Average BP", "Normal, elevated, stage 1, stage 2"], ["Risk", "CVD + CKD + diabetes", "PREVENT adds primary-prevention context"], ["Goal", "Generally below 130/80", "Individual considerations still matter"], ["Reassess", "Response + tolerance", "Goal is not safe if perfusion fails"]] },
  "htn-lifestyle": { eyebrow: "Foundational treatment", title: "Lifestyle changes are active therapies with measurable doses.", accent: "#8fa57c", columns: [["Pattern", "DASH-like eating", "Food quality, fiber, and minerals"], ["Sodium", "Reduce excess", "Response varies with baseline intake"], ["Activity", "Aerobic + resistance", "Progress gradually and sustain"], ["Context", "Weight + alcohol + sleep", "Address stress and structural barriers"]] },
  "htn-first-line": { eyebrow: "First-line selection", title: "Use thiazide-type, ACEi or ARB, and long-acting CCB pathways deliberately.", accent: "#c2a061", columns: [["Thiazide-type", "NCC + vascular adaptation", "Sodium, potassium, urate, glucose"], ["ACEi or ARB", "RAAS interruption", "Potassium, creatinine, pregnancy"], ["DHP CCB", "Arteriolar calcium block", "Edema, headache, gingiva"], ["Choose", "Comorbidity + evidence", "Product, dose, access, and monitoring"]] },
  "htn-combination": { eyebrow: "Combination strategy", title: "Combine complementary therapies; investigate apparent resistance before escalating.", accent: "#9b8dbb", columns: [["Stage 2", "Two first-line agents", "Single-pill combination preferred"], ["Complement", "RAAS + CCB or thiazide", "Different pathways and adverse effects"], ["Audit", "Pressure + adherence + contributors", "Exclude pseudoresistance and secondary causes"], ["Escalate", "Comorbidity + potassium + kidney", "Choose the next mechanism safely"]] },
  "htn-monitoring": { eyebrow: "Longitudinal control", title: "Home averages, labs, symptoms, access, and team care sustain control.", accent: "#c77c6e", columns: [["Home", "Validated cuff + protocol", "Use trends; act on urgent symptoms"], ["Labs", "Class-specific", "Potassium, sodium, kidney function"], ["Adherence", "Access + burden + belief", "Ask without blame"], ["Team", "Pharmacist + clinician + community", "Titrate with shared protocol"]] },
};

export default function HypertensionFoundationsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
