const diagrams = {
  "emergency-dihydropyridines": { eyebrow: "Infusion preparation", title: "Translate the prescribed dose into safe delivery.", accent: "#c2a061", columns: [["Product", "Verify concentration", "The same mg/hour can require a different mL/hour"], ["Access", "Check the line", "Follow the selected product's route and handling instructions"], ["Titrate", "Slow near the target", "Monitor pressure and pulse during adjustment"], ["Exposure", "Count actual volume", "Clevidipine adds lipid and calories"]] },
  "emergency-drug-safety": { eyebrow: "Agent-specific monitoring", title: "A lower pressure does not establish medication safety.", accent: "#c2a061", columns: [["Labetalol", "Duration versus interval", "Two-minute administration is not a two-minute repeat schedule"], ["Nitroprusside", "Dose and clearance", "Distinguish cyanide from thiocyanate toxicity"], ["Fenoldopam", "Potassium and pulse", "Assess compensatory responses and ocular risks"], ["Enalaprilat", "Delayed peak", "Review renal function, potassium, and ACE-inhibitor interactions"]] },
  "emergency-triage": { eyebrow: "Triage", title: "Assess acute organ injury and recognize the obstetric severe-pressure exception.", accent: "#c77c6e", columns: [["Verify", "Repeat correctly", "Treat the patient and a reliable signal"], ["Search", "Brain + heart + aorta + kidney + retina", "Find new or worsening injury"], ["Classify", "Apply the correct population pathway", "Pregnancy severe pressure needs urgent care even without other injury"], ["Escalate", "Monitored protocol", "Match urgency to the injured organ"]] },
  "emergency-physiology": { eyebrow: "Perfusion", title: "Controlled reduction protects tissue that has adapted to high pressure.", accent: "#7ca7bc", columns: [["Autoregulation", "Chronic pressure shifts the range", "Abrupt normalization may cause ischemia"], ["Goal", "Condition-specific", "Avoid one universal target"], ["Agent", "Mechanism + formulation + clearance", "Match the entire product to the organ state"], ["Monitor", "Continuous pressure + organ response", "Prevent variability, overshoot, and toxicity"]] },
  "emergency-neurologic": { eyebrow: "Neurologic emergency", title: "Ischemia, hemorrhage, and encephalopathy require different pressure strategies.", accent: "#9b8dbb", columns: [["Image", "Exclude hemorrhage", "Do not infer stroke type from pressure"], ["Ischemia", "Reperfusion pathway", "Follow treatment-specific thresholds"], ["ICH", "Smooth sustained control", "Avoid excessive reduction"], ["Encephalopathy", "Reversible edema syndrome", "Treat while excluding mimics"]] },
  "emergency-cardiovascular": { eyebrow: "Cardiovascular emergency", title: "Aorta, coronary perfusion, and pulmonary edema demand mechanism-specific therapy.", accent: "#c28770", columns: [["Aorta", "Anti-impulse therapy first", "Reduce heart rate and wall stress"], ["Coronary", "Balance demand and perfusion", "Avoid reflex tachycardia and low diastolic pressure"], ["Edema", "Afterload + congestion", "Use vasodilation and respiratory support"], ["Drug", "Contraindications matter", "No single infusion fits every syndrome"]] },
  "emergency-special": { eyebrow: "Special populations", title: "Pregnancy, catecholamine excess, and kidney injury change the first move.", accent: "#c2a061", columns: [["Pregnancy", "SBP ≥160 or DBP ≥110 is urgent", "Use obstetric protocol and seizure prevention when indicated"], ["Pheochromocytoma", "Alpha control before beta", "Avoid unopposed vasoconstriction"], ["Kidney", "Trend injury and volume", "Do not confuse chronic disease with acute damage"], ["Substance", "Treat physiology and exposure", "Agitation, temperature, and ischemia matter"]] },
  "emergency-transition": { eyebrow: "Transition", title: "The emergency ends only when organ injury, oral therapy, and follow-up are stable.", accent: "#8fa57c", columns: [["Reassess", "Symptoms + labs + imaging", "Confirm the organ trajectory"], ["Convert", "IV to oral deliberately", "Overlap when pharmacology requires it"], ["Reconcile", "Cause + adherence + access", "Prevent recurrence"], ["Handoff", "Targets + timing + ownership", "Make follow-up executable"]] },
};

export default function HypertensiveEmergenciesVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
