const diagrams = {
  "icu-pain-assessment": { eyebrow: "Pain signal", title: "Measure pain before treating agitation", accent: "#df7d68", columns: [["Ask", "Self report", "Use the patient's report whenever communication is reliable."], ["Observe", "CPOT or BPS", "Use a validated behavioral tool when self report is not possible."], ["Recheck", "Response", "Trend comfort, function, ventilation, and toxicity after treatment."]] },
  "icu-opioid-selection": { eyebrow: "Opioid map", title: "The patient chooses the opioid more than the pain score does", accent: "#c89170", columns: [["Kidney", "Metabolites", "Renal dysfunction increases risk from active or neurotoxic metabolites."], ["Pressure", "Histamine and tone", "Hemodynamic reserve changes the cost of each option."], ["Time", "Context sensitive", "Long infusions can extend recovery even after a short initial half life."]] },
  "icu-multimodal-analgesia": { eyebrow: "Analgesia first", title: "Reduce pain, then decide what sedation remains necessary", accent: "#e2ad62", columns: [["Treat", "Primary driver", "Address pain before escalating a hypnotic for apparent agitation."], ["Combine", "Different mechanisms", "Use selected nonopioid and regional strategies to reduce opioid burden."], ["Protect", "Function", "Preserve breathing, wakefulness, mobility, and communication when possible."]] },
  "icu-sedation-target": { eyebrow: "Targeted sedation", title: "A written depth target turns an infusion into a controlled intervention", accent: "#6da5bf", columns: [["Set", "RASS goal", "Choose the lightest depth that safely meets the clinical need."], ["Titrate", "One trajectory", "Match dose changes to pain, synchrony, procedures, and neurologic goals."], ["Wake", "Daily readiness", "Use protocolized awakening and breathing assessment when safe."]] },
  "icu-sedative-selection": { eyebrow: "Sedative choice", title: "Select by goal, physiology, and recovery plan", accent: "#a58bc0", columns: [["Dexmedetomidine", "Arousable", "Supports light sedation with little respiratory depression but can slow rate and pressure."], ["Propofol", "Rapid control", "Provides fast titration but can depress circulation and carries metabolic toxicity."], ["Benzodiazepine", "Specific indication", "Retain for seizure or alcohol and benzodiazepine withdrawal rather than routine default use."]] },
  "icu-propofol-safety": { eyebrow: "Propofol surveillance", title: "Rapid recovery requires disciplined metabolic and delivery safety", accent: "#e0b460", columns: [["Circulation", "Dose response", "Titrate slowly and monitor hypotension, apnea, and cardiac depression."], ["Metabolism", "PRIS", "Watch acid base state, lactate, rhythm, muscle injury, kidney, and lipids."], ["Delivery", "Asepsis", "Use dedicated handling, tubing, and discard intervals from current labeling."]] },
  "icu-dexmedetomidine-safety": { eyebrow: "Alpha-2 sedation", title: "Wakeful sedation trades respiratory stability for hemodynamic risk", accent: "#79a99b", columns: [["State", "Arousable", "Patients can remain interactive and may continue through extubation."], ["Rate", "Bradycardia", "Loading and high exposure can produce clinically important slowing."], ["Pressure", "Biphasic", "Transient hypertension or later hypotension requires context and titration."]] },
  "icu-delirium-detection": { eyebrow: "Acute brain failure", title: "Detect delirium through attention and fluctuation, not appearance alone", accent: "#d47c8d", columns: [["Arousal", "RASS first", "Establish whether the patient can participate in delirium assessment."], ["Attention", "CAM-ICU or ICDSC", "Use a validated tool repeatedly across the changing day."], ["Cause", "Reconstruct exposure", "Search infection, drugs, withdrawal, hypoxia, metabolic injury, pain, and environment."]] },
  "icu-delirium-management": { eyebrow: "Delirium response", title: "Remove drivers and restore orientation before reaching for suppression", accent: "#cb8069", columns: [["Correct", "Reversible causes", "Treat pain, hypoxia, infection, withdrawal, retention, and medication toxicity."], ["Restore", "Brain environment", "Use daylight, sleep protection, hearing, vision, family, and mobility."], ["Reserve", "Symptom control", "Antipsychotics do not have proven routine outcome benefit and require a defined target."]] },
  "icu-liberation": { eyebrow: "ICU liberation", title: "Recovery begins while organ support is still running", accent: "#d8a95f", columns: [["Coordinate", "ABCDEF", "Link pain, awakening, breathing, sedative choice, delirium, mobility, and family."], ["Mobilize", "Function", "Use enhanced rehabilitation when stable enough rather than waiting for discharge."], ["Transition", "PICS prevention", "Reconcile exposure, cognition, sleep, weakness, and follow-up at every handoff."]] },
};

export default function IcuAnalgesiaSedationVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
