const diagrams = {
  "ipc-chain": { eyebrow: "Transmission system", title: "Break more than one link before exposure reaches the host", accent: "#8da08a", columns: [["Source", "Agent and reservoir", "Remove, treat, contain, or isolate."], ["Route", "Exit, travel, entry", "Control air, surfaces, hands, devices, and sharps."], ["Host", "Susceptibility", "Reduce exposure and strengthen protection."]] },
  "ipc-standard": { eyebrow: "Every encounter", title: "Anticipate the task, then assemble the right controls", accent: "#879dac", columns: [["Predict", "Exposure risk", "Blood, body fluids, air, surfaces, and sharps."], ["Protect", "Task-based barriers", "Hand hygiene, PPE, asepsis, and source control."], ["Reset", "Safe turnover", "Remove, clean, reprocess, and restore the clean zone."]] },
  "ipc-transmission": { eyebrow: "Route-specific control", title: "Contact, droplets, and shared air require different containment", accent: "#a1869b", columns: [["Contact", "Hands and surfaces", "Gown, gloves, equipment, and environment."], ["Droplet", "Close respiratory space", "Source control, placement, and mask."], ["Airborne", "Suspended particles", "AIIR, closed door, and fit-tested respirator."]] },
  "ipc-hands": { eyebrow: "Method selection", title: "Use alcohol for most care and wash when soil must be removed", accent: "#87a39b", columns: [["Rub", "Routine clinical care", "Cover every surface and rub until dry."], ["Wash", "Visible soil", "Use soap, water, friction, rinse, and dry."], ["Gloves", "Temporary barrier", "Change by task and clean hands after removal."]] },
  "ipc-environment": { eyebrow: "Reprocessing", title: "The tissue an item touches determines the required process", accent: "#9a8b72", columns: [["Noncritical", "Intact skin", "Clean and apply appropriate disinfection."], ["Semicritical", "Mucosa", "Use at least high-level disinfection."], ["Critical", "Sterile tissue", "Use a validated sterilization process."]] },
  "ipc-devices": { eyebrow: "Exposure days", title: "Insert only when needed, maintain aseptically, remove promptly", accent: "#a47c69", columns: [["Line", "Bloodstream", "Maximal barriers, chlorhexidine, hub and dressing care."], ["Catheter", "Urinary tract", "Sterile insertion, closed drainage, early removal."], ["Ventilator", "Lower airway", "Reduce aspiration and unnecessary ventilation."]] },
  "ipc-injections": { eyebrow: "Aseptic medication use", title: "Every entry begins with new sterile equipment", accent: "#8493aa", columns: [["Prepare", "Clean medication zone", "Disinfect, label, and protect sterility."], ["Administer", "One patient", "One needle, one syringe, one time."], ["Discard", "No shared remainder", "Preserve patient-specific systems and remove waste."]] },
  "ipc-sharps": { eyebrow: "Worker protection", title: "Engineer the injury out and treat every exposure as urgent", accent: "#a07c7c", columns: [["Prevent", "Safer device", "Activate protection and avoid hand-to-hand passing."], ["Contain", "Point of use", "Discard immediately before the container overfills."], ["Respond", "Time-sensitive care", "First aid, report, assess, and provide prophylaxis."]] },
  "ipc-surveillance": { eyebrow: "Learning signal", title: "Standard definitions become useful when they change action", accent: "#7f9692", columns: [["Measure", "Valid definitions", "Count events and exposure with one current protocol."], ["Detect", "Person, place, time", "Find trends, clusters, and common pathways."], ["Improve", "Feedback loop", "Assign controls, test reliability, and monitor outcomes."]] },
  "ipc-governance": { eyebrow: "Prevention program", title: "Risk, authority, competency, and readiness must move together", accent: "#9e895f", columns: [["Prioritize", "Local risk", "Population, services, organisms, and environment."], ["Operate", "Shared ownership", "Resources, expertise, workflows, and measures."], ["Prepare", "High consequence", "Exercise identification, isolation, communication, and transfer."]] },
};

export default function InfectionPreventionControlVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual infection-prevention-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
