const diagrams = {
  "infertility-evaluation-clock": ["Evaluation clock", "Age and risk determine when the parallel workup begins", ["Under 35", "After 12 months", "Begin sooner when a known risk or irregular cycle is present"], ["Age 35 to 40", "After 6 months", "Evaluate both partners concurrently when applicable"], ["Over 40 or known risk", "More immediate", "Preserve time while targeting the suspected barrier"]],
  "infertility-fertile-window": ["Timing map", "Conception probability follows biology, not ritual", ["Before", "Follicular development", "Use cycle history and optional LH tracking to anticipate ovulation"], ["Window", "Six days ending on ovulation", "Intercourse every one to two days provides practical exposure"], ["After", "Luteal evidence", "Time progesterone relative to expected menses when confirmation is needed"]],
  "infertility-female-workup": ["Female workup", "Each test should answer a fertility question", ["Ovulation", "Is an oocyte being released?", "Use cycle pattern first and targeted endocrine tests second"], ["Anatomy", "Can sperm and oocyte meet?", "Assess the cavity and tubal patency with appropriate imaging"], ["Reserve", "How might ovaries respond?", "Use AMH and antral count as adjuncts, not guarantees"]],
  "infertility-male-workup": ["Male workup", "A semen profile is interpreted with the whole patient", ["Produce", "Concentration and total number", "Find testicular, endocrine, genetic, medication, and exposure causes"], ["Move", "Motility and vitality", "Repeat a variable specimen when clinical context supports it"], ["Deliver", "Volume, morphology, and anatomy", "Refer significant abnormalities for focused reproductive evaluation"]],
  "infertility-pcos-letrozole": ["PCOS induction", "Remove estrogen feedback long enough to recruit a follicle", ["Block", "Aromatase inhibition", "Estradiol synthesis falls transiently"], ["Release", "Endogenous FSH increases", "Reduced feedback supports follicular recruitment"], ["Monitor", "Ovulation and safety", "Confirm no pregnancy and follow the cycle-specific protocol"]],
  "infertility-clomiphene-metformin": ["Oral therapy", "Match the drug to the treatment target", ["Letrozole", "Preferred PCOS induction", "Aromatase inhibition improves ovulation outcomes in appropriate patients"], ["Clomiphene", "Selective estrogen receptor modulation", "Use a limited monitored course and stop for visual symptoms"], ["Metformin", "Metabolic and selected reproductive support", "Treat dysglycemia without overstating fertility efficacy"]],
  "infertility-gonadotropins": ["Controlled stimulation", "Response determines the next dose and whether a cycle can proceed", ["Stimulate", "FSH with or without LH activity", "Select the product and starting strategy from patient and protocol factors"], ["Measure", "Follicles and estradiol", "Use ultrasound and laboratory trends to adjust exposure"], ["Protect", "Cancellation and trigger criteria", "Avoid unsafe multifollicular response, OHSS, and high-order multiples"]],
  "infertility-protocol-control": ["Protocol sequence", "Every hormone has a specific job and time", ["Prevent", "GnRH antagonist", "Block a premature LH surge during stimulation"], ["Trigger", "hCG or selected agonist trigger", "Complete final maturation and coordinate retrieval or ovulation"], ["Support", "Progesterone", "Maintain an appropriate luteal environment after ART"]],
  "infertility-art-pathway": ["Procedure pathway", "Choose the method that can cross the actual barrier", ["Timed or IUI", "Fertilization remains in the body", "Requires a route for sperm and oocyte to meet"], ["IVF", "Fertilization in the laboratory", "Can bypass severe tubal disease and other selected barriers"], ["ICSI", "Single-sperm injection", "Targets selected fertilization problems, not every cause"]],
  "infertility-ohss-care": ["OHSS prevention", "Risk management spans the entire stimulation cycle", ["Before", "Recognize high response risk", "Use an individualized dose and antagonist-friendly prevention plan"], ["Trigger", "Reduce prolonged stimulation", "Consider agonist trigger, cabergoline, and freeze-all when appropriate"], ["After", "Watch for organ compromise", "Escalate dyspnea, oliguria, rapid weight gain, thrombosis, or severe distension"]],
};

export default function InfertilityOvulationInductionVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
