export const infectiveEndocarditisVisualTypes=["pathogenesis-risk","microbiology-diagnosis","imaging-complications","empiric-therapy","streptococci-hacek","staphylococci","enterococci-resistant","surgery-team-care","monitoring-outpatient","prevention-followup"].map(type=>`ie-${type}`);

const diagrams={
  "pathogenesis-risk":["Vegetation biology","Follow infection from injured surface to systemic injury",["Surface","Endothelial injury","A susceptible native or prosthetic surface collects platelet and fibrin."],["Seed","Bacteremia","Circulating organisms reach and adhere to the thrombotic surface."],["Shelter","Vegetation","Dense growth inside matrix resists immune clearance and drug penetration."],["Damage","Valve and emboli","Destruction causes regurgitation while fragments seed distant organs."]],
  "microbiology-diagnosis":["Evidence architecture","Preserve the organism and classify the complete syndrome",["Culture","Three sets first","Adequate pretherapy volume protects diagnostic yield."],["Classify","2023 Duke-ISCVID","Microbiology, imaging, surgery, pathology, and minor findings combine."],["Track","Clearance","Repeat cultures expose persistent endovascular infection."],["Expand","BCNE pathway","After 72 hours, add exposure-guided serology, molecular work, and tissue planning."]],
  "imaging-complications":["Imaging ladder","Escalate from valve anatomy to hidden extension and emboli",["Screen","TTE","Define valve function, vegetation, and hemodynamics."],["Resolve","TEE","See prostheses, devices, small lesions, and perivalvular disease."],["Repeat","Evolving biology","A negative early study may become diagnostic later."],["Extend","CT and nuclear imaging","Answer prosthetic, anatomic, or extracardiac questions."]],
  "empiric-therapy":["Treatment engine","Move from probability to verified definitive exposure",["Sample","Cultures","Preserve microbiology before therapy when safe."],["Cover","Phenotype","Valve type and acquisition define initial threats."],["Verify","Exposure","Dose, organs, MIC, interactions, and delivery determine activity."],["Narrow","Definitive regimen","Replace empiric breadth within 24 to 48 hours when possible."]],
  "streptococci-hacek":["Susceptibility pathways","Let MIC, valve material, and toxicity set duration",["Identify","Oral streptococci","Use penicillin or ceftriaxone for a valve-specific duration."],["Select","Synergy","Reserve gentamicin for uncomplicated low-risk native-valve disease."],["Investigate","S. gallolyticus","Connect the bloodstream isolate to colon evaluation."],["Treat","HACEK","Use ceftriaxone and distinguish it from non-HACEK disease."]],
  "staphylococci":["Staphylococcal decisions","Choose the strongest drug and remove old toxicity",["Prefer","MSSA beta-lactam","Switch from empiric vancomycin when susceptibility permits."],["Measure","MRSA exposure","Use AUC-guided vancomycin or syndrome-matched daptomycin."],["Avoid","Routine gentamicin","Native-valve benefit is unproven and kidney harm increases."],["Coordinate","Prosthetic infection","Time rifampin after clearance and evaluate surgery and biofilm."]],
  "enterococci-resistant":["Difficult pathogen logic","Create synergy while protecting organs and future options",["Pair","Ampicillin and ceftriaxone","Complementary PBP binding treats susceptible E. faecalis."],["Confirm","HLAR status","Aminoglycoside synergy fails with high-level resistance."],["Design","VRE pathway","Use species, MIC, exposure, combination, and source control."],["Escalate","Rare pathogens","Non-HACEK and fungi demand specialist and surgical planning."]],
  "surgery-team-care":["Surgical triggers","Recognize when drugs cannot repair infected anatomy",["Pump","Heart failure","Severe acute valve dysfunction demands urgent review."],["Control","Persistent infection","Abscess, fistula, hardware, and bacteremia may require removal."],["Protect","Embolic risk","Balance vegetation anatomy against neurologic timing."],["Extract","CIED infection","Remove the complete infected system and plan reimplantation deliberately."]],
  "monitoring-outpatient":["Decision monitoring","Convert every trend into a threshold, action, and owner",["Clear","Cultures","Document bloodstream sterilization and investigate persistence."],["Protect","Organs","Follow drug-specific kidney, liver, blood, nerve, muscle, and ECG risk."],["Consolidate","OPAT or oral","Move out only after complications and surgery are controlled."],["Complete","Verified outcome","Close doses, response, valve plan, access, and recurrence education."]],
  "prevention-followup":["Prevention boundary","Use oral health broadly and antibiotics narrowly",["Confirm","Cardiac eligibility","Restrict prophylaxis to highest-risk conditions."],["Confirm","Dental exposure","Gingiva, periapical tissue, or oral mucosal perforation must be involved."],["Dose","One preprocedure regimen","Use amoxicillin or a current allergy and route alternative."],["Sustain","Oral health","Regular care and rapid fever evaluation matter beyond one procedure."]],
};

export default function InfectiveEndocarditisVisual({type}){const diagram=diagrams[type.replace("ie-","")];if(!diagram)return null;const[eyebrow,title,...nodes]=diagram;return <figure className="chol-visual infective-endocarditis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={`${verb}-${focus}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
