const diagrams = {
  "ibd-biology": { eyebrow: "Disease architecture", title: "Location and depth create two different disease systems", accent: "#b36e5d", columns: [["Ulcerative colitis", "Continuous mucosa", "Rectum to proximal colon, with bleeding and urgency."], ["Crohn disease", "Patchy and transmural", "Any gastrointestinal segment, with strictures and fistulas."], ["Whole patient", "Intestine plus systemic burden", "Nutrition, bone, thrombosis, skin, joints, eyes, and liver matter."]] },
  "ibd-diagnosis": { eyebrow: "Diagnostic stack", title: "Confirmation comes from converging evidence", accent: "#738faa", columns: [["Exclude", "Infection and mimics", "Do not immunosuppress an unconfirmed syndrome."], ["Define", "Endoscopy, biopsy, imaging", "Map extent, depth, behavior, and complications."], ["Measure", "Symptoms plus biomarkers", "Activity and future risk are different questions."]] },
  "ibd-targets": { eyebrow: "Treat-to-target", title: "Control the life, the biology, and the future course", accent: "#7da08d", columns: [["Clinical", "Function and symptoms", "Restore daily life and resolve bleeding, urgency, pain, and fatigue."], ["Biologic", "CRP and fecal calprotectin", "Track inflammation that symptoms can miss."], ["Structural", "Endoscopic improvement", "Reduce progression, hospitalization, surgery, and cancer risk."]] },
  "ibd-uc-mild": { eyebrow: "Delivery map", title: "Put mesalamine where the inflammation is", accent: "#c6a05f", columns: [["Proctitis", "Suppository", "Treat the distal rectum directly."], ["Left-sided", "Oral plus rectal", "Cover both proximal and distal inflamed mucosa."], ["Extensive", "Oral foundation", "Escalate class after an adequate adherent failure."]] },
  "ibd-uc-advanced": { eyebrow: "Therapy positioning", title: "Choose a mechanism for this patient, not the average patient", accent: "#ad7eaa", columns: [["Disease", "Burden and prior exposure", "Severity and failure mechanism shape efficacy."], ["Therapy", "Speed, route, durability", "Induction and maintenance form one strategy."], ["Person", "Risk and preference", "Infection, cancer, cardiovascular, reproductive, and practical factors matter."]] },
  "ibd-crohn": { eyebrow: "Behavior first", title: "Inflammation, fibrosis, and infection demand different tools", accent: "#9c795f", columns: [["Inflammatory", "Medical control", "Use an evidence-based induction and maintenance strategy."], ["Fibrotic", "Open the lumen", "Endoscopy or surgery may be required."], ["Penetrating", "Control the source", "Drain abscesses and coordinate fistula care."]] },
  "ibd-maintenance": { eyebrow: "Steroid exit", title: "Maintenance begins before induction ends", accent: "#83976d", columns: [["Sustain", "Effective mechanism", "Preserve remission without chronic steroids."], ["Monitor", "Marrow, liver, infection", "Drug-specific surveillance prevents avoidable harm."], ["Protect", "Vaccines, bone, cancer", "Long-term care extends beyond the prescription."]] },
  "ibd-biologics": { eyebrow: "Immune targets", title: "Different biologics interrupt different conversations", accent: "#628da1", columns: [["TNF", "Inflammatory amplifier", "Effective systemic control with infection and immunogenicity considerations."], ["Integrin", "Gut trafficking", "Vedolizumab limits lymphocyte entry into gut tissue."], ["Interleukins", "IL-12/23 or IL-23", "Target cytokine signaling with product-specific routes and monitoring."]] },
  "ibd-small-molecules": { eyebrow: "Oral advanced therapy", title: "Convenient administration still requires intensive selection", accent: "#a16f7a", columns: [["JAK", "Intracellular signaling", "Fast action with boxed infection, cancer, cardiovascular, and thrombotic risks."], ["S1P", "Lymphocyte egress", "Immune trafficking intersects with conduction and ophthalmic safety."], ["Label", "Interactions and reproduction", "Current product instructions determine eligibility and monitoring."]] },
  "ibd-acute-severe": { eyebrow: "Timed rescue", title: "The safest path is defined by what happens next", accent: "#c45f52", columns: [["Today", "Hospital bundle", "Test infection, prevent thrombosis, start intravenous steroids, involve surgery."], ["Day three", "Rescue decision", "Use infliximab or cyclosporine when response is inadequate."], ["Afterward", "Prevent recurrence", "Continue effective maintenance and monitor postoperative Crohn disease objectively."]] },
};

export default function InflammatoryBowelDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
