export const intraAbdominalInfectionsVisualTypes=["definitions-triage","diagnostic-imaging","microbiology","source-control","empiric-spectrum","regimen-selection","duration-response","biliary-infections","spontaneous-bacterial-peritonitis","special-populations-stewardship"].map(type=>`iai-${type}`);

const diagrams={
  "definitions-triage":["Anatomic frame","Name the compartment before the regimen",["Locate","Hollow viscus","Is disease confined to the organ wall or extended into a sterile space?"],["Classify","Peritonitis","Separate primary, secondary, and persistent or recurrent disease."],["Measure","Physiology","Shock and organ dysfunction set urgency, not the word complicated."],["Activate","Parallel care","Resuscitation, imaging, antibiotics, and procedural planning move together."]],
  "diagnostic-imaging":["Imaging pathway","Make every study answer a source question",["Map","CT","Define deep collections, leaks, obstruction, ischemia, and a drainage route."],["Focus","Ultrasound","Start biliary evaluation with stones, gallbladder, and duct anatomy."],["Adapt","MRI","Reduce radiation when appropriate without delaying dangerous disease."],["Repeat","Failure anatomy","Persistent illness requires a new image, not automatic extension."]],
  "microbiology":["Specimen quality","Collect evidence that can reduce spectrum",["Preserve","Fresh source","Aspirated fluid or tissue supports aerobic and anaerobic recovery."],["Select","Blood cultures","Use physiology, immune status, cholangitis, and resistance risk."],["Reject","Old drain swabs","Colonized tubing does not equal the active infected space."],["Narrow","Meaningful results","Remove unnecessary resistant-pathogen and fungal coverage."]],
  "source-control":["Control architecture","Stop the contamination the drug cannot",["Drain","Infected fluid","Choose a safe definitive percutaneous or operative path."],["Repair","Leak or perforation","Close the route that continues to seed the abdomen."],["Remove","Necrotic tissue","Debridement restores the conditions required for recovery."],["Audit","Adequacy","Residual loculation, obstruction, or displaced drains preserve infection."]],
  "empiric-spectrum":["Spectrum gates","Add coverage only when risk opens the gate",["Core","Enteric flora","Community lower-GI disease needs gram-negative and anaerobic activity."],["Broaden","Resistance risk","Healthcare exposure and prior isolates can justify Pseudomonas or ESBL activity."],["Select","Enterococcus","Postoperative, transplant, immune, or culture context can make it relevant."],["Reserve","Candida","Strong host and source risk must support empiric antifungal therapy."]],
  "regimen-selection":["Exposure design","Translate spectrum into a safe administered dose",["Focus","Ceftriaxone plus metronidazole","A common community pathway when ecology and organs fit."],["Broaden","Piperacillin-tazobactam","Useful broad activity with resistance and organ boundaries."],["Complete","Cefepime plus metronidazole","Anaerobic activity must be added and kidney exposure followed."],["Steward","Carbapenems","Match meropenem or ertapenem to the actual resistance threat."]],
  "duration-response":["Stop clock","Adequate control changes the duration question",["Start","Source-control time","Record when contamination stopped and drainage became adequate."],["Treat","Four days","Most controlled cIAI needs no more than 96 hours afterward."],["Do not reset","Oral transition","A route change completes the same total course."],["Investigate","Persistent illness","Repeat imaging and reassess control before broadening or extending."]],
  "biliary-infections":["Biliary control","Different compartments require different procedures",["Image","Ultrasound first","Define gallbladder inflammation, stones, and duct dilation."],["Remove","Gallbladder source","Early cholecystectomy is definitive when feasible."],["Decompress","Infected duct","Cholangitis requires urgent ERCP or another drainage route."],["Reassess","After control","Cultures, clearance, obstruction, and response set the remaining course."]],
  "spontaneous-bacterial-peritonitis":["Ascites pathway","Treat infected fluid while excluding a surgical source",["Count","PMN at least 250","Neutrocytic ascites supports treatment before culture returns."],["Inoculate","Bedside bottles","Immediate aerobic and anaerobic culture improves yield."],["Support","Albumin","Use 1.5 g/kg on day 1 and 1 g/kg on day 3 when indicated."],["Escalate","Secondary clues","Polymicrobial growth or poor response requires imaging and surgery review."]],
  "special-populations-stewardship":["Daily recalculation","Keep exposure and ownership current",["Clarify","Allergy phenotype","Preserve safe beta-lactam options when the history allows."],["Recalculate","Organ clearance","Kidney trajectory, dialysis, liver reserve, and weight change exposure."],["Protect","Pregnancy and children","Adapt imaging and dosing without delaying source control."],["Close","Stop ownership","Document spectrum, route, cultures, duration, and the failure pathway."]],
};

export default function IntraAbdominalInfectionsVisual({type}){const diagram=diagrams[type.replace("iai-","")];if(!diagram)return null;const[eyebrow,title,...nodes]=diagram;return <figure className="chol-visual intra-abdominal-infections-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={`${verb}-${focus}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
