const diagrams = {
  "ibs-network": { eyebrow: "Gut-brain network", title: "Symptoms emerge from a connected system, not a single damaged structure", accent: "#9c82b8", columns: [["Sense", "Visceral signaling", "Distention and motility can generate amplified afferent signals."], ["Regulate", "Transit and secretion", "Motor, secretory, immune, and microbial inputs shape the bowel pattern."], ["Interpret", "Central processing", "Attention, threat, sleep, mood, and experience can modify the final symptom." ]] },
  "ibs-diagnosis": { eyebrow: "Positive diagnosis", title: "Confirm the pattern, screen the danger, and test only what the phenotype requires", accent: "#78a3af", columns: [["Recognize", "Rome IV pattern", "Recurrent pain connects to defecation or changed stool frequency or form."], ["Triage", "Alarm features", "Bleeding, anemia, weight loss, fever, nocturnal symptoms, and progression reopen the pathway."], ["Target", "High-value tests", "Use celiac serology and inflammatory screening in diarrhea phenotypes when appropriate." ]] },
  "ibs-subtypes": { eyebrow: "Stool-form classification", title: "The proportions of hard and loose abnormal stools define the current subtype", accent: "#c29662", columns: [["Hard", "Types 1 and 2", "More than 25 percent with less than 25 percent loose supports IBS-C."], ["Mixed", "Both thresholds", "More than 25 percent hard and more than 25 percent loose supports IBS-M."], ["Loose", "Types 6 and 7", "More than 25 percent with less than 25 percent hard supports IBS-D." ]] },
  "ibs-foundation": { eyebrow: "Foundational care", title: "Design a measured trial, preserve nutrition, and keep only what earns its place", accent: "#86a67f", columns: [["Define", "One priority", "Select pain, urgency, stool form, bloating, or function as the first target."], ["Test", "One structured change", "Titrate soluble fiber or use a limited diet trial with a decision date."], ["Personalize", "Reintroduce and simplify", "Liberalize food, preserve routines, and avoid permanent unnecessary restriction." ]] },
  "ibs-pain": { eyebrow: "Pain pathway", title: "Treat smooth muscle, visceral signaling, and central amplification as distinct targets", accent: "#b387ae", columns: [["Local", "Peppermint or selected antispasmodic", "Use a defined cramping trial while respecting reflux and anticholinergic risk."], ["Neural", "Low-dose tricyclic", "Reduce pain processing while accounting for transit and cardiac safety."], ["Behavioral", "CBT or hypnotherapy", "Change gut-brain amplification without dismissing the biology of pain." ]] },
  "ibs-c-foundation": { eyebrow: "IBS-C sequence", title: "Name the unmet outcome before choosing the next constipation intervention", accent: "#d0a15f", columns: [["Form", "Soluble fiber", "Improve stool consistency and global symptoms through slow titration."], ["Frequency", "Polyethylene glycol", "Increase bowel movements while measuring abdominal pain separately."], ["Evacuation", "Pelvic floor assessment", "Recognize outlet dysfunction when soft stool still cannot be passed normally." ]] },
  "ibs-c-rx": { eyebrow: "IBS-C pharmacology", title: "Four secretory strategies share diarrhea risk but differ in target and label", accent: "#c58b64", columns: [["GC-C", "Linaclotide or plecanatide", "Increase chloride and bicarbonate secretion through CFTR."], ["Chloride", "Lubiprostone", "Activate intestinal chloride transport within its adult-women IBS-C indication."], ["NHE3", "Tenapanor", "Reduce sodium absorption and take immediately before the first meal and dinner." ]] },
  "ibs-d-foundation": { eyebrow: "IBS-D triage", title: "Slow stable diarrhea only after the new or dangerous causes have been screened", accent: "#5fa1a7", columns: [["Screen", "Blood, fever, dehydration", "New red flags require evaluation before antimotility treatment."], ["Control", "Loperamide", "Target frequency and urgency without promising reliable global pain relief."], ["Reconsider", "Bile acids and other mimics", "Look beyond IBS when the exposure, anatomy, or pattern changes probability." ]] },
  "ibs-d-rx": { eyebrow: "IBS-D selection", title: "Course length, anatomy, and rare severe toxicity determine the prescription", accent: "#a97276", columns: [["Course", "Rifaximin", "Use 550 mg three times daily for 14 days with up to two retreatments."], ["Anatomy", "Eluxadoline", "Exclude patients without a gallbladder and screen pancreatitis risk before use."], ["Reserve", "Alosetron", "Limit use to severe refractory IBS-D in women with strict constipation and ischemia stop rules." ]] },
  "ibs-followup": { eyebrow: "Longitudinal loop", title: "Measure the target, stop unsafe therapy, and reopen the diagnosis when the story changes", accent: "#8f9e72", columns: [["Measure", "Symptoms and function", "Track pain, stool form, urgency, bloating, daily activity, and adverse effects."], ["Decide", "Continue, modify, or stop", "Use a preplanned review date instead of accumulating indefinite therapy."], ["Reassess", "Pattern and diagnosis", "New alarm features or a sustained subtype shift require a fresh clinical model." ]] },
};

export default function IrritableBowelSyndromeVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
