export const lefamulinPharmacologyVisualTypes = ["structure-mechanism", "spectrum-resistance", "cabp-selection", "dosing-route", "oral-administration", "iv-preparation", "qt-safety", "cyp-interactions", "organ-reproductive-safety", "integration"];

const diagrams = {
  "structure-mechanism": ["Induced fit", "The mutilin core closes a 50S pocket around the wrong tRNA position", ["Enter", "Peptidyl transferase center", "The scaffold reaches A and P sites in 23S rRNA."], ["Contact", "Noncovalent network", "Hydrogen, hydrophobic, and van der Waals forces align the core."], ["Close", "Ribosomal pocket", "An induced fit locks the drug into the target."], ["Stop", "Peptide transfer", "Correct tRNA positioning and protein synthesis fail."]],
  "spectrum-resistance": ["CABP map", "Keep labeled pathogens and missing organisms visible at the same time", ["Cover", "Typical pathogens", "Susceptible pneumococcus, MSSA, and H. influenzae fit."], ["Include", "Atypical bacteria", "Legionella, Mycoplasma, and Chlamydophila are labeled."], ["Exclude", "Pseudomonas and Enterobacterales", "Choose another pathway when these organisms matter."], ["Interpret", "Target protection", "ABC-F, Cfr, and L3 or L4 changes can reduce activity."]],
  "cabp-selection": ["Decision gate", "Lefamulin belongs only after diagnosis, severity, and alternatives agree", ["Confirm", "Adult bacterial CAP", "Separate bacterial pneumonia from viral or noninfectious disease."], ["Stage", "Nonsevere disease", "Severe CAP requires a broader evidence-based pathway."], ["Explain", "Alternative role", "Document why standard CAP options are unsuitable."], ["Reassess", "Daily stability", "Use diagnostics, response, and complications to refine therapy."]],
  "dosing-route": ["Regimen split", "Route and liver function determine dose, interval, and duration", ["Oral", "600 mg every 12 hours", "Use five days with fasting administration."], ["IV", "150 mg every 12 hours", "Infuse over 60 minutes for five to seven days."], ["Adjust", "Child-Pugh C IV", "Extend IV dosing to every 24 hours."], ["Avoid", "Oral Child-Pugh B or C", "The tablet has not been studied and is not recommended."]],
  "oral-administration": ["Fasting clock", "Twice-daily therapy succeeds only when meals, water, and missed doses align", ["Separate", "One hour before food", "Or wait two hours after a meal."], ["Swallow", "Whole with water", "Use 6 to 8 ounces and never crush or divide."], ["Count", "Eight hours remaining", "Take a missed dose only when this window remains."], ["Test", "Real schedule", "Meals, work, sleep, cost, and interactions must fit."]],
  "iv-preparation": ["Infusion build", "One vial, one supplied bag, and one hour form the safe path", ["Transfer", "150 mg in 15 mL", "Add the entire vial aseptically."], ["Dilute", "250 mL buffered saline", "Use the supplied bag and add no other product."], ["Inspect", "Clear and intact", "Reject particles, discoloration, or container damage."], ["Infuse", "250 mL per hour", "Deliver the prepared dose over 60 minutes."]],
  "qt-safety": ["Repolarization stack", "Patient physiology, other drugs, and lefamulin exposure combine", ["Screen", "QTc and rhythm", "Avoid known long QT and ventricular arrhythmias."], ["Correct", "Potassium and magnesium", "Remove modifiable torsades risks before therapy."], ["Remove", "QT-prolonging drugs", "Avoid additive antiarrhythmics, antipsychotics, and antibiotics."], ["Control", "Concentration and rate", "Preserve dosing, hepatic rules, and the 60-minute infusion."]],
  "cyp-interactions": ["Route-specific matrix", "Oral first-pass exposure changes both victim and perpetrator behavior", ["Avoid", "CYP3A and P-gp inducers", "Reduced exposure can create treatment failure."], ["Limit", "Oral strong inhibitors", "Markedly increased lefamulin exposure raises adverse-effect risk."], ["Monitor", "Sensitive substrates", "Oral lefamulin can increase CYP3A substrate concentrations."], ["Contraindicate", "QT-sensitive substrate", "Pimozide and similar drugs can provoke torsades."]],
  "organ-reproductive-safety": ["Safety ownership", "Every warning becomes a defined test, interval, trigger, and action", ["Verify", "Pregnancy status", "Animal evidence supports potential fetal harm."], ["Continue", "Two-day contraception", "Extend protection beyond the final dose."], ["Pause", "Human milk", "Pump and discard during therapy and for two days after."], ["Distinguish", "Diarrhea and CDAD", "Screen severity rather than calling every symptom expected."]],
  "integration": ["Closed-loop CABP plan", "Make diagnosis, evidence, exposure, safety, response, and exit agree", ["Define", "Adult nonsevere CABP", "Confirm bacterial disease and resistant-pathogen risks."], ["Justify", "Alternative selection", "State why standard options do not fit."], ["Execute", "Exact route and technique", "Preserve dose, food, infusion, hepatic, QT, and CYP rules."], ["Exit", "Transition or complete", "Use stability, diagnostics, toxicity, and duration."]],
};

export default function LefamulinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual lefamulin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
