export const liceScabiesVisualTypes=["arthropod-foundations","head-lice-diagnosis","pediculicide-selection","product-use-retreatment","household-school-control","other-lice","scabies-diagnosis","classic-scabies-treatment","crusted-outbreaks","special-populations-follow-up"];
const diagrams={
"arthropod-foundations":["Habitat map","Localize organism, viable evidence, life cycle, and host response before treatment",["Hair","Head lice","Live louse and near-scalp nits"],["Clothing","Body lice","Seams carry organisms and eggs"],["Coarse hair","Pubic lice","Sexual-health contact pathway"],["Skin","Scabies mite","Burrow, papule, and contact network"]],
"head-lice-diagnosis":["Scalp examination","Move from sectioned hair to evidence without stigma",["Look","Nape and behind ears","Bright light and fine comb"],["Confirm","Crawling louse","Best evidence of active infestation"],["Place","Nit distance","Near-scalp attachment supports viability"],["Explain","No jump, no pet, no blame","Direct hair contact drives spread"]],
"pediculicide-selection":["Product matrix","Match age, egg activity, repeat logic, and hazard",["Pyrethroid","Permethrin or pyrethrins","Repeat needed when eggs survive"],["Ivermectin","OTC 0.5 percent lotion","Usually one dry-hair application"],["Spinosad","Ovicidal suspension","Repeat only for live lice on day seven"],["Malathion","Flammable lotion","No flame or electrical heat while wet"]],
"product-use-retreatment":["Delivered dose","Preparation, saturation, time, rinse, and follow-up determine efficacy",["Prepare","No conditioner","Follow dry or prepared hair label"],["Cover","Scalp and all hair","Volume follows length and density"],["Time","Exact contact interval","Do not copy another product"],["Review","Live-louse response","Audit before reapplying"]],
"household-school-control":["Proportionate control","Treat close active cases while minimizing stigma, chemicals, and absence",["Check","Household and bed contacts","Coordinate treatment when indicated"],["Wash","Items from prior two days","Hot laundry and comb soaking"],["Avoid","Fogging and exhaustive cleaning","Off-host risk is low"],["Include","Return after treatment begins","Reject no-nit exclusion"]],
"other-lice":["Different lice, different systems","Sexual health and clothing access replace scalp-only reasoning",["Pubic","Partner and STI pathway","Treat all linked exposure"],["Eyelash","Clinician-directed ocular care","Keep insecticides away from eyes"],["Body","Clothing-seam habitat","Inspect clothes and bedding"],["Access","Bathing and clean clothes","Make the primary treatment possible"]],
"scabies-diagnosis":["Scabies pattern","Connect nocturnal itch, burrows, sites, and the two-month contact window",["Inspect","Webs, wrists, waist, genital sites","Distribution supports diagnosis"],["Expand","Child head, neck, palms, soles","Age changes morphology"],["Confirm","Dermoscopy or scraping","Find mite, egg, or scybala"],["Trace","Household, sexual, caregiving","Asymptomatic contacts can transmit"]],
"classic-scabies-treatment":["Whole-body prescription","Drug exposure, second dose, contacts, and recent items operate together",["Permethrin","Five percent, 8 to 14 hours","Comprehensive coverage"],["Ivermectin","Two off-label oral doses","Weight and pregnancy limits"],["Spinosad","At least six-hour skin exposure","Scabies directions differ from lice"],["Coordinate","Contacts and linens","Treat the network simultaneously"]],
"crusted-outbreaks":["High-burden emergency","Combine therapy, improve penetration, and activate infection control",["Recognize","Thick crust and limited itch","Mite burden can be massive"],["Combine","Oral plus topical","Severity guides repeated schedules"],["Penetrate","Keratolysis","Reach mites beneath crust"],["Contain","Precautions and contact tracking","Stop institutional amplification"]],
"special-populations-follow-up":["Closed-loop safety","Product, patient, exposed surface, and new-lesion trajectory determine the next decision",["Verify","Age, weight, concentration","Prevent formulation errors"],["Context","Pregnancy, lactation, barrier","Use product-specific evidence"],["Expect","Residual itch","Hypersensitivity resolves slowly"],["Escalate","New burrows, lice, infection","Separate activity from recovery"]],
};
export default function LiceScabiesVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual lice-scabies-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
