export const linezolidTedizolidPharmacologyVisualTypes = ["structure-mechanism", "spectrum-resistance", "agent-selection", "dosing-pk", "pediatric-administration", "hematologic-safety", "neurologic-mitochondrial", "serotonin-adrenergic", "other-safety", "integration"];

const diagrams = {
  "structure-mechanism": ["Translation gate", "Two agents reach one class target by different starting forms", ["Convert", "Tedizolid phosphate", "Phosphatases expose the active tedizolid moiety."], ["Bind", "50S and 23S rRNA", "Oxazolidinones occupy the bacterial ribosomal target."], ["Block", "70S initiation", "Linezolid prevents formation of a productive initiation complex."], ["Suppress", "Protein synthesis", "Growth stops while host and source factors determine outcome."]],
  "spectrum-resistance": ["Coverage map", "Gram-positive activity is useful only when the organism and site agree", ["Cover", "MRSA and streptococci", "Use current susceptibility and a supported syndrome."], ["Distinguish", "Linezolid VRE role", "Do not transfer this indication to tedizolid."], ["Add", "Gram-negative therapy", "Mixed syndromes need complete companion coverage."], ["Repeat", "Failed response", "Recheck source, MIC, exposure, and target-site resistance."]],
  "agent-selection": ["Indication boundary", "Shared class does not mean interchangeable evidence", ["Select", "Linezolid", "Pneumonia, skin, and VRE roles remain syndrome specific."], ["Select", "Tedizolid", "Current labeling supports a six-day ABSSSI course."], ["Control", "Source", "Drainage and device decisions remain central."], ["Declare", "Evidence status", "Separate labeled use from specialist off-label reasoning."]],
  "dosing-pk": ["Route logic", "High oral bioavailability can remove unnecessary IV therapy", ["Switch", "Linezolid one to one", "About 100 percent oral bioavailability preserves the dose."], ["Time", "Linezolid after dialysis", "The parent dose is unchanged, but timing and toxicity matter."], ["Switch", "Tedizolid one to one", "About 91 percent oral bioavailability preserves 200 mg daily."], ["Hold", "Tedizolid organ dose", "Renal, dialysis, and hepatic impairment need no adjustment."]],
  "pediatric-administration": ["Weight-band workflow", "Pediatric tedizolid begins with gestational age, weight, and route", ["Confirm", "At least 26 weeks and 1 kg", "These are the minimum labeled IV eligibility thresholds."], ["Separate", "Below 35 kg", "Use twice-daily IV weight bands, not the tablet."], ["Reconstitute", "200 mg plus 4 mL", "The vial becomes 50 mg per mL."], ["Infuse", "One hour", "Use NS or D5W and avoid vigorous shaking."]],
  "hematologic-safety": ["CBC surveillance", "Counts become safer when every trend has an owner and action", ["Baseline", "All cell lines", "Know what changed before blaming the antibiotic."], ["Trend", "Weekly linezolid CBC", "Increase frequency when duration or host risk rises."], ["Respond", "Falling platelets", "Review causes, necessity, bleeding, and alternatives."], ["Limit", "Tedizolid to six days", "Do not claim prolonged marrow safety from short trials."]],
  "neurologic-mitochondrial": ["Toxicity signals", "Vision, nerves, and acid-base symptoms can reveal cumulative injury", ["See", "Acuity, color, field", "Promptly evaluate any new visual change."], ["Feel", "Distal sensory or motor change", "Map the pattern and competing neurotoxins."], ["Measure", "Lactate and bicarbonate", "Repeated vomiting or acidosis needs urgent evaluation."], ["Reassess", "Duration and necessity", "Twenty-eight days is not a guarantee of safety."]],
  "serotonin-adrenergic": ["Monoamine map", "Current interaction planning begins with the entire medication list", ["Monitor", "Both agents", "The 2026 labels warn about serotonin syndrome."], ["Recognize", "Clonus and hyperreflexia", "Neuromuscular findings sharpen the diagnosis."], ["Limit", "Large tyramine loads", "Linezolid can enhance pressor responses."], ["Titrate", "Decongestants and pressors", "Blood pressure monitoring turns risk into a plan."]],
  "other-safety": ["Signal expansion", "Do not let platelets hide the rest of the safety profile", ["Check", "Glucose", "Linezolid can amplify hypoglycemia risk."], ["Check", "Sodium", "Confusion or weakness can reflect SIADH."], ["Check", "Muscle and kidney", "Rhabdomyolysis requires prompt action."], ["Avoid", "Tedizolid in neutropenia", "Consider an alternative when ANC is below 1,000."]],
  "integration": ["Closed-loop regimen", "Make diagnosis, exposure, response, and exit agree", ["Define", "Pathogen and compartment", "Confirm a supported gram-positive use."], ["Execute", "Agent, route, and duration", "Keep linezolid and tedizolid plans distinct."], ["Measure", "Response and harm", "Cultures and toxicity share one timeline."], ["Exit", "Narrow, switch, or stop", "Write the decision thresholds before risk accumulates."]],
};

export default function LinezolidTedizolidPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual linezolid-tedizolid-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
