const diagrams = {
  "lipid-statin-pathway": { eyebrow: "Hepatic cholesterol synthesis", title: "Statins reduce hepatocyte cholesterol synthesis, which increases LDL receptor expression and plasma particle clearance.", accent: "#d59a62", columns: [["Block", "HMG-CoA reductase", "Reduce mevalonate pathway flux"], ["Sense", "Lower hepatic cholesterol", "Activate sterol-responsive transcription"], ["Express", "More LDL receptors", "Increase receptor availability at the surface"], ["Clear", "Circulating apoB particles", "Lower LDL-C through hepatic uptake"]] },
  "lipid-absorption-bile": { eyebrow: "Intestinal pathways", title: "Absorption blockade and bile acid binding lower hepatic cholesterol through different luminal mechanisms.", accent: "#b8a064", columns: [["Ezetimibe", "Block NPC1L1", "Reduce intestinal cholesterol uptake"], ["Bile resin", "Bind bile acids", "Interrupt enterohepatic recycling"], ["Liver", "Use cholesterol stores", "Increase bile acid synthesis or receptor demand"], ["Clinical", "Check spacing and triglycerides", "Prevent absorption interactions and worsening hypertriglyceridemia"]] },
  "lipid-pcsk9": { eyebrow: "LDL receptor recycling", title: "PCSK9-directed therapies preserve the receptor pathway at the protein or messenger-RNA level.", accent: "#7fa8bd", columns: [["LDL binds", "Receptor internalization", "The complex enters the hepatocyte"], ["Without PCSK9", "Receptor recycles", "The receptor returns to the surface"], ["With PCSK9", "Receptor degrades", "Fewer receptors remain available"], ["Therapy", "Antibody or siRNA", "Block circulating PCSK9 or reduce hepatic production"]] },
  "lipid-acl": { eyebrow: "Upstream synthesis", title: "Bempedoic acid inhibits ATP-citrate lyase upstream of HMG-CoA reductase after liver-selective activation.", accent: "#a78eb7", columns: [["Citrate", "Cytosolic carbon source", "Feeds acetyl-CoA production"], ["ACL", "Bempedoic acid target", "Reduced acetyl-CoA limits cholesterol synthesis"], ["Liver", "Active metabolite formation", "Activation is concentrated in hepatocytes"], ["Monitor", "Urate, tendon, interactions", "Mechanism does not eliminate product-specific toxicity"]] },
  "lipid-triglyceride": { eyebrow: "Triglyceride pharmacology", title: "Triglyceride therapies change production, lipolysis, fatty-acid signaling, or apoC-III control.", accent: "#c87c69", columns: [["Fibrate", "Activate PPAR-alpha", "Increase fatty-acid oxidation and LPL activity"], ["EPA", "Prescription icosapent ethyl", "Distinct product, dose, and outcomes evidence"], ["ApoC-III", "Olezarsen antisense", "Increase clearance in adult FCS"], ["Safety", "Muscle, kidney, bile, bleeding", "Match monitoring to the exact therapy"]] },
  "lipid-rare": { eyebrow: "Rare lipid disease", title: "Rare-disease therapies bypass or complement the LDL receptor pathway but require specialist-level monitoring.", accent: "#8ca47a", columns: [["ANGPTL3", "Evinacumab antibody", "Lower LDL-C in HoFH without requiring normal LDLR activity"], ["MTP", "Lomitapide inhibition", "Reduce apoB lipoprotein assembly"], ["ApoC-III", "Olezarsen antisense", "Treat adult familial chylomicronemia"], ["System", "Specialist and access pathway", "Coordinate indication, organ safety, nutrition, and adherence"]] },
};

export default function LipidLoweringPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
