export const macrolidePharmacologyVisualTypes = ["structure-mechanism", "agent-differences", "clinical-selection", "dosing-formulations", "interactions", "cardiac-safety", "systemic-safety", "special-populations", "resistance-stewardship", "clinical-integration"];

const diagrams = {
  "structure-mechanism": ["Ribosomal route", "Follow the lactone scaffold from binding to stalled protein synthesis", ["Build", "Macrocyclic lactone and sugars", "Substitutions change acid stability, exposure, and interactions"], ["Bind", "23S rRNA in the 50S subunit", "The drug occupies the nascent peptide exit tunnel"], ["Stall", "Translocation and elongation", "Protein synthesis slows or stops in susceptible bacteria"], ["Persist", "Match exposure to MIC", "Tissue residence cannot overcome established resistance"]],
  "agent-differences": ["Agent map", "Keep azithromycin, clarithromycin, and erythromycin distinct", ["Azithromycin", "Long tissue persistence", "Fewer CYP3A effects but meaningful QT, liver, and cardiovascular risks"], ["Clarithromycin", "Active metabolite", "Strong CYP3A and P-gp interaction burden plus coronary disease warning"], ["Erythromycin", "Multiple salts and forms", "GI motility, CYP3A inhibition, QT risk, and product equivalence matter"], ["Choose", "Syndrome and patient", "No class member is the automatic substitute for another"]],
  "clinical-selection": ["Selection gate", "Prove the syndrome before relying on atypical coverage", ["Respiratory", "Atypicals plus resistance reality", "Local pneumococcal resistance limits routine monotherapy"], ["Pertussis", "Treat early when possible", "Age, timing, exposure risk, and resistance geography shape use"], ["Pregnancy STI", "Azithromycin plus follow-up", "Treatment, test of cure, retesting, and partner management stay connected"], ["H pylori", "Require susceptibility", "Do not use legacy clarithromycin triple therapy empirically"]],
  "dosing-formulations": ["Product logic", "Translate the order into the exact dose form and patient", ["Identify", "Agent, salt, and formulation", "Erythromycin products and azithromycin routes are not interchangeable"], ["Calculate", "Age, weight, and renal function", "Clarithromycin requires agent-specific renal adaptation"], ["Prepare", "Reconstitute and store", "Suspension concentration and labeled handling prevent dose error"], ["Transition", "IV to oral deliberately", "Require stability, absorption, activity, and an executable regimen"]],
  "interactions": ["Interaction cascade", "Stop enzyme and transporter inhibition from becoming multiorgan toxicity", ["Screen", "CYP3A and P-gp substrates", "Clarithromycin and erythromycin create the highest interaction burden"], ["Block", "Contraindicated combinations", "Simvastatin, lovastatin, and selected narrow-index drugs demand action"], ["Protect", "Colchicine and anticoagulants", "Renal or hepatic impairment can magnify exposure and harm"], ["Own", "Monitoring and alternatives", "Every interaction plan needs timing, an owner, and a stop threshold"]],
  "cardiac-safety": ["Repolarization map", "Combine agent signals with the patient's electrical reserve", ["Measure", "QTc and rhythm history", "Congenital long QT, torsade, and bradycardia raise risk"], ["Correct", "Potassium and magnesium", "Electrolyte deficits amplify delayed repolarization"], ["Reconcile", "Every QT-active drug", "Antiarrhythmics, antipsychotics, methadone, and others can stack risk"], ["Differentiate", "Azithromycin and clarithromycin signals", "Short-term and longer-term cardiovascular concerns affect selection"]],
  "systemic-safety": ["Safety perimeter", "Separate common intolerance from organ and microbiome injury", ["Gut", "Motilin and local effects", "Cramping, nausea, vomiting, and diarrhea can impair adherence"], ["Liver", "Cholestatic or hepatocellular injury", "Jaundice and hepatitis symptoms require prompt discontinuation"], ["Colon", "C difficile", "Significant diarrhea can occur during or after treatment"], ["Immune", "Allergy and severe skin reaction", "Mucosal or systemic involvement requires urgent action"]],
  "special-populations": ["Population lens", "Use age, physiology, disease risk, and product evidence together", ["Infant", "Pertussis versus IHPS", "Azithromycin may remain preferred with active vomiting and feeding surveillance"], ["Pregnancy", "Current narrative evidence", "Indication-specific guidance replaces obsolete letter categories"], ["Myasthenia", "Bulbar and respiratory weakness", "Avoid when possible and treat deterioration as urgent"], ["Hearing", "Dose and duration burden", "Tinnitus or hearing change requires exposure and toxicity review"]],
  "resistance-stewardship": ["Resistance map", "Track how target protection and efflux erase class activity", ["Methylate", "erm changes 23S rRNA", "Binding falls and MLSB cross-resistance may appear"], ["Export", "mef efflux", "Intracellular macrolide exposure drops"], ["Measure", "MIC and local resistance", "A familiar indication does not guarantee a susceptible organism"], ["Steward", "Narrow and stop", "Use cultures, supported duration, and proof of response"]],
  "clinical-integration": ["Closed-loop regimen", "Make the diagnosis, exposure, interaction, and exit agree", ["Define", "Syndrome and source", "Avoid treating colonization, viral illness, or uncertain disease by habit"], ["Prove", "Organism and susceptibility", "Resistance can invalidate legacy regimens"], ["Protect", "Cardiac, hepatic, neuromuscular, and interaction safety", "Review the whole patient before the first dose"], ["Exit", "Response and end date", "Narrow, switch, stop, or continue at each decision point"]],
};

export default function MacrolidePharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual macrolide-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
