const diagrams = {
  "safety-taxonomy": { eyebrow: "Event classification", title: "Preventability, reach, and harm are separate dimensions", accent: "#7d91a8", columns: [["Process", "Was there a preventable failure?", "Error can occur with or without injury."], ["Reach", "Where was it intercepted?", "Hazards and near misses reveal weak defenses."], ["Outcome", "What happened to the patient?", "Use severity categories without ending analysis."]] },
  "safety-systems": { eyebrow: "Systems lens", title: "The visible action sits above a deeper architecture", accent: "#a57a6b", columns: [["Active", "Patient interface", "The final action is close to the event."], ["Latent", "Design and conditions", "Workflow, tools, staffing, and policy shape risk."], ["Culture", "Fair accountability", "Repair systems while responding proportionately."]] },
  "safety-response": { eyebrow: "Response sequence", title: "Protect the patient, preserve the facts, then learn", accent: "#9a6f7d", columns: [["Stabilize", "Immediate care", "Stop exposure, assess, mitigate, and monitor."], ["Communicate", "People and teams", "Notify, disclose, document, and follow up."], ["Report", "Local and external", "Route the signal to systems that can act."]] },
  "safety-improvement": { eyebrow: "Improvement logic", title: "Look backward, look forward, and measure both", accent: "#6f927f", columns: [["RCA2", "After an event", "Find system contributors and implement strong action."], ["FMEA", "Before an event", "Predict failure modes in a changing process."], ["Control", "Over time", "Measure structure, process, outcome, and drift."]] },
  "safety-communication": { eyebrow: "Unambiguous intent", title: "Identity, medicine, dose, and purpose must all agree", accent: "#a88d60", columns: [["Patient", "Two identifiers", "Never substitute room or appearance."], ["Order", "Metric and complete", "Use safe decimals, indication, route, and schedule."], ["Product", "Layered verification", "Names, storage, barcode, and label reinforce one another."]] },
  "safety-high-alert": { eyebrow: "Control hierarchy", title: "High consequence requires stronger defenses", accent: "#b36c5b", columns: [["Constrain", "Remove unnecessary choice", "Limit access, concentrations, and variants."], ["Standardize", "Align the system", "Orders, preparation, storage, pumps, and labels match."], ["Verify", "Use selective redundancy", "Independent checks support, but do not replace, design."]] },
  "safety-reconciliation": { eyebrow: "Transition bridge", title: "One verified history becomes one intentional plan", accent: "#718e9c", columns: [["Gather", "Best possible history", "Interview and verify actual use from several sources."], ["Resolve", "Compare with intent", "Explain every omission, duplication, and change."], ["Communicate", "One current plan", "Patient and next team understand starts, stops, and monitoring."]] },
  "safety-technology": { eyebrow: "Sociotechnical loop", title: "Automation is a defense only when workflow preserves it", accent: "#777aa3", columns: [["Order", "CPOE and CDS", "Tune decisions without flooding clinicians."], ["Access", "ADC and barcode", "Control overrides and scan at the point of care."], ["Infuse", "Smart-pump library", "Keep concentrations, orders, and limits synchronized."]] },
  "safety-administration": { eyebrow: "Closed loop", title: "The final bedside check depends on every upstream layer", accent: "#9b8266", columns: [["Verify", "Patient, product, order", "Five rights sit inside stronger system controls."], ["Administer", "Route and monitoring", "Label, scan, observe, and preserve stop authority."], ["Partner", "Patient and caregiver", "Questions, access, language, and teach-back reveal risk."]] },
  "safety-governance": { eyebrow: "Learning system", title: "Standards become safety only when the loop closes", accent: "#8f7c58", columns: [["Set", "National Performance Goals", "Translate current expectations into local controls."], ["Learn", "Reports and measures", "Aggregate weak signals and patient experience."], ["Act", "Ownership and sustainment", "Implement, verify, communicate, and revisit change."]] },
};

export default function MedicationSafetyQualityVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual medication-safety-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
