const diagrams = {
  "mht-transition": ["Transition map", "Read the timeline before the laboratory", ["Transition", "Variable cycles", "Symptoms can emerge while ovarian activity fluctuates"], ["Milestone", "Twelve months", "Natural menopause is confirmed retrospectively"], ["Exception", "Unexpected timing", "Early loss or atypical findings require a broader evaluation"]],
  "mht-thermoregulation": ["Thermoregulatory circuit", "A narrowed neutral zone creates the hot flash", ["Signal", "Estrogen withdrawal", "KNDy neuron activity and neurokinin signaling change"], ["Trigger", "Small temperature shift", "Vasodilation and sweating begin sooner"], ["Target", "Hormonal or neural", "Estrogen and neurokinin therapies intervene at different points"]],
  "mht-estrogen": ["Route architecture", "One hormone, different exposure paths", ["Oral", "First-pass liver exposure", "Hepatic protein synthesis and systemic exposure shape selection"], ["Transdermal", "Direct systemic delivery", "Avoids first-pass administration but remains systemic therapy"], ["Vaginal", "Product-dependent exposure", "Low-dose local and systemic vaginal products must be distinguished"]],
  "mht-endometrium": ["Endometrial logic", "Uterus status determines the protection question", ["Estrogen", "Proliferative signal", "Systemic exposure stimulates an intact endometrium"], ["Opposition", "Progestogen or bazedoxifene", "A validated regimen limits proliferation"], ["Pattern", "Continuous or cyclic", "Schedule predicts adherence needs and bleeding"]],
  "mht-bleeding": ["Bleeding pathway", "Predict, observe, investigate", ["Expected", "Regimen-linked pattern", "Cyclic withdrawal or early continuous-combined spotting"], ["Review", "Use and interactions", "Confirm schedule, adherence, products, and baseline history"], ["Escalate", "New or persistent bleeding", "Postmenopausal bleeding requires clinical evaluation"]],
  "mht-nonhormonal": ["Nonhormonal selection", "Match mechanism to the patient", ["Monoamine", "Selected SSRI or SNRI", "Review serotonergic effects and CYP interactions"], ["Neural", "Gabapentin", "Sedation and symptom timing can guide use"], ["Neurokinin", "NK3 or NK1 and NK3", "Use product-specific interaction and monitoring plans"]],
  "mht-gsm": ["GSM treatment ladder", "Treat the tissue and the lived symptom", ["Support", "Moisturizer and lubricant", "Separate scheduled tissue hydration from activity-linked friction relief"], ["Local", "Estrogen or prasterone", "Choose the exact product and account for cancer context"], ["Systemic receptor", "Ospemifene", "Screen systemic contraindications and counsel on oral use"]],
  "mht-risk": ["Risk frame", "No single factor decides alone", ["Patient", "History and baseline risk", "Bleeding, cancer, vascular, liver, and cardiovascular history matter"], ["Timing", "Age and menopause interval", "A younger, recently menopausal population is generally more favorable"], ["Product", "Route, dose, formulation", "Current labeling determines the final safety boundaries"]],
  "mht-prevention": ["Indication boundary", "Benefit is not a universal prevention claim", ["Symptoms", "Vasomotor and GSM", "Treat bothersome symptoms after individualized assessment"], ["Bone", "Loss and fracture", "Systemic estrogen protects while therapy continues"], ["Prevention", "Heart and cognition", "Do not initiate solely for primary chronic-disease prevention"]],
  "mht-followup": ["Care loop", "A prescription is the beginning of reassessment", ["Start", "Define target and baseline", "Document symptoms, uterus status, risks, medicines, and priorities"], ["Measure", "Benefit and safety", "Review response, bleeding, adverse effects, interactions, and required tests"], ["Reconsider", "Continue, adjust, or stop", "Use current evidence and a new shared decision rather than a fixed deadline"]],
};

export default function MenopausalHormoneTherapyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
