export const minorWoundCareVisualTypes=["wound-assessment","bleeding-control","cleaning-debridement","healing-foundations","moist-covered-care","topicals-antiseptics","tetanus-prevention","high-risk-wounds","infection-follow-up"];
const diagrams={
"wound-assessment":["Triage map","Move from mechanism and surface appearance to anatomy, function, contamination, and urgency",["Classify","Abrasion, laceration, puncture","Mechanism predicts hidden risk"],["Inspect","Depth, gaping, contamination","Identify closure and exploration needs"],["Test","Motion, sensation, perfusion","Find tendon, nerve, vessel, or joint injury"],["Escalate","Hemorrhage or major anatomy","Life threats precede cleaning"]],
"bleeding-control":["Hemostasis sequence","Protect the rescuer, compress the source, preserve the clot, and escalate severe loss",["Barrier","Gloves and eye protection","Prevent a second exposure"],["Pressure","Firm and uninterrupted","Add layers without lifting the clot"],["Observe","Rate, shock, distal flow","Recognize failure"],["Escalate","Emergency and tourniquet","Use trained decisive control"]],
"cleaning-debridement":["Contamination pathway","Remove what is safe while protecting viable tissue and deeper anatomy",["Rinse","Clean running water","Mechanical removal is central"],["Inspect","Visible debris and wound base","Do not probe blindly"],["Protect","Embedded object","Stabilize rather than extract"],["Refer","Necrosis or retained material","Debridement follows perfusion and tissue"]],
"healing-foundations":["Repair continuum","Hemostasis, inflammation, proliferation, epithelial migration, and remodeling overlap",["Seal","Platelet and fibrin","Stabilize the wound"],["Clear","Inflammatory signaling","Differentiate expected from progressive"],["Rebuild","Granulation and epithelium","Support moisture, oxygen, and nutrition"],["Remodel","Collagen and scar","Protect from tension and re-injury"]],
"moist-covered-care":["Healing environment","Clean, lightly moist, protected, and inspectable",["Clean","Gentle daily care","Remove contamination without toxicity"],["Moisturize","Plain petroleum jelly","Limit drying and scab fracture"],["Cover","Nonadherent protection","Balance drainage and friction"],["Renew","Daily or when soiled","Inspect the trajectory"]],
"topicals-antiseptics":["Topical decision","Separate clean wound support, dermatitis, tissue toxicity, and true infection",["Default","Petroleum and dressing","Most clean wounds need no antibiotic"],["Sensitize","Neomycin or bacitracin","Contact dermatitis can mimic infection"],["Avoid","Harsh antiseptic exposure","Cell injury can delay healing"],["Treat","Diagnosed infection","Match depth, organism, and host"]],
"tetanus-prevention":["Tetanus matrix","Wound class plus primary series plus time since last dose determine protection",["Clean minor","Ten-year vaccine threshold","TIG never indicated"],["Dirty major","Five-year vaccine threshold","Puncture and devitalized tissue count"],["Unknown series","Vaccinate every wound","Complete the primary series"],["TIG","Selected dirty major wounds","Provide immediate passive protection"]],
"high-risk-wounds":["Hidden-risk filter","Anatomy, host, contamination, and feasibility can outweigh surface size",["Puncture","Deep narrow tract","Foreign body and infection risk"],["Hand or joint","Function-critical anatomy","Test motion, sensation, and perfusion"],["Foot","Diabetes and circulation","Lower the referral threshold"],["Person","Immune, bleeding, self-care","Adapt the plan"]],
"infection-follow-up":["Closed-loop wound care","Measure healing, identify stalled biology, and define the return rule",["Track","Size, edge, pain, drainage","Compare over time"],["Escalate","Pus, spread, fever, function","Recognize infection and dehiscence"],["Investigate","Foreign body, perfusion, pressure","Find the cause of delay"],["Transition","Closed barrier and scar care","Protect after epithelialization"]],
};
export default function MinorWoundCareVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual minor-wound-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
