const diagrams = {
  "motion-biology": { eyebrow: "Sensory mismatch", title: "The eyes, inner ear, and body disagree about motion", accent: "#6b91a8", columns: [["Visual", "What the eyes report", "A stable page can conflict with a turning vehicle."], ["Vestibular", "Acceleration and gravity", "The inner ear reports motion and orientation."], ["Internal model", "Expected pattern", "Mismatch activates autonomic and vomiting pathways."]] },
  "motion-assessment": { eyebrow: "Diagnostic boundary", title: "A motion trigger supports the diagnosis, but red flags reopen it", accent: "#b66b62", columns: [["Typical", "Stimulus linked", "Nausea, pallor, sweating, salivation, dizziness, and fatigue."], ["Urgent", "Neurologic or systemic", "Diplopia, ataxia, syncope, severe headache, fever, or trauma."], ["Persistent", "Beyond the journey", "Migraine, vestibular disease, or another diagnosis may be present."]] },
  "motion-behavior": { eyebrow: "Conflict reduction", title: "Change the sensory environment before adding a drug", accent: "#7f9d82", columns: [["Adapt", "Habituation", "Repeated graded exposure updates the internal model."], ["Align", "Horizon and posture", "Make visual and vestibular motion agree."], ["Stabilize", "Sleep, head, breathing", "Reduce susceptibility and unnecessary movement."]] },
  "motion-pharmacology": { eyebrow: "Selection grid", title: "Duration, intensity, and alertness define the drug decision", accent: "#a48a63", columns: [["Before", "Preexposure timing", "Act before gastric stasis limits absorption."], ["During", "Match the trip", "Short oral coverage or sustained transdermal prevention."], ["After", "Protect function", "Central efficacy can impair driving and critical work."]] },
  "motion-antihistamines": { eyebrow: "Central H1 therapy", title: "The same brain penetration that works can also impair", accent: "#817da1", columns: [["Dimenhydrinate", "Shorter interval", "Read the exact age, dose, timing, and daily maximum."], ["Meclizine", "Longer duration", "Less drowsy does not mean nonimpairing."], ["Burden", "Sedation plus anticholinergic", "Alcohol, sedatives, age, bladder, eye, and lung risk matter."]] },
  "motion-scopolamine": { eyebrow: "Controlled delivery", title: "One intact patch, one precise safety system", accent: "#b88758", columns: [["Apply", "Behind one ear", "At least four hours before exposure for up to three days."], ["Monitor", "Heat, eyes, mind, bladder", "Remove for hyperthermia or concerning reactions."], ["Remove", "MRI, hands, disposal", "Clean the site and fold adhesive sides together."]] },
  "motion-populations": { eyebrow: "Risk adaptation", title: "The prevention plan changes with physiology and responsibility", accent: "#9d7080", columns: [["Children", "Behavior first", "Avoid scopolamine and prevent oversedation."], ["Older adults", "Anticholinergic sensitivity", "Delirium, falls, retention, and heat risk can dominate."], ["Critical work", "Performance first", "No first dose during driving, piloting, or machinery use."]] },
  "motion-recovery": { eyebrow: "Failure pathway", title: "Reduce motion, restore volume, and reassess the diagnosis", accent: "#608f94", columns: [["Stabilize", "Position and airway", "Stop the stimulus and reduce head movement."], ["Restore", "Fluid and electrolytes", "Escalate when oral intake fails."], ["Refer", "Persistent disequilibrium", "Weeks of rocking or spontaneous vertigo need specialist evaluation."]] },
};

export default function MotionSicknessVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
