const diagrams = {
  "ms-recognition": { eyebrow: "Diagnostic architecture", title: "Interpret clinical and test evidence within defined criteria", accent: "#8ba8c9", columns: [["Localize", "Start with anatomy", "Map clinical history and objective lesions; selected presentations can qualify without a typical attack."], ["Corroborate", "Add current evidence", "Use characteristic MRI, CSF, optic nerve, central vein, and rim-lesion evidence within defined criteria."], ["Exclude", "Protect specificity", "Investigate NMOSD, MOG-associated disease, vascular, infectious, nutritional, compressive, and inflammatory mimics."]] },
  "ms-course": { eyebrow: "Disease trajectory", title: "Inflammation and progression leave different signals", accent: "#9b8fc3", columns: [["Activity", "Clinical and MRI evidence", "Track relapses, enhancing lesions, and new or unequivocally enlarging T2 lesions over a stated interval."], ["Accumulate", "Axonal injury", "Incomplete recovery and tissue loss can convert attacks into lasting disability."], ["Progress", "Change outside relapse", "Measure walking, hand function, cognition, vision, and daily performance over time."]] },
  "ms-relapse": { eyebrow: "Acute decision", title: "Confirm the attack, restore function, reassess control", accent: "#d28a79", columns: [["Verify", "Relapse or pseudo-relapse", "Check infection, fever, heat, metabolic stress, timing, localization, and objective change."], ["Treat", "High-dose glucocorticoid", "Use acute therapy for functionally important inflammation, not as chronic disease modification."], ["Escalate", "Plasma exchange", "Move urgently when a severe demyelinating deficit remains steroid refractory."]] },
  "ms-injectables": { eyebrow: "Platform therapy", title: "The product schedule is part of the medicine", accent: "#8faf9e", columns: [["Glatiramer", "Protect the injection system", "Rotate sites. Suspected anaphylaxis needs immediate emergency care, even after years of tolerance."], ["Interferon", "Specify the formulation", "Match route and schedule with flu-like, liver, blood, thyroid, mood, and skin surveillance."], ["Monitor", "Separate use from control", "Confirm exposure and continue relapse, MRI, and disability assessment."]] },
  "ms-orals": { eyebrow: "Oral DMT", title: "Convenience still requires a safety calendar", accent: "#caa068", columns: [["Fumarates", "Follow lymphocytes", "Match product dosing and food instructions. Track lymphocytes; investigate suspected PML or severe GI symptoms promptly."], ["Teriflunomide", "Track persistent exposure", "Monitor liver, blood, pressure, nerves, infection, interactions, and reproduction."], ["Eliminate", "Use the full protocol", "Apply cholestyramine or activated charcoal and verify low concentrations when rapid removal is required."]] },
  "ms-s1p": { eyebrow: "Receptor modulation", title: "One class contains four distinct initiation pathways", accent: "#a994c7", columns: [["Before", "Screen the patient", "Review conduction, medicines, VZV, eyes, liver, blood, lungs, infection, vaccines, and pregnancy."], ["Start", "Follow the product", "Apply the correct genotype, titration, and first-dose observation requirements."], ["Stop", "Prevent rebound", "Plan interruptions, restart requirements, access, and the next effective therapy before a prolonged gap."]] },
  "ms-biologics": { eyebrow: "High efficacy", title: "Powerful control depends on precise risk systems", accent: "#82a4bd", columns: [["CD20", "Name product and route", "Separate ocrelizumab IV and SC, ofatumumab, and ublituximab schedules and indications."], ["Defense", "Prepare immunity", "Screen hepatitis B, immunoglobulins, liver, infection, and vaccines before depletion."], ["Follow-up", "Track immune recovery", "Follow immunoglobulins, infections and B-cell recovery after treatment ends."]] },
  "ms-natalizumab": { eyebrow: "Natalizumab", title: "Link every infusion to an active safety review", accent: "#c0aa78", columns: [["Risk", "Maintain the PML assessment", "Review JCV status, treatment duration, prior immunosuppression and MRI context."], ["Infuse", "Observe and respond", "Use the product protocol and evaluate hypersensitivity promptly; do not re-treat after hypersensitivity."], ["Investigate", "Keep suspicion active", "Withhold treatment and repeat evaluation when PML remains suspected despite initial negative testing."]] },
  "ms-reconstitution": { eyebrow: "Immune reconstitution", title: "The course ends before the safety obligation", accent: "#b98b86", columns: [["Cladribine", "Plan annual courses", "Screen infection, malignancy, blood, liver, vaccines, interactions, and reproduction."], ["Alemtuzumab", "Use the REMS system", "Track monthly CBC, creatinine and urinalysis, plus thyroid tests every three months, through 48 months after the last course."], ["After", "Expect delayed biology", "Investigate warning symptoms even after scheduled surveillance ends. Additional courses extend the monitoring timeline."]] },
  "ms-rehabilitation": { eyebrow: "Function", title: "Disease control and daily performance need separate plans", accent: "#a5b17f", columns: [["Move", "Rehabilitate deliberately", "Combine gait, balance, strength, stretching, energy conservation, equipment, and home safety."], ["Target", "Treat each symptom", "Distinguish spasticity, pain, bladder, bowel, fatigue, sleep, mood, cognition, and sexual health."], ["Protect", "Reduce medicine burden", "Prevent sedation, falls, retention, constipation, and cognitive effects from cumulative symptom therapy."]] },
  "ms-fatigue": { eyebrow: "Fatigue and cognition", title: "Assess, agree on a goal, then reassess", accent: "#c0aa78", columns: [["Assess", "Find contributors", "Review sleep, mood, illness, medicines and cognitive difficulties before attributing everything to MS."], ["Plan", "Choose a measurable goal", "Discuss behavioral approaches and individualized medication trials with the specialist."], ["Review", "Test benefit against burden", "Record daily function and adverse effects. Continue, adjust or stop treatment through a shared plan."]] },
  "ms-autonomic": { eyebrow: "Daily life", title: "Different symptoms need different assessments", accent: "#c0aa78", columns: [["Elimination", "Clarify the mechanism", "Distinguish storage from emptying problems and fecal leakage from uncomplicated diarrhea."], ["Communication", "Protect safe swallowing", "Assess coughing during meals and nutritional effects; tailor speech and swallowing support."], ["Wellbeing", "Ask directly and privately", "Review sexual concerns, mood and involuntary emotional expression without treating them as interchangeable."]] },
  "ms-longitudinal": { eyebrow: "Continuity", title: "The timeline holds every future decision", accent: "#c0aa78", columns: [["Evidence", "Measure breakthrough", "Record relapses, MRI, disability, tolerability, exposure, and safety monitoring."], ["Transition", "Own the switch", "Balance washout, immune recovery, rebound, infection, vaccines, pregnancy, and overlap."], ["Access", "Make treatment reachable", "Resolve coverage, travel, storage, training, language, and laboratory barriers before they become a gap."]] },
};

export default function MultipleSclerosisVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual multiple-sclerosis-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
