export const mupirocinDecolonizationVisualTypes = ["structure-mechanism", "products-routes", "skin-infection-use", "colonization-strategy", "nasal-technique", "current-decolonization", "bundle-evidence", "resistance-stewardship", "safety-populations", "monitoring-counseling"].map((type) => `mupirocin-${type}`);

const diagrams = {
  "structure-mechanism": ["Selective mechanism", "Interrupt bacterial protein synthesis before the ribosome", ["Recognize", "Isoleucyl adenylate", "The scaffold resembles the enzyme reaction intermediate."], ["Bind", "IleRS", "Mupirocin occupies bacterial isoleucyl transfer RNA synthetase."], ["Deplete", "Charged tRNA", "Isoleucine cannot be loaded for translation."], ["Stop", "Protein synthesis", "Growth is inhibited and high local exposure can kill susceptible bacteria."]],
  "products-routes": ["Product map", "Same active moiety, different route and vehicle", ["Ointment", "Polyethylene glycol", "Current dermal product treats susceptible impetigo."], ["Cream", "Oil and water", "A separate formulation treats selected traumatic skin infection."], ["Nasal", "Paraffin base", "The dedicated single use product was discontinued."], ["Verify", "Policy and product", "Do not infer route interchangeability from 2% strength."]],
  "skin-infection-use": ["Local infection pathway", "Keep topical treatment inside a limited skin syndrome", ["Confirm", "Impetigo", "Identify a superficial bacterial process."], ["Apply", "Three times daily", "Use a small amount for up to 10 days."], ["Review", "Day 3 to 5", "Lack of improvement triggers reassessment."], ["Escalate", "Deep or systemic", "Source control or systemic therapy may be needed."]],
  "colonization-strategy": ["Clinical state", "Separate carriage, transmission risk, and active disease", ["Detect", "Nasal carriage", "A screen identifies organisms without proving infection."], ["Map", "Reservoir", "Nares can seed hands, skin, devices, and wounds."], ["Choose", "Prevention goal", "Decolonization reduces carriage for a defined purpose."], ["Reassess", "Recolonization", "Clearance can be temporary."]],
  "nasal-technique": ["Administration sequence", "Turn a protocol into reproducible technique", ["Divide", "Half and half", "Place the designated amount in each nostril."], ["Compress", "Sides of nose", "Press and release repeatedly."], ["Massage", "One minute", "Distribute ointment through the anterior nares."], ["Finish", "Wash and discard", "Prevent eye exposure, sharing, and tube reuse."]],
  "current-decolonization": ["Protocol selection", "Match the decolonization strategy to the risk period", ["ICU", "Universal strategy", "Nasal treatment and daily chlorhexidine address high risk admission."], ["Device", "Targeted period", "Central access outside ICU can justify a supplemental protocol."], ["Surgery", "Preoperative", "High risk procedures use nasal and skin measures."], ["Outbreak", "Institutional", "Screening and decolonization follow the infection control plan."]],
  "bundle-evidence": ["Transmission bundle", "One product cannot manage every reservoir", ["Nose", "Mupirocin", "Reduce the nasal S. aureus reservoir."], ["Skin", "Chlorhexidine", "Reduce organism burden beyond the nares."], ["Care", "Hands and devices", "Interrupt transfer and protect access sites."], ["System", "Audit and feedback", "Measure adherence, resistance, and outcomes."]],
  "resistance-stewardship": ["Resistance map", "Find the reason decolonization failed", ["Mutate", "Native IleRS", "Point mutations can produce low level resistance."], ["Acquire", "mupA or mupB", "An alternate enzyme can create high level resistance."], ["Select", "Repeated exposure", "Unnecessary courses increase pressure."], ["Investigate", "Failure", "Check adherence, sites, recolonization, and susceptibility."]],
  "safety-populations": ["Safety screen", "Route, vehicle, surface, and host determine risk", ["Watch", "Local reaction", "Burning, drying, itching, or rash can limit use."], ["Stop", "Systemic allergy", "Anaphylaxis, angioedema, or generalized rash needs urgent action."], ["Limit", "PEG exposure", "Large damaged surfaces and renal impairment increase concern."], ["Protect", "Infant exposure", "Wash treated breast tissue before feeding."]],
  "monitoring-counseling": ["Closed loop", "Connect purpose, product, performance, and response", ["Name", "Indication", "Treatment and decolonization are different goals."], ["Verify", "Exact product", "Route and vehicle must match the plan."], ["Observe", "Technique", "Ask for demonstration when administration matters."], ["Escalate", "Failure", "Reassess infection, resistance, adherence, and protocol."]],
};

export default function MupirocinDecolonizationVisual({ type }) {
  const diagram = diagrams[type.replace("mupirocin-", "")];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual mupirocin-decolonization-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
