const diagrams = {
  "mg-junction": { eyebrow: "Neuromuscular transmission", title: "A reduced safety factor turns repeated effort into weakness", accent: "#d8aa78", columns: [["Signal", "Release acetylcholine", "The motor nerve supplies a normal chemical signal to the synaptic cleft."], ["Receive", "Protect receptor architecture", "AChR, MuSK, and LRP4 biology determines whether the end plate can translate the signal."], ["Contract", "Sustain repeated output", "Postsynaptic injury lowers reserve, so contraction fails as activity continues and improves with rest."]] },
  "mg-recognition": { eyebrow: "Clinical urgency", title: "Distribution and trajectory determine whether weakness can wait", accent: "#cb7a70", columns: [["Recognize", "Find fatigability", "Ocular, bulbar, axial, limb, and respiratory weakness fluctuate with use and time."], ["Protect", "Assess cough and swallowing", "Wet voice, secretion pooling, choking, and weak cough can precede airway loss."], ["Escalate", "Measure ventilation", "FVC, NIF, speech, gas exchange, and trajectory matter even when oxygen saturation is normal."]] },
  "mg-diagnosis": { eyebrow: "Diagnostic architecture", title: "Phenotype, antibody, physiology, and thymus answer different questions", accent: "#8ea8bc", columns: [["Classify", "Test antibodies", "AChR is usually first, followed by MuSK and selected additional testing when suspicion remains."], ["Demonstrate", "Measure transmission", "Repetitive stimulation and single fiber EMG can reveal junction failure."], ["Search", "Image the mediastinum", "Chest CT or MRI identifies thymoma and thymic abnormality that change management."]] },
  "mg-pyridostigmine": { eyebrow: "Symptomatic pharmacology", title: "Increase acetylcholine where function needs it, not until toxicity appears", accent: "#b89d6d", columns: [["Time", "Support meals and activity", "Short duration makes dose timing as important as total exposure."], ["Titrate", "Follow strength and secretions", "Renal function, response, and muscarinic symptoms define the useful dose."], ["Reassess", "Separate crisis from excess", "Diarrhea, sweating, fasciculation, and paradoxical weakness make blind escalation unsafe."]] },
  "mg-immunotherapy": { eyebrow: "Disease modification", title: "Fast control and durable control operate on different clocks", accent: "#9d8cba", columns: [["Bridge", "Protect current function", "Pyridostigmine and rescue therapy may cover the delay before immune control appears."], ["Suppress", "Choose the immune strategy", "Corticosteroids act sooner but can worsen weakness early; steroid sparing drugs can take months."], ["Measure", "Track disease and harm", "Function, crisis, infection, organ toxicity, bone, metabolic, and reproductive risks define success."]] },
  "mg-thymectomy": { eyebrow: "Surgical selection", title: "Thymoma and immune disease modification are related but distinct indications", accent: "#b47e70", columns: [["Identify", "Treat thymoma", "A thymic tumor requires surgical evaluation while MG is stabilized."], ["Select", "Use phenotype evidence", "Younger adults with generalized AChR positive nonthymomatous disease have the clearest benefit."], ["Time", "Operate when stable", "Elective surgery is safer after respiratory and bulbar function are controlled."]] },
  "mg-crisis": { eyebrow: "Respiratory emergency", title: "Airway support and rapid immune rescue must move together", accent: "#cf655f", columns: [["Ventilate", "Act before collapse", "Cough, secretions, FVC, NIF, speech, and trajectory guide airway timing."], ["Rescue", "Use PLEX or IV immune globulin", "Select rapid therapy from phenotype, access, hemodynamics, kidney function, thrombosis risk, and speed."], ["Resolve", "Treat the precipitant", "Infection, aspiration, surgery, treatment interruption, and medication exposure must be corrected."]] },
  "mg-fcrn": { eyebrow: "Targeted IgG reduction", title: "FcRn blockade changes the life cycle of pathogenic antibody", accent: "#74a89b", columns: [["Block", "Interrupt IgG recycling", "Less FcRn rescue sends more IgG toward degradation."], ["Match", "Verify product labeling", "Efgartigimod, rozanolixizumab, and nipocalimab differ by phenotype, age, route, and schedule."], ["Protect", "Plan infection and vaccines", "Review active infection, live vaccines, treatment cycles, and Fc containing therapies."]] },
  "mg-complement": { eyebrow: "Terminal complement", title: "C5 blockade protects the end plate and creates a distinct infection vulnerability", accent: "#e0a067", columns: [["Match", "Confirm AChR positive disease", "Current US MG labels for eculizumab, ravulizumab, and zilucoplan are phenotype specific."], ["Prevent", "Use MenACWY and MenB", "Vaccination, urgent prophylaxis when required, REMS, and a safety card form one prevention system."], ["Respond", "Treat symptoms as an emergency", "Vaccination cannot eliminate meningococcal risk, so compatible illness needs immediate evaluation."]] },
  "mg-cautions": { eyebrow: "Longitudinal safety", title: "A useful caution list creates decisions, not fear", accent: "#a59a84", columns: [["Review", "Find the strength of risk", "Telithromycin, fluoroquinolones, IV magnesium, and other exposures do not carry identical evidence."], ["Coordinate", "Plan pregnancy and procedures", "Neurology, obstetrics, anesthesia, pharmacy, and surgery need one shared MG plan."], ["Escalate", "Protect speech and breathing", "Rapidly worse swallowing, cough, head control, or breathing requires urgent care."]] },
};

export const myastheniaGravisVisualTypes = Object.keys(diagrams);

export default function MyastheniaGravisVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual myasthenia-gravis-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
