export const nitroimidazolePharmacologyVisualTypes = ["structure-mechanism", "spectrum-roles", "bv-trichomoniasis", "dosing-pk", "agent-formulation-selection", "interactions-counseling", "neurologic-organ-safety", "special-populations", "monitoring-response", "integration"];

const diagrams = {
  "structure-mechanism": ["Activation sequence", "A reduced nitro group turns selective entry into lethal DNA damage", ["Enter", "Susceptible cell", "Anaerobic and protozoal pathways admit the agent."], ["Reduce", "Nitro group", "Nitroreductases generate reactive intermediates."], ["Damage", "DNA integrity", "Helical structure and strands are disrupted."], ["Interrupt", "Resistance", "Uptake, efflux, and reduction can change activity."]],
  "spectrum-roles": ["Coverage boundary", "Useful anaerobic activity becomes safe when its missing coverage stays visible", ["Cover", "Many anaerobes", "Match activity to source and current susceptibility."], ["Treat", "Selected protozoa", "Use the right agent, route, and compartment."], ["Add", "Aerobic coverage", "Mixed syndromes often need a companion agent."], ["Control", "Anatomic source", "Drainage and surgery remain separate interventions."]],
  "bv-trichomoniasis": ["Syndrome split", "Similar drugs serve two conditions with different follow-up structures", ["Diagnose", "Bacterial vaginosis", "Confirm symptomatic dysbiosis before selecting a regimen."], ["Treat", "Trichomoniasis", "Use systemic therapy and sex-specific CDC dosing."], ["Protect", "Partners", "Treat exposure and avoid sex until therapy is complete."], ["Return", "Retesting", "Retest women near three months after trichomoniasis."]],
  "dosing-pk": ["Exposure map", "Agent, organ function, and formulation determine the dosing path", ["Transition", "IV to oral", "High oral exposure can support the right patient."], ["Reduce", "Child-Pugh C", "Severe hepatic impairment increases metronidazole exposure."], ["Extend", "Tinidazole", "A longer half-life changes regimen and precautions."], ["Sprinkle", "Secnidazole", "Use soft food, no chewing, and no liquid dissolution."]],
  "agent-formulation-selection": ["Product matrix", "Choose the anatomic exposure before choosing convenience", ["Systemic", "Oral or IV", "Match severity, absorption, and site."], ["Local", "Vaginal gel", "Use for BV, not trichomoniasis."], ["Longer", "Tinidazole", "Balance exposure with pregnancy and lactation limits."], ["Single", "Secnidazole packet", "Preserve safety and follow-up around one dose."]],
  "interactions-counseling": ["Counseling clock", "Evidence, labels, and measured interactions remain distinct", ["Explain", "Alcohol evidence", "CDC questions certainty while labels still direct avoidance."], ["Time", "Product interval", "Use three days or two days according to the agent."], ["Exclude", "Disulfiram", "Keep a two-week separation from metronidazole."], ["Measure", "Warfarin response", "Use closer INR monitoring and individualized action."]],
  "neurologic-organ-safety": ["Stop-signal map", "New neurologic, immune, or hepatic findings can end exposure", ["Notice", "Ataxia or numbness", "Evaluate peripheral and central neurotoxicity promptly."], ["Stop", "Severe skin reaction", "Mucosal disease or blistering requires urgent care."], ["Protect", "Cockayne syndrome", "Rapid fatal liver injury demands exceptional caution."], ["Trend", "CBC and organs", "Monitoring intensity follows duration and risk."]],
  "special-populations": ["Evidence ladder", "Related drugs carry different pregnancy and lactation decisions", ["Support", "Metronidazole", "CDC considers pregnancy risk low when treatment is indicated."], ["Avoid", "Tinidazole pregnancy", "Human evidence is limited and alternatives are preferred."], ["Pause", "Tinidazole lactation", "Use 72 hours after the final dose."], ["Pause", "Secnidazole lactation", "Use 96 hours after the single dose."]],
  "monitoring-response": ["Reassessment loop", "Every symptom change asks whether the diagnosis, exposure, or safety state changed", ["Measure", "Original syndrome", "Follow direct clinical and source-control endpoints."], ["Verify", "Adherence and partners", "Separate reinfection from resistance."], ["Rediagnose", "New candidiasis", "Post-treatment symptoms may represent another syndrome."], ["Exit", "Stop or escalate", "Define completion and failure criteria in advance."]],
  "integration": ["Closed-loop regimen", "Make diagnosis, product, safety, response, and exit agree", ["Define", "Syndrome and source", "Name the infection and required intervention."], ["Select", "Exact product", "Preserve route, dose, duration, and formulation."], ["Own", "Safety and follow-up", "Assign interaction, organ, partner, and retest plans."], ["Exit", "Complete or change", "Use response, toxicity, and new evidence."]],
};

export default function NitroimidazolePharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual nitroimidazole-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
