export const nitrofurantoinPharmacologyVisualTypes = ["structure-mechanism", "formulations-release", "cystitis-phenotype", "organisms-resistance", "dose-duration", "pk-renal", "selection-evidence", "pulmonary-hepatic", "neuro-hematologic-populations", "interactions-counseling"];

const diagrams = {
  "structure-mechanism": ["Reactive mechanism", "Follow bacterial reduction into multi-target injury", ["Enter", "Nitrofuran", "The intact drug reaches the bacterial cell."], ["Reduce", "Flavoproteins", "Bacterial enzymes generate reactive intermediates."], ["Damage", "Macromolecules", "Ribosomes, nucleic acids, energy pathways, and cell-wall synthesis are altered."], ["Kill", "Urine", "Therapeutic urinary exposure produces bactericidal activity."]],
  "formulations-release": ["Product architecture", "Same active moiety, different release and schedule", ["Macrobid", "25 plus 75 mg", "Macrocrystals and monohydrate total 100 mg."], ["Gel", "Monohydrate", "A matrix supports release across the gastrointestinal tract."], ["Macrodantin", "Macrocrystals", "Controlled crystal size slows absorption."], ["Administer", "With food", "Exposure and gastrointestinal tolerance improve."]],
  "cystitis-phenotype": ["Compartment gate", "Use urine exposure only when infection stays in the bladder", ["Confirm", "Dysuria and urgency", "Lower-tract symptoms establish the syndrome."], ["Exclude", "Fever or flank pain", "Kidney involvement needs tissue-active therapy."], ["Consider", "Prostate or blood", "Low systemic exposure does not cover these sites."], ["Decide", "Treatment indication", "A positive urine result alone is insufficient."]],
  "organisms-resistance": ["Evidence ladder", "Move from species to susceptibility to clinical support", ["Anchor", "E. coli", "Clinical label evidence supports susceptible infection."], ["Include", "S. saprophyticus", "The label establishes uncomplicated urinary use."], ["Separate", "In vitro list", "Possible activity is not proven clinical efficacy."], ["Apply", "ESBL uUTI", "Current guidance retains a preferred bladder role."]],
  "dose-duration": ["Regimen reconciliation", "Make formulation, evidence source, and quantity agree", ["Practice", "Five days", "Macrobid 100 mg twice daily requires 10 capsules."], ["Label", "Seven days", "The printed Macrobid course requires 14 capsules."], ["Macrocrystals", "Four times daily", "Macrodantin uses a separate schedule."], ["Review", "Long-term use", "Suppression magnifies serious toxicity risk."]],
  "pk-renal": ["Exposure balance", "Kidney function drives urinary delivery and systemic risk", ["Absorb", "Food", "Macrobid bioavailability rises about 40 percent."], ["Circulate", "Low plasma", "Peak concentrations are usually below 1 mcg/mL."], ["Deliver", "Urine", "Unchanged active drug reaches the bladder."], ["Reconcile", "60 versus 30", "Label and Beers thresholds answer different questions."]],
  "selection-evidence": ["Clinical decision", "Keep resistant-organism evidence inside the right compartment", ["Classify", "uUTI", "Confirm bladder-confined infection."], ["Review", "Prior cultures", "Estimate the likelihood of active therapy."], ["Compare", "Preferred options", "Nitrofurantoin is one of several current choices."], ["Escalate", "Failure or invasion", "Use broader tissue exposure when the syndrome changes."]],
  "pulmonary-hepatic": ["Toxicity timeline", "Let onset and exposure duration accelerate recognition", ["First week", "Acute lung", "Fever, dyspnea, infiltrates, and eosinophilia can appear."], ["Six months", "Chronic lung", "Cough and progressive fibrosis can develop insidiously."], ["Any course", "Liver", "Hepatitis or cholestatic injury requires withdrawal."], ["Act", "Stop exposure", "Delayed recognition can leave permanent injury."]],
  "neuro-hematologic-populations": ["Population risk map", "Connect host biology to neurologic and red-cell injury", ["Nerves", "Neuropathy", "Renal and metabolic conditions increase risk."], ["Red cells", "G6PD", "Oxidative stress can precipitate hemolysis."], ["Pregnancy", "Avoid at term", "Neonatal hemolysis risk drives the restriction."], ["Lactation", "Infant context", "Age and G6PD status shape the decision."]],
  "interactions-counseling": ["Closed-loop use", "Turn one prescription into an executable and monitored course", ["Remove", "Magnesium trisilicate", "Adsorption can reduce absorption."], ["Avoid", "Probenecid", "Serum rises while urinary delivery falls."], ["Explain", "Brown urine", "Expected color is usually harmless."], ["Close", "Response plan", "Worsening or nonresponse triggers reassessment."]],
};

export default function NitrofurantoinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual nitrofurantoin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
