const diagrams = {
  "bone-remodeling": ["Remodeling cycle", "Bone strength emerges from a balanced renewal system", ["Resorb", "Osteoclast", "Acid and enzymes remove a packet of mineralized matrix"], ["Rebuild", "Osteoblast", "New osteoid fills the site and mineralizes over time"], ["Coordinate", "Osteocyte", "Mechanical sensing and signaling tune both sides of the cycle"]],
  "mineral-homeostasis": ["Mineral control network", "A defended serum pool connects intestine, kidney, and skeleton", ["Absorb", "Calcitriol", "Liver and kidney activation helps the intestine absorb calcium and phosphate"], ["Defend", "Parathyroid hormone", "Conserve calcium, release phosphate, and mobilize mineral when the ionized pool falls"], ["Signal", "RANKL and sclerostin", "Coordinate osteoclast development and the balance between formation and resorption"]],
  "risk-screening": ["Detection pathway", "Move from population screening to diagnostic care", ["Screen", "Age and menopausal risk", "Use current recommendations for people without known disease"], ["Assess", "Clinical risk", "Fractures, medicines, diseases, falls, and family history change urgency"], ["Diagnose", "Suspected fragility", "A sentinel fracture or secondary cause moves beyond routine screening"]],
  "dxa-frax": ["Measurement map", "Density, probability, and history answer different questions", ["Measure", "DXA", "Confirm site, score, artifact, and least significant change"], ["Estimate", "FRAX", "Calculate ten-year hip and major osteoporotic fracture probability"], ["Integrate", "Clinical judgment", "Add fracture recency, falls, multiplicity, and secondary causes"]],
  "prevention-foundations": ["Prevention system", "Reduce both skeletal weakness and the chance of impact", ["Supply", "Calcium and vitamin D", "Fill nutritional gaps and correct measured deficiency"], ["Strengthen", "Muscle and balance", "Progress resistance, weight-bearing activity, and safe movement"], ["Protect", "Environment and medicines", "Correct hazards, vision, orthostasis, footwear, and sedative burden"]],
  "treatment-framework": ["Therapy sequence", "The first choice determines the next transition", ["High risk", "Antiresorptive", "Use a supported oral, intravenous, or biologic option that can be sustained"], ["Very-high risk", "Build first", "Consider anabolic or sclerostin therapy when the expected benefit justifies it"], ["Preserve", "Follow-on therapy", "Maintain gains and prevent rebound with a planned antiresorptive"]],
  "bisphosphonates": ["Mineral affinity", "Bind bone, suppress resorption, and retain effect", ["Absorb", "Oral technique", "Plain water, fasting separation, and upright posture protect exposure and safety"], ["Infuse", "Renal gate", "Check calcium, hydration, creatinine clearance, and infusion duration"], ["Reassess", "Duration and risk", "Continue, change, or consider a monitored holiday after a full risk review"]],
  "denosumab": ["RANKL control", "Potent suppression requires schedule continuity", ["Block", "RANKL", "Prevent osteoclast formation, function, and survival"], ["Monitor", "Calcium and CKD-MBD", "Advanced kidney disease can turn hypocalcemia into a life-threatening event"], ["Transition", "No unprotected stop", "Use subsequent antiresorptive therapy before rebound accelerates remodeling"]],
  "bone-forming-therapy": ["Formation strategy", "Build rapidly, then preserve deliberately", ["PTH1", "Teriparatide or abaloparatide", "Intermittent receptor signaling produces a net formative response"], ["Sclerostin", "Romosozumab", "Increase formation and decrease resorption during a fixed twelve-dose course"], ["Maintain", "Antiresorptive", "Protect new bone after the formation window closes"]],
  "selective-options": ["Narrower roles", "Match the specific benefit to the specific patient", ["SERM", "Raloxifene", "Vertebral protection and breast-risk reduction with thrombotic limits"], ["Hormone", "Estrogen-containing therapy", "Integrate symptom goals, uterus, route, age, and vascular and cancer history"], ["Reserve", "Calcitonin", "Use only when better-supported alternatives are unsuitable"]],
  "longitudinal-care": ["Care loop", "Protection is maintained through reassessment and transitions", ["Observe", "Fracture and function", "Track falls, height, pain, mobility, adherence, and treatment burden"], ["Measure", "BMD and safety", "Use comparable DXA plus product-specific laboratory and clinical monitoring"], ["Adapt", "Next treatment state", "Continue, pause, switch, or sequence without leaving risk unprotected"]],
};

export default function OsteoporosisVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
