const diagrams = {
  "parenteral-target-map": { eyebrow: "Targets and dependence", title: "Parenteral anticoagulants differ by antithrombin dependence, factor selectivity, route, clearance, monitoring, and reversibility.", accent: "#bc765f", columns: [["UFH", "Antithrombin dependent", "Inhibits thrombin and factor Xa"], ["LMWH", "Antithrombin dependent", "Greater anti-Xa activity"], ["Fondaparinux", "Antithrombin dependent", "Selective factor Xa inhibition"], ["Direct inhibitors", "Antithrombin independent", "Argatroban and bivalirudin inhibit thrombin"]] },
  "parenteral-ufh": { eyebrow: "Unfractionated heparin", title: "UFH combines rapid titration and short persistence with variable binding, laboratory surveillance, concentration risk, and HIT potential.", accent: "#8e9eb4", columns: [["Verify", "Indication and concentration", "Separate treatment from flush products"], ["Initiate", "Weight-based protocol", "Use the correct route and bolus"], ["Measure", "aPTT or anti-Xa", "Account for assay discordance"], ["Respond", "Bleeding, resistance, or HIT", "Reassess before escalating"]] },
  "parenteral-lmwh": { eyebrow: "Low molecular weight heparins", title: "LMWH provides more predictable subcutaneous exposure, but kidney function, body size, pregnancy, neuraxial timing, and indication still matter.", accent: "#86a57f", columns: [["Select", "Agent and indication", "Prophylaxis is not treatment"], ["Calculate", "Weight and renal function", "Avoid unexamined dose caps"], ["Administer", "Subcutaneous technique", "Keep the air bubble when instructed"], ["Monitor", "CBC, kidney, bleeding", "Use anti-Xa selectively"]] },
  "parenteral-fondaparinux": { eyebrow: "Fondaparinux", title: "Fondaparinux selectively enhances antithrombin inhibition of factor Xa and uses fixed prophylaxis or weight-tiered treatment dosing.", accent: "#aa8bba", columns: [["Target", "Factor Xa through antithrombin", "No direct thrombin inhibition"], ["Dose", "Indication and body weight", "Treatment uses weight tiers"], ["Clear", "Predominantly renal", "Avoid severe renal impairment"], ["Protect", "Neuraxial and bleeding safety", "No routine protamine reversal"]] },
  "parenteral-dti": { eyebrow: "Parenteral direct thrombin inhibitors", title: "Argatroban and bivalirudin inhibit thrombin without antithrombin and occupy distinct HIT, PCI, hepatic, renal, and transition pathways.", accent: "#c19764", columns: [["Argatroban", "HIT and PCI pathways", "Hepatic clearance and INR effect"], ["Bivalirudin", "PCI including HIT", "Renal adjustment and ACT"], ["Monitor", "aPTT or ACT by use", "Interpret with clinical context"], ["Transition", "Restore durable therapy", "Avoid unprotected gaps"]] },
  "parenteral-critical-safety": { eyebrow: "Critical safety", title: "Bleeding, neuraxial hematoma, HIT, protamine reactions, organ dysfunction, and transition errors require explicit prevention and response plans.", accent: "#c07070", columns: [["Bleeding", "Stabilize and control source", "Stop or reverse when appropriate"], ["HIT", "Use 4Ts before testing", "Stop all heparin and start nonheparin therapy"], ["Neuraxial", "Coordinate dose and catheter timing", "Monitor neurologic symptoms"], ["Transition", "Document last and next dose", "Protect against thrombosis gaps"]] },
};

export default function ParenteralAnticoagulantsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
