const diagrams = {
  "pud-defense": { eyebrow: "Mucosal balance", title: "Ulceration begins when injury outruns defense and repair", accent: "#cc7c65", columns: [["Challenge", "Acid, pepsin, H. pylori", "Luminal chemistry and inflammation create the damaging pressure."], ["Defense", "Mucus, bicarbonate, perfusion", "Prostaglandin-supported protection limits back-diffusion and sustains repair."], ["Failure", "Defect extends in depth", "Persistent imbalance crosses the muscularis mucosae and becomes an ulcer."]] },
  "pud-triage": { eyebrow: "Clinical triage", title: "The complication determines how quickly the pathway must move", accent: "#d06658", columns: [["Uncomplicated", "Stable dyspepsia", "Assess cause and testing strategy without inferring location from pain timing."], ["Concerning", "Anemia, weight loss, vomiting", "Escalate evaluation for bleeding, obstruction, or malignant disease."], ["Emergent", "Shock or peritoneal signs", "Resuscitate and obtain urgent endoscopic or surgical evaluation."]] },
  "pud-cause": { eyebrow: "Cause audit", title: "Do not call an ulcer idiopathic until the common drivers are truly excluded", accent: "#c79764", columns: [["Infection", "Active H. pylori", "Verify the method, preparation, and timing of every negative test."], ["Exposure", "NSAID and aspirin", "Count prescriptions, over-the-counter products, and interacting antithrombotics."], ["Expand", "Atypical disease", "Consider malignancy, hypersecretion, ischemia, infection, and inflammatory disease."]] },
  "pud-testing": { eyebrow: "Active-infection testing", title: "The right assay can still fail when preparation is wrong", accent: "#72a6ae", columns: [["Select", "Breath, stool, or biopsy", "Use a test that detects active infection and fits the clinical setting."], ["Prepare", "Hold suppressive therapy", "PPIs and PCABs need two weeks; bismuth and antibiotics need four weeks."], ["Confirm", "Universal test of cure", "Test every treated patient at least four weeks after eradication therapy."]] },
  "pud-bqt": { eyebrow: "First-line eradication", title: "Four components, fourteen days, one executable schedule", accent: "#c38fba", columns: [["Suppress", "PPI twice daily", "Sustain an intragastric environment that supports antibiotic activity."], ["Combine", "Bismuth plus two antibiotics", "Use bismuth four times daily, tetracycline four times daily, and metronidazole three or four times daily."], ["Complete", "Fourteen days", "Design timing, interaction, food, water, and adverse-effect counseling before the first dose."]] },
  "pud-alternatives": { eyebrow: "Regimen sequencing", title: "Previous therapy becomes the map for the next therapy", accent: "#8b8fc2", columns: [["Treatment-naive", "BQT or supported alternative", "Rifabutin triple or vonoprazan-amoxicillin dual therapy can fit selected patients."], ["After BQT", "Rifabutin triple", "Use a 14-day empiric salvage path when penicillin is safe."], ["Resistance-sensitive", "Clarithromycin or levofloxacin", "Require demonstrated susceptibility instead of another empiric guess."]] },
  "pud-confirmation": { eyebrow: "Eradication loop", title: "Treatment is unfinished until active infection is shown to be gone", accent: "#80a57d", columns: [["Schedule", "Test at prescribing", "Give the future date and medication-hold instructions before therapy begins."], ["Audit", "Execution and exposure", "Reconstruct every dose, adverse effect, interaction, and prior antibiotic."], ["Adapt", "Salvage with evidence", "Use treatment history, susceptibility, and allergy evaluation to preserve options."]] },
  "pud-healing": { eyebrow: "Mucosal repair", title: "Every medicine needs a defined job in the healing plan", accent: "#d0a35f", columns: [["Suppress", "PPI", "Support clot stability and epithelial repair while the cause is removed."], ["Coat", "Sucralfate", "Create a local protective complex with an empty-stomach and interaction plan."], ["Protect", "Bismuth", "Add local protection and antibacterial activity while distinguishing discoloration from bleeding."]] },
  "pud-nsaid": { eyebrow: "Risk engineering", title: "Reduce exposure, choose the anti-inflammatory, then add protection", accent: "#c27d67", columns: [["Assess", "GI and cardiovascular risk", "Use ulcer history, age, dose, combinations, comorbidity, and cardiovascular need."], ["Reduce", "Dose and duplication", "Choose the lowest effective exposure and remove avoidable over-the-counter use."], ["Protect", "PPI or selected misoprostol", "Match protection to the duration and severity of the remaining risk."]] },
  "pud-complications": { eyebrow: "Bleeding sequence", title: "Stabilize, control the lesion, protect the clot, prevent recurrence", accent: "#bf5d54", columns: [["Stabilize", "Resuscitation and risk", "Use hemodynamics, laboratories, comorbidity, and validated scoring."], ["Control", "Endoscopic hemostasis", "Treat active bleeding and visible vessels, then use high-dose PPI for three days."], ["Prevent", "Cause correction", "Eradicate H. pylori, revise ulcerogenic drugs, and protect necessary therapies."]] },
};

export default function PepticUlcerDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
