export const perioperativeAntimicrobialProphylaxisVisualTypes = ["prevention-model", "procedure-pathogens", "timing-exposure", "dose-redose", "cefazolin-firstline", "allergy-assessment", "mrsa-decolonization", "colorectal-special", "duration-stewardship", "implementation-monitoring"].map((type) => `perioperative-${type}`);

const diagrams = {
  "prevention-model": ["Operative window", "Protect the incision from first cut through closure", ["Before", "Prepare", "Define the procedure, host, organisms, and prevention bundle."], ["Incision", "Expose", "Reach effective tissue concentration before contamination."], ["Operation", "Maintain", "Redose when time or blood loss threatens exposure."], ["Closure", "Stop", "End prophylaxis unless a treatment diagnosis exists."]],
  "procedure-pathogens": ["Selection map", "Let the operative field define the spectrum", ["Skin", "Gram positive", "Cefazolin centers susceptible staphylococci and streptococci."], ["Colon", "Mixed flora", "Add aerobic gram-negative and anaerobic coverage."], ["Implant", "Biofilm risk", "Preserve strong antistaphylococcal prevention."], ["Local data", "Refine", "Use procedure-specific surveillance, not vague fear."]],
  "timing-exposure": ["Time architecture", "Work backward from incision and forward to closure", ["Standard", "Within 60 minutes", "Most agents begin close enough to incision for useful exposure."], ["Long infusion", "Within 120 minutes", "Vancomycin and fluoroquinolones need more time."], ["Tourniquet", "Before inflation", "Deliver drug before blood flow is isolated."], ["Delay", "Recalculate", "A changed incision time can require a new plan."]],
  "dose-redose": ["Exposure controls", "Dose the patient, then protect the concentration", ["Weight", "2 g or 3 g", "Cefazolin commonly increases at 120 kg."], ["Clock", "Four hours", "Redose cefazolin from the first administration time."], ["Volume", "Major blood loss", "Loss of circulating drug can trigger an early redose."], ["Rate", "10 mg/min", "Vancomycin dose determines its minimum infusion time."]],
  "cefazolin-firstline": ["First-line logic", "Focused spectrum usually beats reflexive breadth", ["Default", "Cefazolin", "Reliable susceptible skin-flora coverage for many procedures."], ["Extend", "By anatomy", "Add coverage only for organisms the field introduces."], ["Reconcile", "Active treatment", "Avoid both procedural gaps and duplicate exposure."], ["Compare", "Label and guidance", "Expose conflicts and follow governed evidence."]],
  "allergy-assessment": ["Allergy pathway", "Turn a label into a defensible phenotype", ["Name", "Culprit", "Identify the exact drug and later tolerated agents."], ["Time", "Latency", "Immediate and delayed patterns imply different risks."], ["Describe", "Phenotype", "Separate intolerance, urticaria, anaphylaxis, and SCAR."], ["Decide", "Protocol", "Preserve cefazolin when the evaluated risk permits."]],
  "mrsa-decolonization": ["MRSA pathway", "Use targeted coverage inside a complete bundle", ["Detect", "Colonization", "A current screen can identify a high-risk reservoir."], ["Reduce", "Nose and skin", "Pair an antistaphylococcal nasal agent with antisepsis."], ["Cover", "Procedure", "Vancomycin does not replace every other spectrum need."], ["Monitor", "Resistance", "Track adherence, outcomes, tolerance, and selection."]],
  "colorectal-special": ["Colorectal bundle", "Coordinate oral, parenteral, and mechanical preparation", ["Lower", "Bowel burden", "Oral antibiotics act before the operative exposure."], ["Prepare", "Mechanical", "Preparation supports the combined pathway."], ["Protect", "Incision", "Parenteral prophylaxis remains necessary."], ["Adapt", "Actual field", "Unexpected contamination can create a treatment diagnosis."]],
  "duration-stewardship": ["Stop logic", "Every dose after closure needs a new indication", ["Close", "End prophylaxis", "Current SSI guidance stops at incision closure."], ["Diagnose", "Treat if infected", "Purulence or perforation requires a treatment plan."], ["Remove", "Drain myth", "A device alone does not justify antibiotics."], ["Balance", "Prevent harm", "Avoid CDI, toxicity, resistance, and excess cost."]],
  "implementation-monitoring": ["Reliable system", "Convert policy into action at the bedside", ["Assign", "Ownership", "Name who verifies each decision and timestamp."], ["Pause", "Checklist", "Resolve discrepancies before incision."], ["Measure", "Process and outcome", "Track delivery, SSI, CDI, and adverse effects."], ["Learn", "Case review", "Improve the pathway with evidence, not reflexive breadth."]],
};

export default function PerioperativeAntimicrobialProphylaxisVisual({ type }) {
  const diagram = diagrams[type.replace("perioperative-", "")];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual perioperative-antimicrobial-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
