const diagrams = {
  "periop-stress-ulcer": { eyebrow: "Temporary prevention", title: "Risk starts the therapy, and risk resolution stops it", accent: "#d8a15f", columns: [["Assess", "Active risk", "Coagulopathy, shock, and chronic liver disease carry the clearest current signal."], ["Prevent", "PPI or H2RA", "Use a low-dose enteral or intravenous option when risk justifies exposure."], ["Stop", "Daily review", "Discontinue when risk resolves and avoid an unnecessary discharge medicine."]] },
  "periop-local-anesthetic": { eyebrow: "Regional pharmacology", title: "Membrane access and sodium-channel binding create local block", accent: "#74a7ba", columns: [["Cross", "Neutral fraction", "Uncharged drug moves through tissue and axonal membrane."], ["Bind", "Charged fraction", "Protonated drug reaches the intracellular sodium-channel site."], ["Contain", "Total exposure", "Dose, blood flow, organ function, and every local anesthetic shape systemic risk."]] },
  "periop-last": { eyebrow: "LAST rescue", title: "Stop exposure, protect physiology, and use lipid early", accent: "#e3b55e", columns: [["Stabilize", "Airway and seizure", "Prevent hypoxemia, hypercapnia, and acidosis while controlling seizure."], ["Rescue", "20 percent lipid", "Use the current ASRA weight-based bolus and infusion pathway."], ["Modify", "Not standard ACLS", "Use smaller epinephrine and avoid vasopressin and other aggravating drugs."]] },
  "periop-induction": { eyebrow: "Induction choice", title: "The patient's limiting physiology selects the hypnotic", accent: "#b995c8", columns: [["Propofol", "Rapid but depressant", "Fast hypnosis and recovery can cost pressure and ventilation."], ["Etomidate", "Pressure with endocrine cost", "Relative hemodynamic stability trades against myoclonus and adrenal suppression."], ["Ketamine", "Dissociation and analgesia", "Often stimulating, but not immune to apnea, emergence, or catecholamine-depleted collapse."]] },
  "periop-mh": { eyebrow: "Hypermetabolic crisis", title: "Treat the trajectory before temperature becomes the headline", accent: "#e26554", columns: [["Recognize", "Carbon dioxide and rigidity", "Early hypercapnia, tachycardia, acidosis, and muscle rigidity define the pattern."], ["Interrupt", "Triggers and dantrolene", "Stop volatile agents and succinylcholine, then give repeated actual-weight dantrolene."], ["Control", "Heat and metabolism", "Cool, correct potassium and acidosis, protect kidneys, and monitor recurrence."]] },
  "periop-nmb-foundations": { eyebrow: "Motor end plate", title: "Two routes to immobility, neither route to unconsciousness", accent: "#88a977", columns: [["Depolarize", "Succinylcholine", "Persistent end-plate activation produces phase I paralysis."], ["Compete", "Nondepolarizers", "Receptor antagonism prevents acetylcholine from generating contraction."], ["Protect", "Brain and breathing", "Sedation, analgesia, ventilation, and monitoring remain separate requirements."]] },
  "periop-succinylcholine": { eyebrow: "Rapid does not mean simple", title: "A brief drug can expose long and lethal vulnerabilities", accent: "#d06e66", columns: [["Screen", "Potassium risk", "Denervation, burns, immobility, myopathy, and injury can amplify potassium release."], ["Reserve", "Pediatric emergency", "The boxed warning limits routine pediatric convenience use."], ["Support", "Prolonged apnea", "Ventilate and maintain unconsciousness until objective recovery is complete."]] },
  "periop-nondepolarizing": { eyebrow: "Agent map", title: "Choose onset and duration together with the exit strategy", accent: "#6f9dac", columns: [["Rocuronium", "Fast aminosteroid", "Rapid intubation is followed by variable hepatobiliary and renal recovery."], ["Vecuronium", "Metabolite exposure", "Organ dysfunction and active metabolite can extend block."], ["Cisatracurium", "Hofmann elimination", "Organ-independent degradation is useful, but pH, temperature, and monitoring still matter."]] },
  "periop-nmb-safety": { eyebrow: "High-reliability paralysis", title: "Storage engineering and bedside protection must work together", accent: "#d7aa67", columns: [["Sequester", "Wrong-vial prevention", "Restrict access and use unmistakable paralyzing-agent warnings."], ["Verify", "Ventilation and consciousness", "Confirm mechanical support, analgesia, sedation, and indication before dosing."], ["Protect", "Whole patient", "Maintain eye, skin, thrombosis, positioning, temperature, and daily stop safeguards."]] },
  "periop-monitoring-reversal": { eyebrow: "Objective recovery", title: "Measured depth selects reversal and measured recovery permits extubation", accent: "#74a791", columns: [["Measure", "Quantitative TOF", "Use adductor-pollicis monitoring rather than strength tests or elapsed time."], ["Reverse", "Depth-specific", "Match sugammadex or neostigmine to the blocker and objective depth."], ["Confirm", "Ratio at least 0.9", "Do not extubate until quantitative recovery and airway readiness are established."]] },
  "periop-antifibrinolytic": { eyebrow: "Clot preservation", title: "Stabilize fibrin without losing route, renal, or thrombotic control", accent: "#cc7e6d", columns: [["Indicate", "Fibrinolytic bleeding", "Use the medicine only when clot breakdown is part of the problem."], ["Label", "Intravenous route", "Keep tranexamic acid physically and visually separated from neuraxial drugs."], ["Adjust", "Kidney and exposure", "Renal elimination makes dose and toxicity surveillance patient specific."]] },
};

export default function PerioperativeCriticalCareVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
