const diagrams = {
  "pad-spectrum": { eyebrow: "Clinical spectrum", title: "Peripheral arterial disease is one atherosclerotic process expressed across four clinical subsets, each with a different urgency, limb threat, and treatment goal.", accent: "#b87868", columns: [["Silent", "Asymptomatic PAD", "Risk persists without classic pain"], ["Effort", "Chronic symptomatic PAD", "Walking reveals flow limitation"], ["Threat", "Chronic limb-threatening ischemia", "Rest pain, wound, or gangrene"], ["Acute", "Acute limb ischemia", "Sudden perfusion loss threatens viability"]] },
  "pad-diagnosis": { eyebrow: "Physiologic diagnosis", title: "History and pulse examination create suspicion, while pressure, waveform, exercise, and tissue-perfusion tests establish and localize hemodynamic disease.", accent: "#839eb3", columns: [["Rest ABI", "Compare ankle with arm pressure", "Classify compressible vessels"], ["Exercise", "Unmask exertional pressure decline", "Evaluate normal resting ABI with symptoms"], ["Toe", "Bypass medial calcification", "Support CLTI assessment"], ["Image", "Map anatomy when it changes care", "Do not replace physiology by default"]] },
  "pad-risk-therapy": { eyebrow: "Cardiovascular and limb protection", title: "Treatment reduces both major cardiovascular events and major adverse limb events through antithrombotic selection and intensive risk-factor control.", accent: "#a58ab6", columns: [["Platelet", "Single antiplatelet therapy", "Symptomatic PAD foundation"], ["Dual path", "Rivaroxaban 2.5 mg twice daily plus aspirin", "Balance ischemia with bleeding"], ["Lipid", "High-intensity statin", "Aim for at least 50 percent LDL reduction"], ["Risk", "Pressure, diabetes, tobacco", "Treat the whole vascular patient"]] },
  "pad-function": { eyebrow: "Walking function", title: "Structured exercise, symptom pharmacotherapy, foot protection, and measured follow-up convert a vascular diagnosis into better daily function.", accent: "#8ca47c", columns: [["Exercise", "Planned frequency, intensity, time, and type", "Supervised or structured community program"], ["Cilostazol", "Improve walking distance", "Avoid in heart failure"], ["Foot", "Inspect skin, pressure, footwear, and wounds", "Prevent small injuries from becoming limb threats"], ["Measure", "Track walking and quality of life", "Symptoms alone can underestimate impairment"]] },
  "pad-revascularization": { eyebrow: "Restore flow for the right goal", title: "Revascularization is used to prevent limb loss in chronic limb-threatening ischemia and to improve function when claudication remains limiting despite medical therapy and exercise.", accent: "#c09b61", columns: [["Define", "Confirm anatomy and hemodynamic significance", "Match lesion to symptoms"], ["Choose", "Endovascular, surgical, or hybrid", "Consider durability and patient risk"], ["Protect", "Continue medical and exercise therapy", "Procedure does not cure atherosclerosis"], ["Follow", "Examine limb and investigate new symptoms", "Watch patency, wound, and function"]] },
  "pad-limb-emergency": { eyebrow: "Limb preservation", title: "Chronic tissue loss and sudden acute ischemia require rapid viability assessment, multidisciplinary action, perfusion restoration, wound care, and a plan for life after the procedure.", accent: "#bd7268", columns: [["CLTI", "Chronic rest pain, wound, or gangrene", "Stage wound, ischemia, and infection"], ["ALI", "Pain, pallor, pulse loss, coolness, sensory or motor change", "Determine viability immediately"], ["Flow", "Restore useful perfusion", "Target the threatened tissue"], ["Recovery", "Foot care, surveillance, rehabilitation", "Preserve a functional limb"]] },
};

export default function PeripheralArterialDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, mechanism, meaning], index) => <div key={name}>
      <span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{mechanism}</em><p>{meaning}</p>
    </div>)}</div>
  </figure>;
}
