const diagrams = {
  "pk-adme-map": { eyebrow: "Exposure framework", title: "A dose becomes a concentration, then a response", accent: "#d3a56f", columns: [["Input", "Absorption", "Route, formulation, dissolution, permeability, and first pass."], ["Body", "Distribution", "Perfusion, barriers, transporters, ionization, and binding."], ["Output", "Metabolism and excretion", "Enzymes, transporters, kidney, liver, and other routes."]] },
  "pk-bioavailability": { eyebrow: "Dose-normalized exposure", title: "Absolute bioavailability compares extravascular exposure with IV exposure", accent: "#d9bc83", columns: [["Measure", "AUC", "Systemic exposure over the sampled concentration-time curve."], ["Normalize", "AUC divided by dose", "Correct the comparison when doses are unequal."], ["Compare", "F = oral to IV", "Multiply the AUC ratio by the inverse dose ratio."]] },
  "pk-distribution": { eyebrow: "Apparent distribution", title: "Plasma concentration is one window into a larger body burden", accent: "#9eb5b8", columns: [["Bind", "Total versus unbound", "Albumin and other proteins alter the measured fractions."], ["Partition", "Plasma to tissue", "Perfusion, permeability, ionization, and transport shape movement."], ["Relate", "Vd = amount divided by concentration", "A proportional volume, not an anatomic container."]] },
  "pk-metabolism": { eyebrow: "Biotransformation network", title: "Enzymes and transporters reshape exposure before and after circulation", accent: "#9ead82", columns: [["Transform", "Phase I", "Oxidation, reduction, or hydrolysis can activate or inactivate."], ["Conjugate", "Phase II", "Conjugation can occur directly and does not guarantee inactivity."], ["Move", "Transporters", "Uptake and efflux alter absorption, tissue access, and clearance."]] },
  "pk-clearance": { eyebrow: "Elimination capacity", title: "Clearance converts concentration into elimination rate", accent: "#8facbe", columns: [["Kidney", "Filter, secrete, reabsorb", "Function, binding, flow, pH, and transporters matter."], ["Liver", "Flow and capacity", "Blood flow, unbound fraction, enzymes, and transporters interact."], ["Total", "Cl = rate divided by concentration", "Independent organ clearances can contribute to the whole."]] },
  "pk-saturation": { eyebrow: "Linear and nonlinear kinetics", title: "A constant fraction can become a capacity-limited amount", accent: "#c88872", columns: [["Linear", "First order", "A constant fraction is removed during each equal interval."], ["Capacity", "Vmax and Km", "Elimination approaches a ceiling as concentration rises."], ["Consequence", "Disproportionate exposure", "Small dose changes can produce large concentration changes."]] },
  "pk-decay": { eyebrow: "Concentration prediction", title: "The elimination slope connects clearance, volume, time, and concentration", accent: "#a5a1c3", columns: [["Derive", "ke = Cl divided by Vd", "The elimination rate constant has units of inverse time."], ["Predict", "C2 = C1 times e to negative ke t", "Use post-distribution levels under stable linear conditions."], ["Estimate", "ke = ln(C1 divided by C2) divided by t", "Actual sample times define the log-linear slope."]] },
  "pk-half-life": { eyebrow: "Time constant", title: "Half-life links washout, accumulation, and steady state", accent: "#c4a676", columns: [["Half-life", "0.693 divided by ke", "Also 0.693 times Vd divided by clearance."], ["Accumulate", "Repeated input", "Linear exposure approaches steady state over successive half-lives."], ["Wash out", "Stop input", "About 3 percent remains after five linear half-lives."]] },
  "pk-dosing": { eyebrow: "Dose architecture", title: "Loading fills the distribution space. Maintenance replaces clearance.", accent: "#d29d72", columns: [["Load", "Target times Vd divided by F", "Approach a target concentration without changing half-life."], ["Maintain", "Target Css times Cl divided by F", "Replace average elimination over time."], ["Shape", "Dose and interval", "Control average exposure and peak-trough fluctuation."]] },
  "pk-tdm": { eyebrow: "Measurement to decision", title: "A drug level is useful only when its place on the curve is known", accent: "#88aaa5", columns: [["Question", "Why measure", "Efficacy, toxicity, adherence, interaction, or changing clearance."], ["Context", "When measured", "Dose history, draw time, distribution, and steady state."], ["Decision", "What changes", "Integrate concentration with response, safety, and patient goals."]] },
};

export default function PharmacokineticsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual pharmacokinetics-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
