const diagrams = {
  "pgx-foundations": { eyebrow: "Genetic vocabulary", title: "Sequence becomes useful only after context and function are established", accent: "#d5a978", columns: [["Sequence", "Variant and allele", "Identify what differs and whether the assay can resolve it."], ["Inheritance", "Haplotype and diplotype", "Place variants on each chromosome before assigning function."], ["Meaning", "Genotype to phenotype", "Translate inherited structure into gene-specific activity."]] },
  "pgx-translation": { eyebrow: "Functional translation", title: "A stable genotype meets a changing medication environment", accent: "#b99ac6", columns: [["Inherited", "Star alleles and copy number", "Define the functional alleles carried by the patient."], ["Predicted", "Activity score and phenotype", "Apply the current gene-specific translation model."], ["Observed", "Phenoconversion", "Add inhibitors, inducers, disease, and organ function."]] },
  "pgx-evidence": { eyebrow: "Evidence architecture", title: "Each source answers a different medication question", accent: "#86abb5", columns: [["Regulatory", "FDA label and table", "Read requirements, associations, and explicit limitations."], ["Implementation", "CPIC and other guidance", "Translate an available result in the correct indication."], ["Essential test", "Companion diagnostic", "Match biomarker, assay, specimen, and therapeutic label."]] },
  "pgx-hla": { eyebrow: "Immune-risk prevention", title: "The allele can change selection, but the patient still requires vigilance", accent: "#d17d70", columns: [["Abacavir", "HLA-B*57:01", "Avoid if positive and never rechallenge after suspected hypersensitivity."], ["Allopurinol", "HLA-B*58:01", "Avoid if positive because severe-cutaneous-reaction risk is high."], ["Antiseizure", "HLA-B*15:02 and HLA-A*31:01", "Apply the drug and allele-specific risk pathway."]] },
  "pgx-cyp2d6": { eyebrow: "Prodrug activation", title: "Too little activation loses benefit. Too much can amplify toxicity.", accent: "#ce9871", columns: [["Poor", "Low active metabolite", "Codeine or tramadol may provide inadequate opioid effect."], ["Normal", "Expected genetic activity", "Check inhibitors because phenotype can still convert."], ["Ultrarapid", "Excess active metabolite", "Avoid activation-dependent opioids when toxicity risk rises."]] },
  "pgx-clopidogrel": { eyebrow: "Antiplatelet activation", title: "The same CYP2C19 result carries different weight across indications", accent: "#c97c84", columns: [["Pathway", "Clopidogrel activation", "Loss-of-function alleles reduce active metabolite formation."], ["Strong context", "ACS and PCI", "Use an alternative in reduced-function phenotypes when appropriate."], ["Different context", "Neurovascular disease", "Apply the indication-specific evidence and contraindications."]] },
  "pgx-antiseizure": { eyebrow: "Two independent hazards", title: "Metabolism guides exposure. HLA guides severe immune risk.", accent: "#9b9bc6", columns: [["Exposure", "CYP2C9", "Reduced function can require a lower phenytoin maintenance start."], ["Immune risk", "HLA-B*15:02", "A positive result can change antiseizure-drug selection."], ["Follow-up", "Levels and symptoms", "Nonlinear kinetics and binding still govern adjustment."]] },
  "pgx-antimetabolites": { eyebrow: "Toxicity prevention", title: "Partial and complete deficiency require different starting strategies", accent: "#78a897", columns: [["Thiopurines", "TPMT plus NUDT15", "Combine both pathways before choosing a starting dose."], ["Fluoropyrimidines", "DPYD and DPD activity", "Distinguish intermediate from poor metabolism."], ["Reality check", "CBC and toxicity monitoring", "Genotype-guided dosing never replaces surveillance."]] },
  "pgx-multigene": { eyebrow: "Integrated dosing", title: "Algorithms begin the plan. Measured response completes it.", accent: "#c2a468", columns: [["Warfarin", "CYP2C9, VKORC1, CYP4F2", "Combine genotype with clinical variables for initiation."], ["Statins", "SLCO1B1", "Match transporter function to drug, dose, and treatment goal."], ["Response", "INR and toxicity", "Let observed benefit and harm guide ongoing therapy."]] },
  "pgx-oncology": { eyebrow: "Tumor precision", title: "A biomarker is meaningful only inside its disease and assay context", accent: "#b2877d", columns: [["Target", "HER2 and other drivers", "Identify a treatment-sensitive tumor state."], ["Resistance", "RAS and evolving clones", "Detect biology that can block expected benefit."], ["Gate", "Companion diagnostic", "Confirm the authorized specimen, assay, indication, and therapy."]] },
};

export default function PharmacogenomicsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual pharmacogenomics-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
