export const polymyxinPharmacologyVisualTypes = ["structure-mechanism", "agents-units", "spectrum-resistance", "susceptibility-selection", "site-evidence", "colistimethate-dosing", "polymyxin-b-dosing", "renal-electrolyte-safety", "neurologic-respiratory-safety", "integration"];

const diagrams = {
  "structure-mechanism": ["Membrane sequence", "A cationic ring breaks the gram-negative outer-membrane architecture", ["Attract", "Negative lipid A", "The charged peptide approaches the lipopolysaccharide surface."], ["Displace", "Calcium and magnesium", "Stabilizing ionic bridges leave the outer membrane."], ["Insert", "Fatty acyl tail", "The amphipathic scaffold disrupts the barrier."], ["Leak", "Cellular contents", "Permeability failure produces bacterial death."]],
  "agents-units": ["Identity control", "Two agents require distinct names, forms, strengths, and conversions", ["Name", "Colistimethate sodium", "An inactive prodrug that forms active colistin."], ["Read", "150 mg CBA", "The current United States vial displays colistin base activity."], ["Name", "Polymyxin B", "Active drug supplied as 500,000 units per vial."], ["Convert", "10,000 units per mg", "This mass conversion belongs only to polymyxin B."]],
  "spectrum-resistance": ["Coverage boundary", "The outer-membrane target creates useful activity and decisive gaps", ["Consider", "Pseudomonas", "Use current organism and MIC data within a justified site."], ["Consider", "Acinetobacter", "Current guidance still places preferred agents ahead of polymyxins."], ["Exclude", "Proteus group", "Intrinsic resistance defeats a class-level shortcut."], ["Detect", "Lipid A change", "Chromosomal pathways and mcr genes can reduce binding."]],
  "susceptibility-selection": ["Unconventional MIC", "Current FDA categories contain no susceptible result", ["Report", "Intermediate", "An MIC at or below 2 mg/L uses this category."], ["Reject", "Resistant", "An MIC at or above 4 mg/L is resistant."], ["Omit", "Susceptible", "Available evidence does not support this category."], ["Verify", "Testing method", "Technical limitations make one number insufficient."]],
  "site-evidence": ["Agent and site", "Distribution determines which rescue role remains plausible", ["Form", "Colistin in urine", "Prodrug conversion can support a limited urinary role."], ["Avoid", "Polymyxin B for UTI", "Predominantly nonrenal clearance limits urinary exposure."], ["Question", "Lung exposure", "Intravenous epithelial lining-fluid activity is suboptimal."], ["Reserve", "Systemic polymyxin B", "Use only when safer active agents cannot be used."]],
  "colistimethate-dosing": ["CBA workflow", "Keep the daily dose, renal schedule, and preparation in one unit system", ["Calculate", "2.5 to 5 mg/kg/day", "Use CBA and divide the total into two to four doses."], ["Reduce", "Renal impairment", "Apply the exact current table or approved protocol."], ["Reconstitute", "2 mL sterile water", "The 150 mg CBA vial becomes 75 mg/mL."], ["Limit", "Final infusion to 24 h", "Fresh preparation has a shorter stability window."]],
  "polymyxin-b-dosing": ["Two-source order", "The label and consensus must remain visibly distinct", ["Read", "15,000 to 25,000 units/kg/day", "The label states a total daily range and ceiling."], ["Load", "2 to 2.5 mg/kg", "The endorsed consensus uses total body weight for severe infection."], ["Maintain", "1.25 to 1.5 mg/kg q12h", "Consensus maintenance is infused over one hour."], ["Escalate", "Renal conflict", "Label reduction and consensus nonadjustment require oversight."]],
  "renal-electrolyte-safety": ["Tubular surveillance", "Creatinine is only one view of polymyxin kidney injury", ["Trend", "Urine and creatinine", "Falling output or rising azotemia changes the exposure plan."], ["Measure", "Potassium and bicarbonate", "Hypokalemic alkalosis can reveal tubulopathy."], ["Measure", "Magnesium and calcium", "Renal wasting can occur with normal creatinine."], ["Remove", "Nephrotoxin burden", "Concurrent and recent exposures compound risk."]],
  "neurologic-respiratory-safety": ["Escalation path", "Early neurologic symptoms can precede respiratory paralysis", ["Notice", "Perioral tingling", "Treat paresthesia as an exposure signal."], ["Assess", "Ataxia and weakness", "Check progression, renal function, and interactions."], ["Review", "Anesthesia and paralytics", "Neuromuscular effects can combine dangerously."], ["Support", "Ventilation", "Hypoventilation or apnea is an emergency."]],
  "integration": ["Closed-loop rescue", "Make every benefit, risk, unit, and exit decision reconstructable", ["Define", "Infection and source", "Confirm organism, site, burden, and source action."], ["Justify", "Why alternatives fail", "Current preferred agents come before polymyxins."], ["Execute", "Exact agent and units", "Document dose source, vial, volume, infusion, and timing."], ["Exit", "Response or toxicity", "Write the conditions to narrow, replace, or stop."]],
};

export default function PolymyxinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual polymyxin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
