const diagrams = {
  "perinatal-vaccines": ["Maternal immunization", "Match the vaccine to the pregnancy", ["Review", "Product and prior doses", "Tdap and maternal RSV have different repeat-dose rules"], ["Time", "Gestational age and season", "Check the vaccine-specific window and local guidance"], ["Coordinate", "Parent and infant protection", "Document the maternal plan and infant RSV handoff"]],
  "perinatal-nutrition": ["Feeding nutrition", "Separate the parent and infant plans", ["Parent", "Diet plus supplements", "Assess energy, iodine and choline against total intake"], ["Infant", "Age and feeding pattern", "Plan vitamin D and iron with term status and growth in view"], ["Measure", "Dose divided by concentration", "Check elemental iron and IU per drop versus IU per mL"]],
  "perinatal-thyroid": ["Thyroid care", "Adjust to diagnosis, timing and laboratory results", ["Identify", "Overt or subclinical disease", "A standard increase does not fit every levothyroxine-treated patient"], ["Administer", "Protect consistent absorption", "Separate iron/calcium prenatal products by at least four hours"], ["Reassess", "Pregnancy and postpartum", "Monitor after treatment changes and revisit doses after delivery"]],
  "perinatal-infections": ["Infection decisions", "Site, susceptibility and pregnancy timing", ["Localize", "Bladder, kidney or vagina", "Fever and flank pain change the treatment setting and required tissue exposure"], ["Select", "Culture plus gestational context", "Check resistance, term restrictions and the exact product"], ["Prevent", "Food, soil and litter", "Toxoplasmosis prevention extends beyond avoiding the litter box"]],
  "perinatal-context": ["Decision frame", "Treat the condition, protect the pregnancy", ["Define", "Patient, condition, timing", "Confirm indication, exposure, gestational age, and clinical urgency"], ["Compare", "Treatment and no treatment", "Include maternal relapse, fetal effects, and baseline pregnancy risk"], ["Decide", "Shared monitored plan", "State evidence, uncertainty, goals, and follow-up"]],
  "perinatal-pk": ["Maternal pharmacokinetics", "Pregnancy changes exposure over time", ["Distribute", "More water and plasma", "Distribution volume can expand while albumin and total levels fall"], ["Clear", "Higher GFR and pathway shifts", "Renal clearance often rises while hepatic effects remain enzyme specific"], ["Reassess", "Physiology shifts postpartum", "A pregnancy-adjusted dose can become excessive postpartum"]],
  "perinatal-placenta": ["Placental interface", "Structure influences transfer, timing shapes effect", ["Molecule", "Size, charge, lipid solubility", "Protein binding and transport also influence fetal exposure"], ["Gradient", "Concentration and transport", "Concentrations, blood flow, metabolism and transport shape fetal exposure"], ["Window", "Developmental process", "Implantation, organogenesis, growth, and neonatal adaptation create distinct questions"]],
  "perinatal-skin-drug-exposure": ["Retinoids and Antiandrogen Exposure", "Identify the product and exposure route before selecting prevention, urgent action and follow-up.", ["Route", "Oral and topical risks differ", "Assess actual absorption and exposure"], ["Prevent", "Product-specific precautions", "Follow the active program and handling instructions"], ["Respond", "Stop exposure and assess", "Use drug-specific action and counseling"]],
  "perinatal-neurologic-drugs-pregnancy": ["Antiseizure and Migraine Drugs in Pregnancy", "Plan treatment before conception and coordinate changes with neurology and obstetric care.", ["Plan", "Syndrome and control", "Choose an appropriate regimen before conception"], ["Screen", "Exposure-specific fetal assessment", "Coordinate anatomy, cardiac or growth screening as indicated"], ["Monitor", "Concentrations and symptoms", "Reassess through pregnancy and postpartum"]],
  "perinatal-mental-health-pregnancy": ["Mental-Health Treatment During Pregnancy", "Balance fetal and newborn effects against relapse and withdrawal, with an explicit delivery and follow-up plan.", ["Compare", "Medication and untreated illness", "Include relapse, withdrawal and patient goals"], ["Coordinate", "Fetal and newborn assessment", "Match surveillance to the specific exposure"], ["Reassess", "Delivery and postpartum", "Plan dose changes and follow-up explicitly"]],
  "perinatal-cardiometabolic-drugs-pregnancy": ["Cardiometabolic Drugs and Pregnancy Planning", "Separate product-specific contraindications, selected specialist exceptions and changing program requirements.", ["Identify", "Exact drug and indication", "Weight loss, lipids and arrhythmia need different plans"], ["Prevent", "Product-specific contraception", "Check interactions and post-treatment intervals"], ["Update", "Label versus program status", "Separate REMS changes from clinical risk"]],
  "perinatal-immune-hematology-pregnancy": ["Immune and Hematology Drugs in Pregnancy", "Verify the treated person, indication, conception timing and product-specific testing or elimination requirements.", ["Clarify", "Patient and partner exposure", "Do not apply one reproductive rule to both roles"], ["Verify", "Testing and elimination", "Use the exact drug protocol and interval"], ["Coordinate", "Disease control and alternatives", "Selected specialist decisions do not prove fetal safety"]],
  "perinatal-reproductive-drugs-pregnancy": ["Hormones and Reproductive-Care Indications", "Distinguish intentional reproductive treatment from unintended exposure and unrelated hormone products.", ["Name", "Molecule and formulation", "Progesterone, megestrol and testosterone are different"], ["Match", "Clinical indication", "Separate reproductive protocols from other uses"], ["Protect", "Patient and household", "Prevent unintended exposure and skin transfer"]],
  "perinatal-evidence": ["Evidence stack", "Replace the letter with the evidence", ["Label", "FDA sections 8.1 to 8.3", "Read risk summary, clinical considerations, data, and reproductive potential"], ["Literature", "Registry and cohort evidence", "Assess comparator, timing, confounding, precision, and mechanism"], ["Explain", "Absolute clinical meaning", "Separate known findings from uncertainty and background risk"]],
  "perinatal-symptoms": ["Symptom pathway", "Triage before self-care", ["Screen", "Severity and red flags", "Assess hydration, weight, bleeding, pain, fever, and alternate diagnoses"], ["Treat", "Least burdensome effective step", "Use current pregnancy-compatible nonpharmacologic and medication options"], ["Follow", "Response and escalation", "Set a time to reassess and clear reasons to seek urgent care"]],
  "perinatal-diabetes": ["Glucose pathway", "Match treatment to the pattern", ["Measure", "Fasting and postmeal", "Interpret each reading against its time-specific target"], ["Treat", "Individualize medication", "For GDM, add insulin when needed; teach hypoglycemia care"], ["Continue", "Postpartum surveillance", "Reassess insulin after delivery; arrange OGTT and ongoing screening after GDM"]],
  "perinatal-preeclampsia": ["Hypertensive pathway", "Prevent, recognize, stabilize", ["Prevent", "Eligible risk profile", "Match aspirin dose and timing to the guideline and risk profile"], ["Recognize", "Pressure and organ findings", "Proteinuria is not required when qualifying severe features are present"], ["Stabilize", "Seizure and vascular risk", "Treat severe pressure, use magnesium when indicated, and coordinate delivery"]],
  "perinatal-vte": ["Anticoagulation timeline", "Plan from diagnosis through delivery", ["Select", "LMWH for most pregnancy VTE", "Match prevention or treatment intensity to risk and organ function"], ["Coordinate", "Delivery and neuraxial care", "Verify the exact dose-specific interruption interval and reversal options"], ["Restart", "Postpartum transition", "Balance bleeding, thrombosis, breastfeeding, duration, and follow-up"]],
  "perinatal-lactation-pk": ["Milk exposure", "Trace the dose from parent to infant", ["Enter", "Maternal plasma to milk", "Binding, ionization, lipid solubility, transport, and time affect concentration"], ["Consume", "Drug ingested through milk", "RID compares ingested doses; oral absorption and toxicity require separate assessment"], ["Clear", "Infant metabolism and excretion", "Prematurity, illness, and neonatal age can increase accumulation"]],
  "perinatal-lactation-care": ["Lactation care loop", "Treat the parent and watch the infant", ["Verify", "Label, LactMed, and evidence", "Avoid fixed class lists and use the exact product, dose, and duration"], ["Optimize", "Effective lower exposure plan", "Choose a suitable drug and formulation without relying on universal feed timing"], ["Monitor", "Infant, supply, and response", "Name observable signs, maternal goals, follow-up, and an escalation route"]],
};

export default function PregnancyLactationPharmacotherapyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
