const diagrams = {
  "perinatal-context": ["Decision frame", "Treat the condition, protect the pregnancy", ["Define", "Patient, condition, timing", "Confirm indication, exposure, gestational age, and clinical urgency"], ["Compare", "Treatment and no treatment", "Include maternal relapse, fetal effects, and baseline pregnancy risk"], ["Decide", "Shared monitored plan", "State evidence, uncertainty, goals, and follow-up"]],
  "perinatal-pk": ["Maternal pharmacokinetics", "Pregnancy changes exposure over time", ["Distribute", "More water and plasma", "Distribution volume can expand while albumin and total levels fall"], ["Clear", "Higher GFR and pathway shifts", "Renal clearance often rises while hepatic effects remain enzyme specific"], ["Reassess", "Delivery reverses physiology", "A pregnancy-adjusted dose can become excessive postpartum"]],
  "perinatal-placenta": ["Placental interface", "Structure influences transfer, timing shapes effect", ["Molecule", "Size, charge, lipid solubility", "Protein binding and transport also influence fetal exposure"], ["Gradient", "Maternal to fetal movement", "Dose, blood flow, metabolism, and placental physiology change the gradient"], ["Window", "Developmental process", "Implantation, organogenesis, growth, and neonatal adaptation create distinct questions"]],
  "perinatal-evidence": ["Evidence stack", "Replace the letter with the evidence", ["Label", "FDA sections 8.1 to 8.3", "Read risk summary, clinical considerations, data, and reproductive potential"], ["Literature", "Registry and cohort evidence", "Assess comparator, timing, confounding, precision, and mechanism"], ["Explain", "Absolute clinical meaning", "Separate known findings from uncertainty and background risk"]],
  "perinatal-symptoms": ["Symptom pathway", "Triage before self-care", ["Screen", "Severity and red flags", "Assess hydration, weight, bleeding, pain, fever, and alternate diagnoses"], ["Treat", "Least burdensome effective step", "Use current pregnancy-compatible nonpharmacologic and medication options"], ["Follow", "Response and escalation", "Set a time to reassess and clear reasons to seek urgent care"]],
  "perinatal-diabetes": ["Glucose pathway", "Match treatment to the pattern", ["Measure", "Fasting and postmeal", "Interpret each reading against its time-specific target"], ["Treat", "Nutrition, behavior, then insulin", "Use insulin when targets remain unmet and teach hypoglycemia care"], ["Continue", "Postpartum surveillance", "Reduce therapy as physiology changes and arrange OGTT plus lifelong screening"]],
  "perinatal-preeclampsia": ["Hypertensive pathway", "Prevent, recognize, stabilize", ["Prevent", "Eligible risk profile", "Use 81 mg aspirin in the recommended gestational window"], ["Recognize", "Pressure and organ findings", "Proteinuria is not required when qualifying severe features are present"], ["Stabilize", "Seizure and vascular risk", "Treat severe pressure, use magnesium when indicated, and coordinate delivery"]],
  "perinatal-vte": ["Anticoagulation timeline", "Plan from diagnosis through delivery", ["Select", "LMWH for most pregnancy VTE", "Match prevention or treatment intensity to risk and organ function"], ["Coordinate", "Delivery and neuraxial care", "Verify the exact dose-specific interruption interval and reversal options"], ["Restart", "Postpartum transition", "Balance bleeding, thrombosis, breastfeeding, duration, and follow-up"]],
  "perinatal-lactation-pk": ["Milk exposure", "Trace the dose from parent to infant", ["Enter", "Maternal plasma to milk", "Binding, ionization, lipid solubility, transport, and time affect concentration"], ["Consume", "Milk intake and oral absorption", "Relative infant dose estimates exposure but does not define toxicity"], ["Clear", "Infant metabolism and excretion", "Prematurity, illness, and neonatal age can increase accumulation"]],
  "perinatal-lactation-care": ["Lactation care loop", "Treat the parent and watch the infant", ["Verify", "Label, LactMed, and evidence", "Avoid fixed class lists and use the exact product, dose, and duration"], ["Optimize", "Effective lower exposure plan", "Choose a suitable drug and formulation without relying on universal feed timing"], ["Monitor", "Infant, supply, and response", "Name observable signs, maternal goals, follow-up, and an escalation route"]],
};

export default function PregnancyLactationPharmacotherapyVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
