const diagrams = {
  "psoriasis-axis": { eyebrow: "Inflammatory circuit", title: "Immune signals and keratinocytes sustain one another", accent: "#d27c67", columns: [["Initiate", "Activate innate immunity", "Dendritic and tissue signals establish an IL-23 rich inflammatory environment."], ["Amplify", "Drive type 17 signaling", "IL-17 and TNF activate keratinocytes and recruit additional immune cells."], ["Express", "Build the plaque", "Accelerated turnover, incomplete maturation, vessels, and inflammation create scale and erythema."]] },
  "psoriasis-phenotypes": { eyebrow: "Clinical phenotype", title: "Morphology, site, and systemic illness determine urgency", accent: "#d68f74", columns: [["Routine", "Map plaque and special sites", "Scalp, folds, nails, palms, soles, face, and genitals can change treatment and burden."], ["Investigate", "Recognize guttate triggers", "An abrupt small lesion eruption can follow infection without proving active infection remains."], ["Escalate", "Identify unstable disease", "Generalized pustules, erythroderma, fever, pain, or organ dysfunction require urgent care."]] },
  "psoriasis-severity": { eyebrow: "Multidimensional severity", title: "Extent is one measurement, not the verdict", accent: "#c6a06f", columns: [["Measure", "Record BSA and morphology", "Extent and global assessment establish a reproducible objective baseline."], ["Listen", "Quantify lived burden", "Pain, itch, sleep, function, intimacy, work, and treatment effort reveal hidden severity."], ["Screen", "Find joints and comorbidity", "Psoriatic arthritis, cardiometabolic risk, bowel disease, mood, and uveitis change care."]] },
  "psoriasis-topicals": { eyebrow: "Topical engineering", title: "Drug, potency, vehicle, site, and schedule form one prescription", accent: "#b58b72", columns: [["Deliver", "Match the vehicle", "Ointment, cream, solution, and foam solve different site and adherence problems."], ["Induce", "Control inflammation", "Corticosteroid potency and duration must fit plaque thickness and skin vulnerability."], ["Maintain", "Reduce steroid burden", "Vitamin D analogs, tazarotene, calcineurin inhibitors, and selected adjuncts support control."]] },
  "psoriasis-modern-topicals": { eyebrow: "Nonsteroidal topical therapy", title: "Modern mechanisms expand site and maintenance options", accent: "#88a98d", columns: [["AhR", "Use tapinarof in adults", "A thin layer once daily treats adult plaque psoriasis without topical corticosteroid exposure."], ["PDE4 cream", "Reach age two and older", "Roflumilast cream 0.3 percent supports once daily plaque treatment including folds."], ["PDE4 foam", "Treat scalp and body", "From age 12, foam improves hair bearing delivery with essential flammability counseling."]] },
  "psoriasis-phototherapy": { eyebrow: "Controlled light", title: "Wavelength, dose, exposure, and access define phototherapy", accent: "#c7ad62", columns: [["Widespread", "Use narrowband UVB", "Measured UVB can treat plaque or guttate disease without psoralen photosensitization."], ["Localized", "Target affected skin", "Excimer and targeted systems reduce exposure of uninvolved skin."], ["Complex", "Control PUVA risk", "Psoralen adds medication, eye, nausea, and cumulative carcinogenic constraints."]] },
  "psoriasis-orals": { eyebrow: "Oral systemic selection", title: "Speed, organ risk, reproduction, and monitoring separate the options", accent: "#9b92b8", columns: [["Conventional", "Balance speed and toxicity", "Methotrexate, cyclosporine, and acitretin require distinct organ and reproductive safeguards."], ["PDE4", "Use apremilast deliberately", "Titration, weight, mood, interactions, and renal function shape tolerability."], ["TYK2", "Target intracellular signaling", "Deucravacitinib provides once daily adult therapy with infection and vaccine boundaries."]] },
  "psoriasis-biologics": { eyebrow: "Biologic architecture", title: "The pathway must fit the skin, joints, bowel, and patient", accent: "#8e9fbd", columns: [["TNF and p40", "Use broad established pathways", "Joint evidence, infection, heart failure, demyelination, pregnancy, and access guide selection."], ["IL-17", "Control rapid type 17 signaling", "Skin and joint efficacy must be balanced against bowel disease, candidiasis, and product specific warnings."], ["IL-23 p19", "Interrupt pathway maintenance", "Long intervals and strong skin efficacy can be useful when the comorbidity profile fits."]] },
  "psoriasis-emergency": { eyebrow: "Systemic skin emergency", title: "Stabilization and phenotype specific therapy happen together", accent: "#c35f62", columns: [["Recognize", "Name instability", "Fever, pain, diffuse pustules, erythroderma, fluid loss, and organ change demand escalation."], ["Stabilize", "Protect the whole patient", "Temperature, circulation, fluids, electrolytes, infection, pain, and nutrition require active care."], ["Target", "Block IL-36 in GPP", "Spesolimab provides labeled intravenous flare and subcutaneous between flare pathways."]] },
  "psoriasis-longitudinal": { eyebrow: "Durable control", title: "Response, safety, usability, and life stage remain connected", accent: "#b9a27b", columns: [["Target", "Measure what matters", "Skin activity, special sites, symptoms, joints, function, and quality of life define response."], ["Protect", "Use drug specific safety", "Vaccines, infection, organs, mood, reproduction, and laboratory plans follow the exact treatment."], ["Adapt", "Switch for a named reason", "Efficacy, toxicity, access, preference, burden, and life changes justify deliberate transitions."]] },
};

export const psoriasisVisualTypes = Object.keys(diagrams);

export default function PsoriasisVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual psoriasis-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
