const diagrams = {
  "raynaud-recognition": { eyebrow: "Clinical pattern", title: "Color change is a vascular signal, not the diagnosis by itself", accent: "#7fa7c7", columns: [["Trigger", "Cold or emotional stress", "Digital vasoconstriction reduces perfusion and may produce pallor, cyanosis, pain, or numbness."], ["Recover", "Reperfusion follows", "Warmth can bring erythema, throbbing, swelling, and return of sensation."], ["Interpret", "Classify the pattern", "Age, symmetry, tissue injury, examination, medicines, and systemic clues separate primary from secondary disease."]] },
  "raynaud-mechanism": { eyebrow: "Vascular physiology", title: "Tone, structure, and blood flow determine tissue risk", accent: "#b78b9d", columns: [["Narrow", "Vasospasm", "Adrenergic and endothelial signals transiently constrict digital arteries and arterioles."], ["Obstruct", "Fixed vascular disease", "Structural injury, thrombosis, embolism, or atherosclerosis can reduce reserve beyond reversible spasm."], ["Injure", "Critical ischemia", "Sustained oxygen deficit can produce ulceration, infection, necrosis, and tissue loss."]] },
  "raynaud-evaluation": { eyebrow: "Diagnostic workup", title: "The workup follows the probability of secondary disease", accent: "#8fae91", columns: [["History", "Define the attacks", "Capture triggers, sequence, symmetry, duration, pain, ulcers, occupation, medicines, and systemic symptoms."], ["Examine", "Look beyond color", "Assess pulses, skin, nails, capillary changes, joints, connective tissue findings, and vascular asymmetry."], ["Test", "Answer a focused question", "Use nailfold capillaroscopy and targeted laboratory or vascular testing when the phenotype raises concern."]] },
  "raynaud-prevention": { eyebrow: "Attack prevention", title: "Protect heat, vessels, and daily function before adding medicine", accent: "#c4a86a", columns: [["Warm", "Reduce whole-body heat loss", "Layer clothing, protect hands and feet, prewarm environments, and rewarm gradually."], ["Remove", "Reduce vasoconstrictors", "Address nicotine, stimulants, decongestants, occupational vibration, and avoidable medication triggers."], ["Record", "Measure the burden", "Track frequency, duration, pain, function, ulcers, and trigger context to judge whether the plan works."]] },
  "raynaud-ccb": { eyebrow: "First oral strategy", title: "Dihydropyridine therapy balances perfusion against pressure", accent: "#d49c75", columns: [["Select", "Use a long-acting agent", "Nifedipine is the usual first-line choice for systemic-sclerosis-associated Raynaud; amlodipine is another practical option."], ["Titrate", "Follow benefit and tolerance", "Increase deliberately while monitoring attack burden, blood pressure, dizziness, headache, flushing, and edema."], ["Reassess", "Do not normalize injury", "Persistent ulcer, rest pain, or worsening ischemia requires escalation rather than routine dose cycling."]] },
  "raynaud-pde5": { eyebrow: "Oral escalation", title: "Amplifying cyclic GMP can improve flow and compound hypotension", accent: "#8ea4c5", columns: [["Amplify", "PDE5 inhibition", "Reduced cyclic GMP breakdown supports smooth-muscle relaxation and can reduce systemic-sclerosis Raynaud burden."], ["Reconcile", "Find every nitrate", "Organic nitrates and nitric oxide donors are contraindicated with sildenafil because profound hypotension can occur."], ["Monitor", "Protect the patient", "Assess pressure, headache, flushing, vision or hearing symptoms, interactions, and the reason for off-label use."]] },
  "raynaud-nitrates": { eyebrow: "Local vasodilation", title: "Topical nitrate exposure still belongs in the systemic medication record", accent: "#bf8f79", columns: [["Apply", "Use the prescribed site plan", "Topical nitroglycerin may target a severely affected digit, but absorption and headache remain clinically relevant."], ["Separate", "Never combine with PDE5 therapy", "A topical route does not remove the nitrate contraindication with sildenafil or another PDE5 inhibitor."], ["Teach", "Prevent transfer and error", "Clarify amount, location, timing, handwashing, blood-pressure symptoms, and what to do if pain worsens."]] },
  "raynaud-ischemia": { eyebrow: "Urgent pathway", title: "A threatened digit is not a routine outpatient color complaint", accent: "#c86f68", columns: [["Recognize", "Find threatened tissue", "Persistent pallor or cyanosis, severe rest pain, ulcer, infection, necrosis, or neurologic loss requires urgent action."], ["Restore", "Escalate perfusion", "Specialist care may use intravenous iloprost after oral therapy fails in severe systemic-sclerosis Raynaud."], ["Investigate", "Find the cause", "Evaluate thrombosis, embolism, vasculitis, infection, macrovascular obstruction, trauma, and systemic disease."]] },
  "raynaud-secondary": { eyebrow: "Secondary disease", title: "The finger can be the first visible sign of a systemic process", accent: "#a790ba", columns: [["Connective tissue", "Search the phenotype", "Systemic sclerosis, lupus, mixed connective tissue disease, inflammatory myopathy, and Sjogren syndrome can alter risk."], ["Exposure", "Review causes", "Medicines, nicotine, vibration, chemotherapy, hematologic disease, and vascular obstruction may provoke or worsen attacks."], ["Coordinate", "Treat more than color", "Organ screening and disease-specific care continue even when digital attacks improve."]] },
  "raynaud-longitudinal": { eyebrow: "Longitudinal care", title: "A useful record turns episodic attacks into a measurable treatment plan", accent: "#a9a47d", columns: [["Baseline", "Define severity", "Document frequency, duration, pain, function, ulcers, blood pressure, triggers, and secondary-disease context."], ["Response", "Measure meaningful change", "Follow fewer or shorter attacks, improved function, healing, tolerability, and reduced rescue use."], ["Escalate", "Preserve ownership", "Name who manages medication changes, wound care, rheumatology, vascular assessment, and urgent deterioration."]] },
};

export default function RaynaudPhenomenonVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual raynaud-phenomenon-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
