const diagrams={
"rrt-choice":{accent:"#a48d78",eyebrow:"Kidney failure life plan",title:"Need, choice, access, and future",columns:[["Need","Clinical indication","Symptoms or failed homeostasis"],["Choice","Feasible pathways","Transplant, home or center dialysis, conservative care"],["Future","Life plan","Access, residual function, transitions, and goals"]]},
"rrt-mechanics":{accent:"#7399a4",eyebrow:"Transport mechanics",title:"Move solute and water by different forces",columns:[["Diffuse","Concentration gradient","Small solute crosses a membrane"],["Convect","Solvent drag","Solute travels with filtered water"],["Ultrafilter","Pressure gradient","Net water leaves the circulation"]]},
"rrt-hd":{accent:"#7e9eaf",eyebrow:"Hemodialysis circuit",title:"Access to blood, membrane, dialysate, return",columns:[["Deliver","Blood flow","Access and pump bring solute to the membrane"],["Exchange","Dialyzer and bath","Composition, flow, area, and time determine transfer"],["Return","Tolerance","Fluid goal, pressure, anticoagulation, and recovery"]]},
"rrt-pd":{accent:"#b59a79",eyebrow:"Peritoneal exchange",title:"Drain, fill, dwell, and drain again",columns:[["Fill","Solution and volume","Glucose or icodextrin creates osmotic force"],["Dwell","Time and transport","Solute equilibrates as the gradient evolves"],["Drain","Measure delivery","Effluent, ultrafiltration, symptoms, and clearance"]]},
"rrt-continuous":{accent:"#7897a0",eyebrow:"Continuous and hybrid therapy",title:"Spread clearance and fluid balance across time",columns:[["Diffuse","Dialysate flow","CVVHD moves small solute down a gradient"],["Convect","Replacement fluid","CVVH carries solute with filtered plasma water"],["Combine","Delivered effluent","CVVHDF joins both modes and requires downtime audit"]]},
"rrt-safety":{accent:"#bb7069",eyebrow:"Access safety",title:"Inspect, recognize, culture, and control",columns:[["Vascular","Flow and infection","Thrill, bruit, pressure, bleeding, swelling, fever"],["Peritoneal","Catheter and effluent","Exit site, drainage, cloudy fluid, abdominal pain"],["Systemic","Treatment emergency","Hypotension, arrhythmia, hemolysis, air, disequilibrium"]]},
"rrt-longitudinal":{accent:"#9686ad",eyebrow:"Goal-directed care",title:"Prescription plus delivery plus lived outcome",columns:[["Dose","Native plus therapy","Clearance, timing, medication removal, and levels"],["Deliver","Audit reality","Time, access, interruptions, adherence, and support"],["Adapt","Life changes","Hospital, recovery, transplant, modality, and goals"]]}
};
export default function RenalReplacementTherapyVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
