const diagrams = {
  "resistant-confirmation": { eyebrow: "Confirm the phenotype", title: "Apparent resistance becomes true resistance only after the signal and regimen are verified.", accent: "#7ca7bc", columns: [["Measure", "Standardized office + home or ABPM", "Exclude technique and white-coat effect"], ["Reconcile", "Every drug, dose, and schedule", "Confirm complementary therapy and exposure"], ["Assess", "Access + adherence + interference", "Find solvable causes before adding treatment"], ["Classify", "Uncontrolled on 3 or controlled on 4", "Use maximally tolerated complementary classes"]] },
  "resistant-contributors": { eyebrow: "Pseudoresistance", title: "A difficult pressure may reflect the environment around treatment rather than failed biology.", accent: "#c28770", columns: [["Regimen", "Dose + duration + combination", "Verify long-acting CCB, RAAS blocker, and diuretic"], ["Exposure", "Refills + routine + adverse effects", "Ask without blame"], ["Interference", "NSAIDs + stimulants + hormones", "Include supplements, alcohol, and sodium"], ["Access", "Cost + supply + schedule", "Simplify and support before intensifying"]] },
  "secondary-screening": { eyebrow: "Clue-directed workup", title: "The phenotype determines the secondary hypertension pathway.", accent: "#8fa57c", columns: [["Common", "Kidney disease + primary aldosteronism", "Use renal, electrolyte, and renin-aldosterone data"], ["Sleep", "OSA pattern", "Snoring, witnessed apnea, sleepiness, obesity"], ["Vascular", "Renovascular clues", "Abrupt change, flash edema, asymmetric disease"], ["Endocrine", "Targeted hormonal testing", "Test only when the phenotype supports it"]] },
  "primary-aldosteronism": { eyebrow: "Aldosterone pathway", title: "Suppressed renin with inappropriate aldosterone is a treatable cardiovascular risk state.", accent: "#c2a061", columns: [["Screen", "Aldosterone + renin + ratio", "Measure potassium for interpretation"], ["Prepare", "Correct potassium + review medicines", "Posture, time, sodium, and laboratory method matter"], ["Differentiate", "Bilateral versus unilateral", "Use expert confirmation and subtype evaluation"], ["Treat", "MRA or adrenal surgery", "Match therapy to subtype and candidacy"]] },
  "secondary-causes": { eyebrow: "Major secondary causes", title: "Choose testing from clinical clues, not from an indiscriminate panel.", accent: "#9b8dbb", columns: [["Renal", "Parenchymal or renovascular", "Urine, kidney function, imaging when indicated"], ["Airway", "Obstructive sleep apnea", "Sleep testing follows a compatible phenotype"], ["Endocrine", "Thyroid, cortisol, catecholamine", "Use syndrome-specific biochemical preparation"], ["Anatomy", "Coarctation or rare causes", "Examination and age of onset guide testing"]] },
  "resistant-treatment": { eyebrow: "Stepwise control", title: "Optimize the base, target aldosterone biology, then escalate with specialist support.", accent: "#c77c6e", columns: [["Base", "Long-acting CCB + RAAS + thiazide-like", "Use maximally tolerated doses"], ["Fourth", "Mineralocorticoid receptor antagonist", "Monitor potassium, kidney function, and pregnancy"], ["Beyond", "Complementary add-on therapy", "Match heart rate, volume, kidney, and comorbidity"], ["Advanced", "Specialist + device discussion", "Renal denervation requires team evaluation and shared decisions"]] },
};

export default function ResistantSecondaryHypertensionVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
