const diagrams = {
  "ra-recognition": { eyebrow: "Pattern recognition", title: "Inflammation leaves a distribution", accent: "#d49279", columns: [["Pattern", "Small-joint synovitis", "Map swelling, warmth, stiffness, symmetry, and duration."], ["Evidence", "Support the phenotype", "Use serology, markers, imaging, and examination together."], ["Boundary", "Exclude the dangerous mimic", "A hot swollen joint with infection risk changes the immediate plan."]] },
  "ra-target": { eyebrow: "Treatment cadence", title: "The target determines the next move", accent: "#d5ad72", columns: [["Now", "Measure activity", "Record joints, function, symptoms, and relevant markers."], ["Three months", "Demand improvement", "Audit diagnosis, exposure, response, and tolerability."], ["Six months", "Reach the target", "Adjust disease-modifying therapy when remission or low activity remains out of reach."]] },
  "ra-methotrexate": { eyebrow: "Anchor therapy", title: "One weekly dose, one complete safety system", accent: "#d3c080", columns: [["Prescribe", "Once weekly", "Name the day, route, folate plan, and administration method."], ["Optimize", "Dose and route", "Verify exposure, split over one day, or use subcutaneous delivery when appropriate."], ["Protect", "Monitor toxicity", "Track blood counts, liver, kidney, infection, pregnancy, lungs, and interactions."]] },
  "ra-csdmards": { eyebrow: "Conventional strategy", title: "Three alternatives, three different risk maps", accent: "#8eaf91", columns: [["Hydroxychloroquine", "Retina and exposure", "Match dose and eye surveillance to weight, duration, kidney function, and risk."], ["Sulfasalazine", "Blood, liver, and skin", "Separate expected discoloration from systemic or mucosal toxicity."], ["Leflunomide", "Long persistence", "Plan liver, pregnancy, blood-pressure, and accelerated-elimination safety."]] },
  "ra-biologics": { eyebrow: "Extracellular targets", title: "Choose one immune checkpoint at a time", accent: "#8ca8c5", columns: [["Cytokine", "TNF or IL-6", "Block an inflammatory signal and monitor its mechanism-specific risks."], ["Cell", "T-cell costimulation", "Abatacept interrupts CD80 and CD86 signaling."], ["Lineage", "CD20-positive B cells", "Rituximab changes infusion, hepatitis, and vaccine planning."]] },
  "ra-jak": { eyebrow: "Intracellular target", title: "Oral therapy can carry system-level risk", accent: "#a28bc0", columns: [["Signal", "JAK to STAT", "Interrupt cytokine messages before transcription changes."], ["Select", "Compare major risks", "Review infection, cardiovascular, thrombotic, malignancy, age, and smoking history."], ["Monitor", "Follow the label", "Track blood counts, liver, lipids, organ function, interactions, and symptoms."]] },
  "ra-prevention": { eyebrow: "Before exposure", title: "Prevention starts before the first dose", accent: "#7fa99a", columns: [["Screen", "TB, hepatitis, and baseline risk", "Every result needs an interpretation and action."], ["Vaccinate", "Use the response window", "Give indicated vaccines and coordinate selected medication timing."], ["Respond", "Hold through serious infection", "Treat the infection, define recovery, and document restart ownership."]] },
  "ra-supportive": { eyebrow: "Whole-person care", title: "Relief and disease control are different jobs", accent: "#c89b75", columns: [["Bridge", "Relieve symptoms briefly", "NSAIDs and glucocorticoids do not replace a DMARD."], ["Restore", "Exercise and rehabilitation", "Preserve strength, range, function, participation, and confidence."], ["Explain", "Name the pain mechanism", "Do not escalate immune therapy for clearly noninflammatory pain."]] },
  "ra-longitudinal": { eyebrow: "Continuity", title: "The timeline is the treatment record", accent: "#d1a87c", columns: [["Past", "Why each therapy changed", "Record response, toxicity, access, and the reason for every transition."], ["Present", "Exact active exposure", "Capture weekly day, route, last biologic dose, holds, vaccines, and monitoring."], ["Next", "Own the decision", "State the target, next review, taper or restart criteria, and responsible clinician."]] },
  "ra-remission": { eyebrow: "Sustained control", title: "Reduce carefully without erasing the safety net", accent: "#9eaa83", columns: [["Confirm", "Sustained remission", "Use repeated objective assessment, not one quiet visit."], ["Reduce", "One deliberate step", "Taper gradually through shared decision-making."], ["Recover", "Watch for flare", "Keep monitoring, a rescue plan, and disease-modifying coverage visible."]] },
};

export default function RheumatoidArthritisVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual rheumatoid-arthritis-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
