export const rifaximinPharmacologyVisualTypes = ["structure-mechanism", "local-pk", "travelers-diarrhea", "hepatic-encephalopathy", "ibs-d", "dosing-administration", "hepatic-interactions", "safety-populations", "cdi-boundary", "integration"];

const diagrams = {
  "structure-mechanism": ["Target logic", "Connect the rifamycin scaffold to local transcription arrest", ["Recognize", "Rifamycin", "Structural relation informs class allergy and resistance."], ["Bind", "RNA polymerase", "The beta subunit is the direct bacterial target."], ["Stop", "Transcription", "RNA synthesis falls before downstream protein production."], ["Protect", "Activity", "Stewardship limits rpoB-mediated resistance pressure."]],
  "local-pk": ["Compartment map", "Keep useful gastrointestinal exposure separate from systemic limits", ["Deliver", "Oral dose", "The tablet enters the intestinal lumen."], ["Limit", "Absorption", "Average plasma concentrations remain low and variable."], ["Recover", "Feces", "Most recovered material remains in the gastrointestinal path."], ["Exclude", "Systemic infection", "The exposure profile cannot support bacteremia treatment."]],
  "travelers-diarrhea": ["Phenotype gate", "Let severity and invasive features decide whether rifaximin fits", ["Assess", "Function", "Mild illness usually needs fluids rather than antibiotics."], ["Exclude", "Fever or blood", "Invasive findings require another pathway."], ["Treat", "200 mg three times daily", "Use three days for qualifying noninvasive disease."], ["Escalate", "24 to 48 hours", "Worsening or persistent illness needs reassessment."]],
  "hepatic-encephalopathy": ["Recurrence loop", "Rifaximin works inside a broader hepatic encephalopathy plan", ["Confirm", "Overt HE history", "Exclude neurologic alternatives and define prior episodes."], ["Correct", "Precipitants", "Treat infection, bleeding, constipation, dehydration, and drug causes."], ["Combine", "Lactulose plus rifaximin", "Optimize the bowel plan and add 550 mg twice daily."], ["Follow", "Function and recurrence", "Track cognition, admissions, falls, nutrition, and liver trajectory."]],
  "ibs-d": ["Course architecture", "A defined course can be repeated only after response and reassessment", ["Establish", "IBS-D", "Confirm phenotype and screen alarm findings."], ["Treat", "14 days", "Give 550 mg three times daily."], ["Measure", "Global response", "Track pain, stool pattern, urgency, and function."], ["Retreat", "Up to two times", "Count successful prior courses before repeating."]],
  "dosing-administration": ["Three schedules", "The indication determines strength, frequency, duration, and quantity", ["TD", "200 mg three times daily", "Three days equals nine tablets."], ["HE", "550 mg twice daily", "Thirty days equals sixty tablets."], ["IBS-D", "550 mg three times daily", "Fourteen days equals forty-two tablets."], ["All", "With or without food", "Choose a reproducible schedule."]],
  "hepatic-interactions": ["Exposure modifiers", "Local pharmacology can become more systemic in high-risk contexts", ["Grade", "Child-Pugh", "Exposure rises progressively from class A through class C."], ["Review", "P-gp inhibitors", "Cyclosporine can markedly raise rifaximin exposure."], ["Monitor", "Warfarin", "Assign INR and prothrombin-time follow-up."], ["Interpret", "CYP3A", "Severe liver disease increases interaction uncertainty."]],
  "safety-populations": ["Safety frame", "Use the exact population and indication rather than one generic warning list", ["Exclude", "Rifamycin allergy", "Anaphylaxis, angioedema, and severe skin reactions matter."], ["Reassess", "New diarrhea", "C. difficile disease remains possible after therapy."], ["Narrate", "Pregnancy and lactation", "State limited human evidence and the patient context."], ["Verify", "Age and indication", "Only TD is established from age 12."]],
  "cdi-boundary": ["Off-label boundary", "Keep the multiply recurrent CDI sequence explicit", ["Confirm", "Multiple recurrences", "Initial CDI does not fit this rifaximin role."], ["Lead", "Oral vancomycin", "Complete the defined standard course first."], ["Follow", "Rifaximin", "Use 400 mg three times daily for twenty days."], ["Reassess", "Resistance and alternatives", "Do not repeat indefinitely after failure."]],
  "integration": ["Closed-loop use", "Make indication, exposure, execution, and follow-up agree", ["Define", "Indication and phenotype", "Diagnosis controls every downstream choice."], ["Execute", "Exact regimen", "Select strength, schedule, duration, and quantity."], ["Protect", "Patient", "Review liver severity, interactions, allergy, and age."], ["Close", "Response and exit", "Assign follow-up, escalation, and retreatment logic."]],
};

export default function RifaximinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual rifaximin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
