const diagrams={
"ssp-mechanism":{eyebrow:"Mechanism first",title:"Infarct pattern, vessel imaging, cardiac evaluation, rhythm monitoring, and selective testing convert an event label into a prevention target.",accent:"#b87969",columns:[["Brain","Pattern and territory","Lacunar, cortical, borderzone"],["Artery","Extra and intracranial imaging","Plaque, stenosis, dissection"],["Heart","ECG, monitoring, selective echo","AF, thrombus, valve, shunt"],["Other","Focused cause testing","Do not order panels without a hypothesis"]]},
"ssp-antithrombotic":{eyebrow:"Match drug to cause",title:"Antiplatelet therapy treats most noncardioembolic events, anticoagulation treats eligible cardioembolism, and combination duration must have a defined indication.",accent:"#839db4",columns:[["Single","Aspirin, clopidogrel, or aspirin dipyridamole","Long-term noncardioembolic prevention"],["Dual","Short course in selected early minor stroke or TIA","Stop on schedule"],["Anticoag","Atrial fibrillation and selected cardiac sources","Time by infarct and bleeding"],["Avoid","Routine antiplatelet plus anticoagulant","Bleeding without a prevention target"]]},
"ssp-atherosclerosis":{eyebrow:"Atherosclerotic source control",title:"Carotid and intracranial disease require aggressive medical therapy, with intervention reserved for evidence-based anatomy and patient selection.",accent:"#a58bb6",columns:[["Carotid","Ipsilateral symptomatic stenosis","Early endarterectomy in suitable severe disease"],["Intracranial","Aggressive risk and short DAPT","Stenting is not first line"],["Lipid","High-intensity statin and LDL below 70","Add nonstatin when needed"],["Pressure","Usually below 130 over 80","Individualize safely"]]},
"ssp-cardioembolic":{eyebrow:"Cardioembolic prevention",title:"Rhythm burden, valve type, ventricular or atrial thrombus, infarct size, hemorrhage risk, kidney function, and adherence determine anticoagulant and start time.",accent:"#8da47d",columns:[["Detect","Telemetry and longer monitoring","More monitoring finds more AF"],["Select","DOAC or warfarin by condition","Do not treat all valves alike"],["Time","Balance early embolism and hemorrhage","Repeat imaging when needed"],["Sustain","Dose, interaction, access, adherence","Missed doses rapidly remove protection"]]},
"ssp-special":{eyebrow:"Special mechanisms",title:"PFO, ESUS, dissection, small-vessel disease, and unusual causes require targeted evidence rather than empiric escalation.",accent:"#c09a61",columns:[["PFO","Younger selected nonlacunar stroke","Prove plausible causality"],["ESUS","Do not empirically anticoagulate","Continue diagnostic ownership"],["Dissection","Antithrombotic and vessel follow-up","Individualize bleeding and anatomy"],["Small vessel","Pressure and vascular prevention","Do not search for a large embolus forever"]]},
"ssp-lifelong":{eyebrow:"Prevention that survives discharge",title:"Medication, diet, activity, tobacco treatment, sleep, rehabilitation, cognition, mood, access, and repeated measurement determine whether a plan becomes durable protection.",accent:"#ba7369",columns:[["Measure","Pressure, LDL, glucose, rhythm","Track control over time"],["Support","Behavior change and rehabilitation","Advice alone is insufficient"],["Reconcile","Purpose, dose, duration, ownership","Investigate adherence before switching"],["Respond","New symptoms trigger emergency care","TIA is not a routine visit"]]},
};
export default function SecondaryStrokePreventionVisual({type}){const d=diagrams[type];if(!d)return null;return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,m,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{m}</em><p>{x}</p></div>)}</div></figure>}
