const diagrams = {
  "sexual-health-framework": ["Clinical framework", "Define the concern before choosing a treatment", ["Function", "Name the domain", "Desire, arousal, erection, orgasm, pain, and satisfaction are related but distinct"], ["Context", "Find the contributors", "Health, medicines, mood, relationship context, and goals shape the presentation"], ["Plan", "Share the decision", "Treat reversible causes and match therapy to the person rather than a label alone"]],
  "ed-evaluation": ["Evaluation map", "Erectile dysfunction can reveal more than a sexual symptom", ["Listen", "Medical and sexual history", "Onset, consistency, rigidity, libido, morning erections, medicines, and distress"], ["Examine", "Risk and physiology", "Cardiovascular, neurologic, endocrine, pelvic, and medication clues guide testing"], ["Escalate", "Selective investigation", "Use testosterone, metabolic assessment, or specialized testing when the result can change care"]],
  "erection-physiology": ["Signal pathway", "Preserve cGMP long enough for smooth muscle relaxation", ["Release", "Nitric oxide", "Neural and endothelial stimulation activates soluble guanylate cyclase"], ["Relax", "cGMP rises", "Lower intracellular calcium relaxes cavernosal smooth muscle and increases inflow"], ["Maintain", "PDE5 is inhibited", "Reduced cGMP breakdown supports an erection when sexual stimulation is present"]],
  "pde5-selection": ["Agent selection", "Timing, exposure, and context change the fit", ["Shorter window", "Sildenafil or vardenafil", "Plan around food, timing, interactions, and the required stimulation"], ["Longer window", "Tadalafil", "Use as needed or daily and account for renal function and prolonged nitrate concern"], ["Faster option", "Avanafil", "Use its labeled timing and strict CYP3A4 limits rather than assuming a class schedule"]],
  "pde5-safety": ["Safety circuit", "Block the dangerous combinations before optimizing effect", ["Stop", "Nitrates and GC stimulators", "Combined cGMP signaling can produce profound hypotension"], ["Stabilize", "Alpha blockers and pressure", "Confirm hemodynamic stability and begin the PDE5 inhibitor at the lowest labeled dose"], ["Act", "Priapism, vision, hearing", "An erection beyond four hours or sudden sensory loss requires urgent evaluation"]],
  "pde5-response": ["Response audit", "A failed trial is not proven until use is correct", ["Verify", "Dose and timing", "Confirm the exact product, adequate dose, stimulation, food effect, and repeated attempts"], ["Reassess", "Cause and expectation", "Look again at vascular risk, testosterone, medicines, anxiety, pain, and relationship context"], ["Advance", "Other modalities", "Offer devices, alprostadil, injections, or prosthesis discussion through shared decisions"]],
  "nonoral-ed": ["Nonoral options", "Create rigidity through pressure, prostaglandin, or a device", ["Vacuum", "Mechanical inflow", "Use negative pressure and a constriction ring with technique and time limits"], ["Alprostadil", "Direct vasodilation", "Titrate intraurethral or intracavernosal therapy with priapism and fibrosis counseling"], ["Implant", "Penile prosthesis", "Discuss irreversible surgery, infection, mechanical failure, and expected function"]],
  "hsdd-evaluation": ["Desire assessment", "Low desire becomes a disorder only within the right clinical frame", ["Confirm", "Acquired and generalized", "The change occurs across situations and causes marked distress or interpersonal difficulty"], ["Exclude", "Other explanations", "Medical, psychiatric, relationship, medication, pain, and substance factors may better explain the concern"], ["Align", "Goals and autonomy", "Treatment is not intended to enhance performance or satisfy someone else's expectation"]],
  "flibanserin-safety": ["Daily HSDD therapy", "Flibanserin requires an exposure and alertness plan", ["Dose", "100 mg at bedtime", "Stop after eight weeks without improvement and never double a missed dose"], ["Separate", "Alcohol and sedatives", "Use current timing instructions and avoid driving for at least six hours after a dose"], ["Exclude", "CYP3A4 and liver disease", "Moderate or strong CYP3A4 inhibitors and any hepatic impairment are contraindications"]],
  "bremelanotide-safety": ["As needed HSDD therapy", "Every injection creates a cardiovascular and tolerability window", ["Inject", "1.75 mg subcutaneously", "Use at least 45 minutes before anticipated activity, no more than once daily or eight times monthly"], ["Screen", "Blood pressure and risk", "Uncontrolled hypertension or known cardiovascular disease is a contraindication"], ["Monitor", "Nausea and pigmentation", "Reassess persistent nausea, focal hyperpigmentation, gastric emptying, and oral naltrexone exposure"]],
};

export default function SexualDysfunctionVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
