const diagrams = {
  "shock-recognition": { eyebrow: "Perfusion signal", title: "Pressure can look stable while organs lose flow", accent: "#f27f64", columns: [["Observe", "Bedside", "Mentation, skin, capillary refill, pulse, and urine reveal immediate perfusion."], ["Trend", "Metabolic", "Lactate, pH, kidney, liver, and dose requirement show direction of travel."], ["Act", "Cause plus support", "Stabilize oxygen delivery while the definitive cause is treated."]] },
  "hemodynamic-phenotypes": { eyebrow: "Circulatory map", title: "Locate the dominant failure before choosing the lever", accent: "#f0a565", columns: [["Tank", "Preload", "Volume loss or impaired filling limits stroke volume."], ["Pump", "Cardiac output", "Ventricular failure, rate, or rhythm reduces forward flow."], ["Pipes", "Resistance", "Vasodilation or excessive vasoconstriction changes pressure and distribution."]] },
  "fluid-responsiveness": { eyebrow: "Fluid decision", title: "Potential benefit and tolerance must both be present", accent: "#63b6c5", columns: [["Test", "Dynamic response", "Passive leg raise or a small challenge asks whether flow can rise."], ["Measure", "Useful output", "Stroke volume or pulse-pressure response is more useful than static filling alone."], ["Stop", "Congestion boundary", "Lung, venous, renal, and right-heart findings define the cost of more volume."]] },
  "septic-shock": { eyebrow: "Sepsis sequence", title: "Source, time, pressure, and perfusion move together", accent: "#de705b", columns: [["Control", "Infection", "Cultures, immediate antimicrobials, and early source control run in parallel."], ["Restore", "Initial target", "Crystalloid, MAP near 65, and dynamic reassessment support perfusion."], ["Escalate", "Vasoactive path", "Norepinephrine, then vasopressin, then selected epinephrine or inotropy."]] },
  "catecholamine-vasopressors": { eyebrow: "Receptor translation", title: "Receptor balance becomes rate, resistance, and flow", accent: "#ef8c53", columns: [["Alpha-1", "Vascular tone", "Constriction raises resistance but can increase afterload and ischemia."], ["Beta-1", "Pump and rate", "Contractility can improve flow while tachyarrhythmia increases oxygen demand."], ["Beta-2", "Airway and metabolism", "Bronchodilation and vasodilation coexist with potassium shift and lactate production."]] },
  "noncatecholamine-vasopressors": { eyebrow: "Parallel pathways", title: "Add vascular tone without adding another catecholamine", accent: "#c89467", columns: [["V1", "Vasopressin", "Vascular smooth-muscle signaling supports catecholamine-resistant vasodilation."], ["AT1", "Angiotensin II", "Vasoconstriction and aldosterone signaling can rapidly raise pressure."], ["Audit", "Whole circulation", "Ischemia, thrombosis, cardiac function, and organ perfusion remain the outcome."]] },
  "cardiogenic-inotropes": { eyebrow: "Low-flow strategy", title: "Support pressure, improve flow, and define the bridge", accent: "#dc6d68", columns: [["Stage", "Severity and ventricle", "Etiology, SCAI stage, congestion, and LV, RV, or biventricular failure guide care."], ["Select", "Dobutamine or milrinone", "Rate, pressure, beta exposure, and kidney function determine the tradeoff."], ["Escalate", "Team and support", "Refractory low flow requires early expert transfer and a defined exit strategy."]] },
  "cause-directed-shock": { eyebrow: "Definitive treatment", title: "Some shock states cannot be pressed away", accent: "#eb6a58", columns: [["Anaphylaxis", "Epinephrine", "Immediate intramuscular treatment addresses airway, bronchospasm, and collapse."], ["Hemorrhage", "Control and blood", "Stop the loss and restore oxygen-carrying capacity, coagulation, and temperature."], ["Obstruction", "Relieve the barrier", "Decompress, drain, reperfuse, or correct ventilation to restore filling and ejection."]] },
  "vasodilators-afterload": { eyebrow: "Controlled unloading", title: "Lower resistance only when perfusion can tolerate it", accent: "#8da7d8", columns: [["Nitroglycerin", "Venous first", "Reduce filling pressure and ischemic burden while screening major interactions."], ["Nitroprusside", "Balanced dilation", "Rapid afterload reduction requires continuous pressure and toxicity monitoring."], ["Verify", "Forward flow", "A lower pressure is useful only when organ perfusion and output improve."]] },
  "infusion-safety": { eyebrow: "Closed-loop delivery", title: "Every high-alert infusion must be reconstructable", accent: "#e3b566", columns: [["Calculate", "Dose to rate", "Keep weight, time, concentration, and pump units visible through the equation."], ["Protect", "Line and tissue", "Inspect access continuously and treat extravasation as a medication emergency."], ["Taper", "Autonomous stability", "Reduce support deliberately while pressure, perfusion, and cause remain controlled."]] },
};

export default function ShockVasoactiveVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
