export const sickleCellDiseaseVisualTypes = ["hbs-biology", "prevention", "voc-pain", "emergencies", "hydroxyurea", "disease-modification", "transfusion", "chronic-care", "curative-therapy", "integration"];

const diagrams = {
  "hbs-biology": ["Molecular frame", "Follow HbS from deoxygenation to organ injury", ["Polymerize", "Deoxygenated HbS", "Fibers distort the red cell and damage its membrane"], ["Occlude", "Adhesion and flow", "Sickled cells, endothelium, platelets, and leukocytes obstruct microvessels"], ["Hemolyze", "Shortened survival", "Anemia, bilirubin, nitric oxide biology, and vascular stress emerge"], ["Modify", "Fetal hemoglobin", "More HbF reduces participation in HbS polymer formation"]],
  prevention: ["Prevention system", "Build protection around functional asplenia", ["Vaccinate", "Current risk schedule", "Reconcile pneumococcal, meningococcal, Hib, influenza, and routine products"], ["Prevent", "Daily antibiotic", "Protect eligible young children according to current guidance"], ["Escalate", "Fever", "Treat possible invasive infection as urgent"], ["Teach", "Home action plan", "Make emergency thresholds and contact routes explicit"]],
  "voc-pain": ["Pain pathway", "Treat rapidly while searching for dangerous companions", ["Screen", "Emergency signals", "Check chest, neurologic, infectious, abdominal, and genitourinary features"], ["Treat", "Individualized analgesia", "Use timely multimodal therapy with repeated reassessment"], ["Support", "Deficit, not ritual", "Correct hypoxemia and dehydration without causing fluid harm"], ["Close", "Next step", "Document response, discharge safety, and prevention follow-up"]],
  emergencies: ["Emergency map", "Recognize syndromes where minutes change outcome", ["Lung", "Acute chest syndrome", "Escalate oxygenation, antibiotics, respiratory support, and transfusion decisions"], ["Brain", "Stroke", "Activate imaging and exchange-transfusion expertise"], ["Spleen", "Sequestration", "Treat acute pooling, anemia, and shock"], ["Other", "Priapism and aplasia", "Do not normalize time-sensitive complications"]],
  hydroxyurea: ["Disease modification", "Connect exposure, marrow response, and clinical benefit", ["Increase", "Fetal hemoglobin", "Reduce the fraction of hemoglobin available to sickle"], ["Titrate", "Counts and response", "Use product and protocol-specific dose rules"], ["Monitor", "Myelosuppression", "Interrupt and recover rather than escalating through toxicity"], ["Sustain", "Adherence", "Daily use, laboratories, handling, and reproductive planning belong together"]],
  "disease-modification": ["Current therapy", "Separate active options from obsolete lists", ["Reduce", "L-glutamine", "Offer an oral preventive option to eligible patients"], ["Block", "P-selectin", "Crizanlizumab remains US labeled for VOC reduction from age 16"], ["Retire", "Voxelotor", "FDA withdrawal means historical content must not guide initiation"], ["Compare", "Benefit and burden", "Match goals, route, evidence, access, and patient preference"]],
  transfusion: ["Blood strategy", "Choose the indication, method, match, and follow-up", ["Profile", "Extended antigens", "Preserve genotype, phenotype, antibodies, and reaction history"], ["Choose", "Simple or exchange", "Balance oxygen delivery, HbS reduction, viscosity, and iron"], ["Detect", "Delayed hemolysis", "Treat post-transfusion pain and anemia as a possible reaction"], ["Control", "Iron burden", "Use exposure history, MRI assessment, and product-specific chelation"]],
  "chronic-care": ["Organ protection", "Turn silent injury into a longitudinal surveillance plan", ["Brain", "TCD and history", "Prevent overt and silent cerebrovascular disease"], ["Kidney", "Albumin and filtration", "Look beyond a reassuring low creatinine"], ["Heart and lung", "Symptoms first", "Use targeted evaluation instead of indiscriminate advanced screening"], ["Reproduction", "Current risk model", "Coordinate pregnancy, contraception, and fertility decisions"]],
  "curative-therapy": ["Potentially curative care", "Compare donor transplant with two distinct autologous gene therapies", ["Replace", "Allogeneic transplant", "Balance donor, graft, organ, fertility, and immune risks"], ["Edit", "Casgevy", "Disrupt the erythroid BCL11A enhancer to restore fetal hemoglobin"], ["Add", "Lyfgenia", "Deliver modified beta-globin with a lentiviral vector"], ["Follow", "Lifelong surveillance", "Conditioning and delayed product risks persist beyond infusion"]],
  integration: ["Connected care", "Make every emergency, preventive, and disease-modifying decision travel with the patient", ["Record", "Baseline and history", "Preserve antibodies, effective analgesia, complications, and preferences"], ["Coordinate", "Transitions", "Establish adult care before pediatric care closes"], ["Measure", "Equity and access", "Audit delays and solve barriers without blame"], ["Own", "Closed loop", "Assign every laboratory, vaccine, referral, and response review"]],
};

export default function SickleCellDiseaseVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...nodes] = item;
  return <figure className="chol-visual sickle-cell-visual" aria-label={title}>
    <figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption>
    <div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
