const diagrams = {
  "sjogren-autoimmunity": { eyebrow: "Autoimmune architecture", title: "Gland injury and systemic B cell activity belong to the same disease", accent: "#c79270", columns: [["Target", "Injure exocrine tissue", "Immune activity reduces lacrimal and salivary function and damages protective surfaces."], ["Signal", "Read antibody context", "Anti-SSA, biopsy, and objective gland tests support classification but do not replace diagnosis."], ["Extend", "Search beyond dryness", "Nerves, lungs, kidneys, vessels, joints, and blood can become clinically important targets."]] },
  "sjogren-spectrum": { eyebrow: "Clinical spectrum", title: "Function, tissue injury, and systemic change determine urgency", accent: "#d47f72", columns: [["Describe", "Measure sicca burden", "Vision, speech, swallowing, sleep, nutrition, and dental health reveal the real cost of dryness."], ["Screen", "Map systemic domains", "Raynaud, purpura, neuropathy, dyspnea, renal loss, cytopenia, and gland swelling change the plan."], ["Escalate", "Name red flags", "Eye pain, vision loss, progressive weakness, persistent gland enlargement, and B symptoms cannot wait."]] },
  "sjogren-diagnosis": { eyebrow: "Weighted classification", title: "Five objective findings contribute different evidence", accent: "#88a8b2", columns: [["Three points", "Anti-SSA or qualifying biopsy", "Either finding carries the greatest weight in the 2016 ACR EULAR score."], ["One point", "Measure surface and flow", "Ocular staining, Schirmer testing, and unstimulated saliva each add one when abnormal."], ["Interpret", "Keep diagnosis clinical", "A score of four classifies an eligible patient, but early disease still requires longitudinal judgment."]] },
  "sjogren-dry-eye": { eyebrow: "Ocular surface", title: "Protect the tear film before inflammation becomes structural injury", accent: "#80a9c1", columns: [["Replace", "Choose the lubricant", "Frequent use favors preservative free tears, while gels and ointments extend nighttime protection."], ["Restore", "Treat mixed mechanisms", "Aqueous deficiency and meibomian dysfunction may require different but coordinated measures."], ["Refer", "Protect vision", "Pain, photophobia, reduced vision, epithelial defect, or ulceration needs urgent ophthalmic care."]] },
  "sjogren-eye-therapy": { eyebrow: "Anti-inflammatory eye care", title: "Regular treatment changes the surface on a slower clock", accent: "#8d91c5", columns: [["Cyclosporine", "Reduce ocular inflammation", "Delayed benefit and local burning require realistic counseling and sustained use when tolerated."], ["Lifitegrast", "Block LFA-1 signaling", "Twice daily dosing, lens separation, dysgeusia, and single dose technique shape safe use."], ["Advance", "Match procedure to severity", "Punctal care, serum tears, scleral lenses, and supervised steroids require specialist selection."]] },
  "sjogren-oral-care": { eyebrow: "Oral protection", title: "Saliva defends enamel, mucosa, swallowing, and nutrition", accent: "#d0aa6e", columns: [["Prevent", "Use topical fluoride", "Strong prevention begins before the first cavity and continues with structured dental care."], ["Support", "Stimulate without injury", "Water, xylitol, substitutes, and humidification avoid the sugar and acid costs of unsafe strategies."], ["Inspect", "Find complications", "Caries, erosion, candidiasis, mucosal injury, dysphagia, and poor intake require active care."]] },
  "sjogren-secretagogues": { eyebrow: "Systemic muscarinic therapy", title: "More secretion is useful only when function improves safely", accent: "#74aa91", columns: [["Pilocarpine", "Dose four times daily", "Five milligrams four times daily is the current Sjogren xerostomia regimen."], ["Cevimeline", "Dose three times daily", "Thirty milligrams three times daily can improve saliva with a distinct schedule and tolerability profile."], ["Monitor", "Control cholinergic harm", "Sweating, gut effects, breathing, vision, heart rate, and hydration define the usable trial."]] },
  "sjogren-systemic": { eyebrow: "Organ directed therapy", title: "The inflammatory target must be named before immune risk is accepted", accent: "#a58db7", columns: [["Separate", "Do not immunosuppress dryness", "Topical and secretory care remain the foundation for glandular symptoms."], ["Select", "Treat the active organ", "Hydroxychloroquine, glucocorticoids, conventional therapy, and biologics have different roles."], ["Measure", "Track response and harm", "Disease activity, function, infection, organ toxicity, and steroid burden define success."]] },
  "sjogren-lymphoma": { eyebrow: "Lymphoma surveillance", title: "Persistent change matters more than routine scanning", accent: "#c36e73", columns: [["Observe", "Find gland and node change", "Persistent parotid enlargement, lymphadenopathy, splenomegaly, and purpura increase concern."], ["Correlate", "Read laboratory risk", "Low complement, cryoglobulins, cytopenias, and monoclonal patterns sharpen the signal."], ["Investigate", "Act on B symptoms", "Fever, drenching night sweats, and substantial weight loss need prompt evaluation."]] },
  "sjogren-longitudinal": { eyebrow: "Longitudinal system", title: "Ocular, oral, systemic, reproductive, and safety plans move together", accent: "#b9a27b", columns: [["Coordinate", "Connect the care team", "Rheumatology, eye, dental, primary, pharmacy, and organ specialists share one plan."], ["Plan", "Prepare pregnancy early", "Anti-SSA and anti-SSB status changes medicine review and fetal surveillance."], ["Return", "Use explicit thresholds", "Vision, intake, breathing, neurologic, glandular, constitutional, and toxicity changes trigger earlier care."]] },
};

export const sjogrenDiseaseVisualTypes = Object.keys(diagrams);

export default function SjogrenDiseaseVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual sjogren-disease-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
