export const skinSoftTissueInfectionsVisualTypes=["classification-triage","superficial-infections","cellulitis-erysipelas","purulent-infections","severe-ssti","necrotizing-infections","diabetic-foot-infections","dfi-osteomyelitis","wound-perfusion-care","special-populations-prevention"].map(type=>`ssti-${type}`);
const diagrams={
"classification-triage":["Tissue map","Let morphology and depth set the first branch",["See","Surface","Crust, follicle, diffuse erythema, pus, necrosis, and ulcer are different syndromes."],["Feel","Depth","Pain, fluctuance, fascia, muscle, and bone change urgency."],["Measure","Physiology","Vitals, organs, progression, and host reserve set disposition."],["Challenge","Mimic","Bilateral or chronic inflammatory disease can look infected."]],
"superficial-infections":["Surface care","Scale treatment to lesion burden and depth",["Localize","Few lesions","Topical impetigo therapy can limit systemic exposure."],["Expand","Numerous lesions","Oral therapy must address both common pathogens."],["Drain","Deeper follicle","A carbuncle behaves like a source-control problem."],["Contain","Transmission","Coverage, hygiene, and laundering reduce spread."]],
"cellulitis-erysipelas":["Nonpurulent pathway","Center streptococci and correct the portal",["Target","Streptococci","Use a focused beta-lactam when risk and allergy fit."],["Gate","MRSA","Add coverage only for a credible exposure or severe phenotype."],["Stop","Five days","Extend only when improvement is inadequate."],["Prevent","Portal care","Treat edema, fissures, tinea, and skin breakdown."]],
"purulent-infections":["Abscess pathway","Mechanical control comes before spectrum",["Confirm","Collection","Examination or ultrasound identifies drainable pus."],["Control","Incision and drainage","Evacuate the protected infected space."],["Select","Adjunct drug","Systemic illness and host risk determine added therapy."],["Investigate","Recurrence","Find anatomy, colonization, and shared reservoirs."]],
"severe-ssti":["Exposure system","Make parenteral activity measurable and safe",["Control","Source","Drain, debride, and culture before relying on drug exposure."],["Choose","Site-matched drug","Vancomycin, daptomycin, linezolid, and ceftaroline are not interchangeable."],["Measure","AUC 400 to 600","Use current serious-MRSA vancomycin monitoring when applicable."],["Narrow","Evidence","Cultures and stability should reduce route and spectrum burden."]],
"necrotizing-infections":["Emergency sequence","Do not let the diagnostic process delay debridement",["Suspect","Disproportionate pain","Rapid progression and systemic toxicity outweigh a reassuring surface."],["Explore","Surgery now","Direct tissue assessment and debridement are primary therapy."],["Cover","Lethal ecology","Start MRSA, streptococcal, gram-negative, and anaerobic activity."],["Repeat","Viability check","Return until only viable controlled tissue remains."]],
"diabetic-foot-infections":["Clinical classification","Separate colonization from invasive disease",["Diagnose","Inflammation","A positive swab alone does not make an infection."],["Grade","Mild to severe","Extent, depth, systemic signs, and morbidity set care."],["Sample","Debrided tissue","Aseptic curettage or biopsy improves pathogen confidence."],["Restrain","Pseudomonas","Temperate-climate empiric therapy needs a specific risk."]],
"dfi-osteomyelitis":["Compartment clock","Bone changes evidence, culture, and duration",["Probe","Bedside evidence","Combine probe-to-bone with radiograph and biomarkers."],["Resolve","MRI","Use advanced imaging when initial evidence remains uncertain."],["Culture","Bone","Obtain a clean compartment specimen when definition matters."],["Time","Residual burden","Soft tissue, positive margins, and unresected bone use different durations."]],
"wound-perfusion-care":["Limb preservation","Create the conditions in which infection can resolve",["Remove","Necrosis","Debridement reduces burden and reveals viable anatomy."],["Restore","Perfusion","Vascular assessment and revascularization support healing."],["Unload","Pressure","Off-loading stops repeated mechanical injury."],["Coordinate","Whole system","Wound, diabetes, nutrition, footwear, and follow-up act together."]],
"special-populations-prevention":["Safe closeout","Prevent the next episode while protecting this patient",["Clarify","Allergy","Separate intolerance from immediate and severe delayed injury."],["Recalculate","Exposure","Organs, weight, interactions, pregnancy, and age change safety."],["Select","Decolonization","Use a short strategy only after recurrence causes are addressed."],["Teach","Return signs","Rapid spread, severe pain, color change, or instability needs urgent care."]],
};
export default function SkinSoftTissueInfectionsVisual({type}){const diagram=diagrams[type.replace("ssti-","")];if(!diagram)return null;const[eyebrow,title,...nodes]=diagram;return <figure className="chol-visual skin-soft-tissue-infections-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={`${verb}-${focus}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
