export const streptococcalPharyngitisVisualTypes = ["biology-pathogenesis", "syndrome-differential", "risk-testing", "specimen-diagnostics", "supportive-red-flags", "first-line-beta-lactams", "allergy-resistance", "dosing-administration", "response-transmission", "complications-sequelae", "recurrence-carriage"].map((type) => `strep-${type}`);

const diagrams = {
  "biology-pathogenesis": ["Disease architecture", "Connect organism, surface, toxin, and immune response", ["Adhere", "Oropharynx", "Group A strep establishes local epithelial infection."], ["Inflame", "Local tissue", "Host response produces pain, fever, and tonsillar change."], ["Express", "Toxin", "Selected strains produce the scarlet fever phenotype."], ["Follow", "Immune injury", "Delayed cardiac, joint, neurologic, or renal disease can appear."]],
  "syndrome-differential": ["Sore-throat map", "Move from common virus to urgent airway disease", ["Stop", "Clear viral", "Cough, rhinorrhea, hoarseness, ulcers, or conjunctivitis argue against testing."], ["Test", "Probable GAS", "Sudden fever, anterior nodes, and tonsillar inflammation raise probability."], ["Reframe", "Mononucleosis", "Posterior nodes, fatigue, or splenic findings change the path."], ["Escalate", "Airway or abscess", "Drooling, stridor, trismus, voice change, or asymmetry are urgent."]],
  "risk-testing": ["Risk gate", "Use a clinical score without turning it into a diagnosis", ["Count", "Score features", "Fever, cough absence, anterior nodes, tonsils, and age shape probability."], ["Avoid", "Low yield", "A low score can prevent unnecessary testing."], ["Override", "High risk", "Exposure, rheumatic fever history, or complicated disease still matters."], ["Confirm", "Microbiology", "A score never replaces an organism test."]],
  "specimen-diagnostics": ["Diagnostic loop", "Collect, interpret, and own every result", ["Swab", "Correct tissue", "Sample tonsillar areas and posterior pharynx."], ["Confirm", "Positive RADT", "A positive rapid antigen test confirms disease."], ["Back up", "Children", "Culture a negative RADT from symptomatic age 3 or older."], ["Close", "Callback", "Assign result ownership and delayed treatment access."]],
  "supportive-red-flags": ["Parallel care", "Treat symptoms while watching for dangerous change", ["Relieve", "Pain and fever", "Use safe age and weight-based analgesia."], ["Hydrate", "Swallowing", "Track intake, urine, dizziness, and function."], ["Avoid", "Low-value adjuncts", "Do not use routine steroids or pediatric aspirin."], ["Escalate", "Red flags", "Protect the airway and detect deep-space disease."]],
  "first-line-beta-lactams": ["Focused therapy", "Match route and schedule to the patient", ["Choose", "Penicillin V", "Narrow oral therapy remains effective."], ["Simplify", "Amoxicillin", "Once or twice daily dosing supports delivery."], ["Complete", "IM benzathine", "One verified long-acting dose solves oral adherence."], ["Protect", "Exposure", "Schedule preserves time above the target concentration."]],
  "allergy-resistance": ["Alternative fork", "Separate reaction phenotype from resistance context", ["Clarify", "Allergy", "Distinguish intolerance, immediate, and severe delayed reactions."], ["Permit", "Cephalosporin", "Selected nonimmediate histories can use a focused option."], ["Avoid", "Immediate reaction", "Cephalexin and cefadroxil do not fit this pathway."], ["Verify", "Resistance", "Macrolide and clindamycin reliability varies locally."]],
  "dosing-administration": ["Dose translation", "Carry units from body weight to completed course", ["Measure", "Kilograms", "Use a current plausible weight."], ["Calculate", "Milligrams", "Apply mg per kg and the regimen maximum."], ["Convert", "Milliliters", "Use the exact dispensed concentration."], ["Deliver", "Course", "Match quantity, device, schedule, and teach-back."]],
  "response-transmission": ["Follow-up clock", "Link improvement, isolation, and reassessment", ["Start", "Appropriate therapy", "Record the exact first-dose time."], ["Return", "12 to 24 hours", "Require afebrile clinical recovery as well."], ["Expect", "24 to 48 hours", "Pain and fever should begin improving."], ["Reopen", "Poor response", "Audit diagnosis, delivery, complication, and carriage."]],
  "complications-sequelae": ["Complication compass", "Separate local spread from delayed immune disease", ["Drain", "Abscess", "Unilateral swelling and trismus need urgent source control."], ["Confirm", "Scarlet fever", "A toxin rash still requires group A strep testing."], ["Prevent", "Rheumatic fever", "Adequate treatment protects against delayed cardiac injury."], ["Detect", "Renal injury", "Dark urine, edema, and hypertension need kidney evaluation."]],
  "recurrence-carriage": ["Recurrence audit", "Build a timeline before prescribing again", ["Rebuild", "Episode", "Compare symptoms, testing, therapy, and response."], ["Verify", "Delivery", "Dose, duration, and adherence may explain persistence."], ["Distinguish", "Carriage", "A viral illness can coexist with a positive test."], ["Reserve", "Eradication", "Treat carriage only in defined special contexts."]],
};

export default function StreptococcalPharyngitisVisual({ type }) {
  const diagram = diagrams[type.replace("strep-", "")];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual streptococcal-pharyngitis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
