export const sulfonamideTrimethoprimPharmacologyVisualTypes = ["folate-mechanism", "product-dosing", "clinical-selection", "renal-pk", "electrolytes", "hematologic-safety", "hypersensitivity", "interactions", "special-populations", "integration"];

const diagrams = {
  "folate-mechanism": ["Folate pathway", "Block two consecutive microbial folate steps", ["Compete", "SMX versus PABA", "Dihydropteroate synthase produces less bacterial dihydrofolate"], ["Inhibit", "TMP versus bacterial DHFR", "Conversion to tetrahydrofolate falls"], ["Deplete", "Reduced folate cofactors", "Purine, thymidine, and cellular synthesis become constrained"], ["Verify", "Organism and exposure", "Dual targets do not guarantee activity in every pathogen"]],
  "product-dosing": ["Dose translation", "Move from TMP milligrams to an exact product", ["Target", "TMP mg per kg per day", "Start with indication, weight, severity, and kidney function"], ["Divide", "TMP per dose", "Match the prescribed daily target to the interval"], ["Pair", "Five-to-one SMX amount", "Verify both active components and total exposure"], ["Dispense", "Tablet, liquid, or IV", "Convert to a measurable amount and an executable administration plan"]],
  "clinical-selection": ["Selection gate", "Let syndrome, susceptibility, and current guidance choose", ["Prioritize", "PCP treatment and prophylaxis", "Severity, oxygenation, immune criteria, renal function, and toxicity shape the plan"], ["Phenotype", "Urinary and skin infection", "Local resistance, culture, purulence, drainage, and streptococcal concern matter"], ["Update", "Invasive Stenotrophomonas", "2026 guidance no longer treats TMP-SMX as automatic preferred monotherapy"], ["Specialize", "Nocardia and opportunistic disease", "Site, immune state, combinations, intensity, and duration differ"]],
  "renal-pk": ["Kidney differential", "Separate a filtration-marker effect from tissue injury", ["Expose", "Renal elimination", "Changing kidney function changes both components and toxicity"], ["Signal", "Tubular creatinine secretion", "TMP can raise serum creatinine without equal GFR decline"], ["Contrast", "True AKI patterns", "Oliguria, active sediment, crystals, hypersensitivity, or volume loss require investigation"], ["Triangulate", "Multiple kidney measures", "Use output, urinalysis, potassium, cystatin C when useful, volume, and trend"]],
  "electrolytes": ["Nephron map", "Anticipate trimethoprim's distal electrolyte effects", ["Block", "Amiloride-like sodium entry effect", "Distal potassium secretion falls"], ["Stack", "CKD plus potassium-raising drugs", "ACE inhibitors, ARBs, MRAs, supplements, and high dose magnify risk"], ["Lose", "Sodium during high-dose therapy", "Natriuresis can resemble or coexist with other hyponatremia mechanisms"], ["Monitor", "Baseline and early repeat", "Schedule laboratories while the plan can still be changed safely"]],
  "hematologic-safety": ["Blood-cell perimeter", "Connect folate reserve, immunity, and oxidative stress", ["Suppress", "Marrow production", "High exposure, kidney dysfunction, folate deficiency, and myelotoxins increase risk"], ["Destroy", "Immune thrombocytopenia", "Abrupt purpura or bleeding requires immediate discontinuation"], ["Oxidize", "G6PD-related hemolysis", "Dose and susceptibility shape red-cell injury"], ["Activate", "HLH", "Persistent fever, cytopenias, organ enlargement, and high ferritin are urgent"]],
  "hypersensitivity": ["Reaction phenotype", "Replace the word sulfa with a complete history", ["Name", "Exact culprit and timing", "Identify the antibiotic, exposure interval, and prior tolerance"], ["Describe", "Skin, mucosa, airway, and organs", "Severity determines whether reuse can ever be considered"], ["Stop", "SJS, TEN, DRESS, or organ injury", "Life-threatening reactions require permanent avoidance"], ["Differentiate", "Nonantibiotic sulfonamides", "Universal immunologic cross-reactivity should not be assumed"]],
  "interactions": ["Interaction map", "Connect enzyme, transporter, folate, and potassium pathways", ["Raise", "Warfarin through CYP2C9", "Arrange an active INR plan or choose another antibiotic"], ["Amplify", "Methotrexate antifolate toxicity", "Avoid combined marrow and renal danger when possible"], ["Contraindicate", "Dofetilide through renal transport", "Excess exposure can cause torsade de pointes"], ["Screen", "Phenytoin, glucose, potassium, and marrow drugs", "Every action needs timing, ownership, and an alternative"]],
  "special-populations": ["Population lens", "Use exact disease and exposure instead of blanket categories", ["Infant", "Age and bilirubin context", "Current labeling contraindicates use below two months"], ["Pregnancy", "Folate pathway versus disease lethality", "PCP benefit can outweigh potential exposure risk with current guidance"], ["Lactation", "Infant maturity and G6PD", "Use product and disease-specific evidence"], ["Older adult", "Converging renal and interaction risk", "Medication reconciliation and early laboratories are central"]],
  "integration": ["Closed-loop regimen", "Make folate target, dose, safety, and exit agree", ["Define", "Syndrome and organism", "Separate infection from colonization and prevention from treatment"], ["Calculate", "TMP-based exposure", "Specify product, route, interval, renal rule, and duration"], ["Protect", "Laboratories and interactions", "Set potassium, sodium, kidney, CBC, INR, glucose, or level timing"], ["Exit", "Narrow, switch, or stop", "Reassess at culture, response, toxicity, kidney change, and end date"]],
};

export default function SulfonamideTrimethoprimPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual sulfonamide-trimethoprim-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
