export const sunscreenPhotoprotectionVisualTypes = ["uv-radiation-biology", "label-literacy", "filter-pharmacology", "application-quantity", "reapplication-water", "photoprotection-system", "special-populations", "medication-photosensitivity", "product-safety-tolerability", "monitoring-counseling"];

const diagrams = {
  "uv-radiation-biology": ["Radiation map", "Separate UVA, UVB, visible light, and the clinical signals each can create", ["UVA", "Deep and persistent", "Photoaging, pigment, oxidative injury"], ["UVB", "Erythema weighted", "Direct DNA injury and sunburn"], ["Visible", "Pigment relevant", "Can worsen melasma and dark spots"], ["Host", "Tone changes presentation", "Protection still matters across skin tones"]],
  "label-literacy": ["Read the protection claim", "A useful label answers four questions before the product reaches the skin", ["Spectrum", "UVA plus UVB", "Look for broad spectrum"], ["Factor", "UVB erythema protection", "Choose SPF 30 or higher"], ["Water", "Tested for 40 or 80 minutes", "No product is waterproof"], ["Directions", "Timing and reapplication", "The label completes the dose"]],
  "filter-pharmacology": ["Build a complete film", "Filters work as a tested formulation, not as isolated ingredient trivia", ["Mineral", "Zinc oxide or titanium dioxide", "Absorb and scatter radiation"], ["Organic", "Wavelength-specific absorption", "Combinations broaden coverage"], ["Vehicle", "Film, spread, and tolerance", "Finished product performance matters"], ["Patient", "Preference and adherence", "The best option must be used correctly"]],
  "application-quantity": ["Dose the surface", "Protection falls when timing, amount, or coverage leaves gaps", ["Before", "About 15 minutes", "Build the film before exposure"], ["Body", "At least about one ounce", "Adjust for exposed area and size"], ["Face", "At least about one teaspoon", "Include ears, edges, and hairline"], ["Lips", "Broad-spectrum SPF 30 plus", "Reapply with the rest of the plan"]],
  "reapplication-water": ["Reset the barrier", "Clock events and physical events both determine when protection must be restored", ["Clock", "At least every two hours outdoors", "Set a practical reminder"], ["Swim", "Respect 40 or 80 minutes", "Follow the exact label"], ["Sweat", "Film can move or wash away", "Reapply promptly"], ["Towel", "Friction removes product", "Do not wait for the clock"]],
  "photoprotection-system": ["Use redundant protection", "No single product replaces shade, clothing, timing, and eye protection", ["Shade", "Reduce direct exposure", "Remember reflected radiation"], ["Clothing", "Coverage and UPF", "Include a wide-brim hat"], ["Eyes", "UV-protective sunglasses", "Protect ocular tissues"], ["Plan", "UV index and schedule", "Avoid intentional tanning"]],
  "special-populations": ["Adapt without abandoning protection", "Age, pigment, sensitivity, pregnancy, lactation, and heat change the plan", ["Infant", "Shade and clothing first", "Prevent overheating"], ["Pigment", "Tint and iron oxides", "Visible-light protection can matter"], ["Sensitive", "Tolerated formulation", "Vehicle and ingredients differ"], ["Reproductive", "Product-specific assessment", "Retired letters do not decide care"]],
  "medication-photosensitivity": ["Medication and light", "Different reactions require different recognition, counseling, and escalation", ["Phototoxic", "Exaggerated sunburn", "No prior immune sensitization required"], ["Photoallergic", "Delayed eczematous pattern", "Immune mechanism"], ["Reconcile", "Exact product and label", "Include topical and OTC exposure"], ["Coordinate", "Protect without abrupt stopping", "Prescriber input preserves therapy"]],
  "product-safety-tolerability": ["Make delivery safe", "Form, vehicle, storage, and technique can introduce risks beyond ultraviolet exposure", ["Spray", "Avoid face inhalation", "Apply in still, ventilated air"], ["Flame", "Aerosols may ignite", "Keep away until fully dry"], ["Skin", "Irritation or allergy", "Switch formulation when appropriate"], ["Storage", "Heat, sun, expiration", "Protect product integrity"]],
  "monitoring-counseling": ["Close the loop", "Track use, injury, medication risk, lesions, and nutritional questions together", ["Adherence", "Amount and reapplication", "Find practical barriers"], ["Burn", "Severity and systemic symptoms", "Escalate red flags"], ["Lesion", "Changing or nonhealing", "Prompt skin evaluation"], ["Vitamin D", "Diet and supplementation", "Do not prescribe ultraviolet injury"]],
};

export default function SunscreenPhotoprotectionVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual sunscreen-photoprotection-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([value, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{value}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
