export const superficialFungalSkinInfectionsVisualTypes=["morphology-diagnosis","body-groin-disease","feet-prevention","candida-intertrigo","topical-pharmacology","hair-scalp-disease","nail-disease","resistance-failure","special-populations-follow-up"];
const diagrams={
"morphology-diagnosis":["Diagnostic map","Move from tissue and morphology to a specimen that can defend the diagnosis",["Locate","Skin, hair, or nail","Name the infected compartment"],["Read","Border, scale, moisture, follicle","Describe before treating"],["Sample","Active edge or diseased tissue","Match specimen to the question"],["Reopen","Atypical or refractory","Protect mimics and treatment-altered disease"]],
"body-groin-disease":["Connected reservoirs","Treat the plaque, its boundary, and every route back to the skin",["Map","Body and groin","Define extent and competing diagnoses"],["Treat","Complete labeled course","Continue beyond early symptom relief"],["Inspect","Feet and nails","Find autoinoculation reservoirs"],["Audit","Product through exposure","Verify before escalating"]],
"feet-prevention":["Foot system","Skin, nail, shoe, moisture, sensation, and circulation shape recurrence",["Pattern","Interdigital, moccasin, vesicular","Choose therapy and vehicle"],["Dry","Toe spaces and footwear","Reduce the fungal environment"],["Protect","Fissure and high-risk host","Prevent bacterial entry"],["Escalate","Pain, pus, fever, spread","Separate cellulitis from tinea"]],
"candida-intertrigo":["Fold ecology","Moisture and friction interact with organism and host",["Clue","Satellite papules or pustules","Support candidal disease"],["Compare","Erythrasma, psoriasis, irritant","Do not equate fold rash with Candida"],["Change","Dryness and friction","Treat the local environment"],["Investigate","Frequent recurrence","Review metabolic and immune drivers"]],
"topical-pharmacology":["Ergosterol and delivery","Match molecular target to organism, tissue, vehicle, and technique",["SQLE","Allylamines","Block squalene epoxidase"],["CYP51","Azoles","Block lanosterol demethylation"],["Vehicle","Cream, solution, spray, powder","Move drug across the right surface"],["Teach","Boundary, amount, duration","Make exposure executable"]],
"hair-scalp-disease":["Follicular exposure","Hair shaft infection changes treatment and transmission",["Recognize","Scale, broken hair, alopecia","Identify the scalp pattern"],["Urgency","Tender boggy kerion","Protect against scarring"],["Systemic","Oral antifungal","Reach the infected follicle"],["Contain","Contacts and hair tools","Reduce shared exposure"]],
"nail-disease":["Nail timeline","Confirm the organism, manage systemic risk, then wait for growth",["Prove","Clipping or subungual sample","Exclude nonfungal dystrophy"],["Select","Extent, matrix, patient risk","Justify oral or topical therapy"],["Protect","Liver and interaction review","Use systemic treatment safely"],["Measure","Proximal clear growth","Separate slow growth from failure"]],
"resistance-failure":["Failure investigation","Audit diagnosis and exposure before moving to specialized resistance testing",["Verify","Diagnosis and complete course","Exclude ordinary failure"],["Recognize","Severe, widespread, persistent","Consider emerging dermatophytes"],["Refer","Molecular and susceptibility testing","Use specialized laboratories"],["Steward","Avoid steroid combinations","Reduce pressure and delay"]],
"special-populations-follow-up":["Closed-loop care","Connect product-specific risk to an observable response and safety plan",["Context","Age, pregnancy, liver, immune","Individualize exposure"],["Reconcile","Drug and pathway interactions","Name the actual systemic product"],["Teach back","Where, how much, how long","Confirm safe execution"],["Return","Response and toxicity targets","Define the next decision"]],
};
export default function SuperficialFungalSkinInfectionsVisual({type}){const x=diagrams[type];if(!x)return null;const [eyebrow,title,...nodes]=x;return <figure className="chol-visual fungal-skin-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([v,f,d],i)=><div key={f}><span>{String(i+1).padStart(2,"0")}</span><strong>{v}</strong><em>{f}</em><p>{d}</p></div>)}</div></figure>}
