const diagrams = {
  "gc-signaling": { eyebrow: "HPA physiology", title: "One signal controls inflammation and feedback", accent: "#d7a56f", columns: [["Signal", "CRH to ACTH", "The hypothalamus and pituitary drive adrenal cortisol production."], ["Act", "Intracellular receptor", "The activated receptor changes inflammatory and metabolic gene expression."], ["Return", "Negative feedback", "Cortisol and exogenous drug suppress upstream CRH and ACTH release."]] },
  "gc-equivalence": { eyebrow: "Potency map", title: "Equivalent does not mean identical", accent: "#cfb27f", columns: [["20 mg", "Hydrocortisone", "Short acting with meaningful mineralocorticoid activity."], ["5 mg", "Prednisone", "Intermediate acting and converted to active prednisolone."], ["0.5 mg", "Dexamethasone", "Long acting with high potency and minimal salt retention."]] },
  "gc-treatment-plan": { eyebrow: "Therapy architecture", title: "Start with the end already visible", accent: "#deb873", columns: [["Purpose", "Name the target", "Define the disease, desired response, and time horizon."], ["Exposure", "Choose route and dose", "Use the most targeted effective regimen for the shortest necessary duration."], ["Exit", "Set reassessment", "Document when to stop, taper, switch, or add steroid-sparing care."]] },
  "gc-hpa-risk": { eyebrow: "Suppression risk", title: "The axis sees total exposure", accent: "#b99bd2", columns: [["Dose", "Above physiologic", "Prednisone above about 4 to 6 mg daily can become relevant with duration."], ["Time", "Three to four weeks", "Sustained exposure makes endogenous recovery a discontinuation concern."], ["Amplify", "Routes and interactions", "Multiple products and CYP3A4 inhibition can raise cumulative exposure."]] },
  "gc-taper": { eyebrow: "Recovery sequence", title: "The taper changes character near physiology", accent: "#8fb2d2", columns: [["Control", "Confirm disease stability", "The original condition must no longer require the current dose."], ["Reduce", "Larger steps up high", "Supraphysiologic doses often permit faster initial reductions."], ["Recover", "Smaller steps down low", "Near physiologic dosing, withdrawal and HPA recovery guide the pace."]] },
  "gc-stress": { eyebrow: "Emergency logic", title: "Stress changes dose and route", accent: "#d98c73", columns: [["Minor", "Oral coverage", "Use when stress is limited and oral absorption remains reliable."], ["Major", "Parenteral coverage", "Use for major illness, anesthesia, instability, or inability to take oral therapy."], ["Crisis", "Treat before proof", "Give parenteral glucocorticoid and fluids without waiting for laboratory certainty."]] },
  "gc-metabolic": { eyebrow: "Toxicity timing", title: "Monitor where the exposure lands", accent: "#c9906f", columns: [["Day", "Glucose and pressure", "Morning prednisone often drives afternoon and evening hyperglycemia."], ["Mind", "Sleep and behavior", "Insomnia, mood change, mania, delirium, and psychosis require active surveillance."], ["Gut", "Layered bleeding risk", "NSAIDs, anticoagulants, history, and illness change the protection plan."]] },
  "gc-infection-vaccine": { eyebrow: "Prevention window", title: "Protect before immune response changes", accent: "#8fac86", columns: [["Infection", "Expect muted signs", "Immunosuppression can blunt fever while infection progresses."], ["Live", "Time for safety", "Dose and duration determine deferral and the post-treatment waiting period."], ["Non-live", "Safe, response may vary", "Give indicated vaccines while recognizing that effectiveness can be reduced."]] },
  "gc-bone-tissue": { eyebrow: "Quiet toxicity", title: "Protect the structures that change slowly", accent: "#c9b879", columns: [["Bone", "Assess fracture risk", "Duration, dose, age, history, density, and falls shape prevention."], ["Tissue", "Test strength and healing", "Proximal myopathy and skin fragility can emerge during sustained exposure."], ["Eyes and growth", "Measure longitudinally", "Monitor ocular effects and pediatric growth before loss becomes obvious."]] },
  "gc-longitudinal": { eyebrow: "Cumulative safety", title: "One exposure record, every formulation", accent: "#d3a474", columns: [["Collect", "Every route", "Include tablets, injections, inhalers, creams, eye products, and procedures."], ["Connect", "Interactions and outcomes", "Track CYP3A4 changes, glucose, bone, eyes, muscle, skin, and growth."], ["Handoff", "One authoritative plan", "Carry the indication, taper, stress instructions, and next decision across care."]] },
};

export default function SystemicGlucocorticoidsVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual systemic-glucocorticoids-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
