const diagrams = {
  "sle-recognition": { eyebrow: "Clinical pattern", title: "One disease can appear across many organs", accent: "#d68f88", columns: [["Phenotype", "Map the whole patient", "Connect skin, joints, blood, kidney, nervous system, lungs, heart, and vessels."], ["Evidence", "Support, do not substitute", "Use serology, complement, urine, imaging, and examination to strengthen clinical judgment."], ["Boundary", "Run the dangerous mimic", "Evaluate infection, toxicity, thrombosis, malignancy, and fixed damage beside the flare."]] },
  "sle-immunity": { eyebrow: "Immune architecture", title: "Loss of tolerance becomes tissue injury", accent: "#a98bc2", columns: [["Signal", "Nucleic acids and interferon", "Innate sensing amplifies type I interferon programs and inflammatory gene expression."], ["Survival", "BLyS supports B cells", "Autoreactive B cells persist, differentiate, and contribute to autoantibody production."], ["Injury", "Immune complexes deposit", "Complement activation and local inflammation translate systemic autoimmunity into organ damage."]] },
  "sle-targets": { eyebrow: "Treat to target", title: "Control activity before it becomes damage", accent: "#d5ad72", columns: [["Now", "Find active inflammation", "Name the organ, severity, dangerous alternative, and immediate treatment target."], ["Next", "Reduce steroid exposure", "Use early steroid-sparing therapy and taper glucocorticoids as control becomes durable."], ["Over time", "Separate damage from activity", "Do not intensify immunosuppression for fixed injury or a noninflammatory symptom pattern."]] },
  "sle-hcq": { eyebrow: "Foundation therapy", title: "Hydroxychloroquine needs a complete safety system", accent: "#d3c080", columns: [["Expose", "Use actual body weight", "Keep the long-term average at 5 mg/kg per day or less unless a deliberate exception is justified."], ["Protect", "Plan retinal surveillance", "Match eye follow-up to dose, duration, kidney function, tamoxifen, and macular risk."], ["Respond", "Recognize systemic toxicity", "Investigate new conduction disease, cardiomyopathy, hypoglycemia, weakness, rash, or blood abnormalities."]] },
  "sle-organs": { eyebrow: "Organ-directed care", title: "The most vulnerable organ sets the pace", accent: "#cf8f78", columns: [["Surface", "Skin and joints", "Build from photoprotection and hydroxychloroquine toward durable steroid-sparing control."], ["System", "Blood and serosa", "Grade urgency, exclude competing causes, and match treatment to bleeding or physiologic risk."], ["Threat", "Brain, lungs, and heart", "Treat inflammatory emergencies in combination while evaluating infection, ischemia, embolism, and damage."]] },
  "sle-conventional": { eyebrow: "Conventional therapy", title: "Each immunosuppressant carries a different map", accent: "#8eaf91", columns: [["Fit", "Methotrexate or azathioprine", "Match the active organ, monitoring burden, interactions, and reproductive plan."], ["Build", "Mycophenolate or calcineurin inhibition", "Use organ-specific evidence and follow blood, kidney, pressure, infection, and exposure."], ["Escalate", "Cyclophosphamide for severity", "Balance urgent disease control against marrow, bladder, malignancy, gonadal, and cumulative toxicity."]] },
  "sle-biologics": { eyebrow: "Targeted therapy", title: "Related pathways are not interchangeable", accent: "#7fa7c7", columns: [["BLyS", "Belimumab", "Reduce soluble B-cell survival signaling within its labeled age, route, and organ boundaries."], ["IFNAR1", "Anifrolumab", "Block type I interferon signaling for appropriate adult nonrenal disease."], ["CD20", "B-cell depletion", "Separate guideline use from current FDA indications and preserve infusion, infection, and hepatitis planning."]] },
  "sle-nephritis": { eyebrow: "Kidney protection", title: "Detect early, biopsy deliberately, combine intelligently", accent: "#8aa7a1", columns: [["Screen", "Quantify urine protein", "Look even when symptoms are quiet and accelerate evaluation during extra-renal activity."], ["Classify", "Use kidney biopsy", "Distinguish active, chronic, proliferative, and membranous injury before choosing a regimen."], ["Respond", "Track the renal trajectory", "Use proteinuria, kidney function, pressure, urine sediment, exposure, and toxicity to judge response."]] },
  "sle-prevention": { eyebrow: "Risk prevention", title: "Treatment must protect the future", accent: "#c99b76", columns: [["Prevent", "Vaccines and infection", "Coordinate non-live vaccines, selected medication timing, exposure screening, and an infection plan."], ["Preserve", "Bone and vascular health", "Reduce glucocorticoid burden and address pressure, lipids, tobacco, diabetes, activity, and screening."], ["Plan", "Reproduction and thrombosis", "Make medication transitions, antibody context, fertility, contraception, and pregnancy goals visible before conception."]] },
  "sle-longitudinal": { eyebrow: "Continuity", title: "The timeline becomes the authoritative record", accent: "#a7aa83", columns: [["History", "Record every involved organ", "Capture prior responses, toxicities, access failures, damage, and the reason for each change."], ["Present", "Measure control precisely", "Document active exposure, disease activity, organ function, safety monitoring, and current holds."], ["Future", "Own the next decision", "State the target, taper or escalation trigger, urgent flare plan, and responsible clinician."]] },
};

export default function SystemicLupusErythematosusVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual systemic-lupus-erythematosus-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
