export const tetracyclinePharmacologyVisualTypes = ["structure-mechanism", "agent-differences", "clinical-selection", "pk-dosing", "administration", "common-safety", "serious-safety", "special-populations", "resistance-stewardship", "clinical-integration"];

const diagrams = {
  "structure-mechanism": ["Ribosomal route", "Follow the four-ring scaffold to stalled bacterial protein synthesis", ["Enter", "Reach the bacterium", "Exposure, site, and susceptibility determine useful intracellular concentration"], ["Bind", "30S ribosomal subunit", "The conserved pharmacophore binds reversibly near the A site"], ["Block", "Aminoacyl-tRNA entry", "Incoming charged tRNA cannot efficiently enter the acceptor site"], ["Slow", "Protein elongation", "The usual effect is bacteriostatic in susceptible organisms"]],
  "agent-differences": ["Agent map", "Keep each tetracycline in its own clinical lane", ["Doxycycline", "Broad guideline roles", "High oral utility with esophageal, cation, sun, and intracranial pressure precautions"], ["Minocycline", "Distinctive toxicity", "Vestibular, pigmentation, autoimmune, hepatic, and hypersensitivity risks"], ["Omadacycline", "CABP and ABSSSI", "Product-specific fasting sequence and current May 2026 labeling"], ["Eravacycline", "IV cIAI therapy", "Source control and strong CYP3A-inducer management remain central"]],
  "clinical-selection": ["Selection gate", "Prove the syndrome before choosing broad activity", ["Urgent", "Suspected RMSF", "Start doxycycline promptly in patients of all ages without waiting for testing"], ["Transmit", "Chlamydial infection", "Connect treatment with site testing, partners, abstinence, and retesting"], ["Localize", "Skin and Lyme disease", "Phenotype, source control, stage, and prophylaxis criteria determine use"], ["Steward", "Acne and respiratory roles", "Use current guidance, topical partners, susceptibility, and a defined duration"]],
  "pk-dosing": ["Product logic", "Translate the order into the exact agent and dosage form", ["Identify", "Product and release design", "Do not crush or substitute without verifying delivery"], ["Calculate", "Age, weight, kidney, liver", "Agent-specific disposition replaces class-wide adjustment"], ["Prepare", "Route and formulation", "Suspension, tablet, capsule, and IV products require exact instructions"], ["Transition", "IV to oral deliberately", "Require stability, absorption, activity, administration feasibility, and follow-up"]],
  "administration": ["Administration clock", "Protect absorption, the esophagus, and delivery", ["Inventory", "Every polyvalent cation", "Map minerals, antacids, dairy, bismuth, multivitamins, and tube feeds"], ["Separate", "Use the exact label", "Food and spacing rules differ by product"], ["Protect", "Water and posture", "Reduce pill contact by using sufficient fluid and avoiding immediate recumbency"], ["Verify", "Feeding-tube plan", "Confirm dosage-form compatibility, feed timing, flushes, and restart"]],
  "common-safety": ["Safety perimeter", "Separate expected intolerance from emerging injury", ["Sun", "Phototoxicity", "Reduce ultraviolet exposure and respond to exaggerated sunburn"], ["Gut", "Tolerance versus C difficile", "Severity, stool pattern, fever, blood, and timing determine response"], ["Liver", "Hepatic warning signs", "Jaundice, dark urine, pruritus, or systemic illness require assessment"], ["Immune", "Skin and mucosa", "Facial edema, mucosal lesions, fever, or organ involvement are urgent"]],
  "serious-safety": ["Signal map", "Recognize the vision and minocycline hazards early", ["Vision", "Intracranial hypertension", "Headache, visual obscurations, diplopia, or papilledema require urgent evaluation"], ["Avoid", "Isotretinoin risk stack", "Do not combine two intracranial-pressure risks casually"], ["Balance", "Minocycline vestibular effects", "Vertigo and dizziness can impair driving and work"], ["Immune", "Lupus, hepatitis, DRESS", "Systemic findings during minocycline therapy require prompt discontinuation and evaluation"]],
  "special-populations": ["Benefit-risk lens", "Replace historic blanket rules with current evidence", ["Child", "Disease-specific urgency", "Doxycycline remains first-line for suspected rickettsial disease at every age"], ["Pregnancy", "Timing and untreated disease", "Use current narrative evidence and disease guidance"], ["Lactation", "Exact agent and interval", "Newer products can require explicit interruption after the final dose"], ["Develop", "Teeth and bone", "Retain active warnings while distinguishing short-course doxycycline evidence"]],
  "resistance-stewardship": ["Resistance map", "Track how bacteria reduce exposure or protect the ribosome", ["Export", "Efflux pumps", "Intracellular drug concentration falls"], ["Protect", "Tet(M) and related proteins", "The bacterial ribosome becomes less vulnerable"], ["Modify", "Inactivation and target change", "Mechanisms vary by organism and agent"], ["Measure", "AST and response", "Newer structures do not guarantee activity at every site"]],
  "clinical-integration": ["Closed-loop regimen", "Make diagnosis, exposure, safety, and exit agree", ["Define", "Syndrome and organism", "Prove a treatable problem and identify the evidence source"], ["Execute", "Product, dose, timing", "Connect formulation, organ function, cations, water, posture, and adherence"], ["Protect", "Patient-specific monitoring", "Track response, rash, GI, liver, headache, vision, and agent-specific harms"], ["Exit", "Narrow, switch, or stop", "Reassess at diagnostic result, clinical change, toxicity signal, and end date"]],
};

export default function TetracyclinePharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual tetracycline-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
