const diagrams = {
  "thyroid-axis": ["Feedback axis", "Read the signal from hypothalamus to tissue and back", ["Signal", "TRH to TSH", "Pituitary TSH stimulates synthesis, release, and thyroid growth"], ["Deliver", "T4 and T3", "The gland releases mostly T4 and tissues generate much of T3"], ["Interpret", "Negative feedback", "Free hormone suppresses TRH and TSH unless central disease disrupts the axis"]],
  "thyroid-hypothyroidism": ["Diagnostic map", "Classify the biochemical pattern before choosing treatment", ["Primary", "High TSH and low free T4", "The thyroid gland cannot meet demand"], ["Subclinical", "High TSH and normal free T4", "Repeat, contextualize, and assess progression risk"], ["Central", "Low free T4 without high TSH", "Evaluate pituitary function and adrenal safety"]],
  "thyroid-levothyroxine": ["Replacement design", "Create a stable and interpretable exposure", ["Select", "Starting intensity", "Match dose to severity, size, age, cardiac reserve, and pregnancy"], ["Administer", "Consistent absorption", "Control food, supplements, binders, and formulation changes"], ["Adjust", "One measured change", "Reassess after a new steady pattern forms"]],
  "thyroid-monitoring": ["Unstable TSH", "Investigate the exposure before increasing the dose", ["Reconstruct", "How it is taken", "Timing, missed doses, catch-up behavior, storage, and product"], ["Interrogate", "What changed", "Food, calcium, iron, medicines, weight, pregnancy, and gut function"], ["Protect", "Avoid overreplacement", "Use symptoms, TSH or free T4 context, rhythm, and bone risk"]],
  "thyroid-myxedema": ["Decompensated hypothyroidism", "Restore physiology while replacing hormone", ["Support", "Airway and circulation", "Ventilation, careful warming, glucose, sodium, and perfusion"], ["Cover", "Possible adrenal failure", "Obtain samples when feasible and give stress-dose glucocorticoid"], ["Replace", "IV thyroid hormone", "Individualize loading and maintenance to severity and cardiac risk"]],
  "thyroid-thyrotoxicosis": ["Cause first", "Determine why thyroid hormone action is excessive", ["Synthesize", "Graves or autonomy", "High gland activity can respond to thionamide therapy"], ["Release", "Destructive thyroiditis", "Stored hormone leaks from damaged follicles"], ["Receive", "Exogenous or iodine related", "Exposure history redirects testing and treatment"]],
  "thyroid-thionamides": ["Antithyroid selection", "Block synthesis while managing rare serious toxicity", ["Prefer", "Methimazole", "Routine first choice for most nonpregnant patients"], ["Reserve", "Propylthiouracil", "Early pregnancy, storm, or defined methimazole intolerance"], ["Escalate", "Urgent symptoms", "Fever, severe sore throat, jaundice, or dark urine need prompt evaluation"]],
  "thyroid-adjuncts": ["Adjunctive control", "Assign every therapy a physiologic job", ["Quiet", "Beta blockade", "Reduce adrenergic symptoms with hemodynamic awareness"], ["Block", "Thionamide before iodine", "Stop synthesis before inhibiting release"], ["Accelerate", "Steroid or binding resin", "Reduce conversion or increase elimination in selected severe states"]],
  "thyroid-definitive": ["Long-term strategy", "Choose the durable path from patient and disease constraints", ["Continue", "Antithyroid therapy", "Preserve the gland with adherence, toxicity, and relapse tradeoffs"], ["Ablate", "Radioactive iodine", "Avoid in pregnancy and consider eye disease and delayed effect"], ["Remove", "Surgery", "Favor rapid control or structural indications with operative planning"]],
  "thyroid-storm": ["Emergency sequence", "Treat decompensated thyrotoxicosis as organ failure", ["Stabilize", "Support organs", "Airway, circulation, temperature, glucose, volume, and trigger"], ["Block", "Synthesis then release", "Thionamide comes before iodine"], ["Modulate", "Conversion and adrenergic drive", "Use steroids and hemodynamically appropriate beta blockade"]],
  "thyroid-pregnancy": ["Reproductive continuum", "Protect maternal control and fetal thyroid development", ["Anticipate", "Changing hormone needs", "Adjust levothyroxine early and monitor in pregnancy context"], ["Choose", "Gestation-aware antithyroid therapy", "Balance methimazole embryopathy and PTU liver risk"], ["Follow", "Antibodies and postpartum change", "TRAb can affect the fetus and postpartum causes can diverge"]],
};

export default function ThyroidDisordersVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
