const diagrams = {
  "thychem-biosynthesis": ["Chemical assembly", "Build thyroid hormone inside thyroglobulin", ["Capture", "Iodide transport", "NIS concentrates iodide and apical transport delivers it to the lumen"], ["Attach", "TPO organification", "Oxidized iodine forms MIT and DIT on tyrosyl residues"], ["Couple", "T3 and T4", "MIT plus DIT forms T3 while DIT plus DIT forms T4"]],
  "thychem-scaffold": ["Molecular anatomy", "Read the iodinated thyronine framework", ["Anchor", "Amino-acid side chain", "A chiral alpha carbon carries amino and carboxyl groups"], ["Bridge", "Diphenyl ether", "An oxygen atom joins the inner and outer aromatic rings"], ["Tune", "Iodine pattern", "Position and count distinguish T4, T3, and inactive metabolites"]],
  "thychem-stereo": ["Three-dimensional recognition", "Structure becomes a tissue signal", ["Orient", "Natural L form", "The chiral center places the side chain for biologic recognition"], ["Transport", "Cellular entry", "Membrane transporters help determine tissue hormone exposure"], ["Bind", "TR alpha and TR beta", "T3 stabilizes receptor complexes that control transcription"]],
  "thychem-deiodination": ["Metabolic switch", "Ring selection directs hormone activity", ["Activate", "Outer-ring removal", "T4 becomes receptor-active T3"], ["Localize", "DIO2 tissue control", "Selected tissues create intracellular T3 near its receptor"], ["Inactivate", "Inner-ring removal", "T4 becomes reverse T3 and T3 can become T2"]],
  "thychem-analogs": ["Replacement comparison", "One iodine changes the exposure profile", ["Buffer", "Levothyroxine or T4", "Long persistence and tissue conversion support stable replacement"], ["Signal", "Liothyronine or T3", "Direct receptor-active hormone acts faster and clears sooner"], ["Formulate", "Sodium salts", "Pharmaceutical salt forms support handling and dissolution"]],
  "thychem-thionamides": ["Antithyroid scaffolds", "Sulfur-bearing rings interrupt synthesis", ["Imidazole", "Methimazole", "A compact mercaptoimidazole scaffold blocks TPO-dependent chemistry"], ["Thiouracil", "Propylthiouracil", "A propyl-substituted pyrimidinethione also blocks synthesis"], ["Differentiate", "Peripheral conversion", "PTU additionally inhibits type 1 conversion of T4 to T3"]],
  "thychem-iodine": ["One element, several roles", "Isotope and dose determine the task", ["Supply", "Stable iodide", "Nutrient substrate enters hormone synthesis"], ["Trace", "Iodine-123", "Short-lived photon emission supports diagnostic imaging"], ["Treat", "Iodine-131", "Beta emission damages iodine-concentrating thyroid tissue"]],
  "thychem-formulation": ["Exposure integrity", "Protect a microgram-dose medicine from product to patient", ["Preserve", "Potency and storage", "Moisture, heat, light, and product quality can alter delivered dose"], ["Release", "Dissolution and gastric context", "Dosage form and gastrointestinal conditions shape availability"], ["Avoid", "Binding and complexation", "Calcium, iron, binders, food, and feeds can reduce absorption"]],
};

export default function ThyroidMedicinalChemistryVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__flow">{columns.map(([name, focus, detail], index) => <div className="chol-visual__node" key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
