export const tigecyclinePharmacologyVisualTypes = ["structure-mechanism", "spectrum-resistance", "indications-evidence", "mortality-site-selection", "dosing-pk", "hepatic-administration", "gastrointestinal-pancreatic", "coagulation-interactions", "special-populations", "integration"];

const diagrams = {
  "structure-mechanism": ["Translation gate", "A modified tetracycline scaffold prevents the next amino acid from entering", ["Modify", "Glycylcycline scaffold", "The side chain reduces vulnerability to common tetracycline resistance."], ["Bind", "30S ribosome", "Tigecycline occupies the bacterial translation machinery."], ["Exclude", "Aminoacyl-tRNA", "The next charged tRNA cannot enter the A site."], ["Suppress", "Peptide elongation", "Protein synthesis and bacterial growth slow."]],
  "spectrum-resistance": ["Coverage boundary", "Broad tissue activity still contains decisive organism gaps", ["Cover", "Selected gram-positive", "Use current susceptibility within a supported syndrome."], ["Cover", "Selected anaerobes", "Pair activity with drainage and source control."], ["Exclude", "Pseudomonas and Proteeae", "Proteus, Providencia, and Morganella need another plan."], ["Recheck", "Multidrug efflux", "Poor response can reflect acquired or selected resistance."]],
  "indications-evidence": ["Evidence map", "Three adult indications sit inside two explicit exclusions", ["Use", "Complicated skin", "Confirm depth, organism, and source control."], ["Use", "Complicated abdomen", "Culture and drain whenever possible."], ["Use", "Community pneumonia", "Do not extend this evidence to hospital pneumonia."], ["Exclude", "DFI, HAP, and VAP", "Choose an evidence-supported alternative."]],
  "mortality-site-selection": ["Reserve decision", "The boxed warning turns alternative analysis into a clinical requirement", ["Measure", "Mortality signal", "Adjusted risk difference was 0.6 percent."], ["Avoid", "VAP", "Lower cure and higher mortality define a firm boundary."], ["Respect", "Low serum exposure", "Large tissue distribution weakens primary bacteremia use."], ["Document", "Why alternatives fail", "State inactivity, toxicity, allergy, or another concrete limit."]],
  "dosing-pk": ["Exposure map", "Loading, tissue distribution, and biliary elimination explain the regimen", ["Load", "100 mg IV once", "Establish intended exposure promptly."], ["Maintain", "50 mg every 12 hours", "Infuse each dose over about 30 to 60 minutes."], ["Distribute", "500 to 700 liters", "High tissue movement means lower intravascular concentration."], ["Eliminate", "Biliary and fecal", "Renal impairment and dialysis do not change the dose."]],
  "hepatic-administration": ["Vial workflow", "The liver and the preparation record belong in one order", ["Adjust", "Child Pugh C", "Keep the 100 mg load, then use 25 mg every 12 hours."], ["Reconstitute", "5.3 mL to 10 mg/mL", "Gently swirl one 50 mg single-dose vial."], ["Withdraw", "5 mL equals 50 mg", "The extra volume accounts for a 6 percent overage."], ["Dilute", "100 mL final bag", "Inspect yellow to orange solution and infuse over 30 to 60 minutes."]],
  "gastrointestinal-pancreatic": ["Symptom triage", "Common intolerance and organ injury can begin with the same complaint", ["Expect", "Nausea and vomiting", "Measure severity, hydration, nutrition, and treatment burden."], ["Escalate", "Epigastric pain", "Evaluate lipase and pancreatitis without delay."], ["Trend", "Liver function", "Injury can worsen after the drug is stopped."], ["Test", "Significant diarrhea", "Consider C. difficile during and after therapy."]],
  "coagulation-interactions": ["Measured safety", "Coagulation and interacting medicines need assigned surveillance", ["Baseline", "Fibrinogen", "Repeat regularly throughout the course."], ["Measure", "Warfarin effect", "Use PT, INR, or another suitable test."], ["Measure", "Tacrolimus trough", "Concentrations can rise during coadministration."], ["Respond", "Bleeding or toxicity", "Reassess the antibiotic and every competing cause."]],
  "special-populations": ["Developmental timing", "Current narrative risk replaces retired pregnancy letters", ["Explain", "Second and third trimester", "Developing teeth and bone can be affected."], ["Limit", "Pediatric use", "Use only when no suitable alternative is available."], ["Plan", "Lactation", "Duration and infant-exposure reduction belong in the decision."], ["Document", "Benefit and alternative", "Severity and active options determine whether risk is justified."]],
  "integration": ["Closed-loop regimen", "Make evidence, exposure, response, and exit agree", ["Define", "Supported syndrome", "Confirm site, organism, severity, and source."], ["Justify", "Reserve use", "Show why safer active alternatives are unsuitable."], ["Execute", "Dose and preparation", "Make every vial, volume, and infusion reconstructable."], ["Exit", "Narrow, stop, or switch", "Use cultures, response, fibrinogen, liver, and symptoms."]],
};

export default function TigecyclinePharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual tigecycline-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={`${verb}-${focus}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
