const diagrams = {
  "tobacco-dependence": { eyebrow: "Dependence circuit", title: "Exposure becomes a learned loop", accent: "#d99a6c", columns: [["Dose", "Receptor activation", "Rapid nicotine delivery stimulates reward pathways."], ["Adapt", "Tolerance and withdrawal", "Repeated exposure changes the response to falling nicotine levels."], ["Cue", "Context reinforcement", "Routines and stress begin to predict and trigger another dose."]] },
  "tobacco-plan": { eyebrow: "Treatment architecture", title: "A quit attempt needs more than a date", accent: "#e4bd72", columns: [["Prepare", "Name cues", "Identify routines, stressors, support, and the desired change."], ["Treat", "Behavior plus medicine", "Control withdrawal while replacing learned responses."], ["Return", "Follow and recover", "Review response early and use a lapse to strengthen the plan."]] },
  "tobacco-nrt-system": { eyebrow: "Nicotine replacement", title: "Baseline control meets craving rescue", accent: "#c3ab78", columns: [["Patch", "Slow background delivery", "Reduces baseline withdrawal across the day."], ["Rescue", "Rapid local delivery", "Gum or lozenge addresses a breakthrough craving."], ["Review", "Total nicotine exposure", "Symptoms, all products, and correct technique guide adjustment."]] },
  "tobacco-patch": { eyebrow: "Transdermal delivery", title: "One steady input, four safety controls", accent: "#c79b65", columns: [["Apply", "Clean intact skin", "Rotate sites and avoid direct heat or irritated skin."], ["Balance", "Sleep and morning craving", "Overnight wear is adjusted to benefit and tolerability."], ["Secure", "Residual nicotine", "Fold used patches and protect children and pets."]] },
  "tobacco-oral-nrt": { eyebrow: "Buccal delivery", title: "Technique controls the dose", accent: "#d7b783", columns: [["Release", "Chew or dissolve slowly", "Create controlled contact with the oral mucosa."], ["Hold", "Park at the cheek", "Limit swallowed nicotine and gastrointestinal effects."], ["Protect", "Pause food and drinks", "Avoid acidic beverages around the dose."]] },
  "tobacco-prescription-nrt": { eyebrow: "Rapid prescription NRT", title: "Choose speed without losing fit", accent: "#cf8f72", columns: [["Inhaler", "Shallow oral puffs", "Buccal absorption supports ritual replacement."], ["Nasal", "Fast mucosal delivery", "One spray per nostril treats intense cravings."], ["Select", "Local anatomy matters", "Airway, nasal disease, irritation, and preference change the choice."]] },
  "tobacco-varenicline": { eyebrow: "Partial agonism", title: "Reduce withdrawal and blunt reward", accent: "#b99cd7", columns: [["Occupy", "Alpha4beta2 receptors", "Partial stimulation reduces withdrawal without nicotine replacement."], ["Limit", "Nicotine reinforcement", "Receptor occupancy reduces the rewarding effect of smoking."], ["Adjust", "Titration and kidney function", "Flexible starts and renal limits make the regimen patient specific."]] },
  "tobacco-bupropion": { eyebrow: "Non-nicotine therapy", title: "Protect the benefit with dose discipline", accent: "#8fb4d5", columns: [["Prime", "Begin before quitting", "Steady exposure develops during the first treatment week."], ["Space", "At least eight hours", "SR integrity and timing reduce avoidable peak exposure."], ["Screen", "Seizure and pressure risk", "Contraindications, duplicate therapy, and monitoring define safety."]] },
  "tobacco-special-populations": { eyebrow: "Evidence boundaries", title: "The patient changes the decision frame", accent: "#9fb68b", columns: [["Pregnancy", "Behavior first", "Medication requires an individualized uncertainty discussion."], ["Adolescence", "Current ATS guidance", "Counseling anchors care and selected medicines may be considered."], ["Comorbidity", "Coordinate, do not exclude", "Psychiatric and cardiovascular conditions require monitoring, not stigma."]] },
  "tobacco-longitudinal": { eyebrow: "Maintenance care", title: "The quit date begins the follow-up", accent: "#dfaa76", columns: [["Monitor", "Symptoms and technique", "Review withdrawal, adverse effects, adherence, and lapses."], ["Reconcile", "Smoke-related interactions", "CYP1A2 substrate exposure can rise when combustion stops."], ["Maintain", "Extend and protect", "Plan duration, high-risk situations, and rapid recovery."]] },
};

export default function TobaccoUseCessationVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual tobacco-cessation-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
