const diagrams = {
  "tox-methylxanthine": {"eyebrow": "Exposure and trajectory", "title": "Treat deterioration before waiting for a threshold", "accent": "#d6aa6a", "columns": [["Identify", "Agent and formulation", "Caffeine and theophylline need exposure-specific interpretation."], ["Follow", "Clinical course", "Connect concentrations with symptoms and their direction of change."], ["Escalate", "Severe toxicity", "Coordinate resuscitation and removal with specialists."]]},
  "tox-ethanol": {"eyebrow": "Separate treatment goals", "title": "Support physiology and identify the additional risk", "accent": "#d6aa6a", "columns": [["Stabilize", "Breathing and glucose", "Treat the immediate threat before completing the exposure history."], ["Protect", "Nutritional risk", "Distinguish prevention from treatment of suspected Wernicke disease."], ["Reassess", "Withdrawal and alternatives", "A detectable ethanol level does not settle the diagnosis."]]},
  "tox-anticoagulant": { eyebrow: "Distinct reversal mechanisms", title: "Drug binding and factor replacement are different", accent: "#d6aa6a", columns: [["Dabigatran", "Idarucizumab", "Bind the specific drug; reassess recurrent anticoagulant effect."], ["Warfarin", "PCC with vitamin K", "Replace deficient factors and sustain their production."], ["Factor Xa inhibitors", "Current hemostatic pathway", "Use current U.S. options; the warfarin INR table does not apply."]] },
  "tox-serotonin": { eyebrow: "Examination and urgency", title: "Treat the clinical course, not a checklist alone", accent: "#d6aa6a", columns: [["Recognize", "Exposure plus examination", "Clonus and hyperreflexia help identify the pattern; severe rigidity can obscure them."], ["Stabilize", "Breathing and temperature", "Escalate respiratory failure and hyperthermia before waiting for an adjunctive drug response."], ["Reassess", "Recovery and alternatives", "Response to cyproheptadine alone does not establish the diagnosis or readiness for discharge."]] },
  "tox-alcohol": {"eyebrow": "Two treatment clocks", "title": "Block formation while removing the burden", "accent": "#d6aa6a", "columns": [["Block", "Antidote delivery", "Track each dose and reconcile the schedule when dialysis starts or stops."], ["Remove", "Toxin-specific criteria", "Use the right concentration units, gap formula and clinical indications."], ["Reassess", "Separate endpoints", "Metabolic recovery, kidney support and antidote completion require distinct decisions."]]},
  "tox-salicylate": {"eyebrow": "Salicylate rescue", "title": "Read three signals together", "accent": "#d6aa6a", "columns": [["Patient", "Neurologic and respiratory course", "A lower reported level does not cancel worsening organ injury."], ["Chemistry", "Blood and urine pH", "Track separate targets and potassium during alkalinization."], ["Elimination", "Response and dialysis", "Escalate on clinical criteria as well as concentration."]]},
  "tox-valproate": {"eyebrow": "Valproate rescue", "title": "Three signals, one evolving patient", "accent": "#d6aa6a", "columns": [["Clinical", "Brain and circulation", "Support ventilation and perfusion; shock or cerebral edema can independently trigger dialysis."], ["Metabolic", "Ammonia and acid-base status", "Investigate encephalopathy even when liver tests are normal."], ["Exposure", "Concentration over time", "Follow formulation, serial levels and units; avoid a single-result clearance decision."]]},
  "tox-isoniazid": {"eyebrow": "Cofactor rescue", "title": "Exposure, prescription and delivery", "accent": "#d6aa6a", "columns": [["Exposure", "Isoniazid amount", "Establish whether the swallowed amount is credible or unknown."], ["Prescription", "Pyridoxine amount", "Use the selected protocol and its initial-dose limits."], ["Delivery", "Volume and response", "Verify concentration, control seizures and support breathing."]]},
  "tox-nicotine": {"eyebrow": "Changing physiology", "title": "A quieter patient may be deteriorating", "accent": "#d6aa6a", "columns": [["Exposure", "Reconstruct every route", "Liquid, tobacco and therapeutic products contribute to the exposure history."], ["Pattern", "Stimulation or depression", "Do not require a witnessed early phase before recognizing severe toxicity."], ["Support", "Breathing and circulation", "Treat the failing system and follow the clinical course."]]},
  "tox-hydrocarbon": {"eyebrow": "Aspiration risk", "title": "Follow the lungs over time", "accent": "#d6aa6a", "columns": [["Exposure", "Identify the route", "Recover the product history without delaying respiratory assessment."], ["Injury", "Coughing or choking", "Avoid induced vomiting and evaluate possible aspiration."], ["Course", "Repeat assessment", "Initial improvement alone does not establish sustained recovery."]]},
  "tox-fab": { eyebrow: "Different meanings of a number", title: "Exposure, antidote and assay", accent: "#d6aa6a", columns: [["Exposure", "mg digoxin", "Estimate body load from the formulation and credible history."], ["Antidote", "mg Fab or vials", "Calculate and prepare the prescribed antibody-fragment dose."], ["Assay", "Free versus total", "After Fab, interpret the laboratory result through binding and clinical response."]] },
  "tox-last-rescue": { eyebrow: "Dose is not rate", title: "Keep three quantities separate", accent: "#d6aa6a", columns: [["Bolus", "mL over minutes", "Calculate the initial volume and its delivery time."], ["Infusion", "mL per minute", "Convert by 60 when the pump displays mL per hour."], ["Total", "All delivered lipid", "Count boluses and infusions together against the protocol limit."]] },
  "tox-aluminum": { eyebrow: "Protocol reconciliation", title: "One drug does not mean one regimen", accent: "#d6aa6a", columns: [["Indication", "Identify the treatment goal", "Distinguish aluminum accumulation from acute iron ingestion."], ["Schedule", "Coordinate the whole plan", "Confirm the dose interval and relationship to dialysis."], ["Safety", "Resolve the discrepancy", "Document specialist rationale, label restrictions and monitoring."]] },
  "tox-decorporation": { eyebrow: "Countermeasure selection", title: "Identify, select, reassess", accent: "#d6aa6a", columns: [["Identify", "Substance and route", "An alert alone does not identify the contaminant inside a patient."], ["Select", "Specific mechanism", "Match the product to the target and the patient."], ["Reassess", "Clinical course and measurements", "Track response, adverse effects and the need for additional support."]] },
  "tox-metal-testing": { eyebrow: "Interpretation sequence", title: "The specimen needs an exposure timeline", accent: "#d6aa6a", columns: [["Identify", "Chemical form and route", "A shared element name does not make exposures clinically equivalent."], ["Time", "Exposure to collection", "Document meals, symptoms, sampling and any prior chelator."], ["Interpret", "A valid comparison", "Match the assay and reference population to the question being asked."]] },
  "tox-iron": { eyebrow: "Three different quantities", title: "Trace the units from tablet to pump", accent: "#d6aa6a", columns: [["Exposure", "mg elemental iron/kg", "Tablet count × elemental amount per tablet ÷ body weight."], ["Treatment", "mg chelator/hour", "Prescribed mg/kg/hour × body weight; track the cumulative dose."], ["Delivery", "mL/hour", "Divide the prescribed mg/hour by the verified final mg/mL."]] },
  "tox-lead": { eyebrow: "Lead treatment safeguards", title: "Confirm the exposure, drug, and follow-up", accent: "#d6aa6a", columns: [["Exposure", "Safe environment", "Connect the blood result to symptoms, the source, and a safe discharge setting."], ["Product", "Complete salt name", "Calcium disodium EDTA and disodium EDTA are not substitutes."], ["Course", "Scheduled reassessment", "A completed prescription is not proof that the exposure problem is resolved."]] },
  "tox-stabilization": { eyebrow: "Critical sequence", title: "Physiology moves before certainty", accent: "#d98b72", columns: [["Stabilize", "Airway to glucose", "Treat ventilation, circulation, seizure, temperature, and reversible metabolic threats."], ["Reconstruct", "Exposure architecture", "Resolve product, ingredient, formulation, dose, route, time, intent, and coexposures."], ["Escalate", "Poison expertise", "Connect the evolving case to poison-center and medical-toxicology guidance."]] },
  "tox-general-decontamination": { eyebrow: "Exposure control", title: "Reduce absorption without adding harm", accent: "#90ad97", columns: [["Route", "Remove ongoing exposure", "Protect rescuers and match irrigation or removal to skin, eye, inhaled, or swallowed toxin."], ["Gut", "Select, never reflex", "Use charcoal only when adsorption, timing, bowel function, and airway safety align."], ["Clear", "Change toxicokinetics", "Reserve alkalinization, multidose charcoal, and dialysis for compatible toxins and severity."]] },
  "tox-patterns": { eyebrow: "Diagnostic field", title: "The pattern narrows the poison, then the data challenge it", accent: "#9a9bc6", columns: [["Examine", "Toxidrome", "Map pupils, moisture, secretions, temperature, bowel activity, tone, reflexes, and clonus."], ["Trace", "ECG phenotype", "Separate QRS widening, QT prolongation, conduction block, and ventricular instability."], ["Trend", "Chemistry over time", "Read pH, anion gap, osmolar gap, lactate, and toxin levels as moving signals."]] },
  "tox-acetaminophen": { eyebrow: "Hepatic rescue", title: "Interrupt toxic metabolism before symptoms arrive", accent: "#d6aa6a", columns: [["Classify", "Exposure pattern", "Known-time acute, unknown-time, repeated, delayed, or extended-release ingestion."], ["Measure", "Nomogram boundary", "Use a level drawn 4 to 24 hours from the start of a reliably timed acute exposure."], ["Rescue", "Acetylcysteine", "Start early, monitor response, and continue until biochemical and clinical stopping criteria are met."]] },
  "tox-methemoglobin": { eyebrow: "Oxygen carriage", title: "Measure the carrier, then check the rescue constraints", accent: "#d6aa6a", columns: [["Recognize", "Co-oximetry", "A normal oxygen tension can coexist with impaired hemoglobin oxygen delivery."], ["Select", "Patient and product", "Check G6PD, kidney function, interactions and the actual drug concentration."], ["Reassess", "Response and rebound", "Follow clinical recovery and measured methemoglobin; escalate failed or contraindicated therapy."]] },
  "tox-opioids": { eyebrow: "Ventilation rescue", title: "Reverse the opioid, preserve the airway", accent: "#7da8b9", columns: [["Breathe", "Ventilation first", "Support oxygenation and ventilation before and during antagonist delivery."], ["Reverse", "Naloxone", "Give promptly and repeat with a new device when response is absent or respiratory depression returns."], ["Watch", "Recurrence", "The opioid can outlast naloxone, so emergency care and continued observation remain essential."]] },
  "tox-cardiotoxic": { eyebrow: "Poisoned circulation", title: "Treat the mechanism behind shock", accent: "#c97777", columns: [["Phenotype", "Rate, rhythm, pump", "Use ECG, glucose, perfusion, and ventricular function to identify the dominant failure."], ["Target", "Antidote plus support", "Connect calcium, insulin, Fab, bicarbonate, vasopressors, or other therapy to the toxin."], ["Escalate", "Refractory shock", "Mobilize invasive monitoring, toxicology, and extracorporeal support before collapse."]] },
  "tox-cellular": { eyebrow: "Oxygen and acid", title: "Block toxic chemistry before organ failure compounds", accent: "#77aaa2", columns: [["Metabolism", "Methanol / ethylene glycol", "Block toxic metabolite formation with fomepizole; assess toxin-specific dialysis criteria."], ["Utilization", "Cyanide", "Give hydroxocobalamin on high clinical suspicion with complete resuscitation."], ["Carriage", "Methemoglobin", "Confirm the dyshemoglobin pattern and apply methylene-blue safety boundaries."]] },
  "tox-neuro": { eyebrow: "Autonomic map", title: "Wet, dry, adrenergic, and serotonergic patterns diverge", accent: "#b18fb0", columns: [["Wet", "Cholinergic", "Dry secretions with atropine and reverse appropriate organophosphate enzyme inhibition with pralidoxime."], ["Hot", "Dry or diaphoretic", "Separate anticholinergic dryness from sympathomimetic sweating, then control heat and agitation."], ["Clonus", "Serotonin", "Use hyperreflexia and clonus to distinguish serotonin toxicity from a medication list alone."]] },
  "tox-metabolic": { eyebrow: "Biochemical rescue", title: "Repair the pathway the toxin has broken", accent: "#b2a66f", columns: [["Fuel", "Hypoglycemia", "Give dextrose and use octreotide to suppress recurrent sulfonylurea-driven insulin release."], ["Cofactor", "Isoniazid", "Replace pyridoxine while controlling seizures and acidosis."], ["Substrate", "Cancer therapy rescue", "Coordinate leucovorin, glucarpidase, or uridine triacetate by mechanism and time window."]] },
  "tox-preparedness": { eyebrow: "Operational readiness", title: "An antidote is only real when the system can deliver it", accent: "#b98c72", columns: [["Stock", "Right product and amount", "Match local risk, transfer time, storage, expiry, and replenishment."], ["Prepare", "People and process", "Place dosing, mixing, compatibility, monitoring, and consultation at the bedside."], ["Sustain", "Community continuity", "Preserve access to critical medicines during disasters and coordinate envenomation and rabies response."]] },
};

export default function ToxicologyAntidotesVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual toxicology-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
