const diagrams = {
  "tox-stabilization": { eyebrow: "Critical sequence", title: "Physiology moves before certainty", accent: "#d98b72", columns: [["Stabilize", "Airway to glucose", "Treat ventilation, circulation, seizure, temperature, and reversible metabolic threats."], ["Reconstruct", "Exposure architecture", "Resolve product, ingredient, formulation, dose, route, time, intent, and coexposures."], ["Escalate", "Poison expertise", "Connect the evolving case to poison-center and medical-toxicology guidance."]] },
  "tox-decontamination": { eyebrow: "Exposure control", title: "Reduce absorption without adding harm", accent: "#90ad97", columns: [["Route", "Remove ongoing exposure", "Protect rescuers and match irrigation or removal to skin, eye, inhaled, or swallowed toxin."], ["Gut", "Select, never reflex", "Use charcoal only when adsorption, timing, bowel function, and airway safety align."], ["Clear", "Change toxicokinetics", "Reserve alkalinization, multidose charcoal, and dialysis for compatible toxins and severity."]] },
  "tox-patterns": { eyebrow: "Diagnostic field", title: "The pattern narrows the poison, then the data challenge it", accent: "#9a9bc6", columns: [["Examine", "Toxidrome", "Map pupils, moisture, secretions, temperature, bowel activity, tone, reflexes, and clonus."], ["Trace", "ECG phenotype", "Separate QRS widening, QT prolongation, conduction block, and ventricular instability."], ["Trend", "Chemistry over time", "Read pH, anion gap, osmolar gap, lactate, and toxin levels as moving signals."]] },
  "tox-acetaminophen": { eyebrow: "Hepatic rescue", title: "Interrupt toxic metabolism before symptoms arrive", accent: "#d6aa6a", columns: [["Classify", "Exposure pattern", "Known-time acute, unknown-time, repeated, delayed, or extended-release ingestion."], ["Measure", "Nomogram boundary", "Use a concentration at least four hours after a valid known-time acute exposure."], ["Rescue", "Acetylcysteine", "Start early, monitor response, and continue until biochemical and clinical stopping criteria are met."]] },
  "tox-opioids": { eyebrow: "Ventilation rescue", title: "Reverse the opioid, preserve the airway", accent: "#7da8b9", columns: [["Breathe", "Ventilation first", "Support oxygenation and ventilation before and during antagonist delivery."], ["Reverse", "Naloxone", "Give promptly and repeat with a new device when response is absent or respiratory depression returns."], ["Watch", "Recurrence", "The opioid can outlast naloxone, so emergency care and continued observation remain essential."]] },
  "tox-cardiotoxic": { eyebrow: "Poisoned circulation", title: "Treat the mechanism behind shock", accent: "#c97777", columns: [["Phenotype", "Rate, rhythm, pump", "Use ECG, glucose, perfusion, and ventricular function to identify the dominant failure."], ["Target", "Antidote plus support", "Connect calcium, insulin, Fab, bicarbonate, vasopressors, or other therapy to the toxin."], ["Escalate", "Refractory shock", "Mobilize invasive monitoring, toxicology, and extracorporeal support before collapse."]] },
  "tox-cellular": { eyebrow: "Oxygen and acid", title: "Block toxic chemistry before organ failure compounds", accent: "#77aaa2", columns: [["Metabolism", "Toxic alcohols", "Use fomepizole to stop toxic metabolite formation and dialysis when severity requires."], ["Utilization", "Cyanide", "Give hydroxocobalamin on high clinical suspicion with complete resuscitation."], ["Carriage", "Methemoglobin", "Confirm the dyshemoglobin pattern and apply methylene-blue safety boundaries."]] },
  "tox-neuro": { eyebrow: "Autonomic map", title: "Wet, dry, adrenergic, and serotonergic patterns diverge", accent: "#b18fb0", columns: [["Wet", "Cholinergic", "Dry secretions with atropine and reverse appropriate organophosphate enzyme inhibition with pralidoxime."], ["Hot", "Dry or diaphoretic", "Separate anticholinergic dryness from sympathomimetic sweating, then control heat and agitation."], ["Clonus", "Serotonin", "Use hyperreflexia and clonus to distinguish serotonin toxicity from a medication list alone."]] },
  "tox-metabolic": { eyebrow: "Biochemical rescue", title: "Repair the pathway the toxin has broken", accent: "#b2a66f", columns: [["Fuel", "Hypoglycemia", "Give dextrose and use octreotide to suppress recurrent sulfonylurea-driven insulin release."], ["Cofactor", "Isoniazid", "Replace pyridoxine while controlling seizures and acidosis."], ["Substrate", "Cancer therapy rescue", "Coordinate leucovorin, glucarpidase, or uridine triacetate by mechanism and time window."]] },
  "tox-preparedness": { eyebrow: "Operational readiness", title: "An antidote is only real when the system can deliver it", accent: "#b98c72", columns: [["Stock", "Right product and amount", "Match local risk, transfer time, storage, expiry, and replenishment."], ["Prepare", "People and process", "Place dosing, mixing, compatibility, monitoring, and consultation at the bedside."], ["Sustain", "Community continuity", "Preserve access to critical medicines during disasters and coordinate envenomation and rabies response."]] },
};

export default function ToxicologyAntidotesVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual toxicology-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={`${name}-${action}`}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
