export const tuberculosisVisualTypes=["biology-transmission","infection-testing","disease-diagnosis-public-health","ltbi-regimens","first-line-pharmacology","drug-susceptible-treatment","toxicity-monitoring","interactions-special-populations","drug-resistant-treatment","adherence-response-prevention"].map(type=>`tb-${type}`);

const diagrams={
  "biology-transmission":["Disease states","Follow bacilli from exposure to containment or disease",["Enter","Airborne exposure","Inhaled particles reach the distal respiratory tract."],["Contain","Granuloma","Cell-mediated immunity can establish latent infection."],["Escape","Active disease","Loss of containment creates tissue injury and symptoms."],["Transmit","Pulmonary burden","Aerosol generation can expose the next person."]],
  "infection-testing":["Testing pathway","Turn immune sensitization into an actionable decision",["Target","Pretest risk","Test when exposure or progression risk makes treatment useful."],["Select","IGRA or TST","BCG, return ability, age, immunity, and access shape the choice."],["Interpret","Risk threshold","TST induration thresholds change with clinical risk."],["Exclude","Active disease","Symptoms and imaging come before preventive treatment."]],
  "disease-diagnosis-public-health":["Diagnostic system","Protect, detect, confirm, and report at the same time",["Protect","Airborne control","Contain exposure while disease is still presumed."],["Detect","Smear and NAA","Estimate burden and identify MTB rapidly."],["Confirm","Culture and DST","Grow the organism and define susceptibility."],["Coordinate","Public health","Report early and activate contact and treatment systems."]],
  "ltbi-regimens":["Preventive pathways","Match the shortest safe regimen to the person",["Weekly","3HP","Twelve doses of isoniazid and rifapentine for eligible patients."],["Daily","4R","One hundred twenty rifampin doses with interaction ownership."],["Combined","3HR","Ninety daily isoniazid and rifampin doses."],["Alternative","6H or 9H","Longer isoniazid when rifamycin pathways do not fit."]],
  "first-line-pharmacology":["Drug contributions","Connect bacterial target to regimen role and monitoring",["Build","Isoniazid","Block mycolic-acid synthesis and protect nerves with pyridoxine when indicated."],["Silence","Rifamycin","Block RNA polymerase while managing potent induction."],["Sterilize","Pyrazinamide","Reach acidic populations while monitoring liver and urate effects."],["Protect","Ethambutol","Suppress resistance until susceptibility clarifies the regimen."]],
  "drug-susceptible-treatment":["Regimen selection","Use the phenotype to choose four or six months",["Confirm","Susceptibility","Rapid and growth-based evidence supports the pathway."],["Screen","Eligibility","Age, weight, site, pregnancy, QT, and interactions control shortening."],["Deliver","Exact phases","Use HPZM then HPM or HRZE then HR without improvising."],["Count","Required doses","Completion depends on delivered doses and response."]],
  "toxicity-monitoring":["Monitoring loop","Give each signal a predefined action",["Baseline","Make change visible","Record organs, vision, nerves, weight, drugs, and microbiology."],["Ask","Monthly minimum","Reconcile symptoms, doses, barriers, interactions, and response."],["Stop","Danger signal","Act on hepatic, visual, neurologic, cardiac, or hematologic injury."],["Rebuild","Safe regimen","Preserve enough active therapy with expert guidance."]],
  "interactions-special-populations":["Whole-person design","Keep TB therapy compatible with every other priority",["Reconcile","Rifamycin induction","Protect anticoagulation, contraception, ART, transplant drugs, and methadone."],["Time","HIV therapy","Use CD4 and disease site to coordinate ART initiation."],["Adapt","Pregnancy and lactation","Treat active disease promptly and use current narrative risk."],["Redesign","Organ disease","Preserve regimen activity while adjusting exposure and monitoring."]],
  "drug-resistant-treatment":["Resistance pathway","Replace legacy injectables with current all-oral logic",["Detect","Rifampin resistance","Use rapid molecular testing and expert consultation."],["Differentiate","Fluoroquinolone status","Susceptibility separates BPaLM from BPaL."],["Treat","Six-month pathway","Deliver the complete regimen for the eligible phenotype."],["Monitor","Shared toxicity","Track QT, neuropathy, blood counts, liver, response, and resistance."]],
  "adherence-response-prevention":["Closed-loop cure","Connect dose delivery to community protection",["Support","DOT or vDOT","Use the least burdensome reliable observation strategy."],["Measure","Culture conversion","Read microbiology alongside symptoms and exposure."],["Protect","Contacts","Prioritize confidential evaluation of vulnerable people."],["Complete","Verified outcome","Close doses, response, records, toxicity, and recurrence ownership."]],
};

export default function TuberculosisVisual({type}){const diagram=diagrams[type.replace("tb-","")];if(!diagram)return null;const[eyebrow,title,...nodes]=diagram;return <figure className="chol-visual tuberculosis-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb,focus,detail],index)=><div key={`${verb}-${focus}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>}
