const diagrams = {
  "ui-phenotypes": ["Leakage map", "The trigger identifies the first branch", ["Urge", "Urgency", "A sudden difficult-to-defer urge precedes leakage"], ["Pressure", "Stress", "Cough, exertion, or laughter exceeds outlet support"], ["Mismatch", "Emptying or access", "Retention, mobility, cognition, or environment drives leakage"]],
  "ui-evaluation": ["Evaluation path", "Confirm the pattern before escalating tests", ["Describe", "History and diary", "Symptoms, triggers, volumes, medicines, bother, and goals"], ["Screen", "Examination and urine", "Look for infection, support, neurologic change, and reversible causes"], ["Target", "Residual or referral", "Measure emptying and escalate only when risk or uncertainty warrants it"]],
  "ui-neurophysiology": ["Bladder states", "Continence is coordinated switching", ["Store", "Relax detrusor", "Beta-3 signaling and central inhibition support filling"], ["Close", "Preserve outlet", "Sphincter and pelvic floor maintain urethral resistance"], ["Void", "Contract and release", "M3 detrusor contraction pairs with outlet relaxation"]],
  "ui-behavioral": ["Training loop", "Turn advice into repeatable behavior", ["Observe", "Diary", "Map intake, voids, urgency, leakage, and nighttime production"], ["Practice", "Bladder and pelvic floor", "Extend intervals and recruit the correct muscles"], ["Adapt", "Environment and health", "Treat constipation, access, mobility, sleep, and skin needs"]],
  "ui-antimuscarinics": ["Muscarinic tradeoff", "Reduce urgency without ignoring the rest of the body", ["Block", "M3 signaling", "Limit involuntary detrusor contractions during storage"], ["Burden", "Peripheral and central", "Dry mouth, constipation, vision, retention, and cognition can change fit"], ["Select", "Molecule and route", "Formulation, brain access, organ function, and interactions alter risk"]],
  "ui-beta3": ["Beta-3 selection", "Same receptor class, different medication profiles", ["Mirabegron", "25 to 50 mg", "Blood pressure, CYP2D6, renal, hepatic, and retention review"], ["Vibegron", "75 mg", "Digoxin, angioedema, administration, and retention review"], ["Follow", "Response and safety", "Measure symptoms, pressure when relevant, emptying, and interactions"]],
  "ui-combination": ["Shared decision", "Move across categories without a rigid ladder", ["Measure", "One therapy", "Benefit, burden, adherence, access, and patient goal"], ["Combine", "Different mechanisms", "Add only when the expected incremental benefit justifies risk"], ["Change", "Category or procedure", "Preference and safety can justify earlier minimally invasive care"]],
  "ui-procedures": ["Minimally invasive care", "Match the mechanism to the commitment", ["Inject", "OnabotulinumtoxinA", "Reduce acetylcholine release with infection and retention planning"], ["Stimulate", "Tibial nerve", "Modulate afferent pathways through repeated or implanted treatment"], ["Implant", "Sacral neuromodulation", "Use adjustable neural control with device and revision tradeoffs"]],
  "ui-other-phenotypes": ["Treatment redirect", "Not every leak belongs to the OAB pathway", ["Support", "Stress", "Pelvic floor, pessary, urethral support, or a selected procedure"], ["Empty", "Overflow", "Resolve obstruction, contractility, neurologic, or medication causes"], ["Reach", "Functional", "Improve mobility, access, clothing, cognition, and assistance"]],
  "ui-nocturia": ["Nighttime pathway", "Prove the production mechanism before antidiuresis", ["Record", "24-hour diary", "Separate nocturnal polyuria, global polyuria, OAB, and sleep-driven waking"], ["Correct", "Underlying cause", "Address fluid timing, edema, apnea, diabetes, medicines, heart, and kidney disease"], ["Protect", "Desmopressin safety", "Restrict fluid, monitor sodium, and stop during destabilizing illness"]],
};

export default function UrinaryIncontinenceVisual({ type }) {
  const item = diagrams[type];
  if (!item) return null;
  const [eyebrow, title, ...columns] = item;
  return <figure className="chol-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{columns.map(([name, focus, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
