export const vancomycinPharmacologyVisualTypes = ["structure-mechanism", "spectrum-resistance", "route-selection", "pk-dosing", "auc-monitoring", "infusion-administration", "nephrotoxicity", "other-safety", "oral-cdi", "integration"];

const diagrams = {
  "structure-mechanism": ["Cell-wall target", "Bind the precursor before peptidoglycan can mature", ["Recognize", "D-Ala-D-Ala", "A hydrogen-bond pocket surrounds the terminal peptide."], ["Block", "Polymerization", "Steric bulk interrupts transglycosylation and cross-linking."], ["Weaken", "Growing wall", "Susceptible gram-positive cells lose structural integrity."], ["Exclude", "Outer membrane", "The large glycopeptide cannot reliably enter most gram-negative bacteria."]],
  "spectrum-resistance": ["Resistance map", "Separate wall trapping from target replacement", ["Cover", "Susceptible gram-positive organisms", "MRSA activity still depends on syndrome, source control, and exposure."], ["Thicken", "VISA cell wall", "Excess precursor material can trap drug before it reaches the membrane."], ["Replace", "D-Ala-D-Lac", "Van-mediated remodeling sharply reduces glycopeptide binding."], ["Verify", "Species, method, and response", "MIC method and culture clearance belong in the same decision."]],
  "route-selection": ["Compartment map", "Put vancomycin where the infection is", ["Infuse", "Systemic infection", "IV exposure reaches blood and tissues for invasive disease."], ["Deliver", "Colonic lumen", "Oral or enteral dosing creates high local exposure for CDI."], ["Bridge", "Fulminant CDI with ileus", "Enteral, IV companion therapy, and possible rectal delivery cover distinct needs."], ["Escalate", "Source and severity", "Shock, megacolon, or persistent bacteremia requires more than dose adjustment."]],
  "pk-dosing": ["Dose architecture", "Fill distribution first, then replace clearance", ["Load", "Actual body weight", "A loading strategy accelerates exposure when serious illness warrants it."], ["Maintain", "Dynamic clearance", "Renal trajectory and measured AUC shape dose and interval."], ["Reassess", "Changing physiology", "Fluid shifts, obesity, burns, pregnancy, and extracorporeal support alter PK."], ["Coordinate", "Dialysis modality", "Filter, session timing, residual function, and rebound change the plan."]],
  "auc-monitoring": ["Exposure model", "Replace a trough shortcut with a reconstructable AUC", ["Target", "AUC24/MIC 400 to 600", "Use for serious MRSA with an MIC assumption of 1 mg/L by broth microdilution."], ["Reconstruct", "Actual times", "Dose, infusion, and sample timestamps determine model validity."], ["Estimate", "Bayesian or two concentration", "Use a validated method suited to the patient and sampling phases."], ["Respond", "Exposure plus trajectory", "Clinical response, renal change, source, and microbiology determine the next dose."]],
  "infusion-administration": ["Administration system", "Control rate, concentration, access, and compatibility", ["Calculate", "No more than 10 mg/min", "Use at least 60 minutes and extend larger doses accordingly."], ["Dilute", "Usually 5 mg/mL or less", "Selected fluid restriction can justify higher concentration with added vigilance."], ["Differentiate", "Infusion reaction versus anaphylaxis", "Timing, airway findings, and hemodynamics guide the response."], ["Protect", "Line and vein", "Plan compatibility, lumen, flushes, and peripheral-site monitoring."]],
  "nephrotoxicity": ["Kidney loop", "Keep exposure and renal trajectory visible together", ["Measure", "AUC burden", "Excess exposure is a modifiable contributor to injury."], ["Trend", "Creatinine and urine output", "A single normal value cannot define tomorrow's risk."], ["Reconcile", "Nephrotoxin stack", "Hemodynamics, contrast, and concurrent drugs can converge."], ["Exit", "Unnecessary broad therapy", "Culture and source data should shorten avoidable combination exposure."]],
  "other-safety": ["Safety perimeter", "Separate immediate rate effects from delayed organ injury", ["Hear", "Tinnitus and vestibular change", "Review exposure, kidney function, and every ototoxin."], ["Count", "Neutrophils and platelets", "Prolonged therapy and new symptoms warrant CBC surveillance."], ["Recognize", "DRESS and severe skin disease", "Fever, organs, mucosa, eosinophilia, or blisters require urgent action."], ["Document", "Reaction phenotype", "Future decisions depend on an exact event history, not a vague allergy label."]],
  "oral-cdi": ["Luminal therapy", "Keep colonic efficacy and possible systemic absorption visible", ["Concentrate", "Intestinal lumen", "Oral vancomycin produces high local exposure for CDI."], ["Absorb", "Inflamed mucosa", "Severe colitis can make the usual poor absorption clinically meaningful."], ["Accumulate", "Renal impairment", "Reduced elimination raises concern when systemic exposure occurs."], ["Select", "Episode and severity", "Fidaxomicin preference, vancomycin alternatives, recurrence, and fulminant disease differ."]],
  "integration": ["Closed-loop plan", "Connect indication to a documented exit", ["Define", "Syndrome and source", "Name the gram-positive problem and the role of source control."], ["Execute", "Route, dose, and infusion", "Make every administration and sample reconstructable."], ["Measure", "AUC, response, and toxicity", "Exposure only matters when interpreted with the patient trajectory."], ["Stop", "Narrow, switch, or complete", "Write the decision threshold before unnecessary exposure accumulates."]],
};

export default function VancomycinPharmacologyVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  const [eyebrow, title, ...nodes] = diagram;
  return <figure className="chol-visual vancomycin-pharmacology-visual" aria-label={title}><figcaption><span>{eyebrow}</span><strong>{title}</strong></figcaption><div className="chol-visual__grid">{nodes.map(([verb, focus, detail], index) => <div key={focus}><span>{String(index + 1).padStart(2, "0")}</span><strong>{verb}</strong><em>{focus}</em><p>{detail}</p></div>)}</div></figure>;
}
