const diagrams = {
  "vte-risk-formation": { eyebrow: "VTE formation", title: "Venous stasis, endothelial disturbance, and hypercoagulability interact across transient, persistent, and patient-specific risks.", accent: "#c36f64", columns: [["Stasis", "Immobility and venous obstruction", "Slow flow favors local clot growth"], ["Injury", "Surgery, trauma, and catheters", "Expose or activate endothelium"], ["Hypercoagulability", "Cancer, hormones, and inherited states", "Shift thrombin generation"], ["Propagate", "DVT to embolization", "Clot can extend or travel to the lungs"]] },
  "vte-dvt-diagnosis": { eyebrow: "DVT evaluation", title: "Clinical probability determines whether D-dimer can exclude disease or venous ultrasound is needed.", accent: "#7f9eb4", columns: [["Estimate", "Pretest probability", "Use a validated pathway"], ["Exclude", "High-sensitivity D-dimer", "Apply only in the eligible low-risk pathway"], ["Image", "Compression ultrasound", "Identify proximal or distal thrombosis"], ["Decide", "Treat or surveil", "Use location, symptoms, and extension risk"]] },
  "vte-pe-categories": { eyebrow: "2026 acute PE categories", title: "Acute PE categories A through E integrate symptoms, severity, biomarkers, right-ventricular findings, and cardiopulmonary failure.", accent: "#a78ab4", columns: [["A and B", "Asymptomatic or low-severity symptomatic", "Home or early-discharge pathway when eligible"], ["C", "Elevated severity, biomarker, or RV risk", "Hospitalize and optimize therapy"], ["D", "Incipient cardiopulmonary failure", "Escalate monitoring and consider advanced care"], ["E", "Persistent hypotension or failure", "Immediate rescue strategy"]] },
  "vte-initial-treatment": { eyebrow: "Initial VTE treatment", title: "Prompt anticoagulation prevents propagation while severity, contraindications, and organ function determine drug and escalation strategy.", accent: "#b88c62", columns: [["Start", "Therapeutic anticoagulation", "Act promptly when diagnosis is established"], ["Select", "DOAC or parenteral pathway", "Match indication and patient eligibility"], ["Escalate", "Thrombolysis, catheter, surgery", "Reserve for severe PE categories"], ["Support", "PERT and cardiopulmonary care", "Coordinate high-risk decisions"]] },
  "vte-duration-special": { eyebrow: "Duration and special populations", title: "Primary treatment addresses the acute event, while extended therapy depends on recurrence risk, bleeding, preferences, cancer, pregnancy, and anatomy.", accent: "#8ca17a", columns: [["Classify", "Reversible, persistent, or no major factor", "Estimate recurrence after stopping"], ["Treat", "Complete primary therapy", "Avoid premature discontinuation"], ["Extend", "Continue when net benefit persists", "Reassess rather than set and forget"], ["Adapt", "Cancer, pregnancy, kidney, or unusual site", "Use population-specific evidence"]] },
  "vte-follow-up": { eyebrow: "Recovery and surveillance", title: "Follow-up closes medication gaps, detects recurrent bleeding or thrombosis, and identifies post-thrombotic and chronic thromboembolic disease.", accent: "#c29c62", columns: [["Confirm", "Medicine and duration", "Verify acquisition, adherence, and interactions"], ["Recover", "Symptoms and function", "Support mobility and individualized rehabilitation"], ["Screen", "Dyspnea after PE", "Assess at every visit for at least one year"], ["Reevaluate", "Recurrence and bleeding balance", "Update the extended-treatment plan"]] },
};

export default function VenousThromboembolismVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
