const diagrams = {
  "ventricular-risk-map": { eyebrow: "Ventricular rhythm spectrum", title: "Ventricular ectopy ranges from isolated PVCs to sustained VT and VF, with risk defined by symptoms, substrate, burden, hemodynamics, and reversibility.", accent: "#bc7569", columns: [["PVC", "Premature ventricular activation", "Assess morphology and burden"], ["NSVT", "Three or more ventricular beats", "Link duration to substrate"], ["VT", "Sustained organized ventricular rhythm", "Stability drives acute action"], ["VF", "Disorganized ventricular activation", "Immediate defibrillation"]] },
  "ventricular-monomorphic": { eyebrow: "Monomorphic VT", title: "Stable morphology suggests one dominant circuit or focus, commonly scar-mediated reentry in structural heart disease.", accent: "#879fb3", columns: [["Identify", "Regular wide tachycardia", "Assume VT when uncertain"], ["Stabilize", "Pulse and perfusion", "Cardiovert instability"], ["Define", "Ischemia and scar substrate", "Image and evaluate"], ["Prevent", "Drug, ablation, ICD", "Address recurrence and death risk"]] },
  "ventricular-polymorphic": { eyebrow: "Polymorphic VT", title: "The baseline QT separates torsades from polymorphic VT driven more often by acute ischemia or other non-long-QT mechanisms.", accent: "#aa8cb7", columns: [["Shock", "Unsynchronized defibrillation", "Treat sustained episodes"], ["QT long", "Torsades mechanism", "Magnesium and cause removal"], ["QT normal", "Often ischemic", "Treat coronary and trigger state"], ["Prevent", "Correct pause, electrolyte, drug", "Match to mechanism"]] },
  "ventricular-arrest-storm": { eyebrow: "VF and electrical storm", title: "Repeated ventricular arrhythmia demands simultaneous resuscitation, defibrillation optimization, ischemia treatment, trigger correction, sympathetic control, and specialist escalation.", accent: "#c49b5e", columns: [["Resuscitate", "CPR and defibrillation", "Minimize interruption"], ["Correct", "Hs, Ts, ischemia, electrolytes", "Remove recurring triggers"], ["Suppress", "Antiarrhythmic and sympathetic strategy", "Reduce recurrence"], ["Escalate", "Ablation and mechanical support", "Use expert team"]] },
  "ventricular-inherited": { eyebrow: "Inherited and structural syndromes", title: "Long-QT, Brugada, catecholaminergic polymorphic VT, cardiomyopathy, myocarditis, and sarcoidosis require phenotype-directed family and structural evaluation.", accent: "#88a47d", columns: [["Phenotype", "ECG and trigger pattern", "Do not diagnose from one clue"], ["Structure", "Imaging and function", "Find scar or inflammation"], ["Family", "History and genetics", "Use expert counseling"], ["Protect", "Lifestyle, drugs, ablation, device", "Match syndrome risk"]] },
  "ventricular-prevention": { eyebrow: "Sudden-death prevention", title: "ICDs terminate dangerous rhythm, ablation modifies substrate, drugs reduce recurrence, and disease therapy changes the risk environment.", accent: "#b48967", columns: [["Secondary", "Prior arrest or sustained VA", "Exclude reversible cause"], ["Primary", "Risk phenotype and timing", "Use guideline thresholds"], ["Ablate", "Focus or scar circuit", "Reduce recurrent VT"], ["Follow", "Programming, shocks, function", "Treat the whole disease"]] },
};
export default function VentricularArrhythmiasVisual({ type }) { const d=diagrams[type]; if(!d)return null; return <figure className="chol-visual" style={{"--chol-accent":d.accent}} aria-label={d.title}><figcaption><span>{d.eyebrow}</span><strong>{d.title}</strong></figcaption><div className="chol-visual__grid">{d.columns.map(([n,a,x],i)=><div key={n}><span>{String(i+1).padStart(2,"0")}</span><strong>{n}</strong><em>{a}</em><p>{x}</p></div>)}</div></figure>; }
