const diagrams = {
  "warfarin-vitamin-k": { eyebrow: "Vitamin K cycle", title: "Warfarin blocks vitamin K recycling, reducing synthesis of functional clotting factors as existing factors turn over.", accent: "#c36f64", columns: [["Recycle", "VKORC1", "Regenerate reduced vitamin K"], ["Modify", "Gamma carboxylation", "Enable calcium and membrane binding"], ["Deplete", "Factors II, VII, IX, and X", "Anticoagulation follows factor turnover"], ["Balance", "Proteins C and S", "Early decline shapes initiation risk"]] },
  "warfarin-initiation": { eyebrow: "Initiation and indication", title: "A safe start identifies the indication and INR goal, chooses a patient-specific dose, and provides overlap when immediate anticoagulation is required.", accent: "#b88c62", columns: [["Define", "Indication and INR goal", "Mechanical valve, VTE, AF, or another use"], ["Estimate", "Dose sensitivity", "Age, genetics, nutrition, organ function, and interactions"], ["Protect", "Parenteral overlap when required", "Cover delayed factor II reduction"], ["Measure", "Frequent INR", "Adjust from trend and total weekly dose"]] },
  "warfarin-inr": { eyebrow: "INR control", title: "Warfarin management follows INR trend, total weekly dose, timing, causes, and time in therapeutic range rather than isolated reactive dosing.", accent: "#7f9eb4", columns: [["Verify", "Dose and timing", "Reconstruct the actual weekly exposure"], ["Explain", "Diet, illness, and interactions", "Find the change before adjusting"], ["Adjust", "Small weekly percentage change", "Match urgency and direction"], ["Recheck", "Response and stability", "Shorten or extend the interval"]] },
  "warfarin-interactions": { eyebrow: "Interaction control", title: "Warfarin response changes through CYP metabolism, vitamin K availability, clotting-factor synthesis, illness, adherence, and additive hemostatic injury.", accent: "#8ca17a", columns: [["Metabolism", "CYP2C9, CYP1A2, and CYP3A4", "Inhibition raises and induction lowers effect"], ["Substrate", "Vitamin K intake", "Consistency is safer than avoidance"], ["Physiology", "Fever, diarrhea, liver or heart failure", "Disease can move INR"], ["Hemostasis", "Antiplatelets, NSAIDs, and alcohol", "Bleeding can rise without INR change"]] },
  "warfarin-reversal": { eyebrow: "Elevated INR and bleeding", title: "Management follows bleeding severity, INR, source control, urgency, thrombotic indication, and the need for rapid versus sustained reversal.", accent: "#a78ab4", columns: [["Classify", "No bleeding to life-threatening bleeding", "Treat the patient, not only the INR"], ["Hold", "Remove warfarin exposure", "Use selective vitamin K when indicated"], ["Replace", "Four-factor PCC for major bleeding", "Restore factors rapidly"], ["Resume", "Reassess thrombosis risk", "Restart when hemostasis permits"]] },
  "warfarin-longitudinal": { eyebrow: "Longitudinal safety", title: "Durable warfarin care links procedures, pregnancy, adverse effects, home testing, medication reconciliation, and patient self-management.", accent: "#c29c62", columns: [["Coordinate", "Procedures and bridging", "Select by thrombotic and bleeding risk"], ["Protect", "Pregnancy and special populations", "Use specialist indication-specific planning"], ["Detect", "Skin, kidney, and calcification injury", "Recognize uncommon serious toxicity"], ["Empower", "Teach-back and self-monitoring", "Make dose and warning plans explicit"]] },
};

export default function WarfarinManagementVisual({ type }) {
  const diagram = diagrams[type];
  if (!diagram) return null;
  return <figure className="chol-visual" style={{ "--chol-accent": diagram.accent }} aria-label={diagram.title}>
    <figcaption><span>{diagram.eyebrow}</span><strong>{diagram.title}</strong></figcaption>
    <div className="chol-visual__grid">{diagram.columns.map(([name, action, detail], index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><em>{action}</em><p>{detail}</p></div>)}</div>
  </figure>;
}
